"""Distinct Grade 4 requirements and the set whose MAIN section focuses on each (for COVERAGE.md)."""
REQUIREMENTS = [
    ('4.OA.A.1', 'Interpret a multiplication equation as a comparison', [1]),
    ('4.OA.A.1', 'Write a comparison statement as a multiplication equation', [2]),
    ('4.OA.A.2', 'Solve multiplicative comparison word problems by multiplying', [3]),
    ('4.OA.A.2', 'Solve multiplicative comparison word problems by dividing', [4]),
    ('4.OA.A.2', 'Tell multiplicative comparison from additive comparison', [5]),
    ('4.OA.A.3', 'Solve multistep word problems and write an equation with a letter for the unknown', [6]),
    ('4.OA.A.3', 'Interpret remainders in word problems', [7]),
    ('4.OA.A.3', 'Use rounding and mental math to check whether an answer is reasonable', [8]),
    ('4.OA.B.4', 'Find all factor pairs of a whole number from 1 to 100', [9]),
    ('4.OA.B.4', 'A whole number is a multiple of each of its factors; find multiples', [10]),
    ('4.OA.B.4', 'Decide whether a whole number from 1 to 100 is prime or composite', [11]),
    ('4.OA.C.5', 'Generate a number or shape pattern that follows a given rule', [12]),
    ('4.OA.C.5', 'Identify features of a pattern that the rule does not state, and explain them', [13]),
    ('4.NBT.A.1', 'A digit in one place is worth ten times what it is worth in the place to its right', [14]),
    ('4.NBT.A.1', 'Use place value and division to explain why one number is ten times another', [15]),
    ('4.NBT.A.2', 'Read and write multi-digit whole numbers using numerals and number names', [16]),
    ('4.NBT.A.2', 'Write multi-digit whole numbers in expanded form', [17]),
    ('4.NBT.A.2', 'Compare multi-digit whole numbers using >, =, and <', [18]),
    ('4.NBT.A.3', 'Round multi-digit whole numbers to any place', [19]),
    ('4.NBT.B.4', 'Add multi-digit whole numbers using the standard algorithm', [20]),
    ('4.NBT.B.4', 'Subtract multi-digit whole numbers using the standard algorithm', [21]),
    ('4.NBT.B.5', 'Multiply a whole number of up to four digits by a one-digit number', [22]),
    ('4.NBT.B.5', 'Multiply two two-digit numbers', [23]),
    ('4.NBT.B.5', 'Illustrate and explain multiplication with equations, arrays, and area models', [24]),
    ('4.NBT.B.6', 'Divide up to four-digit dividends by one-digit divisors, with remainders', [25]),
    ('4.NBT.B.6', 'Illustrate and explain division with equations, area models, and place value', [26]),
    ('4.NF.A.1', 'Explain why fractions are equivalent using visual fraction models', [27]),
    ('4.NF.A.1', 'Generate equivalent fractions', [28]),
    ('4.NF.A.2', 'Compare two fractions by finding a common denominator or a common numerator', [29]),
    ('4.NF.A.2', 'Compare fractions using the benchmark 1/2, and only when they refer to the same whole', [30]),
    ('4.NF.B.3.a', 'Understand adding and subtracting fractions as joining and separating parts of the same whole', [31]),
    ('4.NF.B.3.b', 'Decompose a fraction into a sum of fractions with the same denominator, and justify it with a model', [32]),
    ('4.NF.B.3.c', 'Add mixed numbers with like denominators', [33]),
    ('4.NF.B.3.c', 'Subtract mixed numbers with like denominators', [34]),
    ('4.NF.B.3.d', 'Solve word problems by adding and subtracting fractions with like denominators', [35]),
    ('4.NF.B.4.a', 'Understand a fraction a/b as a multiple of 1/b', [36]),
    ('4.NF.B.4.b', 'Multiply a fraction by a whole number: n × (a/b) = (n × a)/b', [37]),
    ('4.NF.B.4.c', 'Solve word problems by multiplying a fraction by a whole number', [38]),
    ('4.NF.C.5', 'Write tenths as hundredths and add fractions with denominators 10 and 100', [39]),
    ('4.NF.C.6', 'Write fractions with denominators 10 or 100 as decimals', [40]),
    ('4.NF.C.6', 'Locate decimals to hundredths on a number line', [41]),
    ('4.NF.C.7', 'Compare two decimals to hundredths and justify the comparison', [42]),
    ('4.MD.A.1', 'Know the relative sizes of measurement units within one system', [43]),
    ('4.MD.A.1', 'Express a larger unit in terms of a smaller unit and record the pairs in a table', [44]),
    ('4.MD.A.2', 'Solve word problems about distances and intervals of time', [45]),
    ('4.MD.A.2', 'Solve word problems about liquid volume, mass, and money', [46]),
    ('4.MD.A.2', 'Solve measurement problems with simple fractions or decimals, using number line diagrams', [47]),
    ('4.MD.A.3', 'Apply the area and perimeter formulas for rectangles', [48]),
    ('4.MD.A.3', 'Find an unknown side length from the area or the perimeter of a rectangle', [49]),
    ('4.MD.B.4', 'Make a line plot of measurements in fractions of a unit (1/2, 1/4, 1/8)', [50]),
    ('4.MD.B.4', 'Solve addition and subtraction problems using fraction data in a line plot', [51]),
    ('4.MD.C.5.a', 'An angle is measured as a fraction of a full circle; a one-degree angle is 1/360 of a circle', [52]),
    ('4.MD.C.5.b', 'An angle that turns through n one-degree angles has a measure of n degrees', [53]),
    ('4.MD.C.6', 'Measure angles in whole-number degrees using a protractor', [54]),
    ('4.MD.C.6', 'Sketch angles of a given measure using a protractor', [55]),
    ('4.MD.C.7', 'Angle measure is additive', [56]),
    ('4.MD.C.7', 'Solve for unknown angles in diagrams and real-world problems with an equation', [57]),
    ('4.G.A.1', 'Draw and identify points, lines, line segments, and rays', [58]),
    ('4.G.A.1', 'Draw and identify right, acute, and obtuse angles', [59]),
    ('4.G.A.1', 'Draw and identify perpendicular and parallel lines', [60]),
    ('4.G.A.2', 'Classify two-dimensional figures by parallel or perpendicular sides and by angles', [61]),
    ('4.G.A.2', 'Recognize right triangles as a category, and identify them', [62]),
    ('4.G.A.3', 'Recognize lines of symmetry and line-symmetric figures', [63]),
    ('4.G.A.3', 'Draw lines of symmetry', [64]),
]
