from qb import S, B, sa, mc, tf, plot, coord, draw_write
from common import prot, angles, grid, DRAW

SETS = [
    # ------------------------------------------------------------------ 4.MD.C.5.a
    S('4.MD.C.5.a', 'An angle is measured as a fraction of a full circle; a one-degree angle is 1/360 of a circle',
      main=[
          sa('The circle is centered where the rays meet. The thick arc is {1/6} of the circle.\n'
             'What is the angle\'s measure? Explain. What angle has an arc of {1/360}?', ['Measure:', 'Explanation:', 'Arc of {1/360}:'], key='60°; 1°',
             note='Explanation: a full circle is 360°, and the angle turns through 1/6 of the circle, so it measures 1/6 of 360°, which is 60°. '
                  'An arc of 1/360 of the circle gives a one-degree angle (1°). All three parts are required.',
             fig=dict(k='rays', rays=[0, 60], labels=[], ra=[], h=260, fs=1.05, circle=dict(r=0.6, parts=6, arc=(0, 60)),
                      desc='Two rays from one point, at 0 and 60 degrees. A circle is centered at the point and divided by tick marks into '
                           '6 equal arcs; the arc between the two rays is drawn thick.')),
          tf('An angle that turns through {1/4} of a full circle measures 90°.', key=True),
          mc('What fraction of a full circle does a 180° angle turn through?', ['{1/2}', '{1/4}', '{1/3}', '{1/180}']),
          sa('The circle is centered at the common endpoint of the two rays and is divided into 8 equal arcs.\n'
             'What fraction of the circle is the thick arc between the rays? What is the measure of the angle?', ['Fraction:', 'Measure:'],
             key='3/8; 135°', note='3/8 of 360° = 135°. Both parts are required.',
             fig=dict(k='rays', rays=[0, 135], labels=[], ra=[], h=260, fs=1.05, circle=dict(r=0.6, parts=8, arc=(0, 135)),
                      desc='Two rays from one point, at 0 and 135 degrees. A circle is centered at the point and divided by tick marks into '
                           '8 equal arcs; the arc between the two rays is drawn thick.')),
          tf('An angle that turns through {1/3} of a full circle measures 30°.', key=False),
      ],
      back=[
          B('Equal parts of a shape', '3.G.A.2', [
              sa('A circle is cut into 4 equal parts.\nWhat fraction of the circle is 1 part?', 'Fraction:', key='1/4'),
              tf('A circle cut into 2 equal parts is cut into halves.', key=True),
              mc('A circle is cut into 6 equal parts.\nWhat fraction of the circle is each part?', ['{1/6}', '{6/1}', '{1/3}', '{5/6}']),
              sa('Each part of a circle is {1/8} of the circle.\nInto how many equal parts is the circle cut?', 'Parts:', key='8'),
              tf('A circle cut into 3 parts of different sizes is cut into thirds.', key=False),
          ]),
          B('Turns of the minute hand on a clock', '3.MD.A.1', [
              sa('The minute hand turns from 12 to 3.\nHow many minutes pass?', 'Minutes:', key='15'),
              tf('When the minute hand makes a full turn, 60 minutes pass.', key=True),
              mc('The minute hand turns halfway around the clock.\nHow many minutes pass?', ['30', '15', '60', '12']),
              sa('The minute hand turns from 12 to 9.\nHow many minutes pass?', 'Minutes:', key='45'),
              tf('A quarter turn of the minute hand takes 25 minutes.', key=False),
          ]),
      ],
      f1=B('Classify triangles by their angles', '5.G.B.4', [
          sa('A triangle has angles of 90°, 60°, and 30°.\nClassify it by its angles.', 'Classification:', key='Right triangle'),
          tf('A triangle with angles of 70°, 60°, and 50° is an acute triangle.', key=True),
          mc('A triangle has one angle of 120°.\nWhat kind of triangle is it?', ['Obtuse', 'Right', 'Acute', 'Equilateral']),
          sa('Can a triangle have two right angles? Write yes or no.', 'Answer:', key='No'),
          tf('An obtuse triangle has three angles that are each less than 90°.', key=False),
      ]),
      f2=B('Find a percent of a full turn', '6.RP.A.3.c', nearest=True, qs=[
          sa('What is 25% of 360°?', 'Answer:', key='90°'),
          tf('50% of a full turn is 180°.', key=True),
          mc('What percent of a full circle is 36°?', ['10%', '36%', '1%', '20%']),
          sa('What is 75% of 360°?', 'Answer:', key='270°'),
          tf('20% of 360° is 20°.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.MD.C.5.b
    S('4.MD.C.5.b', 'An angle that turns through n one-degree angles has a measure of n degrees',
      main=[
          sa('An angle turns through 45 one-degree angles.\nWhat is its measure?', 'Measure:', key='45°'),
          tf('An angle made of 120 one-degree angles measures 120°.', key=True),
          mc('How many one-degree angles make a 75° angle?', ['75', '285', '360', '15']),
          sa('A fan blade turns through 30 one-degree angles and then 20 more in the same direction.\nWhat angle did it turn through?', 'Angle:', key='50°'),
          tf('A 90° angle is made of 9 one-degree angles.', key=False),
      ],
      back=[
          B('A shape covered by n unit squares has an area of n square units', '3.MD.C.5.b', [
              sa('A shape is covered by 14 unit squares with no gaps or overlaps.\nWhat is its area?', 'Area:', key='14 square units'),
              tf('A shape covered by 9 unit squares with no gaps has an area of 9 square units.', key=True),
              mc('A rectangle is covered by 20 unit squares.\nWhat is its area?', ['20 square units', '20 units', '10 square units', '40 square units']),
              sa('How many unit squares cover a shape with an area of 6 square units?', 'Unit squares:', key='6'),
              tf('A shape covered by 8 unit squares has an area of 16 square units.', key=False),
          ]),
          B('Measure length by laying units end to end', '1.MD.A.2', [
              sa('A pencil is as long as 6 paper clips laid end to end.\nHow many paper clips long is it?', 'Paper clips:', key='6'),
              tf('Length units laid end to end must have no gaps or overlaps.', key=True),
              mc('A crayon is as long as 4 cubes in a row.\nHow long is the crayon?', ['4 cubes', '5 cubes', '8 cubes', '1 cube']),
              sa('A book is 9 tiles long. A desk is 3 tiles longer.\nHow many tiles long is the desk?', 'Tiles:', key='12'),
              tf('If the cubes overlap when you measure, the count is still correct.', key=False),
          ]),
      ],
      f1=B('A solid packed with n unit cubes has a volume of n cubic units', '5.MD.C.3.b', nearest=True, qs=[
          sa('A box is filled with 24 unit cubes with no gaps or overlaps.\nWhat is its volume?', 'Volume:', key='24 cubic units'),
          tf('A solid built from 15 unit cubes has a volume of 15 cubic units.', key=True),
          mc('A prism has 3 layers with 8 unit cubes in each layer.\nWhat is its volume?', ['24 cubic units', '11 cubic units', '24 square units', '38 cubic units']),
          sa('How many unit cubes fill a box with a volume of 40 cubic units?', 'Unit cubes:', key='40'),
          tf('A cube with edges 1 unit long has a volume of 6 cubic units.', key=False),
      ]),
      f2=B('Find volume by packing with unit-fraction cubes', '6.G.A.2', nearest=True, qs=[
          sa('How many cubes with edges {1/2} unit long fill a cube with edges 1 unit long?', 'Cubes:', key='8'),
          tf('A cube with edges {1/2} unit long has a volume of {1/8} cubic unit.', key=True),
          mc('A box is packed with 16 cubes that each have edges {1/2} unit long.\nWhat is its volume?',
             ['2 cubic units', '8 cubic units', '16 cubic units', '4 cubic units']),
          sa('Find the volume of a prism that is 2 units by 1{1/2} units by {1/2} unit.', 'Volume:', key='1 1/2 cubic units'),
          tf('A box that is 1 unit by 1 unit by {1/2} unit holds exactly 2 cubes with edges {1/2} unit long.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.MD.C.6 (measure)
    S('4.MD.C.6', 'Measure angles in whole-number degrees using a protractor',
      main=[
          sa('Use the protractor.\nWhat is the measure of the angle?', 'Measure:', key='65°', fig=prot([0, 65])),
          sa('Use the protractor.\nWhat is the measure of the angle?', 'Measure:', key='140°', fig=prot([0, 140])),
          mc('Use the protractor. One ray points to 180 on the outer scale.\nWhat is the measure of the angle?', ['30°', '150°', '180°', '120°'],
             fig=prot([180, 150], inner=True)),
          tf('The angle measures 90°.', key=True, fig=prot([0, 90])),
          sa('Use the protractor.\nWhat is the measure of the angle?', 'Measure:', key='75°', fig=prot([40, 115]),
             note='The rays cross the scale at 40 and 115, and 115 - 40 = 75.'),
      ],
      back=[
          B('Measure length with a ruler', '2.MD.A.1', [
              sa('A pencil reaches from 0 to 7 on an inch ruler.\nHow long is the pencil?', 'Length:', key='7 inches'),
              tf('When you measure with a ruler, you can line up one end of the object with 0.', key=True),
              mc('A crayon starts at 2 cm and ends at 9 cm on a ruler.\nHow long is the crayon?', ['7 cm', '9 cm', '11 cm', '2 cm']),
              sa('A leaf reaches from 0 to 5 on a centimeter ruler.\nHow long is the leaf?', 'Length:', key='5 cm'),
              tf('An eraser that reaches from 3 to 8 on a ruler is 8 units long.', key=False),
          ]),
          B('Shapes with a given number of angles', '2.G.A.1', [
              sa('How many angles does a triangle have?', 'Angles:', key='3'),
              tf('A square has 4 angles.', key=True),
              mc('Which shape has 6 angles?', ['Hexagon', 'Pentagon', 'Quadrilateral', 'Triangle']),
              sa('How many angles does a pentagon have?', 'Angles:', key='5'),
              tf('A circle has 4 angles.', key=False),
          ]),
      ],
      f1=B('Attributes of a category belong to its subcategories', '5.G.B.3', [
          tf('Every right triangle has one 90° angle. An isosceles right triangle is a right triangle, so it has a 90° angle.', key=True),
          mc('A shape is a rhombus.\nWhich statement must be true?', ['Its opposite angles are equal.', 'All its angles are 90°.',
                                                                     'It has exactly one pair of parallel sides.', 'It has 3 sides.']),
          sa('A quadrilateral has four 90° angles and four sides of equal length.\nWhat is its most specific name?', 'Name:', key='Square'),
          tf('Every parallelogram has four 90° angles.', key=False),
          sa('A triangle has angles of 45°, 45°, and 90°.\nName two categories of triangles it belongs to.', 'Categories:',
             key='Right triangle and isosceles triangle', note='Both are required.'),
      ]),
      f2=B('Write and solve x + p = q to find an unknown angle', '6.EE.B.7', nearest=True, qs=[
          sa('Two angles together make a 90° angle. One of them is 35°.\nWrite and solve an equation for the other angle, x.', ['Equation:', 'x ='],
             key='x + 35 = 90; x = 55°', note='Any equivalent equation is correct. Both parts are required.'),
          tf('If x + 120 = 180, then x = 60.', key=True),
          mc('Solve for a.\na + 48 = 90', ['42', '138', '52', '48']),
          sa('Solve for y.\ny + 75 = 180', 'y =', key='105'),
          tf('If 2x = 90, then x = 180.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.MD.C.6 (sketch)
    S('4.MD.C.6', 'Sketch angles of a given measure using a protractor',
      main=[
          plot('Use the protractor to draw an angle of 50°. One ray is drawn for you.', prot([0]),
               key='A second ray drawn from the center through the 50° mark, making a 50° angle with the given ray'),
          plot('Use the protractor to draw an angle of 120°. One ray is drawn for you.', prot([0]),
               key='A second ray drawn from the center through the 120° mark'),
          draw_write('Use the protractor to draw an angle of 90°. One ray is drawn for you.\nWhat kind of angle is it?', prot([0]), 'Kind of angle:',
                     draw='A second ray drawn from the center through the 90° mark', key='Right angle',
                     note='Grade both: a ray through 90°, and the name "right angle".'),
          mc('Kim wants to draw a 70° angle. Her first ray points to 0 on the outer scale.\nWhere should she draw the second ray?',
             ['Through 70 on the outer scale', 'Through 110 on the outer scale', 'Through 70 on the inner scale', 'Through 0 on the inner scale'],
             fig=prot([0], inner=True)),
          draw_write('Use the protractor to draw an angle of 35°. One ray is drawn for you.\nIs the angle acute or obtuse?', prot([0]), 'Answer:',
                     draw='A second ray drawn from the center through the 35° mark', key='Acute',
                     note='Grade both: a ray through 35°, and "acute".'),
      ],
      back=[
          B('Draw shapes with given attributes', '2.G.A.1', [
              sa('A shape has 4 sides and 4 angles.\nName a shape it could be.', 'Shape:', key='A square',
                 note='Any quadrilateral (rectangle, rhombus, trapezoid, and so on) is correct.'),
              tf('A triangle has 3 sides and 3 angles.', key=True),
              mc('Which shape has 5 sides?', ['Pentagon', 'Hexagon', 'Triangle', 'Square']),
              plot('Draw a shape that has 3 sides.', DRAW, key='Any closed shape with 3 straight sides (a triangle)'),
              tf('A shape with 6 angles has 4 sides.', key=False),
          ]),
          B('Defining attributes of shapes', '1.G.A.1', [
              tf('A triangle can be any color or size and still be a triangle.', key=True),
              mc('Which is a defining attribute of a square?', ['It has 4 equal sides.', 'It is blue.', 'It is big.', 'It is turned on its corner.']),
              sa('How many corners (vertices) does a rectangle have?', 'Corners:', key='4'),
              tf('A shape must be large to be a hexagon.', key=False),
              sa('A closed shape has 3 straight sides.\nWhat is it called?', 'Name:', key='Triangle'),
          ]),
      ],
      f1=B('Graph points in the first quadrant to solve problems', '5.G.A.2', [
          draw_write('On a map grid, Ana\'s house is at (1, 2) and the park is at (1, 7). Each unit is 1 block.\n'
                     'Plot and label both points. How many blocks apart are they?', grid(8, 8), 'Blocks:',
                     draw='Points plotted at (1, 2) and (1, 7), each labeled', key='5 blocks',
                     note='Grade both: the two points plotted and labeled, and the distance 5 blocks (7 - 2 = 5).'),
          tf('A plant is 4 cm tall on day 0 and grows 2 cm each day. The point (3, 10) shows its height on day 3.', key=True),
          mc('A tank holds 2 liters at minute 0 and fills 3 liters each minute.\nWhich point (minutes, liters) shows the amount after 4 minutes?',
             ['(4, 14)', '(14, 4)', '(4, 12)', '(3, 4)']),
          draw_write('Plot (1, 1), (5, 1), and (1, 4), and connect them.\nWhat kind of angle is at (1, 1)?', grid(6, 6), 'Kind of angle:',
                     draw='Points plotted at (1, 1), (5, 1) and (1, 4) and joined to make a triangle', key='Right angle',
                     note='Grade both: the three points joined, and "right angle".'),
          tf('On a map grid, a store is at (6, 3) and a bank is at (2, 3). They are 8 units apart.', key=False),
      ]),
      f2=B('Draw polygons in the coordinate plane', '6.G.A.3', [
          draw_write('Plot A(-3, 2), B(3, 2), C(3, -2), and D(-3, -2). Connect them in order.\nWhat is the most specific name for the polygon?', coord(),
                     'Name:', draw='A, B, C and D plotted and joined in order A-B-C-D-A', key='Rectangle',
                     note='Grade both: the four points joined in order, and "rectangle" (sides 6 and 4 units, four right angles).'),
          sa('What is the length of the side from (-2, 4) to (5, 4)?', 'Length:', key='7 units'),
          mc('Three vertices of a square are (0, 0), (4, 0), and (4, 4).\nWhat is the fourth vertex?', ['(0, 4)', '(4, 8)', '(8, 4)', '(0, 8)']),
          tf('The points (1, 1), (1, 5), and (4, 1) are the vertices of a right triangle.', key=True),
          tf('The side from (-3, -1) to (2, -1) is 1 unit long.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.MD.C.7 (additive)
    S('4.MD.C.7', 'Angle measure is additive',
      main=[
          sa('Angle ABC is split into two angles of 35° and 50°.\nWhat is the measure of angle ABC?', 'Measure:', key='85°',
             fig=angles([0, 35, 85], [(17, '35°'), (60, '50°')],
                        desc='An angle split by a ray into two parts: 35° (lower) and 50° (upper).')),
          tf('A 90° angle is split into two angles. One is 40°, so the other is 50°.', key=True),
          mc('Angles of 65° and 25° are side by side with no overlap.\nWhat angle do they make together?', ['90°', '40°', '100°', '80°']),
          sa('Angles of 30°, 45°, and 60° are side by side with no overlap.\nWhat angle do they make together?', 'Measure:', key='135°'),
          tf('An angle of 120° can be split into angles of 70° and 60°.', key=False),
      ],
      back=[
          B('Add within 100', '2.NBT.B.5', [
              sa('Add.\n35 + 50', 'Sum:', key='85'),
              tf('65 + 25 = 90', key=True),
              mc('45 + 38 = ?', ['83', '73', '93', '713']),
              sa('Add.\n27 + 46', 'Sum:', key='73'),
              tf('58 + 34 = 82', key=False),
          ]),
          B('Area is additive', '3.MD.C.7.d', [
              sa('A figure is made of two rectangles that do not overlap. Their areas are 12 and 15 square units.\nWhat is the area of the figure?', 'Area:',
                 key='27 square units'),
              tf('The area of a figure made of parts that do not overlap is the sum of the areas of the parts.', key=True),
              mc('A figure is made of two rectangles that do not overlap. Their areas are 12 and 6 square units.\nWhat is the area of the figure?',
                 ['18 square units', '12 square units', '72 square units', '6 square units']),
              sa('Two squares that do not overlap have areas of 9 and 16 square units.\nWhat is their total area?', 'Area:', key='25 square units'),
              tf('Two rectangles of 10 and 6 square units that do not overlap have a total area of 60 square units.', key=False),
          ]),
      ],
      f1=B('Volume is additive', '5.MD.C.5.c', nearest=True, qs=[
          sa('Two prisms that do not overlap have volumes of 24 and 36 cubic units.\nWhat is their total volume?', 'Volume:', key='60 cubic units'),
          tf('A figure made of a 2-by-3-by-4 prism and a 1-by-3-by-4 prism has a volume of 36 cubic units.', key=True),
          mc('A figure is made of a 5-by-2-by-2 prism and a 3-by-2-by-1 prism that do not overlap.\nWhat is its volume?',
             ['26 cubic units', '20 cubic units', '6 cubic units', '120 cubic units']),
          sa('A building is a 9-by-6-by-5 prism with a 3-by-6-by-2 prism attached.\nWhat is its total volume?', 'Volume:', key='306 cubic units'),
          tf('The volume of two prisms that touch is the product of their volumes.', key=False),
      ]),
      f2=B('Write expressions and equations for parts of an angle', '6.EE.B.6', nearest=True, qs=[
          sa('An angle is split into two parts, x° and 40°.\nWrite an expression for the measure of the whole angle.', 'Expression:', key='x + 40'),
          tf('A 90° angle is split into x° and 25°, so x + 25 = 90.', key=True),
          mc('Two equal angles of n° make a straight angle (180°).\nWhich equation is true?', ['2n = 180', 'n + 180 = 2', 'n = 180', '2 + n = 180']),
          sa('Three equal angles of a° make a full turn (360°).\nWrite an equation.', 'Equation:', key='3a = 360', note='a + a + a = 360 is also correct.'),
          tf('An angle made of parts of y° and 30° measures 30y°.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.MD.C.7 (unknown angles)
    S('4.MD.C.7', 'Solve for unknown angles in diagrams and real-world problems with an equation',
      main=[
          sa('The whole angle is a right angle (90°).\nWrite an equation with a letter for the unknown part. Then solve it.', ['Equation:', 'Unknown angle:'],
             key='x + 28 = 90; x = 62°', note='Any equivalent equation with a letter is correct. Both parts are required.',
             fig=angles([0, 62, 90], [(31, 'x°', 0.7), (76, '28°', 0.62)], ra=[0],
                        desc='A right angle split by a ray into two parts: x° (lower) and 28° (upper). A right-angle mark is shown.')),
          sa('The whole angle is 150°.\nWrite an equation with a letter for the unknown part. Then solve it.', ['Equation:', 'Unknown angle:'],
             key='95 + a = 150; a = 55°', note='Any equivalent equation with a letter is correct. Both parts are required.',
             fig=angles([0, 95, 150], [(47, '95°'), (122, 'a°')],
                        desc='An angle of 150° split by a ray into two parts: 95° (right) and a° (left).')),
          mc('A straight angle (180°) is split into angles of 110° and m°.\nWhich equation can be used to find m?',
             ['110 + m = 180', '110 + m = 90', 'm = 110 + 180', 'm - 110 = 180'],
             fig=angles([0, 70, 180], [(35, 'm°'), (125, '110°')],
                        desc='A straight line with a ray from a point on it, making angles of m° (right) and 110° (left).')),
          tf('A door opens 35° and then 40° more. It has turned through 75° in all.', key=True),
          sa('A skater turns 90° and then 135° in the same direction.\nHow many degrees did she turn in all? How many more degrees would make a full turn (360°)?',
             ['Total turn:', 'More to a full turn:'], key='225°; 135°'),
      ],
      back=[
          B('Solve one-step word problems with an unknown in any position', '2.OA.A.1', [
              sa('A box had some crayons. After 28 more crayons were put in, it had 90 crayons.\nHow many crayons were in the box at first?', 'Crayons:',
                 key='62'),
              tf('Kim had 45 stickers. She got some more, and now she has 80. She got 35 stickers.', key=True),
              mc('Some birds were on a fence. 37 more birds came, and then there were 60 birds.\nHow many birds were on the fence at first?',
                 ['23', '97', '33', '27']),
              sa('Ty had 100 cards. He gave some away and has 64 left.\nHow many cards did he give away?', 'Cards:', key='36'),
              tf('A shelf had some books. 19 more books were added, making 50 books. There were 41 books at first.', key=False),
          ]),
          B('Find an unknown in an equation within 20', '1.OA.D.8', [
              sa('Find the unknown number.\n8 + ? = 15', 'Unknown:', key='7'),
              tf('If 6 + n = 13, then n = 7.', key=True),
              mc('? - 4 = 9', ['13', '5', '4', '12']),
              sa('Find the unknown number.\n14 - ? = 6', 'Unknown:', key='8'),
              tf('If 9 + n = 17, then n = 9.', key=False),
          ]),
      ],
      f1=B('Evaluate expressions with grouping symbols', '5.OA.A.1', [
          sa('Evaluate.\n180 - (45 + 60)', 'Value:', key='75'),
          tf('360 - (90 + 90 + 120) = 60', key=True),
          mc('Evaluate.\n90 - (12 + 33)', ['45', '111', '69', '35']),
          sa('Evaluate.\n[360 - (100 + 80)] ÷ 2', 'Value:', key='90'),
          tf('180 - 50 + 30 = 100', key=False),
      ]),
      f2=B('Write and solve one-step equations for unknown angles', '6.EE.B.7', nearest=True, qs=[
          sa('Two equal angles together make 130°.\nWrite and solve an equation for each angle, x.', ['Equation:', 'x ='], key='2x = 130; x = 65°',
             note='Any equivalent equation is correct. Both parts are required.'),
          tf('If 4 equal angles make a full turn of 360°, each angle is 90°.', key=True),
          mc('Solve for x.\nx + 72 = 180', ['108', '252', '118', '98']),
          sa('Five equal angles meet at a point and make 360°.\nWrite and solve an equation for each angle, a.', ['Equation:', 'a ='],
             key='5a = 360; a = 72°', note='Any equivalent equation is correct. Both parts are required.'),
          tf('If x + 45 = 90, then x = 135.', key=False),
      ])),
]
