from qb import S, B, sa, mc, tf, table, tape, plot, work, DIVISION_ALGORITHM
from common import arr, grid

SETS = [
    # ------------------------------------------------------------------ 4.OA.A.1 (interpret)
    S('4.OA.A.1', 'Interpret a multiplication equation as a comparison',
      main=[
          mc('Which statement matches 24 = 6 × 4?', ['24 is 6 times as many as 4.', '24 is 6 more than 4.',
                                                    '6 is 4 times as many as 24.', '24 is 4 more than 6.']),
          sa('Write a comparison statement for 45 = 9 × 5.', 'Statement:', key='45 is 9 times as many as 5.',
             note='"45 is 5 times as many as 9" is also correct. A statement with "more than" is not correct.'),
          tf('56 = 7 × 8 can mean that 56 is 8 times as many as 7.', key=True),
          tf('18 = 3 × 6 means that 18 is 3 more than 6.', key=False),
          mc('Which equation means "63 is 7 times as many as 9"?', ['63 = 7 × 9', '63 = 7 + 9', '63 = 9 - 7', '7 = 63 × 9']),
      ],
      back=[
          B('Products as equal groups', '3.OA.A.1', [
              sa('What is the total in 4 groups of 6?', 'Total:', key='24'),
              tf('5 × 3 can mean 5 groups with 3 objects in each group.', key=True),
              mc('Which expression shows 3 groups of 7?', ['3 × 7', '3 + 7', '7 - 3', '7 ÷ 3']),
              sa('Write a multiplication equation for 6 groups of 2.', 'Equation:', key='6 × 2 = 12'),
              tf('2 × 8 means 2 more than 8.', key=False),
          ]),
          B('Multiplication facts within 100', '3.OA.C.7', [
              sa('Multiply.\n9 × 5', 'Product:', key='45'),
              tf('7 × 8 = 54', key=False),
              mc('6 × 4 = ?', ['24', '20', '28', '10']),
              sa('Multiply.\n8 × 6', 'Product:', key='48'),
              sa('Multiply.\n7 × 9', 'Product:', key='63'),
          ]),
      ],
      f1=B('Compare the size of a product to the size of one factor', '5.NF.B.5.a', [
          mc('Without multiplying, how does 3 × 25 compare with 25?',
             ['It is 3 times as large.', 'It is 3 more.', 'It is smaller than 25.', 'It is equal to 25.']),
          tf('{1/2} × 40 is less than 40.', key=True),
          sa('A rope is 12 feet long. A second rope is 2{1/2} times as long.\nWithout multiplying, is the second rope longer or shorter than the first rope? Explain.',
             ['Answer:', 'Explanation:'], key='Longer',
             note='Explanation: 2 1/2 is greater than 1, so 2 1/2 times 12 feet is more than 12 feet. The comparison and this reason are both '
                  'required; computing 30 feet without comparing the scale factor with 1 is not full credit.'),
          tf('5 × 18 is less than 18.', key=False),
          mc('Which product is greater than 30?', ['2 × 30', '{1/3} × 30', '{3/4} × 30', '{1/2} × 30']),
      ]),
      f2=B('Use ratio language to describe a relationship', '6.RP.A.1', [
          sa('A class has 12 girls and 4 boys.\nWrite the ratio of girls to boys.', 'Ratio:', key='12 : 4',
             note='3 : 1, 12 to 4, and 12/4 are also correct.'),
          tf('If there are 3 times as many cats as dogs, the ratio of cats to dogs is 3 : 1.', key=True),
          mc('A bag has 5 red marbles for every 2 blue marbles.\nWhich statement describes the ratio?',
             ['For every 5 red marbles there are 2 blue marbles.', 'There are 5 more red marbles than blue.',
              'There are 2 times as many red marbles as blue.', 'There are 7 red marbles.']),
          sa('There are 18 apples and 6 pears.\nHow many apples are there for every 1 pear?', 'Apples:', key='3'),
          tf('The ratio 2 : 8 means there are 2 times as many of the first quantity as the second.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.1 (write)
    S('4.OA.A.1', 'Write a comparison statement as a multiplication equation',
      main=[
          sa('Write an equation.\n32 is 4 times as many as 8.', 'Equation:', key='32 = 4 × 8', note='32 = 8 × 4 is also correct.'),
          mc('Kai has 5 stickers. Lena has 3 times as many stickers as Kai.\nWhich equation gives Lena\'s stickers, s?',
             ['s = 3 × 5', 's = 3 + 5', 's = 5 - 3', 's = 5 ÷ 3']),
          sa('Write an equation.\n54 is 6 times as many as 9.', 'Equation:', key='54 = 6 × 9', note='54 = 9 × 6 is also correct.'),
          tf('"40 is 8 times as many as 5" can be written as 40 = 8 + 5.', key=False),
          sa('A tree is 7 times as tall as a 2-meter bush.\nWrite an equation for the tree\'s height, t.', 'Equation:', key='t = 7 × 2',
             note='t = 2 × 7 is also correct. (The tree is 14 meters tall.)'),
      ],
      back=[
          B('Multiplication word problems within 100', '3.OA.A.3', [
              sa('There are 6 boxes with 8 crayons in each box.\nHow many crayons are there?', 'Crayons:', key='48'),
              tf('5 bags with 9 apples in each bag hold 45 apples.', key=True),
              mc('A garden has 4 rows with 7 plants in each row.\nHow many plants are there?', ['28', '11', '21', '32']),
              sa('Each pack has 3 juice boxes.\nHow many juice boxes are in 9 packs?', 'Juice boxes:', key='27'),
              tf('8 teams with 5 players each have 13 players in all.', key=False),
          ]),
          B('Find the unknown number in a multiplication equation', '3.OA.A.4', [
              sa('Find the unknown number.\n? × 6 = 30', 'Unknown:', key='5'),
              tf('If 4 × n = 36, then n = 8.', key=False),
              mc('8 × ? = 56', ['7', '6', '8', '48']),
              sa('Find the unknown number.\n3 × ? = 27', 'Unknown:', key='9'),
              tf('If m × 7 = 42, then m = 6.', key=True),
          ]),
      ],
      f1=B('Write numerical expressions from words', '5.OA.A.2', [
          sa('Write an expression.\n3 times the sum of 8 and 4', 'Expression:', key='3 × (8 + 4)'),
          mc('Which expression means "add 9 and 6, then multiply by 2"?', ['(9 + 6) × 2', '9 + 6 × 2', '9 × 6 + 2', '2 + 9 × 6']),
          tf('5 × (12 - 3) is 5 times as large as 12 - 3.', key=True),
          sa('Write an expression.\n4 times as large as 25 + 15', 'Expression:', key='4 × (25 + 15)'),
          tf('2 × (7 + 1) is 2 more than 7 + 1.', key=False),
      ]),
      f2=B('Write expressions that use a variable', '6.EE.A.2.a', [
          sa('Write an expression for 5 times a number n.', 'Expression:', key='5n', note='5 × n is also correct.'),
          mc('Which expression means "8 more than y"?', ['y + 8', '8y', 'y - 8', '8 - y']),
          sa('Maya has m marbles. Jo has 4 times as many marbles as Maya.\nWrite an expression for Jo\'s marbles.', 'Expression:', key='4m',
             note='4 × m is also correct.'),
          tf('"3 times the sum of x and 2" can be written as 3(x + 2).', key=True),
          tf('"7 less than k" can be written as 7 - k.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.2 (multiply)
    S('4.OA.A.2', 'Solve multiplicative comparison word problems by multiplying',
      main=[
          sa('A puppy weighs 6 pounds. Its mother weighs 8 times as much.\nHow much does the mother weigh?', 'Weight:', key='48 pounds',
             fig=tape(dict(name='Puppy', n=1, seg='6'), dict(name='Mother', n=8, seg='6'))),
          sa('Sam read 9 pages. Ana read 5 times as many pages as Sam.\nHow many pages did Ana read?', 'Pages:', key='45'),
          mc('A red ribbon is 7 inches long. A blue ribbon is 6 times as long.\nHow long is the blue ribbon?',
             ['42 inches', '13 inches', '1 inch', '48 inches']),
          sa('A small tank holds 9 gallons. A large tank holds 7 times as much.\nHow much does the large tank hold?', 'Gallons:', key='63'),
          tf('A bike costs $80. A used car costs 100 times as much. The car costs $800.', key=False),
      ],
      back=[
          B('Multiplication word problems within 100', '3.OA.A.3', [
              sa('7 vans each carry 8 students.\nHow many students are there in all?', 'Students:', key='56'),
              sa('4 children each have 9 crayons.\nHow many crayons are there in all?', 'Crayons:', key='36'),
              tf('6 rows of 6 chairs make 36 chairs.', key=True),
              mc('A book has 9 chapters with 9 pages in each chapter.\nHow many pages does it have?', ['81', '18', '72', '90']),
              tf('5 piles with 8 cards in each pile make 45 cards.', key=False),
          ]),
          B('Multiply in either order', '3.OA.B.5', [
              tf('6 × 8 = 8 × 6', key=True),
              sa('Fill in the blank.\n9 × 4 = 4 × ___', 'Blank:', key='9'),
              mc('Which is equal to 7 × 5?', ['5 × 7', '7 + 5', '75', '5 + 5 + 5']),
              sa('3 × 9 = 27.\nWhat is 9 × 3?', 'Product:', key='27'),
              tf('8 × 2 = 2 + 8', key=False),
          ]),
      ],
      f1=B('Solve real-world problems by multiplying by a fraction or mixed number', '5.NF.B.6', [
          sa('A pup weighs 6 pounds. An adult dog weighs 4{1/2} times as much.\nHow much does the adult weigh?', 'Weight:', key='27 pounds'),
          sa('A path is 12 miles long. Kim walked {2/3} of the path.\nHow far did she walk?', 'Distance:', key='8 miles'),
          mc('A red rope is 8 feet long. A blue rope is 1{1/4} times as long.\nHow long is the blue rope?',
             ['10 feet', '9{1/4} feet', '2 feet', '6 feet']),
          tf('A 10-cm plant grows until it is 2{1/2} times as tall. It is then 25 cm tall.', key=True),
          sa('A recipe uses 3 cups of flour. Mia makes {1/2} of the recipe.\nHow much flour does she use?', 'Flour:', key='1 1/2 cups'),
      ]),
      f2=B('Solve unit rate problems', '6.RP.A.3.b', [
          sa('5 notebooks cost $15.\nAt the same price, how much do 8 notebooks cost?', 'Cost:', key='$24'),
          tf('If 4 pounds of grapes cost $10, then 1 pound costs $2.50.', key=True),
          mc('A car goes 180 miles in 3 hours at a steady speed.\nHow far does it go in 5 hours?', ['300 miles', '240 miles', '360 miles', '185 miles']),
          sa('A printer prints 42 pages in 6 minutes.\nHow many pages does it print per minute?', 'Pages per minute:', key='7'),
          tf('If 3 tickets cost $27, then 7 tickets cost $56.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.2 (divide)
    S('4.OA.A.2', 'Solve multiplicative comparison word problems by dividing',
      main=[
          sa('A dog weighs 48 pounds. That is 6 times as much as a cat weighs.\nHow much does the cat weigh?', 'Weight:', key='8 pounds'),
          sa('Leo has 72 cards. That is 9 times as many cards as Ty has.\nHow many cards does Ty have?', 'Cards:', key='8'),
          mc('A building is 60 feet tall. That is 5 times as tall as a tree.\nHow tall is the tree?', ['12 feet', '55 feet', '300 feet', '65 feet']),
          sa('A jacket costs $56. A hat costs $8.\nThe jacket costs how many times as much as the hat?', 'Times as much:', key='7'),
          tf('Mo ran 36 laps. That is 4 times as many laps as Ed ran. Ed ran 9 laps.', key=True),
      ],
      back=[
          B('Division as an unknown-factor problem', '3.OA.B.6', [
              sa('Find 42 ÷ 6 by thinking 6 × ? = 42.', 'Quotient:', key='7'),
              tf('54 ÷ 9 = 6 because 9 × 6 = 54.', key=True),
              mc('Which fact helps you find 63 ÷ 7?', ['7 × 9 = 63', '7 × 7 = 49', '63 - 7 = 56', '9 + 7 = 16']),
              sa('Divide.\n32 ÷ 8', 'Quotient:', key='4'),
              tf('48 ÷ 6 = 9 because 6 × 9 = 48.', key=False),
          ]),
          B('Find the unknown number in a multiplication or division equation', '3.OA.A.4', [
              sa('Find the unknown number.\n5 × ? = 40', 'Unknown:', key='8'),
              tf('If 27 ÷ ? = 3, the unknown number is 9.', key=True),
              mc('? × 9 = 72', ['8', '9', '63', '81']),
              sa('Find the unknown number.\n? ÷ 4 = 6', 'Unknown:', key='24'),
              tf('If 6 × ? = 36, the unknown number is 5.', key=False),
          ]),
      ],
      f1=B('Solve division word problems with two-digit divisors', '5.NBT.B.6', [
          sa('A truck carries 384 boxes. That is 12 times as many boxes as a van carries.\nHow many boxes does the van carry?', 'Boxes:', key='32'),
          mc('A school has 864 students in 24 classes of the same size.\nHow many students are in each class?', ['36', '34', '38', '840']),
          tf('1,050 ÷ 15 = 70', key=True),
          sa('Divide.\n2,016 ÷ 36', 'Quotient:', key='56'),
          tf('A farm has 630 trees in rows of 18 trees. There are 45 rows.', key=False),
      ]),
      f2=B('Solve one-step equations of the form px = q', '6.EE.B.7', [
          sa('Solve for c.\n6c = 48', 'c =', key='8'),
          tf('The solution of 9x = 72 is x = 8.', key=True),
          mc('Solve for n.\n5n = 65', ['13', '60', '70', '325']),
          sa('A dog weighs 48 pounds, which is 6 times the weight c of a cat.\nWrite and solve an equation for c.', ['Equation:', 'c ='],
             key='6c = 48; c = 8 pounds', note='Any equivalent equation is correct. Both parts are required.'),
          tf('The solution of 4y = 36 is y = 32.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.2 (multiplicative vs additive)
    S('4.OA.A.2', 'Tell multiplicative comparison from additive comparison',
      main=[
          mc('Ana has 4 shells. Ben has 12 shells.\nWhich statement is true?',
             ['Ben has 3 times as many shells as Ana.', 'Ben has 3 more shells than Ana.',
              'Ana has 8 times as many shells as Ben.', 'Ben has 4 more shells than Ana.']),
          sa('The red team scored 24 points. The blue team scored 6 points.\nHow many more points did the red team score? How many times as many points?',
             ['How many more:', 'How many times as many:'], key='18 more; 4 times as many'),
          tf('"8 more than 5" is 40.', key=False),
          mc('Which question is answered by multiplying?',
             ['A cat is 3 years old. A dog is 4 times as old. How old is the dog?',
              'A cat is 3 years old. A dog is 4 years older. How old is the dog?',
              'A cat is 7 years old. A dog is 3 years old. How much older is the cat?',
              'A cat ate 4 treats and then 3 more. How many did it eat?']),
          tf('A pencil is 6 inches long. A ruler that is 2 times as long is 12 inches, but a crayon that is 2 inches longer than the pencil is 8 inches.', key=True),
      ],
      back=[
          B('Compare quantities by adding or subtracting', '2.OA.A.1', [
              sa('Jo has 15 stamps. Ty has 9 stamps.\nHow many more stamps does Jo have?', 'Stamps:', key='6'),
              tf('Mia has 8 beads. That is 5 more beads than Kim has. Kim has 3 beads.', key=True),
              mc('A red rope is 34 cm long. A green rope is 18 cm long.\nHow much longer is the red rope?', ['16 cm', '52 cm', '14 cm', '26 cm']),
              sa('A tower has 27 blocks. Another tower has 8 more blocks.\nHow many blocks does it have?', 'Blocks:', key='35'),
              tf('Sam has 20 cards. Lee has 6 fewer cards. Lee has 26 cards.', key=False),
          ]),
          B('Multiplication facts within 100', '3.OA.C.7', [
              sa('Multiply.\n4 × 9', 'Product:', key='36'),
              tf('6 × 7 = 42', key=True),
              mc('3 × 8 = ?', ['24', '11', '21', '32']),
              sa('Multiply.\n5 × 6', 'Product:', key='30'),
              tf('8 × 8 = 16', key=False),
          ]),
      ],
      f1=B('Interpret numerical expressions without evaluating them', '5.OA.A.2', [
          tf('6 × (25 + 9) is 6 times as large as 25 + 9.', key=True),
          mc('How does 4 × (17 - 3) compare with 17 - 3?', ['It is 4 times as large.', 'It is 4 more.', 'It is 4 less.', 'It is the same.']),
          tf('(48 + 6) + 3 is 3 times as large as 48 + 6.', key=False),
          sa('Without calculating, how does 10 × (325 + 19) compare with 325 + 19?', 'Answer:', key='It is 10 times as large.'),
          mc('Which expression is 2 more than 9 × 7?', ['9 × 7 + 2', '2 × 9 × 7', '(9 + 2) × 7', '9 × (7 + 2)']),
      ]),
      f2=B('Tell an additive relationship from a multiplicative one in tables and equations', '6.EE.C.9', [
          mc('Which equation shows that y is always 4 times x?', ['y = 4x', 'y = x + 4', 'x = 4y', 'y = x - 4']),
          tf('The table fits the equation y = 5x.', key=False, fig=table([['x', '1', '2', '3'], ['y', '5', '6', '7']])),
          sa('Write an equation for y in terms of x.', 'Equation:', key='y = 3x', fig=table([['x', '2', '4', '6'], ['y', '6', '12', '18']])),
          sa('Write an equation for y in terms of x.', 'Equation:', key='y = x + 3', fig=table([['x', '2', '4', '6'], ['y', '5', '7', '9']])),
          tf('In y = x + 6, y is always 6 more than x.', key=True),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.3 (multistep with a letter)
    S('4.OA.A.3', 'Solve multistep word problems and write an equation with a letter for the unknown',
      main=[
          sa('A school bought 8 packs of 24 pencils. It gave away 57 pencils.\nWrite an equation with a letter for the number of pencils left. Then solve it.',
             ['Equation:', 'Pencils left:'], key='p = 8 × 24 - 57; p = 135',
             note='Any equivalent equation with a letter is correct. 8 × 24 = 192 and 192 - 57 = 135. Both parts are required.'),
          sa('Ty has $250. He buys 3 games that cost $45 each.\nWrite an equation with a letter for the money left. Then solve it.',
             ['Equation:', 'Money left:'], key='m = 250 - 3 × 45; m = $115',
             note='Any equivalent equation with a letter is correct. 3 × 45 = 135 and 250 - 135 = 115. Both parts are required.'),
          mc('A farmer has 6 crates with 35 apples in each crate. She sells 98 apples.\nWhich equation gives the number of apples left, a?',
             ['a = 6 × 35 - 98', 'a = 6 + 35 - 98', 'a = 6 × (35 - 98)', 'a = 98 - 6 × 35']),
          sa('Tickets cost $9 for adults and $6 for children. A group buys 4 adult tickets and 7 child tickets.\nWrite an equation with a letter for the total cost. Then solve it.',
             ['Equation:', 'Total cost:'], key='c = 4 × 9 + 7 × 6; c = $78',
             note='Any equivalent equation with a letter is correct. 36 + 42 = 78. Both parts are required.'),
          tf('A baker makes 128 rolls and puts them in bags of 8. She sells 11 bags. The equation b = 128 ÷ 8 - 11 gives the bags left, and b = 5.', key=True),
      ],
      back=[
          B('Subtract within 1000', '3.NBT.A.2', num=2, qs=[
              sa('Subtract.\n725 - 257', 'Difference:', key='468'),
              sa('Subtract.\n803 - 469', 'Difference:', key='334'),
              tf('825 - 475 = 350', key=True),
              mc('612 - 238 = ?', ['374', '484', '386', '850']),
              tf('900 - 345 = 665', key=False),
          ]),
          B('One-step equal-groups problems with a symbol for the unknown', '3.OA.A.3', num=3, qs=[
              sa('There are 8 packs with 6 pencils in each pack.\nWrite an equation with a symbol for the total number of pencils. Then find the total.',
                 ['Equation:', 'Pencils:'], key='8 × 6 = p; p = 48',
                 note='Any equation with a symbol for the total (such as 8 × 6 = ? or p = 6 × 8) is correct. Both parts are required.'),
              tf('Ann buys 3 packs with 8 beads in each pack. The equation 3 × 8 = b gives the number of beads she buys, and b = 24.', key=True),
              mc('There are 7 rows with 6 chairs in each row.\nWhich equation gives the number of chairs, c?', ['7 × 6 = c', '7 + 6 = c', '7 - 6 = c', '7 ÷ 6 = c']),
              sa('Leo has 3 boxes with 9 markers in each box.\nHow many markers does he have?', 'Markers:', key='27'),
              tf('6 bags with 9 oranges in each bag hold 15 oranges.', key=False),
          ]),
      ],
      f1=B('Evaluate expressions with parentheses, brackets, and braces', '5.OA.A.1', [
          sa('Evaluate.\n8 × 24 - 57', 'Value:', key='135'),
          sa('Evaluate.\n250 - 3 × 45', 'Value:', key='115'),
          mc('Evaluate.\n(36 + 12) ÷ 6', ['8', '38', '12', '42']),
          tf('4 × (9 + 6) = 42', key=False),
          sa('Evaluate.\n[40 - (5 × 6)] × 3', 'Value:', key='30'),
      ]),
      f2=B('Use variables to write expressions for real-world problems', '6.EE.B.6', [
          sa('Pens cost $3 each.\nWrite an expression for the cost of p pens.', 'Expression:', key='3p', note='3 × p is also correct.'),
          mc('Ty has 40 stickers and gives away s stickers.\nWhich expression shows how many he has left?', ['40 - s', 's - 40', '40s', '40 + s']),
          sa('A movie ticket costs $9 and a popcorn costs $4.\nWrite an expression for the cost of t tickets and one popcorn.', 'Expression:',
             key='9t + 4'),
          tf('If n is the number of packs with 12 cards in each pack, then 12n is the total number of cards.', key=True),
          tf('The expression 5 + b means 5 times b.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.3 (remainders)
    S('4.OA.A.3', 'Interpret remainders in word problems',
      main=[
          sa('29 students ride in cars that hold 4 students each.\nHow many cars are needed?', 'Cars:', key='8',
             note='29 ÷ 4 = 7 R 1. The 1 extra student needs another car, so 8 cars.'),
          sa('A baker has 50 muffins. She puts 6 muffins in each box.\nHow many boxes can she fill completely?', 'Boxes:', key='8',
             note='50 ÷ 6 = 8 R 2. The 2 left over do not fill a box.'),
          mc('Ella shares 35 stickers equally among 4 friends.\nHow many stickers are left over?', ['3', '8', '4', '1']),
          sa('A rope 46 feet long is cut into 5-foot pieces.\nHow many full pieces are there, and how much rope is left over?',
             ['Full pieces:', 'Left over:'], key='9 pieces; 1 foot'),
          tf('70 people need tables that seat 8 people each. They need 8 tables.', key=False),
      ],
      back=[
          B('Quotients as shares or as groups', '3.OA.A.2', [
              sa('24 pencils are shared equally by 6 students.\nHow many pencils does each student get?', 'Pencils:', key='4'),
              tf('30 ÷ 5 can mean 30 objects put into groups of 5.', key=True),
              mc('Which question does 18 ÷ 3 answer?', ['How many groups of 3 are in 18?', 'What is 3 more than 18?',
                                                         'How many are in 18 groups of 3?', 'What is 18 take away 3?']),
              sa('40 crayons are put into boxes of 8.\nHow many boxes are filled?', 'Boxes:', key='5'),
              tf('12 ÷ 4 means 12 groups of 4.', key=False),
          ]),
          B('Division facts within 100', '3.OA.C.7', [
              sa('Divide.\n56 ÷ 7', 'Quotient:', key='8'),
              tf('45 ÷ 5 = 9', key=True),
              mc('64 ÷ 8 = ?', ['8', '7', '9', '56']),
              sa('Divide.\n36 ÷ 4', 'Quotient:', key='9'),
              tf('81 ÷ 9 = 8', key=False),
          ]),
      ],
      f1=B('Interpret a fraction as division to write a remainder as a fraction', '5.NF.B.3', [
          sa('3 friends share 7 pizzas equally.\nHow much pizza does each friend get? Write a mixed number.', 'Pizza:', key='2 1/3 pizzas'),
          tf('When 9 feet of ribbon is cut into 4 equal pieces, each piece is 2{1/4} feet long.', key=True),
          mc('5 sandwiches are shared equally by 2 people.\nHow much does each person get?', ['2{1/2} sandwiches', '2 sandwiches', '{2/5} sandwich', '3 sandwiches']),
          sa('Write 17 ÷ 5 as a mixed number.', 'Mixed number:', key='3 2/5'),
          tf('11 ÷ 4 = 2{1/4}', key=False),
      ]),
      f2=B('Divide multi-digit numbers with the standard algorithm', '6.NS.B.2', [
          work('Use the standard algorithm to divide. Show your work.\n4,368 ÷ 52', 'Quotient:', method=DIVISION_ALGORITHM, key='84'),
          sa('Divide.\n7,695 ÷ 81', 'Quotient:', key='95'),
          mc('Divide.\n9,072 ÷ 36', ['252', '242', '262', '25']),
          sa('Divide. Write the quotient and the remainder.\n1,000 ÷ 23', ['Quotient:', 'Remainder:'], key='43 R 11'),
          tf('3,240 ÷ 45 = 72', key=True),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.3 (multistep with a remainder) — added in 2.0.0
    S('4.OA.A.3', 'Solve multistep word problems in which a remainder must be interpreted', num=65,
      main=[
          sa('32 students are going on a trip, but 3 students stay home. The rest ride in cars that hold 4 students each.\n'
             'Write an equation with a letter for the number of students who ride. Then find how many cars are needed.',
             ['Equation:', 'Cars needed:'], key='s = 32 - 3, so s = 29; 8 cars',
             note='Any equivalent equation with a letter is correct. 29 ÷ 4 = 7 R 1, and the 1 extra student needs another car, '
                  'so 8 cars (not 7, and not 7 R 1). Both parts are required.'),
          sa('A baker makes 4 trays of 15 muffins. She packs all the muffins in boxes that hold 8 muffins each.\n'
             'How many boxes can she fill completely? How many muffins are left over?', ['Full boxes:', 'Left over:'],
             key='7 full boxes; 4 muffins left over', note='4 × 15 = 60 and 60 ÷ 8 = 7 R 4. Both parts are required.'),
          mc('A class has $100. It buys a game for $30, then spends the rest on puzzles that cost $9 each.\nHow many puzzles can it buy?',
             ['7', '8', '11', '9']),
          sa('Ms. Ruiz has 3 bags with 18 apples in each bag. She puts all the apples in baskets that hold 5 apples each.\n'
             'Write an equation with a letter for the number of apples. Then find the fewest baskets she needs.',
             ['Equation:', 'Baskets:'], key='a = 3 × 18, so a = 54; 11 baskets',
             note='Any equivalent equation with a letter is correct. 54 ÷ 5 = 10 R 4, and the 4 extra apples need an 11th basket. '
                  'Both parts are required.'),
          tf('Ty has 50 feet of ribbon. He uses 8 feet for a bow and cuts the rest into 5-foot pieces. He gets 8 full pieces, and 2 feet are left over.',
             key=True),
      ],
      back=[
          B('Division word problems within 100', '3.OA.A.3', [
              sa('28 students ride in 4 cars with the same number of students in each car.\nHow many students ride in each car?', 'Students:', key='7'),
              tf('48 muffins packed 8 to a box fill 6 boxes.', key=True),
              mc('A coach puts 45 balls into 5 bins with the same number in each bin.\nHow many balls are in each bin?', ['9', '8', '40', '50']),
              sa('Ty cuts 36 feet of rope into 4-foot pieces.\nHow many pieces does he get?', 'Pieces:', key='9'),
              tf('63 apples shared equally by 9 baskets puts 8 apples in each basket.', key=False),
          ]),
          B('Subtract within 1000', '3.NBT.A.2', [
              sa('Subtract.\n100 - 28', 'Difference:', key='72'),
              tf('250 - 76 = 174', key=True),
              mc('512 - 145 = ?', ['367', '433', '377', '657']),
              sa('Subtract.\n403 - 167', 'Difference:', key='236'),
              tf('600 - 254 = 356', key=False),
          ]),
      ],
      f1=B('Interpret the quotient in multistep problems with two-digit divisors', '5.NBT.B.6', [
          sa('A school has 412 students, and 20 are absent. The rest ride buses that hold 48 students each.\nHow many buses are needed?',
             'Buses:', key='9', note='412 - 20 = 392 and 392 ÷ 48 = 8 R 8. The 8 extra students need another bus, so 9 buses.'),
          tf('A farm packs 4 crates of 96 eggs into cartons of 12. It fills exactly 32 cartons.', key=True),
          mc('A club has $500. It spends $86 on snacks and the rest on tickets that cost $25 each.\nHow many tickets can it buy?',
             ['16', '17', '20', '414']),
          sa('A printer makes 3 boxes of 250 cards. The cards are tied in stacks of 35.\nHow many full stacks are there? How many cards are left over?',
             ['Full stacks:', 'Left over:'], key='21 full stacks; 15 cards left over',
             note='3 × 250 = 750 and 750 ÷ 35 = 21 R 15. Both parts are required.'),
          tf('A hall has 340 seats, and 15 are closed. The open seats are split into rows of 26. There are 13 full rows.', key=False),
      ]),
      f2=B('Divide multi-digit numbers to solve multistep problems', '6.NS.B.2', nearest=True, qs=[
          work('A theater has 2,450 seats, and 90 are closed for repairs. The open seats are sold in blocks of 24.\n'
               'Use the standard algorithm to find how many full blocks can be sold. Show your work.', 'Full blocks:',
               method=DIVISION_ALGORITHM, key='98',
               note='2,450 - 90 = 2,360 and 2,360 ÷ 24 = 98 R 8, so 98 full blocks.'),
          sa('A factory makes 6 batches of 1,250 bolts. It packs them in boxes that hold 144 bolts each.\nHow many boxes are needed to pack every bolt?',
             'Boxes:', key='53', note='6 × 1,250 = 7,500 and 7,500 ÷ 144 = 52 R 12. The 12 extra bolts need another box, so 53 boxes.'),
          mc('A charity has $5,000. It spends $310 on shipping and the rest on blankets that cost $45 each.\nHow many blankets can it buy?',
             ['104', '105', '111', '4,690']),
          sa('1,000 runners sign up for a race, and 64 do not start. The starters run in waves of 36.\nHow many waves are needed so every starter runs?',
             'Waves:', key='26', note='1,000 - 64 = 936 and 936 ÷ 36 = 26 with no remainder, so 26 waves.'),
          tf('A school orders 3 cases of 1,200 pencils and shares them equally among 28 classes. Each class gets 128 pencils, and 16 pencils are left over.',
             key=True),
      ])),

    # ------------------------------------------------------------------ 4.OA.A.3 (estimation)
    S('4.OA.A.3', 'Use rounding and mental math to check whether an answer is reasonable',
      main=[
          sa('Round each number to the nearest hundred. Then estimate the sum.\n512 + 289', ['Rounded numbers:', 'Estimate:'],
             key='500 and 300; 800', note='Both parts are required. The exact sum, 801, is not the estimate asked for.'),
          sa('Mia says 48 × 6 = 188.\nRound 48 to the nearest ten and estimate 48 × 6. Is her answer reasonable?', ['Estimate:', 'Reasonable?'],
             key='300; no', note='50 × 6 = 300, which is far from 188 (the exact product is 288). Both parts are required.'),
          mc('Round each number to the nearest ten. Which is the estimate of 73 + 28 + 41?', ['140', '130', '150', '142']),
          sa('A store had 1,215 shirts and sold 487 of them.\nRound each number to the nearest hundred to estimate how many shirts are left.', 'Estimate:',
             key='700', note='1,200 - 500 = 700. The exact answer, 728, is not the estimate asked for.'),
          tf('Rounding each number to the nearest hundred, 395 + 612 is about 900.', key=False),
      ],
      back=[
          B('Round whole numbers to the nearest 10 or 100', '3.NBT.A.1', [
              sa('Round 67 to the nearest ten.', 'Rounded:', key='70'),
              tf('348 rounded to the nearest hundred is 400.', key=False),
              mc('Round 452 to the nearest ten.', ['450', '460', '500', '400']),
              sa('Round 815 to the nearest hundred.', 'Rounded:', key='800'),
              tf('75 rounded to the nearest ten is 80.', key=True),
          ]),
          B('Check answers with rounding', '3.OA.D.8', [
              tf('Rounding each number to the nearest ten, 38 + 51 is about 90.', key=True),
              mc('Leo says 297 + 102 = 499. Rounding to the nearest hundred gives 300 + 100 = 400.\nWhat does the estimate show?',
                 ['His answer is too big.', 'His answer is correct.', 'His answer is too small.', 'An estimate cannot check a sum.']),
              sa('Round each number to the nearest ten. Then estimate.\n62 - 29', 'Estimate:', key='30'),
              tf('Rounding each number to the nearest hundred, 710 - 290 is about 600.', key=False),
              sa('Round each number to the nearest ten. Then estimate.\n47 + 33', 'Estimate:', key='80'),
          ]),
      ],
      f1=B('Round decimals to estimate', '5.NBT.A.4', [
          sa('Round each number to the nearest whole number. Then estimate.\n4.8 + 7.3', 'Estimate:', key='12'),
          tf('Rounding each number to the nearest whole number, 9.6 - 3.2 is about 7.', key=True),
          mc('Round 6.47 to the nearest tenth.', ['6.5', '6.4', '6', '7']),
          sa('Round each number to the nearest whole number. Then estimate.\n2.9 × 4.1', 'Estimate:', key='12'),
          tf('Rounding each number to the nearest whole number, 12.5 + 6.5 is about 18.', key=False),
      ]),
      f2=B('Use estimates to check computations with multi-digit decimals', '6.NS.B.3', nearest=True, qs=[
          sa('Round each number to the nearest whole number. Use your estimate to decide whether 18.75 + 6.4 = 25.15 is reasonable.',
             ['Estimate:', 'Reasonable?'], key='25; yes', note='19 + 6 = 25. Both parts are required.'),
          tf('Rounding each number to the nearest whole number, 3.9 × 5.2 is about 20, so a product of 202.8 is not reasonable.', key=True),
          mc('Ann computed 45.6 ÷ 3.8 = 1.2. Rounding each number to the nearest whole number gives 46 ÷ 4, which equals 11.5.\nWhat does this show?',
             ['Her answer is far too small.', 'Her answer is correct.', 'Her answer is too large.', 'The estimate cannot be used.']),
          sa('Multiply.\n12.4 × 3.5', 'Product:', key='43.4'),
          tf('Rounding each number to the nearest whole number, 7.1 × 2.9 is about 21, so a product of 2.059 is reasonable.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.B.4 (factor pairs)
    S('4.OA.B.4', 'Find all factor pairs of a whole number from 1 to 100',
      main=[
          sa('List all the factor pairs of 24.', 'Factor pairs:', key='1 × 24, 2 × 12, 3 × 8, 4 × 6',
             note='All four pairs are required, in any order.'),
          sa('List all the factor pairs of 45.', 'Factor pairs:', key='1 × 45, 3 × 15, 5 × 9', note='All three pairs are required.'),
          mc('Which is NOT a factor pair of 60?', ['7 × 9', '6 × 10', '4 × 15', '5 × 12']),
          tf('36 has exactly 5 factor pairs.', key=True),
          sa('How many factors does 18 have? List them.', ['How many:', 'Factors:'], key='6; 1, 2, 3, 6, 9, 18'),
      ],
      back=[
          B('Solve a division problem by finding an unknown factor', '3.OA.B.6', [
              sa('Find 24 ÷ 4 by finding the unknown factor.\n4 × ? = 24', 'Quotient:', key='6'),
              tf('32 ÷ 8 = 4 because 8 × 4 = 32.', key=True),
              mc('Which unknown-factor equation helps you find 45 ÷ 5?', ['5 × ? = 45', '45 × 5 = ?', '45 + ? = 5', '5 - ? = 45']),
              sa('Write the unknown-factor equation for 28 ÷ 7. Then find the quotient.', ['Equation:', 'Quotient:'], key='7 × ? = 28; 4',
                 note='? × 7 = 28 is also correct. Both parts are required.'),
              tf('48 ÷ 6 = 7 because 6 × 7 = 48.', key=False),
          ]),
          B('Arrays with up to 5 rows and 5 columns', '2.OA.C.4', [
              sa('How many dots are in the array?', 'Dots:', key='15', fig=arr(3, 5)),
              tf('An array with 4 rows of 5 dots has 20 dots.', key=True),
              mc('Which addition equation matches an array with 2 rows of 4?', ['4 + 4 = 8', '2 + 4 = 6', '4 - 2 = 2', '2 + 2 = 4']),
              sa('Write an addition equation for the array.', 'Equation:', key='4 + 4 + 4 = 12', fig=arr(3, 4)),
              tf('An array with 5 rows of 3 dots has 8 dots.', key=False),
          ]),
      ],
      f1=B('Use multiples to find a common denominator', '5.NF.A.1', [
          sa('Find the least common denominator of {1/4} and {1/6}.', 'Denominator:', key='12'),
          tf('{2/3} and {3/4} can both be written with a denominator of 12.', key=True),
          mc('Which is a common denominator of {1/3} and {2/5}?', ['15', '8', '10', '3']),
          sa('Rewrite {1/2} and {1/3} as fractions with a common denominator.', 'Fractions:', key='3/6 and 2/6',
             note='Any common denominator is correct (for example, 6/12 and 4/12).'),
          tf('A common denominator of {1/4} and {1/10} is 14.', key=False),
      ]),
      f2=B('Find the greatest common factor', '6.NS.B.4', [
          sa('Find the greatest common factor of 24 and 36.', 'GCF:', key='12'),
          sa('Find the greatest common factor of 18 and 45.', 'GCF:', key='9'),
          mc('What is the greatest common factor of 16 and 40?', ['8', '4', '2', '16']),
          tf('The greatest common factor of 14 and 35 is 7.', key=True),
          tf('The greatest common factor of 20 and 30 is 5.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.B.4 (multiples)
    S('4.OA.B.4', 'A whole number is a multiple of each of its factors; find multiples',
      main=[
          sa('List the first six positive multiples of 7.', 'Multiples:', key='7, 14, 21, 28, 35, 42'),
          tf('Because 6 is a factor of 42, 42 is a multiple of 6.', key=True),
          mc('Which number is a multiple of 9?', ['54', '39', '92', '19']),
          sa('Is 84 a multiple of 6? Explain.', ['Answer:', 'Explanation:'], key='Yes',
             note='6 × 14 = 84 (or 84 ÷ 6 = 14 with no remainder), so 6 is a factor of 84 and 84 is a multiple of 6.'),
          tf('70 is a multiple of 4.', key=False),
      ],
      back=[
          B('Skip count and find patterns in the multiplication table', '3.OA.D.9', [
              sa('Skip count by 6.\n6, 12, 18, ___, ___', 'Next two:', key='24, 30'),
              tf('Every number in the 5s row of the multiplication table ends in 0 or 5.', key=True),
              mc('Which number is in the 4s row of the multiplication table?', ['28', '26', '30', '18']),
              sa('What comes next?\n9, 18, 27, 36, ___', 'Next:', key='45'),
              tf('Every number in the 3s row of the multiplication table is odd.', key=False),
          ]),
          B('Odd and even numbers', '2.OA.C.3', [
              tf('16 is even.', key=True),
              sa('Is 13 odd or even?', 'Answer:', key='Odd'),
              mc('Which number is even?', ['18', '7', '11', '15']),
              sa('Write 14 as the sum of two equal addends.', 'Sum:', key='7 + 7'),
              tf('An even number of objects cannot be put into two equal groups.', key=False),
          ]),
      ],
      f1=B('Generate two patterns and compare their terms', '5.OA.B.3', [
          sa('Pattern A starts at 0 and adds 4. Pattern B starts at 0 and adds 12.\nWrite the first five terms of each pattern.',
             ['Pattern A:', 'Pattern B:'], key='Pattern A: 0, 4, 8, 12, 16; Pattern B: 0, 12, 24, 36, 48'),
          tf('Pattern A starts at 0 and adds 4. Pattern B starts at 0 and adds 12. Each term of B is 3 times the matching term of A.', key=True),
          mc('Pattern A: 0, 5, 10, 15. Pattern B: 0, 10, 20, 30.\nWhich ordered pair (A, B) comes from the patterns?', ['(15, 30)', '(30, 15)', '(15, 20)', '(10, 30)']),
          sa('Pattern A starts at 0 and adds 2. Pattern B starts at 0 and adds 10.\nWhat is the 5th term of Pattern B?', 'Term:', key='40'),
          tf('Each term of Pattern B is 4 times the matching term of Pattern A. When A is 9, B is 13.', key=False),
      ]),
      f2=B('Find the least common multiple', '6.NS.B.4', [
          sa('Find the least common multiple of 6 and 8.', 'LCM:', key='24'),
          sa('Find the least common multiple of 5 and 7.', 'LCM:', key='35'),
          mc('What is the least common multiple of 4 and 10?', ['20', '40', '14', '2']),
          tf('The least common multiple of 9 and 12 is 36.', key=True),
          tf('The least common multiple of 3 and 6 is 18.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.B.4 (prime or composite)
    S('4.OA.B.4', 'Decide whether a whole number from 1 to 100 is prime or composite',
      main=[
          mc('Which number is neither prime nor composite?', ['1', '2', '9', '29']),
          tf('51 is a prime number.', key=False),
          sa('Is 39 prime or composite? Explain.', ['Answer:', 'Explanation:'], key='Composite',
             note='39 = 3 × 13, so 39 has factors other than 1 and itself.'),
          sa('List all the prime numbers between 20 and 40.', 'Primes:', key='23, 29, 31, 37', note='All four are required.'),
          tf('A composite number has more than two factors.', key=True),
      ],
      back=[
          B('Find the unknown number in a multiplication or division equation', '3.OA.A.4', [
              sa('Find the unknown number.\n? × 3 = 21', 'Unknown:', key='7'),
              tf('If 7 × ? = 49, the unknown number is 7.', key=True),
              mc('9 × ? = 54', ['6', '5', '7', '45']),
              sa('Find the unknown number.\n35 ÷ ? = 5', 'Unknown:', key='7'),
              tf('If ? × 4 = 32, the unknown number is 9.', key=False),
          ]),
          B('Arrays with up to 5 rows and 5 columns', '2.OA.C.4', [
              sa('Write an addition equation for the array.', 'Equation:', key='5 + 5 = 10', fig=arr(2, 5),
                 note='2 + 2 + 2 + 2 + 2 = 10 (adding the columns) is also correct.'),
              tf('5 dots can make a rectangle only as 1 row of 5 or 5 rows of 1.', key=True),
              mc('Which array has 12 dots?', ['3 rows of 4', '3 rows of 5', '2 rows of 5', '4 rows of 4']),
              sa('How many dots are in an array with 4 rows of 4?', 'Dots:', key='16'),
              tf('An array with 2 rows of 3 dots has 5 dots.', key=False),
          ]),
      ],
      f1=B('Evaluate expressions with grouping symbols', '5.OA.A.1', [
          sa('Evaluate.\n2 × 3 × 7', 'Value:', key='42'),
          sa('Evaluate.\n2 × (5 × 5)', 'Value:', key='50'),
          mc('Evaluate.\n(2 × 2) × (3 × 3)', ['36', '12', '10', '24']),
          tf('3 × (2 × 11) = 66', key=True),
          tf('[2 × (3 + 5)] × 2 = 22', key=False),
      ]),
      f2=B('Write and evaluate expressions with whole-number exponents', '6.EE.A.1', [
          sa('Evaluate.\n2³ × 3', 'Value:', key='24'),
          sa('Write 2 × 2 × 2 × 2 × 5 using an exponent.', 'Expression:', key='2⁴ × 5'),
          mc('Which expression equals 72?', ['2³ × 3²', '2² × 3³', '2 × 3 × 6', '6²']),
          tf('3² × 5 = 45', key=True),
          tf('2⁵ = 10', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.C.5 (generate)
    S('4.OA.C.5', 'Generate a number or shape pattern that follows a given rule',
      main=[
          sa('The rule is "add 7." The pattern starts at 4.\nWrite the first five terms.', 'Terms:', key='4, 11, 18, 25, 32'),
          sa('The rule is "multiply by 3." The pattern starts at 2.\nWrite the first four terms.', 'Terms:', key='2, 6, 18, 54'),
          mc('Which pattern follows the rule "subtract 6," starting at 50?', ['50, 44, 38, 32', '50, 56, 62, 68', '50, 45, 40, 35', '44, 38, 32, 26']),
          tf('The rule "add 9," starting at 15, gives 15, 24, 33, 43.', key=False),
          sa('In a shape pattern, each figure has 2 more squares than the one before. The 1st figure has 3 squares.\nHow many squares are in the 6th figure?',
             'Squares:', key='13', note='3, 5, 7, 9, 11, 13.'),
      ],
      back=[
          B('Arithmetic patterns', '3.OA.D.9', [
              sa('What comes next?\n12, 16, 20, 24, ___', 'Next:', key='28'),
              tf('The pattern 5, 10, 15, 20 adds 5 each time.', key=True),
              mc('What is the rule for 30, 27, 24, 21?', ['Subtract 3', 'Add 3', 'Subtract 2', 'Multiply by 3']),
              sa('What comes next?\n7, 14, 21, 28, ___', 'Next:', key='35'),
              tf('The pattern 2, 4, 8, 16 adds 2 each time.', key=False),
          ]),
          B('Add or subtract 10 or 100 mentally', '2.NBT.B.8', [
              sa('What is 10 more than 347?', 'Answer:', key='357'),
              tf('100 less than 612 is 512.', key=True),
              mc('What is 100 more than 285?', ['385', '295', '286', '185']),
              sa('What is 10 less than 503?', 'Answer:', key='493'),
              tf('10 more than 790 is 890.', key=False),
          ]),
      ],
      f1=B('Form ordered pairs from two patterns', '5.OA.B.3', [
          sa('Pattern A starts at 1 and adds 1. Pattern B starts at 5 and adds 5.\nWrite the first four ordered pairs (A, B).', 'Ordered pairs:',
             key='(1, 5), (2, 10), (3, 15), (4, 20)'),
          tf('Pattern A is 0, 3, 6, 9 and Pattern B is 0, 9, 18, 27. Each B term is 3 times the matching A term.', key=True),
          mc('Pattern A starts at 0 and adds 2. Pattern B starts at 0 and adds 8.\nWhat is the B term when the A term is 6?', ['24', '12', '14', '48']),
          plot('Graph the ordered pairs (0, 0), (1, 3), (2, 6), and (3, 9) from two patterns.', grid(4, 10),
               key='Points plotted at (0, 0), (1, 3), (2, 6), (3, 9)'),
          tf('Pattern A starts at 0 and adds 5. Pattern B starts at 0 and adds 10. The 4th pair is (20, 40).', key=False),
      ]),
      f2=B('Write an equation for a pattern with dependent and independent variables', '6.EE.C.9', [
          sa('Figure 1 has 4 tiles, and each figure has 4 more tiles than the one before.\nWrite an equation for the tiles t in figure n.', 'Equation:',
             key='t = 4n'),
          mc('In t = 4n, which variable depends on the other?', ['t', 'n', '4', 'Neither']),
          sa('Write an equation for y in terms of x.', 'Equation:', key='y = 6x', fig=table([['x', '1', '2', '3', '4'], ['y', '6', '12', '18', '24']])),
          tf('In c = 8h, when h increases by 1, c increases by 8.', key=True),
          tf('The table x: 1, 2, 3 and y: 3, 5, 7 fits y = 3x.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.OA.C.5 (features and explanations)
    S('4.OA.C.5', 'Identify features of a pattern that the rule does not state, and explain them',
      main=[
          sa('The rule is "add 4," starting at 2: 2, 6, 10, 14, 18.\nWhat do you notice about every term? Explain why it happens.', ['Feature:', 'Why:'],
             key='Every term is even.',
             note='Why: the pattern starts at an even number and adding 4 (an even number) to an even number always gives an even number. '
                  'Another true feature with a correct reason (for example, the ones digits repeat 2, 6, 0, 4, 8) is also correct.'),
          mc('The rule is "add 5," starting at 3: 3, 8, 13, 18, 23.\nWhich statement is true?',
             ['The ones digits alternate between 3 and 8.', 'Every term is odd.', 'Every term is a multiple of 5.', 'Every term is even.']),
          tf('The rule "add 2," starting at 7, makes only odd numbers.', key=True),
          tf('The rule "add 6," starting at 1, makes terms that alternate between odd and even.', key=False),
          sa('The rule is "multiply by 2," starting at 3: 3, 6, 12, 24, 48.\nAfter the first term, are the terms odd or even? Explain why.', ['Answer:', 'Why:'],
             key='Even', note='Each term after the first is 2 times a whole number, and 2 times any whole number is even.'),
      ],
      back=[
          B('Explain patterns in the multiplication and addition tables', '3.OA.D.9', [
              tf('4 times any whole number is even.', key=True),
              mc('Why is every product in the 6s row of the multiplication table even?',
                 ['6 is 2 × 3, so every product is 2 times a number.', '6 is greater than 5.', 'The 6s row has 10 products.', 'Every number is even.']),
              sa('The 10s row is 10, 20, 30, 40, ...\nWhat is the same about every product?', 'Answer:', key='They all end in 0.'),
              tf('Every product in the 9s row of the multiplication table is odd.', key=False),
              sa('Is the sum of two odd numbers odd or even?', 'Answer:', key='Even'),
          ]),
          B('Odd and even numbers', '2.OA.C.3', [
              tf('11 is odd.', key=True),
              sa('Is 16 odd or even?', 'Answer:', key='Even'),
              mc('Which number is odd?', ['17', '8', '14', '10']),
              sa('Write 18 as the sum of two equal addends.', 'Sum:', key='9 + 9'),
              tf('Adding two even numbers can give an odd number.', key=False),
          ]),
      ],
      f1=B('Explain the relationship between two patterns', '5.OA.B.3', [
          sa('Pattern A starts at 0 and adds 6. Pattern B starts at 0 and adds 2.\nExplain why each term of A is 3 times the matching term of B.', 'Explanation:',
             key='Both start at 0 and take the same number of steps, and A adds 6, which is 3 × 2, at every step, so A has always added 3 times as much.',
             note='Must connect the rule amounts (6 = 3 × 2) to the same start of 0 and the same number of steps.'),
          tf('Pattern A starts at 0 and adds 4. Pattern B starts at 0 and adds 8. Each B term is 2 times the A term because B adds twice as much at every step.', key=True),
          mc('Pattern A starts at 2 and adds 2. Pattern B starts at 2 and adds 6.\nWhy is B NOT always 3 times A?',
             ['They start at the same number, not at 0.', 'B adds less than A.', 'A has more terms.', 'Both rules add even numbers.']),
          sa('Pattern A starts at 0 and adds 7. Pattern B starts at 0 and adds 21.\nWhat is the B term when the A term is 35?', 'Term:', key='105'),
          tf('Two patterns start at 0 and add 5 and 10. Each B term is 5 more than the matching A term.', key=False),
      ]),
      f2=B('Evaluate expressions for a given value of the variable', '6.EE.A.2.c', [
          sa('Evaluate 4n + 2 when n = 6.', 'Value:', key='26'),
          tf('The expression 2n gives an even number for every whole number n.', key=True),
          mc('The nth term of 5, 9, 13, 17, ... is 4n + 1.\nWhat is the 10th term?', ['41', '40', '45', '14']),
          sa('Evaluate 3n - 1 when n = 12.', 'Value:', key='35'),
          tf('When n = 5, 2n + 1 = 12.', key=False),
      ])),
]
