from qb import S, B, sa, mc, tf, plot, coord, shape, poly, draw_write
from common import geo, angles, grid, DRAW

SQUARE_CORNERS = [((0, 0), (6, 0), (0, 3)), ((0, 3), (0, 0), (4, 3))]

SETS = [
    # ------------------------------------------------------------------ 4.G.A.1 (points, lines, segments, rays)
    S('4.G.A.1', 'Draw and identify points, lines, line segments, and rays',
      main=[
          mc('What is the figure called?', ['Ray', 'Line', 'Line segment', 'Point'],
             fig=geo(('ray', (0, 0), (4, 1)), ('point', (0, 0), 'A'), ('point', (2, 0.5), 'B'))),
          mc('What is the figure called?', ['Line segment', 'Ray', 'Line', 'Angle'],
             fig=geo(('segment', (0, 0), (4, 0)), ('point', (0, 0), 'C'), ('point', (4, 0), 'D'))),
          tf('A line goes on without end in both directions.', key=True),
          plot('Draw ray PQ. It starts at point P and goes through point Q.', geo(('point', (0, 0), 'P'), ('point', (4, 2), 'Q')),
               key='A ray that starts at P, passes through Q, and has an arrow past Q'),
          tf('A line segment has an arrow at each end.', key=False),
      ],
      back=[
          B('Shapes with straight sides', '1.G.A.1', [
              tf('A triangle has 3 straight sides.', key=True),
              mc('Which shape has no straight sides?', ['Circle', 'Square', 'Triangle', 'Rectangle']),
              sa('How many straight sides does a rectangle have?', 'Sides:', key='4'),
              tf('A closed shape with 4 straight sides is a circle.', key=False),
              sa('A closed shape has 3 straight sides.\nWhat is it called?', 'Name:', key='Triangle'),
          ]),
          B('Measure the length of a segment with a ruler', '2.MD.A.1', [
              sa('A segment starts at 0 cm and ends at 8 cm on a ruler.\nHow long is it?', 'Length:', key='8 cm'),
              tf('You can measure the length of a line segment with a ruler.', key=True),
              mc('Which tool is best for measuring the length of a segment?', ['A ruler', 'A scale', 'A clock', 'A measuring cup']),
              sa('A segment goes from 3 inches to 7 inches on a ruler.\nHow long is it?', 'Length:', key='4 inches'),
              tf('A segment from 2 cm to 6 cm on a ruler is 6 cm long.', key=False),
          ]),
      ],
      f1=B('Understand the coordinate plane: perpendicular axes and the origin', '5.G.A.1', [
          sa('What is the point where the x-axis and the y-axis meet called?', 'Answer:', key='The origin'),
          tf('The x-axis and the y-axis are perpendicular lines.', key=True),
          mc('In the ordered pair (6, 2), what does the 6 tell you?', ['Move 6 units along the x-axis', 'Move 6 units along the y-axis',
                                                                       'Move 2 units to the right', 'The point is on the y-axis']),
          sa('What are the coordinates of point A?', 'A =', key='(4, 7)', fig=grid(8, 8, pts=[(4, 7, 'A')])),
          tf('(3, 5) and (5, 3) name the same point.', key=False),
      ]),
      f2=B('Name and plot points in all four quadrants', '6.NS.C.6.c', [
          sa('What are the coordinates of point B?', 'B =', key='(-4, 3)', fig=coord(pts=[(-4, 3, 'B')])),
          tf('The point (0, -5) is on the y-axis.', key=True),
          mc('Which ordered pair names point C?', ['(2, -3)', '(-3, 2)', '(-2, 3)', '(3, -2)'], fig=coord(pts=[(2, -3, 'C')])),
          plot('Plot and label the points D(-2, -4) and E(5, 1).', coord(), key='D plotted at (-2, -4) and E at (5, 1), each labeled'),
          tf('The point (-1, -1) is in Quadrant II.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.G.A.1 (angles)
    S('4.G.A.1', 'Draw and identify right, acute, and obtuse angles',
      main=[
          mc('What kind of angle is shown?', ['Obtuse', 'Acute', 'Right', 'Straight'],
             fig=angles([0, 130], [], desc='Two rays from one point forming an angle of about 130°.')),
          mc('What kind of angle is shown?', ['Acute', 'Obtuse', 'Right', 'Straight'],
             fig=angles([0, 40], [], desc='Two rays from one point forming an angle of about 40°.')),
          tf('A right angle measures exactly 180°.', key=False),
          plot('Draw an obtuse angle.', DRAW, key='Two rays from one point that form an angle greater than 90° and less than 180°'),
          sa('Classify each angle as acute, right, or obtuse.\n15°     90°     165°', 'Answers:', key='acute; right; obtuse'),
      ],
      back=[
          B('Shapes with a given number of angles', '2.G.A.1', [
              sa('How many angles does a hexagon have?', 'Angles:', key='6'),
              tf('A quadrilateral has 4 angles.', key=True),
              mc('Which shape has 3 angles?', ['Triangle', 'Square', 'Pentagon', 'Hexagon']),
              sa('How many angles does a rectangle have?', 'Angles:', key='4'),
              tf('A pentagon has 6 angles.', key=False),
          ]),
          B('Rectangles and squares have square corners', '3.G.A.1', [
              tf('Every rectangle has 4 square corners.', key=True),
              mc('Which shape always has 4 square corners?', ['Square', 'Rhombus', 'Triangle', 'Trapezoid']),
              sa('How many square corners does a square have?', 'Square corners:', key='4'),
              tf('Every quadrilateral has 4 square corners.', key=False),
              sa('Name a quadrilateral that has 4 square corners but is not a square.', 'Shape:', key='Rectangle'),
          ]),
      ],
      f1=B('Classify triangles by their angles', '5.G.B.4', [
          sa('A triangle has angles of 100°, 40°, and 40°.\nClassify it by its angles.', 'Classification:', key='Obtuse triangle'),
          tf('A right triangle has exactly one right angle.', key=True),
          mc('Which kind of triangle has three acute angles?', ['An acute triangle', 'A right triangle', 'An obtuse triangle', 'A straight triangle']),
          sa('A triangle has angles of 55°, 35°, and 90°.\nClassify it by its angles.', 'Classification:', key='Right triangle'),
          tf('An acute triangle can have one obtuse angle.', key=False),
      ]),
      f2=B('Use the right angle of a right triangle to find its area', '6.G.A.1', nearest=True, qs=[
          sa('A right triangle has legs that are 6 cm and 10 cm long.\nWhat is its area?', 'Area:', key='30 square cm'),
          tf('In a right triangle, the two sides that form the right angle can be used as the base and the height.', key=True),
          mc('An 8-by-5 rectangle is cut along a diagonal into two triangles.\nWhat is the area of each triangle?',
             ['20 square units', '40 square units', '13 square units', '10 square units']),
          sa('A triangle has a base of 12 m and a height of 7 m.\nWhat is its area?', 'Area:', key='42 square meters'),
          tf('An obtuse triangle does not have a height.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.G.A.1 (perpendicular and parallel)
    S('4.G.A.1', 'Draw and identify perpendicular and parallel lines',
      main=[
          mc('How are the two lines related?', ['Perpendicular', 'Parallel', 'Neither', 'They are the same line'],
             fig=geo(('line', (0, 1), (4, 1)), ('line', (2, -0.5), (2, 2.5)), ('ra', (2, 1), (4, 1), (2, 2.5)))),
          mc('How are the two lines related?', ['Parallel', 'Perpendicular', 'Neither', 'They are the same line'],
             fig=geo(('line', (0, 0), (4, 1)), ('line', (0, 1.5), (4, 2.5)))),
          tf('Parallel lines never meet.', key=True),
          plot('Draw a line through point P that is parallel to line m.', geo(('line', (0, 0), (5, 0)), ('text', (5.4, 0.3), 'm'), ('point', (2, 2), 'P')),
               key='A line through P that never meets line m (a line through P going the same direction as m), with arrows at both ends'),
          tf('Perpendicular lines meet to form four obtuse angles.', key=False),
      ],
      back=[
          B('Split a rectangle into rows and columns of squares', '2.G.A.2', [
              sa('A rectangle is split into 2 rows of 3 same-size squares.\nHow many squares are there?', 'Squares:', key='6'),
              tf('A rectangle split into 3 rows of 4 same-size squares has 12 squares.', key=True),
              mc('A rectangle has 2 rows of 4 same-size squares.\nHow many squares are there?', ['8', '6', '4', '2']),
              sa('How many squares are in 5 rows of 2 squares?', 'Squares:', key='10'),
              tf('A rectangle split into 2 rows and 2 columns of squares has 2 squares.', key=False),
          ]),
          B('Quadrilaterals share attributes', '3.G.A.1', [
              tf('A rhombus, a rectangle, and a square are all quadrilaterals.', key=True),
              mc('Which shape is a quadrilateral?', ['Rhombus', 'Triangle', 'Pentagon', 'Circle']),
              sa('How many sides does every quadrilateral have?', 'Sides:', key='4'),
              tf('A triangle is a quadrilateral.', key=False),
              sa('Name a quadrilateral that is not a rectangle.', 'Shape:', key='A rhombus',
                 note='Any quadrilateral that is not a rectangle (for example a trapezoid or a kite) is correct.'),
          ]),
      ],
      f1=B('Attributes of a category belong to all its subcategories', '5.G.B.3', [
          tf('All parallelograms have two pairs of parallel sides. A rectangle is a parallelogram, so every rectangle has two pairs of parallel sides.', key=True),
          mc('Which shape must have two pairs of parallel sides?', ['Rhombus', 'Kite', 'Trapezoid', 'Triangle']),
          sa('Do the sides of every square meet at right angles? Explain.', ['Answer:', 'Explanation:'], key='Yes',
             note='A square is a rectangle, and a rectangle has four right angles, so its sides that meet are perpendicular.'),
          tf('Every quadrilateral has at least one pair of parallel sides.', key=False),
          mc('Which shape has exactly one pair of parallel sides?', ['A trapezoid with only one pair of parallel sides', 'A rectangle', 'A square', 'A rhombus']),
      ]),
      f2=B('Use coordinates to find parallel and perpendicular sides of polygons', '6.G.A.3', [
          tf('The segment from (1, 2) to (5, 2) is parallel to the segment from (1, -3) to (5, -3).', key=True),
          sa('What is the length of the side from (-3, -1) to (-3, 4)?', 'Length:', key='5 units'),
          mc('Which segment is perpendicular to the segment from (0, 0) to (6, 0)?',
             ['From (2, 0) to (2, 5)', 'From (0, 1) to (6, 1)', 'From (1, 1) to (4, 4)', 'From (0, 0) to (6, 3)']),
          draw_write('Plot (-2, 1), (4, 1), (4, -3), and (-2, -3). Connect them in order.\nHow many pairs of parallel sides does the polygon have?', coord(),
                     'Pairs:', draw='The four points plotted and joined in order', key='2',
                     note='Grade both: the four points joined in order, and the answer 2.'),
          tf('The segment from (0, 1) to (3, 1) is perpendicular to the segment from (0, 4) to (3, 4).', key=False),
      ])),

    # ------------------------------------------------------------------ 4.G.A.2 (classify figures)
    S('4.G.A.2', 'Classify two-dimensional figures by parallel or perpendicular sides and by angles',
      main=[
          mc('Which shape has two pairs of parallel sides and no right angles?',
             ['A rhombus that is not a square', 'A square', 'A rectangle', 'A right triangle']),
          sa('A quadrilateral has exactly one pair of parallel sides.\nWhat is it called?', 'Name:', key='Trapezoid'),
          tf('A rectangle has two pairs of parallel sides and four right angles.', key=True),
          mc('Which shape always has perpendicular sides?', ['Square', 'Rhombus', 'Trapezoid', 'Parallelogram']),
          sa('The shape has one pair of parallel sides and two right angles.\nWhat kind of quadrilateral is it?', 'Name:', key='Trapezoid',
             note='"Right trapezoid" is also correct.',
             fig=shape([poly([(0, 0), (6, 0), (4, 3), (0, 3)])], ra=SQUARE_CORNERS)),
      ],
      back=[
          B('Quadrilaterals as a category', '3.G.A.1', [
              tf('Squares and rectangles are both quadrilaterals.', key=True),
              sa('What is a closed shape with 4 straight sides called?', 'Name:', key='Quadrilateral'),
              mc('Which shape is NOT a quadrilateral?', ['Pentagon', 'Rhombus', 'Square', 'Rectangle']),
              tf('All quadrilaterals are squares.', key=False),
              sa('Name two different quadrilaterals.', 'Shapes:', key='Square and rectangle',
                 note='Any two different quadrilaterals (square, rectangle, rhombus, trapezoid, kite) are correct.'),
          ]),
          B('Triangles, quadrilaterals, pentagons, and hexagons', '2.G.A.1', [
              sa('What is a shape with 5 sides called?', 'Name:', key='Pentagon'),
              tf('A hexagon has 6 sides.', key=True),
              mc('Which shape has 4 sides?', ['Quadrilateral', 'Triangle', 'Pentagon', 'Hexagon']),
              sa('How many sides does a triangle have?', 'Sides:', key='3'),
              tf('A pentagon has 8 sides.', key=False),
          ]),
      ],
      f1=B('Classify quadrilaterals in a hierarchy', '5.G.B.4', [
          mc('Which list goes from the most general category to the most specific?',
             ['Quadrilateral, parallelogram, rhombus, square', 'Square, rhombus, parallelogram, quadrilateral',
              'Rhombus, square, quadrilateral, parallelogram', 'Parallelogram, quadrilateral, square, rhombus']),
          tf('Every square is a rhombus.', key=True),
          sa('Which of these categories does every rectangle belong to?\nquadrilateral, parallelogram, rhombus, square', 'Categories:',
             key='Quadrilateral and parallelogram', note='Both are required; rhombus and square are wrong.'),
          tf('Every rhombus is a rectangle.', key=False),
          mc('A quadrilateral has 4 sides of equal length and no right angles.\nWhat is its most specific name?', ['Rhombus', 'Square', 'Rectangle', 'Quadrilateral']),
      ]),
      f2=B('Find the area of parallelograms, rhombuses, and trapezoids', '6.G.A.1', [
          sa('A parallelogram has a base of 9 cm and a height of 4 cm.\nWhat is its area?', 'Area:', key='36 square cm'),
          tf('A rhombus with a base of 6 m and a height of 5 m has an area of 30 square meters.', key=True),
          mc('A trapezoid has bases of 4 ft and 8 ft and a height of 5 ft.\nWhat is its area?', ['30 square feet', '60 square feet', '17 square feet', '40 square feet']),
          sa('A trapezoid has bases of 6 units and 10 units and a height of 3 units.\nWhat is its area?', 'Area:', key='24 square units'),
          tf('A parallelogram with a base of 10 units, slanted sides of 6 units, and a height of 5 units has an area of 60 square units.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.G.A.2 (right triangles)
    S('4.G.A.2', 'Recognize right triangles as a category, and identify them',
      main=[
          sa('A triangle has angles of 90°, 50°, and 40°.\nIs it a right triangle? Explain.', ['Answer:', 'Explanation:'], key='Yes',
             note='It has a 90° angle, which is a right angle.'),
          tf('The triangle shown is a right triangle.', key=True,
             fig=shape([poly([(0, 0), (4, 0), (0, 3)])], ra=[((0, 0), (4, 0), (0, 3))])),
          mc('Which could be the angles of a right triangle?', ['90°, 60°, 30°', '80°, 60°, 40°', '100°, 50°, 30°', '70°, 70°, 40°']),
          tf('A right triangle can have two right angles.', key=False),
          draw_write('Draw a right triangle on the grid and mark its right angle.\nHow many right angles does your triangle have?', DRAW, 'Right angles:',
                     draw='A triangle with two sides along grid lines that meet at a square corner, with the right angle marked', key='1',
                     note='Grade both: a right triangle with its right angle marked, and the answer 1.'),
      ],
      back=[
          B('Triangles', '2.G.A.1', [
              sa('How many sides does every triangle have?', 'Sides:', key='3'),
              tf('A triangle has 3 corners.', key=True),
              mc('Which describes a triangle?', ['A closed shape with 3 straight sides', 'A closed shape with 4 straight sides',
                                                  'A round shape', 'A closed shape with 5 corners']),
              sa('How many angles does a triangle have?', 'Angles:', key='3'),
              tf('All triangles are the same size.', key=False),
          ]),
          B('Square corners', '3.G.A.1', [
              tf('A square corner is a right angle.', key=True),
              mc('Which shape always has a square corner?', ['Rectangle', 'Circle', 'Oval', 'Hexagon']),
              sa('How many square corners does a rectangle have?', 'Square corners:', key='4'),
              tf('A triangle can never have a square corner.', key=False),
              sa('Which can you use to check for a square corner: the corner of a sheet of paper or a pencil?', 'Answer:', key='The corner of a sheet of paper'),
          ]),
      ],
      f1=B('Right triangles share the attributes of all triangles', '5.G.B.3', [
          tf('All triangles have 3 sides. A right triangle is a triangle, so it has 3 sides.', key=True),
          mc('An isosceles right triangle belongs to which categories?',
             ['Right triangles and isosceles triangles', 'Only right triangles', 'Only isosceles triangles', 'Equilateral triangles']),
          sa('Can a right triangle be scalene? Write yes or no.', 'Answer:', key='Yes'),
          tf('An equilateral triangle can be a right triangle.', key=False),
          sa('A right triangle has sides of 3, 4, and 5 units.\nIs it isosceles, equilateral, or scalene?', 'Answer:', key='Scalene'),
      ]),
      f2=B('Find the area of right triangles', '6.G.A.1', [
          sa('A right triangle has legs that are 8 m and 5 m long.\nWhat is its area?', 'Area:', key='20 square meters'),
          tf('Two copies of the same right triangle can be put together to make a rectangle.', key=True),
          mc('A right triangle has legs that are 12 in. and 6 in. long.\nWhat is its area?', ['36 square inches', '72 square inches', '18 square inches', '9 square inches']),
          sa('A 10-by-4 rectangle is cut along a diagonal into two right triangles.\nWhat is the area of each triangle?', 'Area:', key='20 square units'),
          tf('A right triangle with legs of 7 and 4 units has an area of 28 square units.', key=False),
      ])),

    # ------------------------------------------------------------------ 4.G.A.3 (recognize)
    S('4.G.A.3', 'Recognize lines of symmetry and line-symmetric figures',
      main=[
          tf('The dashed line is a line of symmetry of the triangle.', key=True,
             fig=shape([poly([(0, 0), (4, 0), (2, 3)])], segs=[dict(a=(2, -0.6), b=(2, 3.6), label=None)])),
          tf('The dashed line is a line of symmetry of the rectangle.', key=False,
             fig=shape([poly([(0, 0), (5, 0), (5, 2), (0, 2)])], segs=[dict(a=(-0.5, -0.2), b=(5.5, 2.2), label=None)])),
          mc('How many lines of symmetry does a square have?', ['4', '2', '1', '0']),
          sa('How many lines of symmetry does a rectangle that is not a square have?', 'Lines:', key='2'),
          mc('Which capital letter has a vertical line of symmetry?', ['A', 'F', 'J', 'R']),
      ],
      back=[
          B('Split circles and rectangles into equal shares', '2.G.A.3', [
              tf('A rectangle cut into 2 equal shares is cut into halves.', key=True),
              sa('A circle is cut into 4 equal shares.\nWhat is one share called?', 'Name:', key='A fourth', note='"A quarter" is also correct.'),
              mc('A rectangle is cut into 3 equal shares.\nWhat are the shares called?', ['Thirds', 'Halves', 'Fourths', 'Fifths']),
              sa('How many halves make a whole?', 'Halves:', key='2'),
              tf('Equal shares of the same whole must have the same shape.', key=False),
          ]),
          B('Halves and fourths', '1.G.A.3', [
              sa('A square is cut into 2 equal parts.\nWhat is each part called?', 'Name:', key='A half'),
              tf('Cutting a circle into 4 equal parts makes smaller parts than cutting it into 2 equal parts.', key=True),
              mc('How many fourths make a whole?', ['4', '2', '1', '8']),
              sa('A pizza is cut into 4 equal parts.\nWhat is one part called?', 'Name:', key='A fourth', note='"A quarter" is also correct.'),
              tf('Halves are smaller than fourths of the same whole.', key=False),
          ]),
      ],
      f1=B('Graph points that match across a line of symmetry', '5.G.A.2', [
          plot('The line through (4, 0) and (4, 8) is a line of symmetry.\nPlot the point that matches (2, 5) on the other side of the line.',
               grid(8, 8, pts=[(2, 5)], lines=[((4, 0), (4, 8))]), key='A point plotted at (6, 5)'),
          tf('Across the line through (3, 0) and (3, 5), the point (1, 2) matches the point (5, 2).', key=True),
          mc('Across the line through (5, 0) and (5, 8), which point matches (7, 4)?', ['(3, 4)', '(7, 6)', '(5, 4)', '(2, 4)']),
          sa('Across the line through (4, 0) and (4, 8), which point matches (1, 6)?', 'Point:', key='(7, 6)'),
          tf('Across the line through (2, 0) and (2, 5), the point (0, 3) matches the point (3, 3).', key=False),
      ]),
      f2=B('Reflect points across the axes', '6.NS.C.6.b', [
          sa('Reflect (3, 4) across the y-axis.\nWhat are the coordinates of the image?', 'Image:', key='(-3, 4)'),
          tf('Reflecting (2, -5) across the x-axis gives (2, 5).', key=True),
          mc('Which point is the reflection of (-4, 1) across the x-axis?', ['(-4, -1)', '(4, 1)', '(4, -1)', '(1, -4)']),
          sa('Reflect (-6, -2) across the y-axis.\nWhat are the coordinates of the image?', 'Image:', key='(6, -2)'),
          tf('Reflecting (5, 0) across the x-axis gives (-5, 0).', key=False),
      ])),

    # ------------------------------------------------------------------ 4.G.A.3 (draw)
    S('4.G.A.3', 'Draw lines of symmetry',
      main=[
          plot('Draw all the lines of symmetry of the rectangle.', shape([poly([(0, 0), (6, 0), (6, 3), (0, 3)])]),
               key='Two lines: one vertical line through the middle and one horizontal line through the middle'),
          draw_write('Draw all the lines of symmetry of the square.\nHow many are there?', shape([poly([(0, 0), (4, 0), (4, 4), (0, 4)])]), 'Lines:',
                     draw='Four lines: vertical, horizontal, and both diagonals, each through the center', key='4',
                     note='Grade both: all four lines drawn, and the answer 4.'),
          draw_write('Draw the line of symmetry of the triangle, which has two sides of equal length.\nHow many lines of symmetry does it have?',
                     shape([poly([(0, 0), (4, 0), (2, 4)])]), 'Lines:',
                     draw='A line from the top vertex straight down to the middle of the base', key='1',
                     note='Grade both: the line from the top vertex to the middle of the base, and the answer 1.'),
          plot('Complete the figure so that the dashed line is a line of symmetry.',
               shape([poly([(0, 0), (6, 0), (6, 3), (0, 3)], hidden=True), poly([(3, 0), (1, 0), (1, 2), (2, 3), (3, 3)], closed=False)],
                     segs=[dict(a=(3, -0.6), b=(3, 3.6), label=None)],
                     desc='Half of a figure drawn to the left of a dashed vertical line: a path from (3, 0) to (1, 0), up to (1, 2), '
                          'to (2, 3), and to (3, 3) on the dashed line. The space to the right of the line is empty for drawing.'),
               key='The mirror image drawn on the right of the dashed line: a segment from (3, 0) to (5, 0), up to (5, 2), to (4, 3), and back to (3, 3)'),
          sa('A regular hexagon has 6 equal sides and 6 equal angles.\nHow many lines of symmetry does it have?', 'Lines:', key='6'),
      ],
      back=[
          B('Split circles and rectangles into equal shares', '2.G.A.3', [
              sa('A square is cut into 4 equal shares.\nHow many shares make the whole?', 'Shares:', key='4'),
              tf('A circle can be cut into 3 equal shares called thirds.', key=True),
              mc('Which one shows halves?', ['A rectangle cut into 2 equal parts', 'A rectangle cut into 2 unequal parts',
                                             'A circle cut into 3 equal parts', 'A circle cut into 4 equal parts']),
              sa('A rectangle is cut into 3 equal shares.\nWhat is one share called?', 'Name:', key='A third'),
              tf('A circle cut into 2 parts of different sizes shows halves.', key=False),
          ]),
          B('Put shapes together to make new shapes', '1.G.A.2', [
              tf('Two matching right triangles can be put together to make a rectangle.', key=True),
              mc('Which two shapes can be put together to make a square?', ['Two matching rectangles', 'Two circles', 'A circle and a triangle', 'Three circles']),
              sa('How many squares do you need to make a rectangle that is 2 squares long and 1 square wide?', 'Squares:', key='2'),
              tf('Two half-circles can be put together to make a square.', key=False),
              sa('Two matching trapezoids are put together to make a shape with 6 sides.\nWhat is the shape called?', 'Name:', key='Hexagon'),
          ]),
      ],
      f1=B('Graph points to make and check symmetric figures', '5.G.A.2', [
          draw_write('Plot (1, 1), (3, 4), and (5, 1) and connect them. Then draw the line of symmetry.\nWhere does the line of symmetry cross the x-axis?',
                     grid(6, 5), 'Crosses at:', draw='Triangle with vertices (1, 1), (3, 4) and (5, 1), and a vertical line through x = 3',
                     key='(3, 0)', note='Grade both: the triangle and its vertical line of symmetry, and the point (3, 0).'),
          tf('The rectangle with corners (1, 1), (5, 1), (5, 3), and (1, 3) is symmetric about the line through (3, 0) and (3, 4).', key=True),
          mc('A shape has a line of symmetry through (4, 0) and (4, 6). The point (2, 3) is on the shape.\nWhich point must also be on it?',
             ['(6, 3)', '(2, 5)', '(4, 3)', '(8, 3)']),
          plot('Plot (2, 2), (2, 5), and (6, 2). Then plot one more point so that the four points are the corners of a rectangle.', grid(8, 6),
               key='Points plotted at (2, 2), (2, 5), (6, 2) and (6, 5)'),
          tf('The points (1, 4) and (7, 4) match across the line through (3, 0) and (3, 6).', key=False),
      ]),
      f2=B('Draw polygons in the coordinate plane and reflect them across an axis', '6.G.A.3', [
          plot('Plot (2, 3), (5, 3), and (5, 1). Then reflect each point across the y-axis and plot the images.', coord(),
               key='Points plotted at (2, 3), (5, 3), (5, 1) and their images at (-2, 3), (-5, 3), (-5, 1)'),
          tf('The rectangle with vertices (-3, 2), (3, 2), (3, -2), and (-3, -2) is symmetric about the y-axis.', key=True),
          mc('A square has vertices (-2, -2), (2, -2), and (2, 2).\nWhat is the fourth vertex?', ['(-2, 2)', '(2, -4)', '(-2, 4)', '(0, 2)']),
          sa('A polygon has vertices (1, 4), (4, 4), and (4, 1).\nWhat is the image of (4, 1) when it is reflected across the x-axis?', 'Image:', key='(4, -1)'),
          tf('The segment from (-4, 1) to (4, 1) is 4 units long.', key=False),
      ])),
]
