from qb import S, B, sa, mc, tf, nl, coord, q1, table, stack, shape, poly, rect

LET = ['Point A', 'Point B', 'Point C', 'Point D']
ABCD = ['A', 'B', 'C', 'D']
SYM = shape([poly([(0, 0), (6, 0), (6, 4), (0, 4)])], segs=[dict(a=(3, -0.6), b=(3, 4.6), color='#155a9c')])


def setup(a, b):
    return stack(*a, rule=len(a), fs=1.1), stack(*b, rule=len(b), fs=1.1)


def fr(n, d):
    return {i / d: '{%d/%d}' % (i, d) if 0 < i < d else str(i // d) for i in range(0, n + 1)}


SETS = [
    # ------------------------------------------------------------------ 6.NS.A.1 compute
    S('6.NS.A.1', 'Divide fractions by fractions',
      main=[
          sa('Divide.\n{2/3} ÷ {3/4}', 'Quotient:'),
          sa('Divide.\n{5/6} ÷ {1/3}', 'Quotient:'),
          sa('Divide.\n1{1/2} ÷ {3/4}', 'Quotient:'),
          mc('Which is equal to {4/5} ÷ {2/3}?', ['1{1/5}', '{8/15}', '{5/6}', '{2/15}']),
          sa('Divide.\n3{1/3} ÷ {5/6}', 'Quotient:'),
      ],
      back=[
          B('Multiplying fractions', '5.NF.B.4.a', [
              sa('Multiply.\n{2/3} × {4/3}', 'Product:'),
              tf('{3/4} × {2/5} = {6/20}'),
              mc('{1/2} × {5/6} = ?', ['{5/12}', '{6/8}', '{5/8}', '{1/3}']),
              sa('Multiply.\n{4/5} × {3/2}', 'Product:'),
              sa('Multiply.\n{5/6} × 3', 'Product:'),
          ]),
          B('Whole number ÷ unit fraction', '5.NF.B.7.b', [
              sa('Divide.\n3 ÷ {1/4}', 'Quotient:'),
              tf('4 ÷ {1/2} = 8'),
              mc('How many thirds are in 2?', ['6', '{2/3}', '5', '{1/6}']),
              sa('Divide.\n6 ÷ {1/5}', 'Quotient:'),
              sa('Divide.\n2 ÷ {1/8}', 'Quotient:'),
          ]),
          B('Unit fraction ÷ whole number', '5.NF.B.7.a', [
              sa('Divide.\n{1/3} ÷ 4', 'Quotient:'),
              tf('{1/2} ÷ 3 = {1/6}'),
              mc('{1/4} ÷ 2 = ?', ['{1/8}', '{1/2}', '8', '{2/4}']),
              sa('Divide.\n{1/5} ÷ 5', 'Quotient:'),
              tf('{1/6} ÷ 2 = {2/6}'),
          ]),
          B('Equivalent fractions', '4.NF.A.1', [
              tf('{8/12} is equivalent to {2/3}.'),
              sa('Find the missing number.\n{10/15} = {?/3}', 'Missing number:'),
              mc('Which fraction is equivalent to {9/12}?', ['{3/4}', '{2/3}', '{9/4}', '{12/9}']),
              sa('Find the missing number.\n{6/8} = {?/4}', 'Missing number:'),
              tf('{4/6} is equivalent to {6/8}.'),
          ]),
          B('Mixed numbers as fractions', '4.NF.B.3.b', [
              sa('Write 1{1/2} as a fraction.', 'Fraction:'),
              sa('Write 3{1/3} as a fraction.', 'Fraction:'),
              tf('2{1/4} = {9/4}'),
              mc('Which fraction is equal to 1{2/3}?', ['{5/3}', '{3/3}', '{12/3}', '{7/3}']),
              sa('Write {11/4} as a mixed number.', 'Mixed number:'),
          ]),
      ],
      f1=B('Multiply and divide rational numbers', '7.NS.A.2.c', [
          sa('Find the value.\n(-{2/3}) ÷ {4/5}', ''),
          sa('Find the value.\n-{3/4} × (-{8/9})', ''),
          mc('(-1{1/2}) ÷ (-{3/8}) = ?', ['4', '-4', '{9/16}', '-{9/16}']),
          sa('Find the value.\n{5/6} ÷ (-{5/12})', ''),
          tf('(-{1/2}) × {4/5} = -{2/5}'),
      ]),
      f2=B('Equations with fraction coefficients', '8.EE.C.7.b', [
          sa('Solve for x.\n{3/4}(x - 2) = {1/2}x + 5', 'x ='),
          sa('Solve for x.\n{2/3}x + 4 = {1/6}x + 7', 'x ='),
          mc('Solve for x.\n{x/2} + {x/3} = 10', ['12', '60', '5', '6']),
          sa('Solve for x.\n{1/2}(4x + 6) = 3x - 5', 'x ='),
          sa('Solve for y.\n{5/8}y - 1 = {3/8}y + 2', 'y ='),
      ])),

    # ------------------------------------------------------------------ 6.NS.A.1 word problems
    S('6.NS.A.1', 'Interpret and solve word problems with fraction division',
      main=[
          sa('How many {3/4}-cup servings are in {2/3} cup of yogurt?', 'Servings:'),
          sa('A path is {3/4} mile long. It is divided into sections that are each {1/8} mile long.\nHow many sections are there?', 'Sections:'),
          sa('A rectangle has an area of {1/2} square mile. Its width is {3/4} mile.\nWhat is its length?', 'Length:'),
          mc('Which question can be answered by {3/4} ÷ {2/5}?',
             ['How many {2/5}s are in {3/4}?', 'What is {2/5} of {3/4}?', 'How many {3/4}s are in {2/5}?', 'What is {3/4} more than {2/5}?']),
          sa('Ana has {5/6} pound of trail mix. She fills bags that each hold {5/12} pound.\nHow many bags can she fill?', 'Bags:'),
      ],
      back=[
          B('Division as "how many groups?"', '3.OA.A.2', [
              sa('How many groups of 4 are in 20?', 'Groups:'),
              tf('12 ÷ 3 can mean "How many groups of 3 are in 12?"'),
              mc('Tom has 18 cookies. He puts 6 cookies in each bag.\nWhich equation finds the number of bags?', ['18 ÷ 6 = □', '18 × 6 = □', '18 - 6 = □', '6 ÷ 18 = □']),
              sa('24 students are split into teams of 8.\nHow many teams are there?', 'Teams:'),
              sa('How many 5s are in 35?', 'Answer:'),
          ]),
          B('Unit fractions build a fraction', '3.NF.A.1', [
              sa('How many {1/4}s make {3/4}?', 'Answer:'),
              sa('How many {1/8}s make 1 whole?', 'Answer:'),
              tf('{5/6} is 5 parts of size {1/6}.'),
              mc('{3/8} is made of how many parts of size {1/8}?', ['3', '8', '5', '{1/3}']),
              sa('How many {1/3}s make {2/3}?', 'Answer:'),
          ]),
          B('Area with fractional side lengths', '5.NF.B.4.b', [
              sa('What is the area of the rectangle?', 'Area:', fig=rect(4, 3, '{3/4} m', '{2/3} m')),
              tf('A rectangle that is {1/2} foot by {1/3} foot has an area of {1/6} square foot.'),
              mc('A rectangle is {2/5} unit by {1/2} unit.\nWhat is its area?', ['{1/5} square unit', '{3/7} square unit', '{2/7} square unit', '{9/10} square unit']),
              sa('What is the area of the rectangle?', 'Area:', fig=rect(6, 1.6, '1{1/2} ft', '{1/4} ft')),
              sa('A garden is {5/6} yard long and {3/5} yard wide.\nWhat is its area?', 'Area:'),
          ]),
          B('Word problems: dividing with unit fractions', '5.NF.B.7.c', [
              sa('How many {1/3}-cup servings are in 2 cups of raisins?', 'Servings:'),
              sa('A 4-pound bag of rice is divided into {1/2}-pound portions.\nHow many portions are there?', 'Portions:'),
              mc('Which expression finds how many {1/5}-mile laps are in 3 miles?', ['3 ÷ {1/5}', '{1/5} ÷ 3', '3 × {1/5}', '3 - {1/5}']),
              sa('3 people share {1/2} pound of chocolate equally.\nHow much chocolate does each person get?', 'Each person:'),
              tf('There are 10 half-hours in 5 hours.'),
          ]),
      ],
      f1=B('Real-world problems with rational numbers', '7.NS.A.3', [
          sa('A diver descends {3/4} foot each second.\nHow many seconds does it take to descend 5{1/4} feet?', 'Seconds:'),
          sa('The temperature was 4°F. It dropped 2{1/2}°F each hour for 3 hours.\nWhat was the final temperature?', 'Temperature:'),
          mc('A stock\'s value changed by -$1{1/4} each day for 4 days.\nWhat was the total change?', ['-$5', '$5', '-$4{1/4}', '-$1']),
          sa('A recipe needs {2/3} cup of oil per batch. Jo has 3{1/3} cups of oil.\nHow many batches can Jo make?', 'Batches:'),
          sa('A hiker descends 1,250 feet in {5/6} hour at a constant rate.\nWhat is the change in elevation per hour?', 'Change per hour:'),
      ]),
      f2=B('Solve linear equations from contexts', '8.EE.C.7.b', [
          sa('Solve for x.\n{1/2}(x + 6) = {1/3}(x + 12)', 'x ='),
          sa('Lee\'s age plus {1/3} of his age is 24.\nWrite and solve an equation to find Lee\'s age.', 'Age:'),
          sa('Tank A has 40 gallons and drains {3/4} gallon per minute. Tank B has 10 gallons and fills at 1{1/4} gallons per minute.\nAfter how many minutes will the tanks hold the same amount?', 'Minutes:'),
          mc('Solve for x.\n{2/5}x - 3 = {1/5}x + 1', ['20', '10', '4', '-10']),
          sa('Solve for n.\n{3/4}n + {1/2} = {1/4}n + 4', 'n ='),
      ])),

    # ------------------------------------------------------------------ 6.NS.B.2
    S('6.NS.B.2', 'Divide multi-digit numbers using the standard algorithm',
      main=[
          sa('Use the standard algorithm to divide.\n4,508 ÷ 23', 'Quotient:'),
          sa('Use the standard algorithm to divide.\n7,236 ÷ 36', 'Quotient:'),
          sa('Use the standard algorithm to divide.\n9,975 ÷ 75', 'Quotient:'),
          mc('A school sets up 1,680 chairs in rows of 48 chairs.\nHow many rows are there?', ['35', '30', '350', '36']),
          sa('Use the standard algorithm to divide.\n25,494 ÷ 42', 'Quotient:'),
      ],
      back=[
          B('Multiplying multi-digit numbers', '5.NBT.B.5', [
              sa('Multiply.\n46 × 23', 'Product:'),
              sa('Multiply.\n196 × 23', 'Product:'),
              tf('35 × 48 = 1,680'),
              mc('133 × 75 = ?', ['9,975', '9,875', '1,596', '9,775']),
              sa('Multiply.\n607 × 42', 'Product:'),
          ]),
          B('Dividing by a one-digit number', '4.NBT.B.6', [
              sa('Divide.\n852 ÷ 4', 'Quotient:'),
              sa('Divide.\n1,256 ÷ 8', 'Quotient:'),
              tf('936 ÷ 3 = 312'),
              mc('714 ÷ 7 = ?', ['102', '12', '120', '1,002']),
              sa('Divide.\n2,345 ÷ 5', 'Quotient:'),
          ]),
          B('Estimating quotients', '5.NBT.B.6', [
              mc('Which is the best estimate for 4,508 ÷ 23?', ['200', '20', '2,000', '2']),
              mc('Which is the best estimate for 7,236 ÷ 36?', ['200', '20', '2,000', '2']),
              tf('9,975 ÷ 75 is between 100 and 200.'),
              sa('Estimate 6,120 ÷ 29 by rounding 29 to 30.', 'Estimate:'),
              mc('How many digits are in the quotient of 1,680 ÷ 48?', ['2', '1', '3', '4']),
          ]),
          B('Multi-digit subtraction', '4.NBT.B.4', [
              sa('Subtract.\n5,012 - 4,698', 'Difference:'),
              sa('Subtract.\n3,000 - 1,847', 'Difference:'),
              tf('7,236 - 7,200 = 36'),
              mc('9,975 - 9,000 = ?', ['975', '9,075', '1,975', '75']),
              sa('Subtract.\n6,203 - 2,875', 'Difference:'),
          ]),
      ],
      f1=B('Long division: fractions to decimals', '7.NS.A.2.d', [
          sa('Use long division to write {5/11} as a decimal.', 'Decimal:'),
          sa('Use long division to write {3/8} as a decimal.', 'Decimal:'),
          mc('Which fraction has a repeating decimal?', ['{2/3}', '{3/4}', '{7/8}', '{1/5}']),
          tf('The decimal form of {7/20} terminates.'),
          sa('Use long division to write {5/6} as a decimal.', 'Decimal:'),
      ]),
      f2=B('Repeating decimals and rational numbers', '8.NS.A.1', [
          sa('Write 0.272727... as a fraction in simplest form.', 'Fraction:'),
          sa('Write 0.444... as a fraction.', 'Fraction:'),
          mc('Which number is irrational?', ['√7', '0.333...', '{5/8}', '√16']),
          tf('Every repeating decimal is a rational number.'),
          sa('Write 1.1666... as a fraction.', 'Fraction:'),
      ])),

    # ------------------------------------------------------------------ 6.NS.B.3 add/subtract
    S('6.NS.B.3', 'Add and subtract multi-digit decimals',
      main=[
          sa('Find the sum.\n315.4 + 28.75 + 6.309', 'Sum:'),
          sa('Find the difference.\n52.3 - 18.47', 'Difference:'),
          sa('Jon put this example on the board.\nWhat mistake was made? What should the sum be?', ['Mistake:', 'Correct sum:'],
             fig=stack('315.2', '24.8', '+7.936', '11.336', rule=3), pos='right', split=0.55),
          mc('A runner\'s times were 12.45 seconds and 11.9 seconds.\nHow much faster was the second time?', ['0.55 second', '1.45 seconds', '0.45 second', '11.26 seconds']),
          sa('Sam has $50. He buys a book for $12.89 and a pen for $3.75.\nHow much money does he have left?', 'Money left:'),
      ],
      back=[
          B('Place value of decimal digits', '5.NBT.A.3.a', [
              mc('In 7.358, what place value does the digit 5 have?', ['Tenths', 'Hundredths', 'Thousandths', 'Ones']),
              sa('In 42.906, which digit is in the tenths place?', 'Digit:'),
              tf('In 3.47, the digit 7 is in the hundredths place.'),
              mc('What is the value of the 8 in 0.584?', ['0.08', '0.8', '0.008', '8']),
              sa('Write 5 + 0.3 + 0.07 as a decimal.', 'Decimal:'),
          ]),
          B('Equivalent decimals', '5.NBT.A.3.b', [
              tf('2.4 and 2.40 have the same value.'),
              tf('5.6 and 5.06 have the same value.'),
              mc('Which decimal is equal to 7.5?', ['7.50', '7.05', '7.005', '0.75']),
              sa('Write 24.5 with a zero in the hundredths place.', 'Decimal:'),
              tf('0.300 = 0.3'),
          ]),
          B('Lining up decimal points', '5.NBT.B.7', [
              mc('Which setup lines up the decimal points for 36.2 + 4.58?', None, cfigs=list(setup(['36.2', '+4.58'], ['36.20', '+ 4.58'])), cfh=150),
              mc('Which setup lines up the decimal points for 5.07 + 12.3?', None, cfigs=list(setup(['5.07', '+12.30'], ['5.07', '+12.3'])), cfh=150),
              tf('The decimal points are lined up correctly.', fig=stack('8.4', '+2.75', rule=2), pos='right'),
              mc('Which setup lines up the decimal points for 15.6 - 3.42?', None, cfigs=list(setup(['15.60', '- 3.42'], ['15.6', '-3.42'])), cfh=150),
              tf('The decimal points are lined up correctly.', fig=stack('9.30', '+ 0.45', rule=2), pos='right'),
          ]),
          B('Money in decimal notation', '4.NF.C.6', [
              sa('A pen costs 2 dollars and 9 cents.\nWrite the price using a dollar sign and a decimal point.', 'Price:'),
              sa('A snack costs 75 cents.\nWrite the price using a dollar sign and a decimal point.', 'Price:'),
              tf('Six dollars and forty cents is written as $6.04.'),
              mc('Which shows 12 dollars and 30 cents?', ['$12.30', '$12.03', '$1.230', '$123.0']),
              sa('A toy costs 8 dollars and 50 cents.\nWrite the price using a dollar sign and a decimal point.', 'Price:'),
          ]),
          B('Multi-digit addition and subtraction', '4.NBT.B.4', [
              sa('Subtract.\n5,230 - 1,847', 'Difference:'),
              sa('Add.\n4,605 + 2,798', 'Sum:'),
              tf('6,000 - 2,458 = 3,542'),
              mc('8,014 - 3,276 = ?', ['4,738', '5,262', '4,838', '4,748']),
              sa('Add.\n1,975 + 3,489 + 612', 'Sum:'),
          ]),
      ],
      f1=B('Add and subtract rational numbers', '7.NS.A.1.d', [
          sa('Find the value.\n-18.6 + 4.35 =', '', fs=34),
          sa('Find the value.\n7.2 - 12.85 =', '', fs=34),
          sa('Find the value.\n-3.4 - (-9.15) =', '', fs=34),
          mc('Find the value.\n-6.25 + (-2.8) = ?', ['-9.05', '-3.45', '3.45', '9.05']),
          sa('Find the value.\n-15.75 + 20.3 =', '', fs=34),
      ]),
      f2=B('Linear equations with decimal coefficients', '8.EE.C.7.b', [
          sa('Solve for x.\n-1.5x + 6.4 = 0.5x - 1.6', 'x =', fs=28),
          sa('Solve for x.\n3.6x - 2.5 = 1.6x + 4.5', 'x =', fs=28),
          sa('Solve for x.\n0.8x + 7.2 = -1.2x + 1.2', 'x =', fs=28),
          sa('Solve for x.\n-4.5x - 3.25 = -2.5x + 0.75', 'x =', fs=28),
          sa('Solve for x.\n2.4(x + 1.5) = 1.4x + 6.6', 'x =', fs=28),
      ])),

    # ------------------------------------------------------------------ 6.NS.B.3 multiply
    S('6.NS.B.3', 'Multiply multi-digit decimals',
      main=[
          sa('Multiply.\n3.6 × 0.45', 'Product:'),
          sa('Multiply.\n12.5 × 3.8', 'Product:'),
          sa('Gas costs $3.40 per gallon.\nHow much do 12.5 gallons of gas cost?', 'Cost:'),
          mc('0.07 × 0.6 = ?', ['0.042', '0.42', '4.2', '0.0042']),
          sa('A rectangle is 4.25 meters long and 2.4 meters wide.\nWhat is its area?', 'Area:'),
      ],
      back=[
          B('Multiplying whole numbers', '5.NBT.B.5', [
              sa('Multiply.\n36 × 45', 'Product:'),
              sa('Multiply.\n125 × 38', 'Product:'),
              tf('425 × 24 = 10,200'),
              mc('34 × 125 = ?', ['4,250', '4,150', '425', '3,750']),
              sa('Multiply.\n208 × 15', 'Product:'),
          ]),
          B('Powers of 10 and the decimal point', '5.NBT.A.2', [
              sa('Multiply.\n0.45 × 10', 'Product:'),
              sa('Multiply.\n3.6 × 100', 'Product:'),
              tf('24 ÷ 10 = 2.4'),
              mc('1,620 ÷ 1,000 = ?', ['1.62', '16.2', '0.162', '162']),
              sa('Multiply.\n47.5 × 10', 'Product:'),
          ]),
          B('Multiplying tenths and hundredths', '5.NBT.B.7', [
              sa('Multiply.\n0.3 × 0.2', 'Product:'),
              sa('Multiply.\n0.5 × 0.8', 'Product:'),
              tf('0.4 × 0.4 = 1.6'),
              mc('0.2 × 0.03 = ?', ['0.006', '0.06', '0.6', '6']),
              sa('Multiply.\n1.2 × 0.3', 'Product:'),
          ]),
          B('Rounding decimals', '5.NBT.A.4', [
              sa('Round 3.62 to the nearest whole number.', 'Rounded:'),
              sa('Round 12.48 to the nearest tenth.', 'Rounded:'),
              tf('4.25 rounded to the nearest whole number is 4.'),
              mc('Round 0.456 to the nearest hundredth.', ['0.46', '0.45', '0.5', '0.4']),
              sa('Round 8.75 to the nearest whole number.', 'Rounded:'),
          ]),
      ],
      f1=B('Multiply rational numbers', '7.NS.A.2.c', [
          sa('Find the value.\n(-3.6)(0.45)', ''),
          sa('Find the value.\n(-2.5)(-4.2)', ''),
          mc('-0.8 × 1.5 = ?', ['-1.2', '1.2', '-0.12', '0.12']),
          sa('Find the value.\n(-1.2)(-0.5)(-3)', ''),
          tf('(-0.6)(0.7) = 0.42'),
      ]),
      f2=B('Multiply numbers in scientific notation', '8.EE.A.4', [
          sa('Multiply. Write the answer in scientific notation.\n(3.6 × 10⁴)(4.5 × 10⁻²)', 'Product:'),
          sa('Multiply. Write the answer in scientific notation.\n(2.5 × 10³)(4 × 10⁵)', 'Product:'),
          mc('(1.2 × 10⁶)(3 × 10⁻⁴) = ?', ['3.6 × 10²', '3.6 × 10¹⁰', '4.2 × 10²', '3.6 × 10⁻²']),
          sa('A light-year is about 9.5 × 10¹² km.\nAbout how many kilometers are in 4.2 light-years? Write the answer in scientific notation.', 'Kilometers:'),
          tf('(5 × 10³)(6 × 10²) = 3 × 10⁶'),
      ])),

    # ------------------------------------------------------------------ 6.NS.B.3 divide
    S('6.NS.B.3', 'Divide multi-digit decimals',
      main=[
          sa('Divide.\n15.75 ÷ 0.35', 'Quotient:'),
          sa('Divide.\n8.64 ÷ 2.4', 'Quotient:'),
          sa('A rope is 12.6 meters long. It is cut into pieces that are each 0.45 meter long.\nHow many pieces are there?', 'Pieces:'),
          mc('0.72 ÷ 0.08 = ?', ['9', '0.9', '90', '0.09']),
          sa('A car traveled 283.5 miles on 13.5 gallons of gas.\nHow many miles did it travel per gallon?', 'Miles per gallon:'),
      ],
      back=[
          B('Dividing by a two-digit number', '5.NBT.B.6', [
              sa('Divide.\n1,575 ÷ 35', 'Quotient:'),
              sa('Divide.\n864 ÷ 24', 'Quotient:'),
              tf('1,260 ÷ 45 = 28'),
              mc('672 ÷ 32 = ?', ['21', '12', '210', '22']),
              sa('Divide.\n936 ÷ 18', 'Quotient:'),
          ]),
          B('Using powers of 10 to shift the decimal point', '5.NBT.A.2', [
              mc('Which has the same quotient as 15.75 ÷ 0.35?', ['1,575 ÷ 35', '157.5 ÷ 35', '1,575 ÷ 3.5', '15.75 ÷ 35']),
              tf('8.64 ÷ 2.4 has the same quotient as 86.4 ÷ 24.'),
              sa('Multiply.\n0.35 × 100', 'Product:'),
              sa('Multiply.\n15.75 × 100', 'Product:'),
              mc('0.08 × ___ = 8', ['100', '10', '1,000', '0.1']),
          ]),
          B('Dividing tenths and hundredths', '5.NBT.B.7', [
              sa('Divide.\n2.4 ÷ 0.6', 'Quotient:'),
              sa('Divide.\n3.5 ÷ 0.5', 'Quotient:'),
              tf('1.2 ÷ 0.3 = 0.4'),
              mc('0.9 ÷ 0.3 = ?', ['3', '0.3', '30', '0.03']),
              sa('Divide.\n4.8 ÷ 4', 'Quotient:'),
          ]),
      ],
      f1=B('Divide rational numbers', '7.NS.A.2.b', [
          sa('Find the value.\n(-15.75) ÷ 0.35', ''),
          sa('Find the value.\n-8.64 ÷ (-2.4)', ''),
          tf('-(12 ÷ 4) = (-12) ÷ 4'),
          mc('7.2 ÷ (-0.9) = ?', ['-8', '8', '-0.8', '0.8']),
          sa('The temperature fell 13.5°F in 4.5 hours at a constant rate.\nWhat was the change in temperature per hour?', 'Change per hour:'),
      ]),
      f2=B('Compare quantities with powers of 10', '8.EE.A.3', [
          sa('The population of a city is about 3 × 10⁶. The population of a town is about 6 × 10⁴.\nHow many times as large is the city\'s population?', 'Times as large:'),
          mc('About how many times as large is 9 × 10⁸ as 3 × 10⁵?', ['3,000', '300', '30,000', '3']),
          sa('Estimate 0.00047 as a single digit times an integer power of 10.', 'Estimate:'),
          sa('An elephant has a mass of about 6 × 10³ kg. An ant has a mass of about 3 × 10⁻⁶ kg.\nHow many times as large is the elephant\'s mass?', 'Times as large:'),
          tf('8 × 10⁷ is 20 times as large as 4 × 10⁶.'),
      ])),

    # ------------------------------------------------------------------ 6.NS.B.4 GCF / LCM
    S('6.NS.B.4', 'Greatest common factor and least common multiple',
      main=[
          sa('Find the greatest common factor of 24 and 36.', 'GCF:'),
          sa('Find the least common multiple of 6 and 8.', 'LCM:'),
          sa('Hot dogs come in packs of 10. Buns come in packs of 8.\nWhat is the least number of hot dogs you can buy to have the same number of hot dogs and buns?', 'Hot dogs:'),
          mc('What is the greatest common factor of 18 and 45?', ['9', '3', '90', '15']),
          sa('A teacher has 42 pencils and 56 erasers. She makes identical kits and uses every item.\nWhat is the greatest number of kits she can make?', 'Kits:'),
      ],
      back=[
          B('Factors', '4.OA.B.4', [
              sa('List all the factors of 18.', 'Factors:'),
              tf('7 is a factor of 42.'),
              mc('Which number is NOT a factor of 36?', ['8', '9', '12', '4']),
              tf('5 is a factor of 32.'),
              sa('List all the factors of 24.', 'Factors:'),
          ]),
          B('Multiples', '4.OA.B.4', [
              sa('List the first five multiples of 6.', 'Multiples:'),
              tf('36 is a multiple of 8.'),
              mc('Which number is a multiple of both 4 and 6?', ['12', '18', '8', '20']),
              tf('45 is a multiple of 9.'),
              sa('What is the 4th multiple of 7?', 'Multiple:'),
          ]),
          B('Prime and composite numbers', '4.OA.B.4', [
              tf('13 is a prime number.'),
              mc('Which number is composite?', ['21', '17', '11', '2']),
              tf('1 is a prime number.'),
              sa('Is 29 prime or composite?', 'Answer:'),
              mc('Which number is prime?', ['31', '27', '33', '39']),
          ]),
      ],
      f1=B('Add and subtract rational numbers with unlike denominators', '7.NS.A.1.d', [
          sa('Find the value.\n-{5/6} + {3/8}', ''),
          sa('Find the value.\n{3/4} - (-{1/6})', ''),
          mc('-{2/3} - {1/4} = ?', ['-{11/12}', '-{1/12}', '{5/12}', '-{3/7}']),
          sa('Find the value.\n-1{1/2} + {5/6}', ''),
          tf('{3/10} + (-{2/15}) = {1/6}'),
      ]),
      f2=B('Equations with fractions: clearing denominators', '8.EE.C.7.b', [
          sa('Solve for x.\n{x/6} + {x/8} = 7', 'x ='),
          sa('Solve for x.\n{x/4} - 1 = {x/6} + 2', 'x ='),
          mc('Solve for x.\n{2x/3} + {x/2} = 14', ['12', '7', '42', '{84/5}']),
          sa('Solve for x.\n{x/5} + 3 = {x/2}', 'x ='),
          sa('Solve for x.\n{(x+1)/4} = {(x−2)/3}', 'x ='),
      ])),

    # ------------------------------------------------------------------ 6.NS.B.4 distributive
    S('6.NS.B.4', 'Use the distributive property to factor a sum with the GCF',
      main=[
          sa('Use the greatest common factor to write 36 + 8 as a product of the GCF and a sum of two whole numbers.', 'Expression:'),
          mc('Which expression is equal to 42 + 56 and uses the greatest common factor?', ['14(3 + 4)', '7(6 + 8)', '2(21 + 28)', '14(3 + 8)']),
          sa('Use the greatest common factor to write 27 + 45 as a product.', 'Expression:'),
          tf('24 + 60 = 12(2 + 5)'),
          sa('Complete the equation.\n30 + 75 = 15(___ + ___)', ['First blank:', 'Second blank:']),
      ],
      back=[
          B('Factors of a number', '4.OA.B.4', [
              tf('4 is a factor of both 36 and 8.'),
              sa('List the factors of 12 and the factors of 18. Which factors do they share?', 'Shared factors:'),
              mc('Which number is a factor of both 27 and 45?', ['9', '5', '6', '15']),
              sa('List all the factors of 42.', 'Factors:'),
              tf('6 is a factor of 56.'),
          ]),
          B('Distributive property with whole numbers', '3.OA.B.5', [
              tf('8 × 7 = 8 × 5 + 8 × 2'),
              tf('4 × (9 + 2) = 4 × 9 + 2'),
              mc('Which is equal to 6 × 12?', ['6 × 10 + 6 × 2', '6 × 10 + 2', '6 + 10 × 2', '6 × 10 × 2']),
              sa('Fill in the blank.\n5 × 13 = 5 × 10 + 5 × ___', 'Blank:'),
              sa('Fill in the blank.\n3 × (4 + 5) = 3 × 4 + 3 × ___', 'Blank:'),
          ]),
          B('Parentheses and order of operations', '5.OA.A.1', [
              sa('Evaluate.\n4 × (9 + 2)', 'Value:'),
              sa('Evaluate.\n14 × (3 + 4)', 'Value:'),
              tf('9 × (3 + 5) = 32'),
              mc('12 × (2 + 5) = ?', ['84', '29', '17', '60']),
              sa('Evaluate.\n(20 - 5) × 3', 'Value:'),
          ]),
      ],
      f1=B('Factor and expand linear expressions', '7.EE.A.1', [
          sa('Factor.\n12x - 18', 'Factored form:'),
          sa('Expand.\n-3(2x - 5)', 'Expanded form:'),
          mc('Which expression is equivalent to 8y + 20?', ['4(2y + 5)', '8(y + 20)', '2(4y + 20)', '4(2y + 20)']),
          sa('Factor.\n15a + 10b - 5', 'Factored form:'),
          tf('{1/2}(6x - 4) = 3x - 2'),
      ]),
      f2=B('One, none, or infinitely many solutions', '8.EE.C.7.a', [
          mc('How many solutions does the equation have?\n4(x + 3) = 4x + 12', ['One solution', 'No solution', 'Infinitely many solutions']),
          mc('How many solutions does the equation have?\n2(3x - 1) = 6x + 5', ['One solution', 'No solution', 'Infinitely many solutions']),
          mc('How many solutions does the equation have?\n3(x + 2) = 2x + 9', ['One solution', 'No solution', 'Infinitely many solutions']),
          sa('What number goes in the box so that the equation has infinitely many solutions?\n5(x - 2) = 5x - □', '□ ='),
          mc('Which equation has no solution?', ['2(x + 4) = 2x + 5', '2(x + 4) = 2x + 8', '2(x + 4) = x + 8', '2(x + 4) = 3x']),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.5
    S('6.NS.C.5', 'Positive and negative numbers in real-world contexts',
      main=[
          sa('A diver is 30 feet below sea level.\nWrite an integer to represent the diver\'s position.', 'Integer:'),
          sa('The thermometer shows the temperature in °F.\nWhat is the temperature?', 'Temperature:',
             fig=nl(-10, 10, 2, vertical=True, pts=[(-8, '')], caption='°F'), pos='right'),
          mc('A bank account shows a withdrawal of $45.\nWhich number represents this change?', ['-45', '45', '0', '-4.5']),
          tf('When integers describe elevation, 0 represents sea level.'),
          sa('A hawk flies 120 feet above sea level. A submarine is 120 feet below sea level.\nWrite an integer for each position.', ['Hawk:', 'Submarine:']),
      ],
      back=[
          B('Whole numbers as distances from 0', '2.MD.B.6', [
              sa('What number does point A represent?', 'Number:', fig=nl(0, 10, 1, pts=[(7, 'A')])),
              sa('How many units from 0 is the number 6?', 'Units:'),
              tf('On a number line, 9 is farther from 0 than 4 is.'),
              mc('Which point is 3 units from 0?', LET, fig=nl(0, 10, 1, pts=[(3, 'A'), (5, 'B'), (8, 'C'), (1, 'D')])),
              sa('What number does point B represent?', 'Number:', fig=nl(0, 20, 2, pts=[(14, 'B')])),
          ]),
          B('Reading a vertical scale', '4.MD.A.2', [
              sa('What temperature does the thermometer show?', 'Temperature:', fig=nl(0, 50, 10, vertical=True, pts=[(30, '')], caption='°F'), pos='right'),
              sa('What number does the point show?', 'Number:', fig=nl(0, 100, 10, vertical=True, pts=[(70, '')]), pos='right'),
              tf('The point is at 40.', fig=nl(0, 50, 10, vertical=True, pts=[(40, '')]), pos='right'),
              mc('Which point shows 25?', LET, fig=nl(0, 50, 5, labels=[0, 10, 20, 30, 40, 50], vertical=True,
                                                      pts=[(25, 'A'), (30, 'B'), (20, 'C'), (35, 'D')]), pos='right'),
              sa('What number does the point show?', 'Number:', fig=nl(0, 20, 2, vertical=True, pts=[(16, '')]), pos='right'),
          ]),
          B('Increase and decrease situations', '2.OA.A.1', [
              sa('Kim had $20. She spent $8.\nHow much money does she have now?', 'Money:'),
              sa('A plant was 12 cm tall. It grew 5 cm.\nHow tall is the plant now?', 'Height:'),
              mc('Which situation describes a decrease?', ['A balloon loses 6 feet of height.', 'A plant grows 4 inches.', 'Tom earns $10.', 'A team gains 5 yards.']),
              tf('"The temperature fell 7 degrees" describes a decrease.'),
              mc('Which word describes an increase in money?', ['Deposit', 'Withdrawal', 'Loss', 'Drop']),
          ]),
      ],
      f1=B('Adding integers as moving on a number line', '7.NS.A.1.b', [
          sa('The temperature is -4°F. It rises 9°F.\nWhat is the new temperature?', 'Temperature:'),
          sa('A submarine is at -120 feet. It rises 45 feet.\nWhat is its new position?', 'Position:'),
          mc('On a number line, where is 6 + (-4) compared to 6?', ['4 units to the left of 6', '4 units to the right of 6', '6 units to the left of 4', 'At 0']),
          sa('The number line shows -2 + 5.\nWhat is the sum?', 'Sum:', fig=nl(-5, 5, 1, jumps=[(-2, 3, '+5')])),
          tf('A $30 debt plus a $30 deposit makes a balance of $0.'),
      ]),
      f2=B('Negative rate of change in a linear function', '8.F.B.4', [
          sa('A tank holds 60 gallons. It drains 3 gallons per minute.\nWrite a function for the amount A after t minutes.', 'A ='),
          mc('An airplane at 12,000 feet descends 800 feet per minute.\nWhat is the rate of change of its altitude?', ['-800 feet per minute', '800 feet per minute', '12,000 feet per minute', '-12,000 feet per minute']),
          sa('The table shows a linear function.\nWhat is the rate of change in degrees per hour?', 'Rate of change:',
             fig=table([['Hours', '0', '2', '4'], ['Temperature (°F)', '5', '1', '-3']])),
          sa('A diver starts at -10 feet and descends 4 feet per second.\nWrite a function for the diver\'s position d after t seconds.', 'd ='),
          tf('A line through (0, 8) and (4, 0) has a rate of change of -2.'),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.6.a
    S('6.NS.C.6.a', 'Opposite signs as opposite sides of 0; the opposite of the opposite',
      main=[
          sa('What is the opposite of -7?', 'Opposite:'),
          sa('Simplify.\n-(-12)', 'Value:'),
          mc('Which number is the opposite of the number at point P?', ['5', '-5', '0', '{1/5}'], fig=nl(-6, 6, 1, pts=[(-5, 'P')])),
          tf('0 is its own opposite.'),
          sa('What is the opposite of the opposite of 9?', 'Answer:'),
      ],
      back=[
          B('Distance from 0 on a number line', '2.MD.B.6', [
              sa('How far is point A from 0?', 'Units:', fig=nl(0, 10, 1, pts=[(4, 'A')])),
              sa('How many units from 0 is the number 8?', 'Units:'),
              mc('Which number is 2 units from 0?', ['2', '0', '4', '20']),
              sa('What number does point K represent?', 'Number:', fig=nl(0, 12, 1, pts=[(9, 'K')])),
              tf('The distance from 0 to 7 is 7 units.'),
          ]),
          B('Positive and negative numbers in context', '6.NS.C.5', [
              tf('-5 can represent 5 degrees below zero.'),
              sa('Write an integer for a gain of 12 yards.', 'Integer:'),
              mc('Which integer represents 20 feet below sea level?', ['-20', '20', '0', '-2']),
              sa('Write an integer for a loss of $7.', 'Integer:'),
              tf('A deposit of $15 is written as -15.'),
          ]),
      ],
      f1=B('Opposite quantities combine to make 0', '7.NS.A.1.a', [
          sa('A hydrogen atom has 1 proton (charge +1) and 1 electron (charge -1).\nWhat is its total charge?', 'Total charge:'),
          tf('-8 + 8 = 0'),
          mc('Which sum is equal to 0?', ['-3.5 + 3.5', '-3.5 + (-3.5)', '3.5 + 3.5', '-3.5 + 0']),
          sa('You earn $25 and then spend some money. The total change in your money is $0.\nHow much did you spend?', 'Amount spent:'),
          sa('What number added to 14.2 gives 0?', 'Number:'),
      ]),
      f2=B('Solve equations using inverse terms', '8.EE.C.7.b', [
          sa('Solve for x.\n5x - 7 = 2x + 8', 'x ='),
          sa('Solve for x.\n-3x + 4 = 3x - 8', 'x ='),
          mc('Solve for x.\n6 - 2x = 4x - 12', ['3', '-3', '1', '9']),
          sa('Solve for x.\n7x + 3 = -2x + 21', 'x ='),
          sa('Solve for x.\n4(x - 1) = 2x + 10', 'x ='),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.6.b
    S('6.NS.C.6.b', 'Signs of coordinates in the quadrants; reflections across the axes',
      main=[
          mc('In which quadrant is the point (-4, 7)?', ['Quadrant II', 'Quadrant I', 'Quadrant III', 'Quadrant IV']),
          sa('The point (3, -5) is reflected across the x-axis.\nWhat are the coordinates of its image?', 'Image:'),
          sa('The point (-2, 6) is reflected across the y-axis.\nWhat are the coordinates of its image?', 'Image:'),
          mc('How are the points (a, b) and (a, -b) related when b is not 0?',
             ['They are reflections of each other across the x-axis.', 'They are reflections of each other across the y-axis.',
              'They are the same point.', 'They are always in the same quadrant.']),
          sa('Point A is reflected across the y-axis.\nWhat are the coordinates of its image?', 'Image:', fig=coord(pts=[(-4, 3, 'A')])),
      ],
      back=[
          B('Axes, origin, and ordered pairs', '5.G.A.1', [
              tf('The origin is the point (0, 0).'),
              mc('In the ordered pair (5, 2), which number tells how far to move along the x-axis?', ['5', '2', '7', '3']),
              sa('What is the name of the point where the x-axis and the y-axis meet?', 'Name:'),
              tf('In the ordered pair (3, 8), the y-coordinate is 3.'),
              mc('Which axis is horizontal?', ['The x-axis', 'The y-axis']),
          ]),
          B('Plotting points in the first quadrant', '5.G.A.2', [
              sa('What are the coordinates of point B?', 'B =', fig=q1(8, 8, pts=[(5, 4, 'B')])),
              mc('Which point is located at (2, 6)?', LET, fig=q1(8, 8, pts=[(2, 6, 'A'), (6, 2, 'B'), (2, 2, 'C'), (6, 6, 'D')])),
              sa('What are the coordinates of point T?', 'T =', fig=q1(8, 8, pts=[(7, 0, 'T', 'n')])),
              tf('Point R is located at (2, 4).', fig=q1(8, 8, pts=[(4, 2, 'R')])),
              sa('What are the coordinates of point W?', 'W =', fig=q1(8, 8, pts=[(1, 6, 'W')])),
          ]),
          B('Opposite numbers', '6.NS.C.6.a', [
              sa('What is the opposite of 6?', 'Opposite:'),
              tf('The opposite of -9 is 9.'),
              mc('Which pair of numbers are opposites?', ['-4 and 4', '-4 and -4', '4 and {1/4}', '0 and 4']),
              sa('What is the opposite of -2.5?', 'Opposite:'),
              tf('-(-3) = -3'),
          ]),
          B('Lines of symmetry', '4.G.A.3', [
              tf('A line of symmetry divides a figure into two matching halves.'),
              mc('How many lines of symmetry does a square have?', ['4', '2', '1', '0']),
              tf('The dashed line is a line of symmetry of the rectangle.', fig=SYM),
              mc('Which letter has a vertical line of symmetry?', ['A', 'F', 'J', 'R']),
              sa('How many lines of symmetry does a rectangle that is not a square have?', 'Lines:'),
          ]),
      ],
      f1=B('Interpret points on the graph of a proportional relationship', '7.RP.A.2.d', [
          sa('The graph shows the cost of apples.\nWhat does the point (2, 8) represent?', 'Meaning:',
             fig=q1(5, 20, ystep=4, square=False, xlabel='Pounds', ylabel='Cost ($)', pts=[(1, 4), (2, 8), (3, 12)], lines=[((0, 0), (5, 20))])),
          mc('The graph shows the cost of apples.\nWhat does the point (1, 4) represent?',
             ['1 pound costs $4.', '4 pounds cost $1.', 'The cost starts at $4.', '$1 buys 4 pounds.'],
             fig=q1(5, 20, ystep=4, square=False, xlabel='Pounds', ylabel='Cost ($)', pts=[(1, 4), (2, 8), (3, 12)], lines=[((0, 0), (5, 20))])),
          tf('On the graph of a proportional relationship between pounds and cost, the point (0, 0) means 0 pounds cost $0.'),
          sa('The graph of a proportional relationship passes through (1, r) and (5, 30).\nWhat is r?', 'r ='),
          mc('A graph shows the distance y in miles after x hours. It passes through (3, 150).\nWhat does this point mean?',
             ['In 3 hours, the distance is 150 miles.', 'In 150 hours, the distance is 3 miles.', 'The speed is 3 miles per hour.', 'The speed is 150 miles per hour.']),
      ]),
      f2=B('Transformations with coordinates', '8.G.A.3', [
          sa('A triangle has a vertex at (2, -3). The triangle is reflected across the y-axis.\nWhat are the coordinates of the image of that vertex?', 'Image:'),
          mc('Which transformation is described by (x, y) → (x, -y)?', ['A reflection across the x-axis', 'A reflection across the y-axis', 'A rotation of 180°', 'A translation']),
          sa('The point (4, 1) is rotated 180° about the origin.\nWhat are the coordinates of its image?', 'Image:'),
          sa('The point (-3, 5) is translated 4 units right and 2 units down.\nWhat are the coordinates of its image?', 'Image:'),
          tf('Rotating (2, 5) 90° counterclockwise about the origin gives (-5, 2).'),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.6.c number line
    S('6.NS.C.6.c', 'Find and position rational numbers on a number line',
      main=[
          sa('What number does point P represent?', 'P =', fig=nl(-3, 3, 0.5, labels=[-3, -2, -1, 0, 1, 2, 3], pts=[(-1.5, 'P')])),
          mc('Which point is located at -2{1/4}?', LET, fig=nl(-3, 0, 0.25, labels=[-3, -2, -1, 0],
                                                          pts=[(-2.25, 'A'), (-1.75, 'B'), (-2.75, 'C'), (-0.25, 'D')])),
          sa('Write the number at point Q as a mixed number.', 'Q =', fig=nl(-2, 2, 0.25, labels=[-2, -1, 0, 1, 2], pts=[(-1.25, 'Q')])),
          tf('Point R is located at -0.6.', fig=nl(-1, 1, 0.1, labels=[-1, 0, 1], pts=[(-0.4, 'R')])),
          sa('The number line shows elevations in meters.\nWhat elevation does point S show?', 'S =',
             fig=nl(-30, 30, 10, vertical=True, pts=[(-20, 'S')]), pos='right'),
      ],
      back=[
          B('Fractions on a number line', '3.NF.A.2', [
              sa('What fraction does point A represent?', 'A =', fig=nl(0, 1, 0.25, labels={0: '0', 1: '1'}, pts=[(0.75, 'A')])),
              sa('What fraction does point B represent?', 'B =', fig=nl(0, 1, 1 / 3, labels={0: '0', 1: '1'}, pts=[(1 / 3, 'B')])),
              tf('Point C is located at {5/6}.', fig=nl(0, 1, 1 / 6, labels={0: '0', 1: '1'}, pts=[(5 / 6, 'C')])),
              mc('The space from 0 to 1 is split into equal parts.\nHow many equal parts are there?', ['8', '7', '9', '10'], fig=nl(0, 1, 0.125, labels={0: '0', 1: '1'})),
              sa('Write the number at point D as a fraction.', 'D =', fig=nl(0, 2, 0.5, labels={0: '0', 1: '1', 2: '2'}, pts=[(1.5, 'D')])),
          ]),
          B('Decimals on a number line', '4.NF.C.6', [
              sa('What decimal does point A represent?', 'A =', fig=nl(0, 1, 0.1, labels=[0, 1], pts=[(0.7, 'A')])),
              sa('What decimal does point B represent?', 'B =', fig=nl(2, 3, 0.1, labels=[2, 3], pts=[(2.4, 'B')])),
              tf('Point C is located at 0.3.', fig=nl(0, 1, 0.1, labels=[0, 1], pts=[(0.3, 'C')])),
              mc('What decimal does point D represent?', ['0.26', '2.6', '0.206', '0.62'],
                 fig=nl(0.2, 0.3, 0.01, labels={0.2: '0.2', 0.3: '0.3'}, pts=[(0.26, 'D')])),
              sa('What decimal does point E represent?', 'E =', fig=nl(5, 6, 0.1, labels=[5, 6], pts=[(5.9, 'E')])),
          ]),
          B('Opposites on a number line', '6.NS.C.6.a', [
              sa('Point B (not shown) is the opposite of point A.\nWhat number is at point B?', 'B =', fig=nl(-5, 5, 1, pts=[(3, 'A')])),
              tf('-2.5 and 2.5 are the same distance from 0.'),
              mc('What is the opposite of 1{3/4}?', ['-1{3/4}', '1{3/4}', '-{4/7}', '{4/7}']),
              sa('What is the opposite of -0.8?', 'Opposite:'),
              tf('Points A and B represent opposite numbers.', fig=nl(-5, 5, 1, pts=[(-4, 'A'), (3, 'B')])),
          ]),
      ],
      f1=B('Adding rational numbers on a number line', '7.NS.A.1.b', [
          sa('Start at -2.5 on a number line and move 4 units to the right.\nWhere do you end?', 'Number:'),
          sa('The number line shows 1 + (-4).\nWhat is the sum?', 'Sum:', fig=nl(-5, 5, 1, jumps=[(1, -3, '-4')])),
          mc('Which expression does the number line show?', ['-3 + 5', '5 + 3', '-3 - 5', '2 + 5'], fig=nl(-5, 5, 1, jumps=[(-3, 2, '+5')])),
          sa('Find the sum.\n-1{1/2} + 3{1/4}', 'Sum:'),
          tf('On a number line, -3 + 7 is 7 units to the right of -3.'),
      ]),
      f2=B('Approximate irrational numbers on a number line', '8.NS.A.2', [
          sa('Between which two consecutive whole numbers is √20?', 'Between:'),
          mc('Which point best shows √10?', LET, fig=nl(0, 5, 0.5, labels=[0, 1, 2, 3, 4, 5], pts=[(3.16, 'A'), (2.5, 'B'), (3.8, 'C'), (1, 'D')])),
          sa('Estimate √50 to the nearest tenth.', 'Estimate:'),
          mc('Which list is ordered from least to greatest?', ['√5, 2.5, √8', '2.5, √5, √8', '√8, √5, 2.5', '√5, √8, 2.5']),
          tf('π is between 3.1 and 3.2 on the number line.'),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.6.c coordinate plane
    S('6.NS.C.6.c', 'Find and position pairs of numbers on the coordinate plane',
      main=[
          sa('What are the coordinates of point A?', 'A =', fig=coord(pts=[(-4, 3, 'A'), (2, -5, 'B'), (-3, -2, 'C'), (5, 1, 'D')])),
          mc('Which point is located at (-3, -2)?', LET, fig=coord(pts=[(-4, 3, 'A'), (2, -5, 'B'), (-3, -2, 'C'), (5, 1, 'D')])),
          sa('What are the coordinates of point B?', 'B =', fig=coord(pts=[(-4, 3, 'A'), (2, -5, 'B'), (-3, -2, 'C'), (5, 1, 'D')])),
          mc('Which ordered pair names point M?', ['(0, -4)', '(-4, 0)', '(4, 0)', '(0, 4)'], fig=coord(pts=[(0, -4, 'M', 'e')])),
          sa('What are the coordinates of point K?', 'K =', fig=coord(pts=[(-5, -1, 'K')])),
      ],
      back=[
          B('Ordered pairs and the axes', '5.G.A.1', [
              tf('The x-coordinate tells how far to move from the origin along the x-axis.'),
              mc('In the ordered pair (7, 3), what is the y-coordinate?', ['3', '7', '10', '4']),
              sa('What are the coordinates of the origin?', 'Origin:'),
              tf('(2, 5) and (5, 2) name the same point.'),
              mc('To plot (6, 1) starting from the origin, what do you do first?', ['Move 6 units right', 'Move 6 units up', 'Move 1 unit right', 'Move 1 unit up']),
          ]),
          B('Reading points in the first quadrant', '5.G.A.2', [
              sa('What are the coordinates of point E?', 'E =', fig=q1(8, 8, pts=[(3, 6, 'E')])),
              sa('What are the coordinates of point F?', 'F =', fig=q1(8, 8, pts=[(6, 3, 'F')])),
              mc('Which point is located at (4, 0)?', LET, fig=q1(8, 8, pts=[(4, 0, 'A', 'n'), (0, 4, 'B', 'e'), (4, 4, 'C'), (1, 4, 'D')])),
              tf('Point H is located at (5, 2).', fig=q1(8, 8, pts=[(2, 5, 'H')])),
              sa('What are the coordinates of point G?', 'G =', fig=q1(8, 8, pts=[(0, 3, 'G', 'e')])),
          ]),
          B('Quadrants and signs of coordinates', '6.NS.C.6.b', [
              mc('In which quadrant are both coordinates negative?', ['Quadrant III', 'Quadrant I', 'Quadrant II', 'Quadrant IV']),
              mc('In which quadrant is (5, -2)?', ['Quadrant IV', 'Quadrant I', 'Quadrant II', 'Quadrant III']),
              tf('(-3, 4) is in Quadrant II.'),
              sa('A point is in Quadrant IV.\nWrite "positive" or "negative" for each coordinate.', ['x-coordinate:', 'y-coordinate:']),
              tf('The point (0, -6) is in Quadrant III.'),
          ]),
      ],
      f1=B('Proportional relationships on a graph', '7.RP.A.2.a', [
          tf('The graph shows a proportional relationship.', fig=q1(5, 10, ystep=2, square=False, pts=[(1, 2), (2, 4), (3, 6)], lines=[((0, 0), (5, 10))])),
          mc('The points (1, 3), (2, 5), and (3, 7) are graphed.\nDo they show a proportional relationship?',
             ['No, because the line through them does not pass through the origin.', 'Yes, because they form a straight line.',
              'Yes, because y increases by 2.', 'No, because they are not on a line.']),
          sa('The table shows x-values 2, 4, 6 and y-values 5, 10, 15.\nWould the graph be a straight line through the origin? Write yes or no.', 'Answer:'),
          tf('The graph shows a proportional relationship.', fig=q1(4, 10, ystep=2, square=False, pts=[(0, 0), (1, 1), (2, 4), (3, 9)])),
          mc('Which set of points lies on a straight line through the origin?',
             ['(2, 3), (4, 6), (6, 9)', '(1, 3), (2, 4), (3, 5)', '(0, 2), (1, 4), (2, 6)', '(1, 1), (2, 4), (3, 9)']),
      ]),
      f2=B('Functions as sets of ordered pairs', '8.F.A.1', [
          tf('The set of ordered pairs (1, 2), (2, 4), (3, 6), (4, 8) represents a function.'),
          mc('Which set of ordered pairs does NOT represent a function?',
             ['(2, 5), (2, 7), (3, 9)', '(1, 4), (2, 4), (3, 4)', '(0, 0), (1, 1), (2, 2)', '(-1, 3), (0, 5), (1, 7)']),
          sa('Does the set (4, 1), (5, 2), (4, 3) represent a function? Write yes or no.', 'Answer:'),
          tf('The graph represents a function.', fig=coord(pts=[(-3, 2), (-1, -2), (1, 3), (3, -1)])),
          mc('A function assigns to each input ___.', ['exactly one output', 'at least two outputs', 'the same output as the input', 'no output']),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.7.a
    S('6.NS.C.7.a', 'Interpret inequalities as relative position on a number line',
      main=[
          mc('-3 > -7\nWhich statement explains this inequality?',
             ['-3 is to the right of -7 on a number line.', '-3 is to the left of -7 on a number line.',
              '3 is less than 7.', '-3 is farther from 0 than -7.']),
          tf('The number line shows that -6 > -1.', fig=nl(-8, 2, 1, pts=[(-6, 'A'), (-1, 'B')])),
          sa('Write an inequality that compares -4 and -9.', 'Inequality:'),
          mc('Which statement is true?', ['-5 < -2', '-5 > -2', '-2 < -5', '-5 > 0']),
          sa('Write an inequality using the numbers at points P and Q.', 'Inequality:', fig=nl(-5, 5, 1, pts=[(-2, 'P'), (1, 'Q')])),
      ],
      back=[
          B('Comparison symbols', '2.NBT.A.4', [
              sa('Write >, <, or = to compare.\n452 ___ 425', 'Symbol:'),
              tf('67 < 76'),
              mc('Which statement is true?', ['309 > 290', '309 < 290', '309 = 290']),
              sa('Write >, <, or = to compare.\n138 ___ 183', 'Symbol:'),
              tf('500 > 505'),
          ]),
          B('Position on a number line', '2.MD.B.6', [
              tf('On a number line, 8 is to the right of 3.'),
              mc('Which number is farthest to the left on a number line?', ['2', '7', '5', '9']),
              sa('Which point is farther to the left, A or B?', 'Point:', fig=nl(0, 10, 1, pts=[(6, 'A'), (2, 'B')])),
              tf('Numbers get greater as you move to the left on a number line.'),
              mc('Which number is to the right of 14 on a number line?', ['19', '11', '9', '14']),
          ]),
          B('Negative numbers on a number line', '6.NS.C.6.c', [
              sa('What number is at point A?', 'A =', fig=nl(-8, 2, 1, pts=[(-6, 'A')])),
              mc('Which point is at -3?', LET, fig=nl(-5, 5, 1, pts=[(-3, 'A'), (3, 'B'), (-2, 'C'), (-4, 'D')])),
              tf('-4 is to the left of -1 on a number line.'),
              sa('What number is at point B?', 'B =', fig=nl(-10, 0, 2, pts=[(-8, 'B')])),
              mc('Which point is at -5?', LET, fig=nl(-6, 0, 1, pts=[(-1, 'A'), (-5, 'B'), (-6, 'C'), (-4, 'D')])),
          ]),
      ],
      f1=B('Solve and graph inequalities', '7.EE.B.4.b', [
          mc('Which inequality does the graph show?', ['x > 3', 'x ≥ 3', 'x < 3', 'x ≤ 3'], fig=nl(-5, 5, 1, ray=(3, 'right', True))),
          sa('Solve the inequality.\n2x + 5 > 11', 'Solution:'),
          sa('Solve the inequality.\n-3x + 4 ≤ 16', 'Solution:'),
          tf('The graph shows the solutions of 4x - 1 ≤ -9.', fig=nl(-5, 5, 1, ray=(-2, 'left', False))),
          sa('Solve the inequality.\n5x - 2 < 18', 'Solution:'),
      ]),
      f2=B('Compare and order irrational numbers', '8.NS.A.2', [
          sa('Which is greater, √50 or 7.2?', 'Greater:'),
          mc('Which number is between 3 and 4?', ['√12', '√8', '√17', '√3']),
          tf('√30 < 5.5'),
          sa('Order from least to greatest.\nπ, √8, 3.1', 'Order:'),
          mc('Which point best shows -√5?', LET, fig=nl(-4, 0, 0.5, labels=[-4, -3, -2, -1, 0], pts=[(-2.24, 'A'), (-1.5, 'B'), (-2.8, 'C'), (-3.5, 'D')])),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.7.b
    S('6.NS.C.7.b', 'Write, interpret, and explain order statements in real-world contexts',
      main=[
          sa('A temperature of -3°C is warmer than a temperature of -7°C.\nWrite an inequality to show this.', 'Inequality:'),
          mc('Account A has a balance of -$25. Account B has a balance of -$40.\nWhich statement is true?',
             ['-25 > -40, so Account A has the greater balance.', '-40 > -25, so Account B has the greater balance.',
              '-25 < -40, so Account A owes more.', 'The balances are equal.']),
          sa('A fish swims at -12 feet. A turtle swims at -5 feet.\nWrite an inequality to compare the positions. Which animal is deeper?', ['Inequality:', 'Deeper animal:']),
          tf('-15 < -10 means that -15°F is colder than -10°F.'),
          mc('The lowest point in Death Valley is -86 meters. A beach is at 0 meters.\nWhich statement is true?',
             ['-86 < 0, so Death Valley\'s lowest point is lower.', '-86 > 0, so Death Valley\'s lowest point is higher.',
              '0 < -86, so the beach is lower.', '-86 = 0']),
      ],
      back=[
          B('Negative numbers in context', '6.NS.C.5', [
              sa('Write an integer for 12 degrees below zero.', 'Integer:'),
              tf('A debt of $30 can be written as -30.'),
              mc('Which situation could be represented by -6?', ['A loss of 6 yards', 'A gain of 6 yards', '6 feet above sea level', 'A deposit of $6']),
              sa('Write an integer for 50 feet below sea level.', 'Integer:'),
              tf('A temperature of 4 degrees above zero is written as -4.'),
          ]),
          B('Inequality symbols', '1.NBT.B.3', [
              mc('Which symbol makes this true?\n42 ___ 24', ['>', '<', '=']),
              tf('15 > 51'),
              sa('Write >, <, or = to compare.\n73 ___ 37', 'Symbol:'),
              mc('Which symbol means "is less than"?', ['<', '>', '=']),
              tf('89 < 98'),
          ]),
          B('Order as position on a number line', '6.NS.C.7.a', [
              tf('-2 > -6 because -2 is to the right of -6 on a number line.'),
              mc('Which number is greatest?', ['-1', '-4', '-9', '-7']),
              sa('-5 is to the left of 3 on a number line.\nWrite an inequality to show this.', 'Inequality:'),
              tf('-8 is to the right of -3 on a number line.'),
              mc('Which number is to the left of -4 on a number line?', ['-6', '-2', '0', '4']),
          ]),
      ],
      f1=B('Real-world problems with rational numbers', '7.NS.A.3', [
          sa('At 6 a.m., the temperature was -7°F. By noon, it was 12°F.\nHow many degrees did the temperature rise?', 'Degrees:'),
          sa('A submarine is at -250 feet. It rises 95 feet and then dives 130 feet.\nWhat is its final position?', 'Position:'),
          mc('An account balance is -$42. Then $65 is deposited.\nWhat is the new balance?', ['$23', '-$23', '$107', '-$107']),
          sa('A mountain peak has an elevation of 1,250 m. An ocean trench has an elevation of -3,400 m.\nWhat is the difference in elevation?', 'Difference:'),
          tf('A temperature change from -3°C to -11°C is a change of -8°C.'),
      ]),
      f2=B('Solve real-world problems with two linear equations', '8.EE.C.8.c', [
          sa('Plan A costs $20 plus $5 per month. Plan B costs $35 plus $2 per month.\nAfter how many months do the plans cost the same?', 'Months:'),
          mc('Tank A has 100 gallons and drains 6 gallons per minute. Tank B has 40 gallons and fills 4 gallons per minute.\nWhen will the tanks hold the same amount?',
             ['After 6 minutes', 'After 10 minutes', 'After 14 minutes', 'After 4 minutes']),
          sa('Sara has $50 and saves $8 per week. Tom has $90 and saves $3 per week.\nAfter how many weeks will they have the same amount?', 'Weeks:'),
          sa('The sum of two numbers is 24. Their difference is 6.\nWhat are the two numbers?', 'Numbers:'),
          mc('Adult tickets cost $8 and child tickets cost $5. A group buys 10 tickets for $65.\nHow many adult tickets did they buy?', ['5', '3', '7', '6']),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.7.c
    S('6.NS.C.7.c', 'Absolute value as distance from 0',
      main=[
          sa('Find the value.\n|-18|', 'Value:'),
          sa('An account balance is -$30.\nWhat is the absolute value of the balance, and what does it describe?', ['Absolute value:', 'It describes:']),
          mc('Which number has the greatest absolute value?', ['-12', '8', '-5', '10']),
          sa('A diver is at an elevation of -42 feet.\nHow far is the diver from sea level?', 'Distance:'),
          tf('|-6| = |6|'),
      ],
      back=[
          B('Distance on a number line', '2.MD.B.6', [
              sa('How many units apart are points A and B?', 'Units:', fig=nl(0, 12, 1, pts=[(3, 'A'), (9, 'B')])),
              tf('The distance from 0 to 5 is the same as the distance from 5 to 10.'),
              mc('How many units from 0 is the number 11?', ['11', '0', '1', '10']),
              sa('What is the distance from 4 to 10 on a number line?', 'Distance:'),
              sa('How many units is point C from 0?', 'Units:', fig=nl(0, 20, 2, pts=[(16, 'C')])),
          ]),
          B('Opposite numbers', '6.NS.C.6.a', [
              sa('What is the opposite of 15?', 'Opposite:'),
              tf('Opposite numbers are the same distance from 0.'),
              mc('Which number is the opposite of -{2/3}?', ['{2/3}', '-{3/2}', '{3/2}', '-{2/3}']),
              sa('What is the opposite of 0?', 'Opposite:'),
              tf('Points A and B represent opposite numbers.', fig=nl(-5, 5, 1, pts=[(-3, 'A'), (3, 'B')])),
          ]),
          B('Negative numbers in context', '6.NS.C.5', [
              tf('-30 can represent owing $30.'),
              sa('Write an integer for 42 feet below sea level.', 'Integer:'),
              mc('Which situation is represented by +25?', ['A deposit of $25', 'A debt of $25', '25 feet below sea level', 'A loss of 25 yards']),
              sa('Write an integer for a debt of $18.', 'Integer:'),
              tf('A temperature of 0°F means there is no temperature.'),
          ]),
      ],
      f1=B('Distance between rational numbers as |p - q|', '7.NS.A.1.c', [
          sa('Find the distance between -4 and 7 on a number line.', 'Distance:'),
          sa('Find the value.\n|-3.5 - 2|', 'Value:'),
          mc('Which expression gives the distance between -9 and -2?', ['|-9 - (-2)|', '-9 - 2', '|-9 + (-2)|', '-9 + 2']),
          tf('The distance between -6 and 6 is 0.'),
          sa('A bird is 25 feet above sea level. A fish is 12 feet below sea level.\nHow far apart are they?', 'Distance:'),
      ]),
      f2=B('Square roots and cube roots as solutions', '8.EE.A.2', [
          sa('Solve.\nx² = 49', 'x ='),
          sa('Solve.\nx³ = 64', 'x ='),
          mc('What are the solutions of x² = 81?', ['x = 9 or x = -9', 'x = 9 only', 'x = 40.5', 'x = -9 only']),
          sa('Solve. Write the answer using a square root symbol.\nx² = 20', 'x ='),
          tf('Both 6 and -6 are solutions of x² = 36.'),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.7.d
    S('6.NS.C.7.d', 'Distinguish comparisons of absolute value from statements about order',
      main=[
          tf('An account balance less than -30 dollars represents a debt greater than 30 dollars.'),
          mc('Which account balance shows the greatest debt?', ['-$55', '-$20', '-$38', '$10']),
          tf('-12 < -5, so |-12| < |-5|.'),
          sa('Two temperatures are -15°F and -9°F.\nWhich temperature is colder? Which has the greater absolute value?', ['Colder:', 'Greater absolute value:']),
          mc('A submarine is at -300 feet. A diver is at -45 feet.\nWhich statement is true?',
             ['The submarine is deeper because |-300| > |-45|.', 'The diver is deeper because -45 > -300.',
              'The submarine is deeper because -300 > -45.', 'They are at the same depth.']),
      ],
      back=[
          B('Absolute value', '6.NS.C.7.c', [
              sa('Find the value.\n|-25|', 'Value:'),
              sa('Find the value.\n|14|', 'Value:'),
              tf('|-3| = -3'),
              mc('Which number has an absolute value of 7?', ['-7', '{1/7}', '0', '-{1/7}']),
              sa('Find the value.\n|-2.5|', 'Value:'),
          ]),
          B('Ordering negative numbers', '6.NS.C.7.a', [
              mc('Which number is least?', ['-20', '-5', '0', '-12']),
              tf('-9 > -4'),
              sa('Order from least to greatest.\n-3, -8, 1', 'Order:'),
              tf('-1 > -100'),
              mc('Which number is greater?', ['-6', '-16']),
          ]),
          B('Negative numbers in context', '6.NS.C.5', [
              sa('Write an integer for a debt of $40.', 'Integer:'),
              mc('What could -8 represent?', ['8 feet below sea level', '8 feet above sea level', 'A gain of 8 yards', 'A deposit of $8']),
              tf('An account balance of -$10 means you owe $10.'),
              sa('Write an integer for 15 degrees below zero.', 'Integer:'),
              tf('A 20-foot descent can be written as +20.'),
          ]),
      ],
      f1=B('Real-world problems with rational numbers', '7.NS.A.3', [
          sa('A company lost $2.5 million in one year and earned a profit of $1.8 million the next year.\nWhat is the total for the two years?', 'Total:'),
          sa('The temperature was -6°F. It dropped 11°F.\nWhat is the new temperature?', 'Temperature:'),
          mc('A diver at -35.5 feet rises 12.25 feet.\nWhat is the diver\'s new position?', ['-23.25 feet', '-47.75 feet', '23.25 feet', '-22.75 feet']),
          sa('A hiker goes from an elevation of 1,200 feet to an elevation of -80 feet.\nWhat is the change in elevation?', 'Change:'),
          tf('If the temperature drops from -4°C to -9°C, it gets 5°C colder.'),
      ]),
      f2=B('Compare magnitudes with powers of 10', '8.EE.A.3', [
          sa('One company\'s debt is 2 × 10⁶ dollars. Another company\'s debt is 4 × 10⁴ dollars.\nHow many times as large is the first debt?', 'Times as large:'),
          mc('The deepest ocean point is about -1 × 10⁴ meters. A lake bottom is about -5 × 10¹ meters.\nAbout how many times as deep is the ocean point?', ['200', '20', '2,000', '5']),
          sa('Estimate 7,980,000 as a single digit times a power of 10.', 'Estimate:'),
          tf('6 × 10⁹ is 300 times as large as 2 × 10⁷.'),
          sa('Estimate 0.0000031 as a single digit times a power of 10.', 'Estimate:'),
      ])),

    # ------------------------------------------------------------------ 6.NS.C.8
    S('6.NS.C.8', 'Distances between points on the coordinate plane',
      main=[
          sa('Find the distance between (-3, 4) and (5, 4).', 'Distance:'),
          sa('Find the distance between (2, -6) and (2, 5).', 'Distance:'),
          sa('On the map, each unit is 1 block.\nHow many blocks is it from the library L to the park P?', 'Blocks:',
             fig=coord(pts=[(-4, -3, 'L', 'e'), (-4, 5, 'P', 'e')], y=(-6, 6))),
          mc('What is the distance between (-7, -2) and (-1, -2)?', ['6', '8', '-6', '3']),
          sa('A rectangle has vertices at (-2, 3), (4, 3), (4, -1), and (-2, -1).\nWhat is its perimeter?', 'Perimeter:'),
      ],
      back=[
          B('Absolute value', '6.NS.C.7.c', [
              sa('Find the value.\n|-7|', 'Value:'),
              tf('|-3| + |5| = 8'),
              mc('|-4| + |6| = ?', ['10', '2', '-10', '-2']),
              sa('Find the value.\n|-9| + |2|', 'Value:'),
              tf('The distance from -5 to 0 is |-5|.'),
          ]),
          B('Naming points on the coordinate plane', '6.NS.C.6.c', [
              sa('What are the coordinates of point A?', 'A =', fig=coord(pts=[(-3, 4, 'A')])),
              sa('What are the coordinates of point B?', 'B =', fig=coord(pts=[(5, -2, 'B')])),
              mc('Which point is at (-1, -4)?', LET, fig=coord(pts=[(-1, -4, 'A'), (-4, -1, 'B'), (1, 4, 'C'), (4, -1, 'D')])),
              tf('Point C is located at (3, 0).', fig=coord(pts=[(0, 3, 'C', 'e')])),
              sa('What are the coordinates of point D?', 'D =', fig=coord(pts=[(-5, -5, 'D')])),
          ]),
          B('Distance between whole numbers', '2.MD.B.6', [
              sa('What is the distance from 3 to 11 on a number line?', 'Distance:'),
              sa('How many units apart are points A and B?', 'Units:', fig=nl(0, 10, 1, pts=[(2, 'A'), (7, 'B')])),
              tf('The distance from 12 to 4 is 8 units.'),
              mc('What is the distance from 5 to 14?', ['9', '19', '8', '10']),
              sa('What is the distance from 0 to 13 on a number line?', 'Distance:'),
          ]),
          B('Perimeter of rectangles', '3.MD.D.8', [
              sa('What is the perimeter of the rectangle?', 'Perimeter:', fig=rect(6, 4, '6 units', '4 units')),
              sa('A rectangle is 9 cm long and 3 cm wide.\nWhat is its perimeter?', 'Perimeter:'),
              tf('A square with 5-meter sides has a perimeter of 25 meters.'),
              mc('A rectangle is 8 inches long and 2 inches wide.\nWhat is its perimeter?', ['20 inches', '16 inches', '10 inches', '18 inches']),
              sa('A rectangle has a perimeter of 18 feet and a length of 5 feet.\nWhat is its width?', 'Width:'),
          ]),
      ],
      f1=B('Distance between rational numbers', '7.NS.A.1.c', [
          sa('Find the distance between -2.5 and 4.5 on a number line.', 'Distance:'),
          sa('Find the value.\n|-8.4 - 3.6|', 'Value:'),
          mc('What is the distance between -3{1/2} and 2{1/4} on a number line?', ['5{3/4}', '1{1/4}', '-5{3/4}', '6{1/4}']),
          tf('The distance between -7 and -2 is |-7 - (-2)|, which is 5.'),
          sa('Find the distance between -4 and 2.5 on a number line.', 'Distance:'),
      ]),
      f2=B('Distance between points using the Pythagorean Theorem', '8.G.B.8', [
          sa('Find the distance between (1, 2) and (4, 6).', 'Distance:'),
          sa('Find the distance between points A and B.', 'Distance:', fig=coord(x=(-3, 5), y=(-2, 8), pts=[(-2, -1, 'A'), (4, 7, 'B')])),
          mc('What is the distance between (0, 0) and (5, 12)?', ['13', '17', '7', '√119']),
          sa('Find the distance between (-3, 5) and (1, 2).', 'Distance:'),
          tf('The distance between (2, 1) and (5, 5) is 5.'),
      ])),
]
