from qb import S, B, sa, mc, tf, nl, coord, q1, table, tape, hist

FRUIT = hist(['Apple', 'Banana', 'Grape', 'Orange'], [6, 4, 8, 2], gap=0.35, ymax=10, ystep=2,
             xlabel='Favorite fruit', ylabel='Students', h=200)
PETS = table([['Pet', 'Dogs', 'Cats', 'Fish'], ['Students', '8', '6', '3']], header='both')


def bar(n, shade=0, **kw):
    d = dict(n=n, shade=shade)
    d.update(kw)
    return tape(d)


SETS = [
    # ------------------------------------------------------------------ 6.RP.A.1
    S('6.RP.A.1', 'Understand ratios and use ratio language',
      main=[
          sa('A class has 12 girls and 15 boys.\nWrite the ratio of girls to boys.', 'Ratio:'),
          sa('The table shows the pets owned by students in a class.\nWrite the ratio of cats to fish.', 'Ratio:', fig=PETS),
          mc('A recipe uses 3 cups of flour for every 2 cups of sugar.\nWhich statement describes the same ratio?',
             ['For every 2 cups of flour, there are 3 cups of sugar.', 'The ratio of sugar to flour is 2 : 3.',
              'The ratio of flour to sugar is 2 : 3.', 'For every 5 cups of sugar, there are 3 cups of flour.']),
          mc('At a zoo, the ratio of penguins to seals is 5 : 2.\nWhich statement is true?',
             ['For every 5 seals, there are 2 penguins.', 'For every 2 seals, there are 5 penguins.',
              'For every 7 penguins, there are 2 seals.', 'There are 3 more seals than penguins.']),
          sa('A soccer team won 9 games and lost 4 games. There were no ties.\nWrite the ratio of games lost to games played.', 'Ratio:'),
      ],
      back=[
          B('Multiplicative comparison', '4.OA.A.1', [
              tf('24 is 3 times as many as 8.'),
              sa('Maya has 5 stickers. Leo has 4 times as many stickers as Maya.\nHow many stickers does Leo have?', 'Stickers:'),
              mc('Which equation shows "35 is 5 times as many as 7"?', ['35 = 5 × 7', '35 = 5 + 7', '7 = 5 × 35', '35 - 7 = 5']),
              tf('18 is 6 times as many as 3.'),
              sa('A tree is 6 feet tall. A building is 9 times as tall as the tree.\nHow tall is the building?', 'Height:'),
          ]),
          B('Fraction as part of a whole', '3.NF.A.1', [
              sa('The bar is divided into equal parts.\nWhat fraction of the bar is shaded?', 'Fraction:', fig=bar(8, 3)),
              sa('A pizza is cut into 8 equal slices. Sam eats 3 slices.\nWhat fraction of the pizza does Sam eat?', 'Fraction:'),
              tf('A bar is cut into 5 equal parts and 2 parts are shaded. The shaded part is {2/5} of the bar.'),
              mc('What fraction of the bar is shaded?', ['{1/6}', '{1/5}', '{6/1}', '{5/6}'], fig=bar(6, 1)),
              sa('A garden has 4 equal sections. Tomatoes grow in 3 of the sections.\nWhat fraction of the garden has tomatoes?', 'Fraction:'),
          ]),
          B('Reading counts from a table or graph', '3.MD.B.3', [
              sa('The graph shows the favorite fruits of a class.\nHow many students chose grape?', 'Students:', fig=FRUIT),
              sa('The graph shows the favorite fruits of a class.\nHow many more students chose apple than banana?', 'Students:', fig=FRUIT),
              sa('The table shows the pets owned by students.\nHow many students own fish?', 'Students:', fig=PETS),
              mc('Which fruit was chosen by 4 students?', ['Apple', 'Banana', 'Grape', 'Orange'], fig=FRUIT),
              sa('The graph shows the favorite fruits of a class.\nHow many students chose orange?', 'Students:', fig=FRUIT),
          ]),
      ],
      f1=B('Decide whether quantities are proportional', '7.RP.A.2.a', [
          tf('The table shows a proportional relationship between hours worked and pay.',
             fig=table([['Hours', '1', '2', '3', '4'], ['Pay ($)', '12', '24', '36', '48']])),
          tf('The table shows a proportional relationship between tickets and cost.',
             fig=table([['Tickets', '2', '4', '6'], ['Cost ($)', '10', '18', '26']])),
          mc('Does the graph show a proportional relationship?',
             ['Yes, because it is a straight line through (0, 0).', 'No, because it does not pass through (0, 0).',
              'No, because the points are not on a line.', 'Yes, because y increases.'],
             fig=q1(5, 12, ystep=2, square=False, pts=[(1, 3), (2, 6), (3, 9), (4, 12)], lines=[((0, 0), (4, 12))])),
          mc('Which statement about the graph is true?',
             ['It is proportional because it is a straight line.', 'It is not proportional because it does not pass through (0, 0).',
              'It is proportional because y increases by 2.', 'It is not proportional because the points are not on a line.'],
             fig=q1(5, 10, ystep=2, square=False, pts=[(0, 2), (1, 4), (2, 6), (3, 8)], lines=[((0, 2), (4, 10))])),
          mc('Which set of ordered pairs shows a proportional relationship?',
             ['(1, 4), (2, 8), (3, 12)', '(1, 5), (2, 7), (3, 9)', '(2, 3), (4, 5), (6, 7)', '(1, 2), (3, 5), (5, 8)']),
      ]),
      f2=B('Graph proportional relationships; slope as unit rate', '8.EE.B.5', [
          sa('The graph shows the distance a car travels over time.\nWhat is the slope of the line in miles per hour?', 'Slope:',
             fig=q1(5, 300, ystep=50, square=False, xlabel='Hours', ylabel='Miles', pts=[(1, 60), (2, 120), (3, 180), (4, 240)],
                    lines=[((0, 0), (5, 300))])),
          mc('Cyclist A\'s distance is shown in the graph. Cyclist B rides according to d = 7.5t, where d is miles and t is hours.\nWhich cyclist is faster?',
             ['Cyclist A', 'Cyclist B', 'They ride at the same speed.'],
             fig=q1(4, 32, ystep=4, square=False, xlabel='Hours', ylabel='Miles', pts=[(2, 16), (4, 32)], lines=[((0, 0), (4, 32))])),
          sa('Tank A fills according to y = 12x, where x is minutes and y is gallons. The graph of Tank B is a line through (0, 0) and (3, 45).\nWhich tank fills faster, and by how many gallons per minute?', 'Answer:'),
          sa('The graph of a proportional relationship passes through (0, 0) and (6, 9).\nWhat is the slope of the line?', 'Slope:'),
          mc('Store A: 2 pounds of apples cost $3.50 and 4 pounds cost $7.00.\nStore B: the cost is c = 1.6p for p pounds.\nWhich store charges less per pound?', ['Store A', 'Store B', 'Both charge the same.']),
      ])),

    # ------------------------------------------------------------------ 6.RP.A.2
    S('6.RP.A.2', 'Understand unit rate in the context of a ratio',
      main=[
          sa('A car travels 150 miles in 3 hours at a constant speed.\nWhat is the unit rate in miles per hour?', 'Unit rate:'),
          sa('A 4-pound bag of rice costs $12.\nWhat is the price per pound?', 'Price per pound:'),
          sa('A recipe uses 3 cups of flour for every 4 cups of sugar.\nHow many cups of flour are used for each cup of sugar?', 'Cups of flour:'),
          mc('There are 2 teachers for every 30 students on a field trip.\nWhich statement uses the unit rate correctly?',
             ['There are 15 students per teacher.', 'There are 28 students per teacher.',
              'There are 30 students per teacher.', 'There are 60 students per teacher.']),
          sa('A printer prints 90 pages in 6 minutes.\nHow many pages does it print per minute?', 'Pages per minute:'),
      ],
      back=[
          B('Whole-number division', '4.NBT.B.6', [
              sa('Find the quotient.\n150 ÷ 3'),
              mc('Which is equal to 96 ÷ 4?', ['24', '22', '26', '23']),
              tf('84 ÷ 6 = 14'),
              sa('Find the quotient.\n212 ÷ 4'),
              sa('Find the quotient.\n135 ÷ 5'),
          ]),
          B('Fraction as division', '5.NF.B.3', [
              sa('Write 3 ÷ 4 as a fraction.', 'Fraction:'),
              tf('{2/5} means the same as 2 ÷ 5.'),
              sa('Four friends share 3 sandwiches equally.\nHow much sandwich does each friend get?', 'Each friend gets:'),
              mc('Which division expression is equal to {7/8}?', ['7 ÷ 8', '8 ÷ 7', '7 × 8', '8 - 7']),
              sa('A 5-yard ribbon is cut into 6 equal pieces.\nHow long is each piece?', 'Length:'),
          ]),
          B('Meaning of "per" (amount in each group)', '3.OA.A.2', [
              sa('12 apples are packed equally into 4 bags.\nHow many apples are in each bag?', 'Apples:'),
              tf('"5 miles per hour" means 5 miles for each 1 hour.'),
              mc('Which phrase means the same as "$2 per pound"?',
                 ['$2 for each pound', '$2 for all of the pounds', '2 pounds for each dollar', '$2 more than a pound']),
              sa('24 eggs are put into cartons, with 6 eggs per carton.\nHow many cartons are filled?', 'Cartons:'),
              sa('Jen reads 40 pages in 5 days. She reads the same number of pages each day.\nHow many pages does she read per day?', 'Pages:'),
          ]),
      ],
      f1=B('Unit rates with fractions', '7.RP.A.1', [
          sa('Kim walks {1/2} mile in {1/4} hour.\nWhat is her speed in miles per hour?', 'Speed:'),
          sa('A painter paints {2/3} of a wall in {1/3} hour.\nAt this rate, how many walls can the painter paint per hour?', 'Walls per hour:'),
          sa('A snail crawls {5/6} foot in {1/3} minute.\nHow many feet does it crawl per minute?', 'Feet per minute:'),
          mc('A machine fills {3/4} of a tank in {1/2} hour.\nHow many tanks does it fill per hour?', ['1{1/2}', '{3/8}', '{1/4}', '1{1/4}']),
          sa('Leo mows {7/8} of an acre in {1/2} hour.\nHow many acres does he mow per hour?', 'Acres per hour:'),
      ]),
      f2=B('Rate of change and initial value', '8.F.B.4', [
          sa('The table shows a linear function.\nWhat is the rate of change?', 'Rate of change:',
             fig=table([['x', '0', '1', '2', '3'], ['y', '5', '8', '11', '14']])),
          sa('A plumber charges a $40 fee plus $65 per hour.\nWrite a function for the cost C after h hours.', 'C ='),
          sa('A line passes through (2, 7) and (6, 19).\nWhat is the rate of change?', 'Rate of change:'),
          sa('A tank is draining at a constant rate.\nWhat is the rate of change in gallons per minute?', 'Rate of change:',
             fig=table([['Minutes', '0', '5', '10'], ['Gallons', '200', '170', '140']])),
          mc('A taxi ride costs $3 plus $2.50 per mile.\nWhich function gives the cost y for a ride of x miles?',
             ['y = 2.5x + 3', 'y = 3x + 2.5', 'y = 5.5x', 'y = 2.5x - 3']),
      ])),

    # ------------------------------------------------------------------ 6.RP.A.3.a
    S('6.RP.A.3.a', 'Tables of equivalent ratios; plot pairs on the coordinate plane',
      main=[
          sa('The table shows equivalent ratios.\nFind the missing value.', 'Missing value:',
             fig=table([['Cups of juice', '2', '4', '6', '10'], ['Cups of water', '3', '6', '9', '?']])),
          sa('Paint is mixed in the same ratio in every column.\nFind the missing value.', 'Missing value:',
             fig=table([['Blue (cups)', '3', '6', '?', '15'], ['Yellow (cups)', '2', '4', '8', '10']])),
          mc('The points show pairs from a ratio table.\nWhich point also belongs to this ratio table?', ['(4, 12)', '(4, 10)', '(5, 12)', '(12, 4)'],
             fig=q1(6, 15, ystep=3, square=False, pts=[(1, 3), (2, 6), (3, 9)])),
          mc('Class A has 4 boys for every 6 girls.\nClass B has 6 boys for every 9 girls.\nWhich statement is true?',
             ['The ratios are equivalent.', 'Class A has a greater ratio of boys to girls.',
              'Class B has a greater ratio of boys to girls.', 'The ratios cannot be compared.']),
          sa('A recipe uses 5 cups of oats for every 2 cups of raisins.\nFind the missing values A and B.', ['A =', 'B ='],
             fig=table([['Oats (cups)', '5', '10', 'A', '25'], ['Raisins (cups)', '2', 'B', '6', '10']])),
      ],
      back=[
          B('Equivalent fractions', '4.NF.A.1', [
              tf('{2/3} is equivalent to {8/12}.'),
              sa('Find the missing number.\n{3/4} = {?/20}', 'Missing number:'),
              mc('Which fraction is equivalent to {5/6}?', ['{10/12}', '{10/11}', '{6/7}', '{5/12}']),
              tf('{4/5} is equivalent to {6/7}.'),
              sa('Find the missing number.\n{2/5} = {6/?}', 'Missing number:'),
          ]),
          B('Two related number patterns', '5.OA.B.3', [
              sa('Pattern A starts at 0 and adds 3.\nPattern B starts at 0 and adds 6.\nWhat is the 5th number in Pattern B?', 'Number:'),
              tf('Each number in Pattern B is 2 times the matching number in Pattern A.',
                 fig=table([['Pattern A (add 4)', '0', '4', '8', '12'], ['Pattern B (add 8)', '0', '8', '16', '24']])),
              sa('Pattern A starts at 0 and adds 5.\nPattern B starts at 0 and adds 10.\nWhat is the 4th number in Pattern A?', 'Number:'),
              mc('Pattern A: 0, 2, 4, 6, 8\nPattern B: 0, 6, 12, 18, 24\nHow does each number in Pattern B compare to the matching number in Pattern A?',
                 ['3 times as large', '4 more', '6 times as large', '2 times as large']),
              sa('Pattern A: 0, 1, 2, 3, ...\nPattern B: 0, 4, 8, 12, ...\nWrite the ordered pair formed by the 4th numbers of the patterns.', 'Ordered pair:'),
          ]),
          B('Plotting points in the first quadrant', '5.G.A.2', [
              mc('Which point is located at (3, 5)?', ['Point A', 'Point B', 'Point C', 'Point D'],
                 fig=q1(7, 7, pts=[(3, 5, 'A'), (5, 3, 'B'), (3, 2, 'C'), (1, 5, 'D')])),
              sa('What are the coordinates of point P?', 'P =', fig=q1(8, 8, pts=[(6, 2, 'P')])),
              tf('To plot (4, 1), start at (0, 0), move 4 units right, then move 1 unit up.'),
              mc('Which ordered pair names point M?', ['(2, 7)', '(7, 2)', '(2, 2)', '(7, 7)'], fig=q1(8, 8, pts=[(2, 7, 'M')])),
              sa('What are the coordinates of point K?', 'K =', fig=q1(8, 8, pts=[(0, 4, 'K', 'e')])),
          ]),
      ],
      f1=B('Constant of proportionality', '7.RP.A.2.b', [
          sa('The table shows a proportional relationship.\nWhat is the constant of proportionality ({y/x})?', 'k =',
             fig=table([['x', '2', '5', '8'], ['y', '7', '17.5', '28']])),
          sa('The graph shows a proportional relationship.\nWhat is the constant of proportionality?', 'k =',
             fig=q1(6, 15, ystep=3, square=False, pts=[(2, 5), (4, 10)], lines=[((0, 0), (6, 15))])),
          sa('The table shows the cost of cheese.\nWhat is the constant of proportionality in dollars per pound?', 'k =',
             fig=table([['Pounds', '3', '6', '9'], ['Cost ($)', '7.50', '15.00', '22.50']])),
          mc('The graph of a proportional relationship passes through (0, 0) and (5, 2).\nWhat is the constant of proportionality?',
             ['{2/5}', '{5/2}', '2', '5']),
          sa('A faucet fills 15 liters every 6 minutes at a constant rate.\nWhat is the constant of proportionality in liters per minute?', 'k ='),
      ]),
      f2=B('Linear and nonlinear functions', '8.F.A.3', [
          tf('The table represents a linear function.', fig=table([['x', '0', '1', '2', '3'], ['y', '1', '4', '7', '10']])),
          mc('Which equation does NOT represent a linear function?', ['y = 3x + 2', 'y = x²', 'y = {1/2}x', 'y = -4x - 1']),
          tf('The table represents a linear function.', fig=table([['x', '1', '2', '3', '4'], ['y', '1', '4', '9', '16']])),
          mc('Which set of ordered pairs lies on a linear function?',
             ['(0, 2), (1, 4), (2, 8), (3, 16)', '(0, 5), (1, 8), (2, 11), (3, 14)',
              '(0, 0), (1, 1), (2, 4), (3, 9)', '(1, 1), (2, 3), (3, 6), (4, 10)']),
          sa('The area of a square is A = s², where s is the side length.\nIs A a linear function of s? Write yes or no.', 'Answer:'),
      ])),

    # ------------------------------------------------------------------ 6.RP.A.3.b
    S('6.RP.A.3.b', 'Unit rate problems: unit pricing and constant speed',
      main=[
          sa('4 notebooks cost $10.\nAt this rate, how much do 7 notebooks cost?', 'Cost:'),
          sa('It took 7 hours to mow 4 lawns.\nAt that rate, how many lawns could be mowed in 35 hours?', 'Lawns:'),
          mc('Which is the better buy?', ['6 bottles of water for $4.50', '10 bottles of water for $7.00', 'Both cost the same per bottle.']),
          sa('A runner runs 12 kilometers in 60 minutes at a constant speed.\nHow far does the runner go in 25 minutes?', 'Distance:'),
          sa('A machine makes 45 bottles every 3 minutes.\nAt that rate, how many minutes does it take to make 300 bottles?', 'Minutes:'),
      ],
      back=[
          B('Dividing money amounts', '5.NBT.B.7', [
              sa('Find the quotient.\n$4.50 ÷ 6'),
              sa('Find the quotient.\n$10.00 ÷ 4'),
              mc('$7.00 ÷ 10 = ?', ['$0.70', '$7.00', '$0.07', '$70.00']),
              sa('Find the quotient.\n$3.60 ÷ 3'),
              tf('$8.40 ÷ 4 = $2.10'),
          ]),
          B('Multiplying by an amount for each one', '4.NBT.B.5', [
              sa('Each ticket costs $15.\nHow much do 7 tickets cost?', 'Cost:'),
              sa('A bus holds 48 people.\nHow many people can 6 buses hold?', 'People:'),
              mc('Which expression gives the cost of 9 books that cost $12 each?', ['9 × 12', '12 + 9', '12 - 9', '12 ÷ 9']),
              sa('Each box holds 125 pencils.\nHow many pencils are in 4 boxes?', 'Pencils:'),
              tf('A cat sleeps 14 hours each day. In 5 days it sleeps 70 hours.'),
          ]),
          B('Comparing decimals', '5.NBT.A.3.b', [
              mc('Which amount is less?', ['$0.75', '$0.70']),
              tf('0.8 > 0.75'),
              sa('Write >, <, or = to compare.\n2.35 ___ 2.4', 'Symbol:'),
              mc('Which number is greatest?', ['0.6', '0.59', '0.506', '0.065']),
              tf('1.25 < 1.205'),
          ]),
          B('Hours and minutes', '4.MD.A.1', [
              sa('How many minutes are in 3 hours?', 'Minutes:'),
              tf('There are 60 seconds in 1 hour.'),
              sa('Complete.\n4 hours = ___ minutes', 'Minutes:'),
              mc('Which is longer?', ['90 minutes', '2 hours', 'They are the same.']),
              sa('How many minutes are in {1/2} hour?', 'Minutes:'),
          ]),
      ],
      f1=B('Equations for proportional relationships', '7.RP.A.2.c', [
          sa('Apples cost $2.50 per pound.\nWrite an equation for the cost c of p pounds of apples.', 'Equation:'),
          mc('A car travels at 55 miles per hour.\nWhich equation relates the distance d and the time t?', ['d = 55t', 't = 55d', 'd = t + 55', 'd = {t/55}']),
          sa('The table shows a proportional relationship.\nWrite an equation for earnings e after h hours.', 'Equation:',
             fig=table([['Hours (h)', '2', '3', '5'], ['Earnings (e)', '36', '54', '90']])),
          sa('A printer prints 12 pages per minute.\nWrite an equation relating the pages p and the minutes m.', 'Equation:'),
          tf('5 pounds of rice cost $8. The equation c = 1.6p gives the cost c of p pounds of rice.'),
      ]),
      f2=B('Compare functions represented in different ways', '8.F.A.2', [
          mc('Plan A costs y = 12x dollars for x months. Plan B is shown in the table.\nWhich plan has the greater rate of change?',
             ['Plan A', 'Plan B', 'They have the same rate of change.'],
             fig=table([['Months (x)', '2', '4', '6'], ['Cost (y)', '26', '52', '78']])),
          mc('Function A is y = 3x + 4. Function B is shown in the graph.\nWhich function has the greater rate of change?',
             ['Function A', 'Function B', 'They have the same rate of change.'],
             fig=q1(4, 12, ystep=2, square=False, pts=[(0, 1), (2, 9)], lines=[((0, 1), (2.75, 12))])),
          sa('Car A travels 150 miles in 3 hours. Car B travels according to d = 48t.\nHow much faster is Car A, in miles per hour?', 'Miles per hour:'),
          mc('Function A is shown in the table. Function B is y = -3x + 2.\nWhich function has the greater y-intercept?',
             ['Function A', 'Function B', 'They have the same y-intercept.'],
             fig=table([['x', '0', '1', '2'], ['y', '5', '3', '1']])),
          sa('Store A: 3 pounds of grapes cost $7.50.\nStore B: c = 2.4p, where p is pounds.\nWhich store has the lower price per pound, and by how much?', 'Answer:'),
      ])),

    # ------------------------------------------------------------------ 6.RP.A.3.c (percent of a quantity)
    S('6.RP.A.3.c', 'Percent of a quantity as a rate per 100',
      main=[
          sa('What is 30% of 80?', 'Answer:'),
          sa('A jacket costs $60. The sales tax is 8%.\nHow much is the tax?', 'Tax:'),
          sa('A class has 25 students. 40% of the students walk to school.\nHow many students walk to school?', 'Students:'),
          mc('What percent of the grid is shaded?', ['45%', '55%', '4.5%', '0.45%'], fig=dict(k='grid', shade=45)),
          sa('A school has 450 students. 12% of them play in the band.\nHow many students play in the band?', 'Students:'),
      ],
      back=[
          B('Hundredths as decimals', '4.NF.C.6', [
              sa('Write {45/100} as a decimal.', 'Decimal:'),
              tf('0.07 = {7/100}'),
              mc('Which decimal is equal to {30/100}?', ['0.30', '3.0', '0.03', '30.0']),
              sa('Write 0.62 as a fraction with a denominator of 100.', 'Fraction:'),
              tf('{8/100} = 0.8'),
          ]),
          B('Tenths as hundredths', '4.NF.C.5', [
              sa('Find the missing number.\n{3/10} = {?/100}', 'Missing number:'),
              tf('{4/10} + {5/100} = {45/100}'),
              mc('Which fraction is equal to {7/10}?', ['{70/100}', '{7/100}', '{17/100}', '{10/70}']),
              sa('Add.\n{6/10} + {25/100}', 'Sum:'),
              tf('{9/10} = {90/100}'),
          ]),
          B('Fraction of a whole number', '5.NF.B.4.a', [
              sa('Multiply.\n{3/10} × 80', 'Product:'),
              sa('Find {1/4} of 60.', 'Answer:'),
              tf('{2/5} × 25 = 10'),
              mc('{3/4} × 20 = ?', ['15', '12', '16', '5']),
              sa('Find {7/10} of 50.', 'Answer:'),
          ]),
          B('Multiplying a decimal by a whole number', '5.NBT.B.7', [
              sa('Multiply.\n0.3 × 80', 'Product:'),
              sa('Multiply.\n0.08 × 60', 'Product:'),
              tf('0.12 × 450 = 54'),
              mc('0.4 × 25 = ?', ['10', '1', '100', '0.1']),
              sa('Multiply.\n0.25 × 36', 'Product:'),
          ]),
      ],
      f1=B('Multi-step percent problems', '7.RP.A.3', [
          sa('A meal costs $40. You leave a 15% tip.\nWhat is the total cost of the meal with the tip?', 'Total:'),
          sa('A pair of shoes costs $80. They are on sale for 25% off.\nWhat is the sale price?', 'Sale price:'),
          sa('A town\'s population grew from 2,000 to 2,300.\nWhat is the percent increase?', 'Percent increase:'),
          mc('A $50 game is marked up 20%. Then a 5% sales tax is added to the new price.\nWhat is the final cost?',
             ['$63.00', '$62.50', '$60.00', '$62.00']),
          sa('A salesperson earns a 6% commission on sales. She sells $3,500 in products.\nHow much commission does she earn?', 'Commission:'),
      ]),
      f2=B('Build a linear function from a description', '8.F.B.4', [
          sa('A salesperson earns $300 per week plus 5% of her sales s.\nWrite a function for her weekly earnings E.', 'E ='),
          mc('A gym charges a $25 sign-up fee plus $30 per month.\nWhich function gives the total cost C after m months?',
             ['C = 30m + 25', 'C = 25m + 30', 'C = 55m', 'C = 30m - 25']),
          sa('A savings account starts with $150. Each week, $12 is added.\nWhat are the initial value and the rate of change?', ['Initial value:', 'Rate of change:']),
          sa('A candle is 20 cm tall. It burns 1.5 cm per hour.\nWrite a function for its height h after t hours.', 'h ='),
          sa('An agent earns $500 per month plus 3% of her sales r.\nWrite a function for her monthly earnings E.', 'E ='),
      ])),

    # ------------------------------------------------------------------ 6.RP.A.3.c (find the whole)
    S('6.RP.A.3.c', 'Find the whole, given a part and the percent',
      main=[
          sa('12 is 25% of what number?', 'Answer:'),
          sa('A student answered 18 questions correctly. This was 90% of the questions on the test.\nHow many questions were on the test?', 'Questions:'),
          sa('Maria has saved $45. This is 30% of the cost of a bike.\nHow much does the bike cost?', 'Cost:'),
          mc('The tape diagram shows that 20% of a number is 14.\nWhat is the number?', ['70', '28', '34', '280'],
             fig=tape(dict(n=5, shade=1, seg=['14', '', '', '', ''], brace='100% = ?'))),
          sa('In a survey, 36 students chose pizza. This was 40% of the students surveyed.\nHow many students were surveyed?', 'Students:'),
      ],
      back=[
          B('Benchmark percents as fractions', '4.NF.A.1', [
              sa('Find the missing number.\n{25/100} = {1/?}', 'Missing number:'),
              sa('Find the missing number.\n{50/100} = {?/2}', 'Missing number:'),
              tf('{20/100} = {1/5}'),
              mc('Which fraction is equivalent to {75/100}?', ['{3/4}', '{7/10}', '{1/75}', '{4/3}']),
              sa('Find the missing number.\n{10/100} = {1/?}', 'Missing number:'),
          ]),
          B('Finding an unknown factor', '3.OA.A.4', [
              sa('What number goes in the box?\n□ × 4 = 36', '□ ='),
              sa('What number goes in the box?\n5 × □ = 45', '□ ='),
              tf('If 6 × □ = 42, then □ = 7.'),
              mc('□ × 8 = 56\nWhat number goes in the box?', ['7', '6', '8', '48']),
              sa('What number goes in the box?\n9 × □ = 63', '□ ='),
          ]),
          B('Dividing a whole number by a unit fraction', '5.NF.B.7.b', [
              sa('Divide.\n12 ÷ {1/4}', 'Quotient:'),
              sa('Divide.\n5 ÷ {1/3}', 'Quotient:'),
              tf('6 ÷ {1/2} = 3'),
              mc('How many fifths are in 4?', ['20', '9', '{4/5}', '5']),
              sa('Divide.\n8 ÷ {1/5}', 'Quotient:'),
          ]),
      ],
      f1=B('Percent problems: find the original amount', '7.RP.A.3', [
          sa('After a 20% discount, a jacket costs $48.\nWhat was the original price?', 'Original price:'),
          sa('A price increased by 10%. The new price is $55.\nWhat was the original price?', 'Original price:'),
          sa('The sales tax on an item was $3.60. The tax rate is 6%.\nWhat was the price before tax?', 'Price:'),
          mc('A town\'s population grew by 25% to 1,500 people.\nWhat was the population before the increase?',
             ['1,200', '1,125', '1,875', '1,475']),
          sa('A store marks up the price of a bike by 40%. The selling price is $210.\nHow much did the store pay for the bike?', 'Cost:'),
      ]),
      f2=B('Linear equations with decimal coefficients', '8.EE.C.7.b', [
          sa('Solve for x.\nx - 0.2x = 48', 'x ='),
          sa('Solve for x.\n0.4x + 12 = 0.1x + 30', 'x ='),
          sa('Solve for x.\n0.25(x + 40) = 30', 'x ='),
          mc('Which value of n solves the equation?\nn + 0.15n = 92', ['80', '78.2', '105.8', '92.15']),
          sa('Solve for y.\n2.5y - 7 = 1.5y + 3', 'y ='),
      ])),

    # ------------------------------------------------------------------ 6.RP.A.3.d
    S('6.RP.A.3.d', 'Convert measurement units using ratio reasoning',
      main=[
          sa('There are 3 feet in 1 yard.\nHow many feet are in 14 yards?', 'Feet:'),
          sa('There are 12 inches in 1 foot.\nHow many inches are in 4.5 feet?', 'Inches:'),
          sa('There are 16 ounces in 1 pound.\nHow many pounds are in 56 ounces?', 'Pounds:'),
          mc('A recipe needs 3 quarts of milk. There are 4 cups in 1 quart.\nHow many cups of milk are needed?',
             ['12 cups', '7 cups', '{3/4} cup', '1{1/3} cups']),
          sa('1 inch = 2.54 centimeters.\nA book is 10 inches tall. How many centimeters tall is it?', 'Centimeters:'),
      ],
      back=[
          B('Measurement equivalents', '4.MD.A.1', [
              sa('How many ounces are in 1 pound?', 'Ounces:'),
              tf('There are 12 inches in 1 yard.'),
              mc('How many cups are in 1 quart?', ['4', '2', '8', '16']),
              sa('How many grams are in 1 kilogram?', 'Grams:'),
              tf('1 meter = 100 centimeters'),
          ]),
          B('Multiplying and dividing by powers of 10', '5.NBT.A.2', [
              sa('Multiply.\n3.4 × 1,000', 'Product:'),
              sa('Multiply.\n2.5 × 100', 'Product:'),
              tf('0.6 × 1,000 = 60'),
              mc('450 ÷ 100 = ?', ['4.5', '45', '0.45', '45,000']),
              sa('Multiply.\n7.25 × 10', 'Product:'),
          ]),
          B('Multiplying a decimal by a whole number', '5.NBT.B.7', [
              sa('Multiply.\n4.5 × 12', 'Product:'),
              sa('Multiply.\n3.5 × 16', 'Product:'),
              tf('1.5 × 4 = 6'),
              mc('2.25 × 4 = ?', ['9', '8.1', '90', '0.9']),
              sa('Multiply.\n6 × 0.75', 'Product:'),
          ]),
      ],
      f1=B('Scale drawings', '7.G.A.1', [
          sa('A map scale is 1 inch : 20 miles. Two towns are 3.5 inches apart on the map.\nWhat is the actual distance between the towns?', 'Distance:'),
          sa('A floor plan uses the scale 1 cm : 2 m. A room is 4.5 cm long on the plan.\nHow long is the actual room?', 'Length:'),
          mc('A drawing of a car uses the scale 1 inch : 4 feet. The real car is 14 feet long.\nHow long is the car in the drawing?',
             ['3.5 inches', '56 inches', '10 inches', '18 inches']),
          sa('A garden is 3 cm by 5 cm in a scale drawing. The scale is 1 cm : 2 m.\nWhat is the actual area of the garden?', 'Area:'),
          sa('On a map, 2 cm represents 15 km.\nWhat actual distance does 7 cm represent?', 'Distance:'),
      ]),
      f2=B('Dilations on the coordinate plane', '8.G.A.3', [
          sa('Point A(2, 3) is dilated by a scale factor of 4 with the center of dilation at the origin.\nWhat are the coordinates of A′?', 'A′ ='),
          mc('Triangle PQR has vertices P(4, 2), Q(6, 8), and R(2, 6). It is dilated by a scale factor of {1/2} with the center at the origin.\nWhat are the coordinates of Q′?',
             ['(3, 4)', '(12, 16)', '(5, 7)', '(6, 4)']),
          sa('A rectangle is dilated with the center at the origin. The vertex (3, 2) maps to (7.5, 5).\nWhat is the scale factor?', 'Scale factor:'),
          sa('The triangle is dilated by a scale factor of 2 with the center at the origin.\nWhat are the coordinates of C′?', 'C′ =',
             fig=q1(7, 7, pts=[(1, 1, 'A', 'sw'), (3, 1, 'B', 'se'), (1, 3, 'C', 'nw')], polys=[[(1, 1), (3, 1), (1, 3)]])),
          tf('A dilation with a scale factor of 3 and the center at the origin maps (-2, 5) to (-6, 15).'),
      ])),
]
