"""Distinct Grade 3 requirements and the set whose MAIN section focuses on each (for COVERAGE.md)."""
REQUIREMENTS = [
    ('3.OA.A.1', 'Interpret a product as the total number of objects in equal groups', [1]),
    ('3.OA.A.1', 'Write a multiplication equation for equal groups and arrays', [2]),
    ('3.OA.A.2', 'Interpret a quotient as the number of objects in each share', [3]),
    ('3.OA.A.2', 'Interpret a quotient as the number of equal shares', [4]),
    ('3.OA.A.3', 'Solve multiplication word problems within 100', [5]),
    ('3.OA.A.3', 'Solve division word problems within 100', [6]),
    ('3.OA.A.3', 'Represent a multiplication or division word problem with a drawing and an equation', [7]),
    ('3.OA.A.4', 'Find the unknown whole number in a multiplication equation', [8]),
    ('3.OA.A.4', 'Find the unknown whole number in a division equation', [9]),
    ('3.OA.B.5', 'Use the commutative property of multiplication', [10]),
    ('3.OA.B.5', 'Use the associative property of multiplication', [11]),
    ('3.OA.B.5', 'Use the distributive property to multiply', [12]),
    ('3.OA.B.6', 'Understand division as an unknown-factor problem', [13]),
    ('3.OA.C.7', 'Multiply fluently within 100', [14]),
    ('3.OA.C.7', 'Divide fluently within 100', [15]),
    ('3.OA.C.7', 'Use the relationship between multiplication and division', [16]),
    ('3.OA.D.8', 'Solve two-step word problems using the four operations', [17]),
    ('3.OA.D.8', 'Represent two-step word problems with an equation with a letter for the unknown', [18]),
    ('3.OA.D.8', 'Check whether answers are reasonable using mental computation and rounding', [19]),
    ('3.OA.D.9', 'Identify arithmetic patterns in the addition and multiplication tables', [20]),
    ('3.OA.D.9', 'Explain arithmetic patterns using properties of operations', [21]),
    ('3.NBT.A.1', 'Round whole numbers to the nearest 10', [22]),
    ('3.NBT.A.1', 'Round whole numbers to the nearest 100', [23]),
    ('3.NBT.A.2', 'Add within 1000 using place value strategies and algorithms', [24]),
    ('3.NBT.A.2', 'Subtract within 1000 using place value strategies and algorithms', [25]),
    ('3.NBT.A.2', 'Use the relationship between addition and subtraction to subtract and to check answers', [26]),
    ('3.NBT.A.3', 'Multiply one-digit whole numbers by multiples of 10', [27]),
    ('3.NF.A.1', 'Understand a unit fraction as one part of a whole split into equal parts', [28]),
    ('3.NF.A.1', 'Understand a fraction a/b as a parts of size 1/b', [29]),
    ('3.NF.A.2.a', 'Represent a unit fraction on a number line', [30]),
    ('3.NF.A.2.b', 'Represent a fraction a/b on a number line by marking off a lengths of 1/b', [31]),
    ('3.NF.A.3.a', 'Understand equivalent fractions as the same size or the same point on a number line', [32]),
    ('3.NF.A.3.b', 'Recognize and generate simple equivalent fractions, and explain why they are equivalent', [33]),
    ('3.NF.A.3.c', 'Express whole numbers as fractions and recognize fractions that are equal to whole numbers', [34]),
    ('3.NF.A.3.d', 'Compare two fractions with the same denominator', [35]),
    ('3.NF.A.3.d', 'Compare two fractions with the same numerator', [36]),
    ('3.NF.A.3.d', 'Compare fractions only when they refer to the same whole, and justify the comparison with a model', [37]),
    ('3.MD.A.1', 'Tell and write time to the nearest minute', [38]),
    ('3.MD.A.1', 'Solve word problems about time intervals in minutes', [39]),
    ('3.MD.A.1', 'Represent time-interval problems on a number line diagram', [40]),
    ('3.MD.A.2', 'Measure and estimate liquid volumes and masses in liters, grams, and kilograms', [41]),
    ('3.MD.A.2', 'Solve one-step word problems about masses or liquid volumes', [42]),
    ('3.MD.B.3', 'Draw a scaled picture graph to represent data', [43]),
    ('3.MD.B.3', 'Draw a scaled bar graph to represent data', [44]),
    ('3.MD.B.3', 'Solve "how many more" and "how many less" problems using scaled bar graphs and picture graphs', [45]),
    ('3.MD.B.4', 'Measure lengths to the nearest half inch and quarter inch', [46]),
    ('3.MD.B.4', 'Make a line plot of measurement data in whole numbers, halves, or quarters', [47]),
    ('3.MD.C.5.a', 'Understand a unit square and that it is used to measure area', [48]),
    ('3.MD.C.5.b', 'A figure covered by n unit squares without gaps or overlaps has an area of n square units', [49]),
    ('3.MD.C.6', 'Measure areas by counting unit squares in square centimeters, meters, inches, feet, and other units', [50]),
    ('3.MD.C.7.a', 'Find the area of a rectangle by tiling, and show that it equals the product of the side lengths', [51]),
    ('3.MD.C.7.b', 'Multiply side lengths to find the area of a rectangle in real-world problems', [52]),
    ('3.MD.C.7.c', 'Use tiling to show that the area of a rectangle with sides a and b + c is a × b + a × c', [53]),
    ('3.MD.C.7.d', 'Find areas of rectilinear figures by splitting them into rectangles and adding the areas', [54]),
    ('3.MD.D.8', 'Find the perimeter of a polygon from its side lengths', [55]),
    ('3.MD.D.8', 'Find an unknown side length of a polygon from its perimeter', [56]),
    ('3.MD.D.8', 'Show rectangles with the same perimeter and different areas, or the same area and different perimeters', [57]),
    ('3.G.A.1', 'Understand that shapes in different categories can share attributes, and that quadrilaterals form a category', [58]),
    ('3.G.A.1', 'Recognize rhombuses, rectangles, and squares as quadrilaterals, and draw quadrilaterals that are not in these subcategories', [59]),
    ('3.G.A.2', 'Split shapes into parts with equal areas', [60]),
    ('3.G.A.2', 'Express the area of each equal part as a unit fraction of the whole', [61]),
]
