from qb import S, B, sa, mc, tf, plot, draw_write
from common import arr, area_grid, DRAW

SETS = [
    # ------------------------------------------------------------------ 3.OA.A.1 (interpret)
    S('3.OA.A.1', 'Interpret a product as the total number of objects in equal groups',
      main=[
          mc('Which describes 4 × 6?', ['4 groups with 6 objects in each group', '4 groups with 4 objects in each group',
                                        '6 more than 4', '4 objects and 6 objects']),
          sa('There are 3 bags with 9 marbles in each bag.\nWrite a multiplication expression for the total number of marbles. Then find the total.',
             ['Expression:', 'Total:'], key='3 × 9; 27 marbles', note='9 × 3 is also correct for the expression. Both parts are required.'),
          tf('7 × 2 can mean 7 groups with 2 objects in each group.', key=True),
          sa('Describe a situation that 6 × 5 could show.', ['Situation:', ''], key='6 boxes with 5 crayons in each box, 30 crayons in all.',
             note='Any situation with 6 equal groups of 5 (or 5 equal groups of 6) is correct. A situation that adds 6 and 5 is not correct.'),
          tf('8 × 3 means 8 + 3.', key=False),
      ],
      back=[
          B('Find the total of an array by adding equal addends', '2.OA.C.4', [
              sa('Write an addition equation with equal addends for the array.', 'Equation:', key='4 + 4 + 4 = 12', fig=arr(3, 4),
                 note='3 + 3 + 3 + 3 = 12 (adding the columns) is also correct.'),
              tf('An array with 2 rows of 5 dots has 10 dots.', key=True),
              mc('Which addition equation matches an array with 4 rows of 3 dots?', ['3 + 3 + 3 + 3 = 12', '4 + 3 = 7', '4 + 4 = 8', '3 + 4 + 3 = 10']),
              sa('How many dots are in an array with 5 rows of 5 dots?', 'Dots:', key='25'),
              tf('An array with 3 rows of 2 dots has 5 dots.', key=False),
          ]),
          B('Skip-count by 5s, 10s, and 100s', '2.NBT.A.2', [
              sa('Skip-count by 5s.\n5, 10, 15, ___, ___', 'Next two:', key='20, 25'),
              tf('Skip-counting by 10s from 10 gives 10, 20, 30, 40.', key=True),
              mc('Skip-count by 5s.\nWhat number comes after 35?', ['40', '36', '45', '30']),
              sa('Skip-count by 100s.\n100, 200, 300, ___', 'Next:', key='400'),
              tf('Skip-counting by 5s from 5 gives 5, 10, 20, 25.', key=False),
          ]),
      ],
      f1=B('Interpret a multiplication equation as a comparison', '4.OA.A.1', [
          mc('Which statement matches 32 = 4 × 8?', ['32 is 4 times as many as 8.', '32 is 4 more than 8.',
                                                    '8 is 4 times as many as 32.', '32 is 8 more than 4.']),
          sa('Write a comparison statement for 42 = 6 × 7.', 'Statement:', key='42 is 6 times as many as 7.',
             note='"42 is 7 times as many as 6" is also correct. A statement with "more than" is not correct.'),
          tf('27 = 3 × 9 can mean that 27 is 3 times as many as 9.', key=True),
          sa('Write an equation for "40 is 5 times as many as 8."', 'Equation:', key='40 = 5 × 8', note='40 = 8 × 5 is also correct.'),
          tf('15 = 3 × 5 means that 15 is 3 more than 5.', key=False),
      ]),
      f2=B('Interpret a fraction times a whole number as equal parts of a quantity', '5.NF.B.4.a', [
          mc('Which describes {2/3} × 12?', ['Split 12 into 3 equal parts and take 2 of them', 'Split 12 into 2 equal parts and take 3 of them',
                                            'Add {2/3} and 12', 'Make 12 groups of 3']),
          sa('Find {3/4} × 8 by splitting 8 into 4 equal parts and taking 3 of them.', 'Product:', key='6'),
          tf('{1/5} × 20 is the size of one part when 20 is split into 5 equal parts.', key=True),
          sa('Multiply.\n{2/5} × 15', 'Product:', key='6'),
          tf('{3/4} × 12 = 16', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.1 (write equations)
    S('3.OA.A.1', 'Write a multiplication equation for equal groups and arrays',
      main=[
          sa('Write a multiplication equation for the array.', 'Equation:', key='3 × 7 = 21', fig=arr(3, 7), note='7 × 3 = 21 is also correct.'),
          mc('A garden has 5 rows with 8 plants in each row.\nWhich equation gives the number of plants?', ['5 × 8 = 40', '5 + 8 = 13', '8 - 5 = 3', '5 × 5 = 25']),
          tf('The equation 6 × 4 = 24 matches 6 vases with 4 flowers in each vase.', key=True),
          sa('Each of 7 spiders has 8 legs.\nWrite a multiplication equation for the total number of legs.', 'Equation:', key='7 × 8 = 56',
             note='8 × 7 = 56 is also correct.'),
          tf('The equation 4 × 9 = 36 matches 4 boxes with 4 pens in each box.', key=False),
      ],
      back=[
          B('Write an addition equation with equal addends for an array', '2.OA.C.4', [
              sa('Write an addition equation with equal addends for the array.', 'Equation:', key='5 + 5 = 10', fig=arr(2, 5),
                 note='2 + 2 + 2 + 2 + 2 = 10 (adding the columns) is also correct.'),
              tf('3 + 3 + 3 + 3 matches an array with 4 rows of 3 dots.', key=True),
              mc('An array has 3 rows with 5 dots in each row.\nWhich equation gives the total?', ['5 + 5 + 5 = 15', '3 + 5 = 8', '5 + 5 = 10', '3 + 3 = 6']),
              sa('An array has 4 rows with 4 dots in each row.\nWrite an addition equation for the total.', 'Equation:', key='4 + 4 + 4 + 4 = 16'),
              tf('An array with 5 rows of 2 dots matches 5 + 2 = 7.', key=False),
          ]),
          B('Add up to four two-digit numbers', '2.NBT.B.6', [
              sa('Add.\n15 + 15 + 15', 'Sum:', key='45'),
              tf('20 + 20 + 20 + 20 = 80', key=True),
              mc('11 + 11 + 11 + 11 = ?', ['44', '40', '22', '33']),
              sa('Add.\n24 + 24', 'Sum:', key='48'),
              tf('13 + 13 + 13 = 36', key=False),
          ]),
      ],
      f1=B('Write an equation for a multiplicative comparison word problem', '4.OA.A.2', [
          sa('A cat weighs 7 pounds. A dog weighs 5 times as much.\nWrite an equation with a symbol for the dog\'s weight. Then solve it.',
             ['Equation:', 'Weight:'], key='d = 5 × 7; 35 pounds',
             note='Any equivalent equation with a symbol for the unknown is correct. Both parts are required.'),
          tf('Ann has 6 shells. Ben has 3 times as many shells. Ben has 18 shells.', key=True),
          mc('A red tower is 9 blocks tall. A blue tower is 4 times as tall.\nWhich equation gives the blue tower\'s height, b?',
             ['b = 4 × 9', 'b = 4 + 9', 'b = 9 - 4', 'b = 9 ÷ 4']),
          sa('A plant is 8 cm tall. A tree is 10 times as tall.\nHow tall is the tree?', 'Height:', key='80 cm'),
          tf('A rope is 6 feet long. A rope 3 times as long is 9 feet long.', key=False),
      ]),
      f2=B('Write expressions that record calculations with numbers', '5.OA.A.2', [
          sa('Write an expression for "multiply 4 by the sum of 6 and 3."', 'Expression:', key='4 × (6 + 3)'),
          mc('Which expression means "3 times the difference of 10 and 2"?', ['3 × (10 - 2)', '3 × 10 - 2', '10 - 2 × 3', '(3 × 10) - 2']),
          tf('5 × (7 + 2) is 5 times as large as 7 + 2.', key=True),
          sa('There are 4 boxes. Each box has 6 red pens and 2 blue pens.\nWrite an expression for the total number of pens.', 'Expression:',
             key='4 × (6 + 2)', note='(6 + 2) × 4 and 4 × 6 + 4 × 2 are also correct.'),
          tf('2 × (8 + 1) is 2 more than 8 + 1.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.2 (number in each share)
    S('3.OA.A.2', 'Interpret a quotient as the number of objects in each share',
      main=[
          mc('28 stickers are shared equally among 4 friends.\nWhat does 28 ÷ 4 tell you?',
             ['The number of stickers each friend gets', 'The number of friends', 'The number of stickers left over', 'The total number of stickers']),
          sa('18 apples are shared equally among 3 baskets.\nWrite a division equation for the number of apples in each basket. Then solve it.',
             ['Equation:', 'Apples in each basket:'], key='18 ÷ 3 = 6; 6 apples', note='Both parts are required.'),
          tf('In 35 ÷ 5 = 7, the 7 can mean the number in each group when 35 objects are shared equally among 5 groups.', key=True),
          sa('Describe a situation in which 24 ÷ 6 tells how many objects are in each share.', ['Situation:', ''],
             key='24 cookies are shared equally by 6 children, so each child gets 4 cookies.',
             note='Any situation in which 24 objects are shared equally among 6 groups, with the answer as the number in each group, is correct.'),
          tf('When 20 pencils are shared equally among 4 students, each student gets 16 pencils.', key=False),
      ],
      back=[
          B('Split a group of up to 20 objects into two equal groups', '2.OA.C.3', [
              sa('Write 16 as the sum of two equal addends.', 'Sum:', key='8 + 8'),
              tf('14 objects can be split into 2 equal groups of 7.', key=True),
              mc('Which number of objects can be split into 2 equal groups?', ['12', '9', '15', '7']),
              sa('12 counters are split into 2 equal groups.\nHow many counters are in each group?', 'Counters:', key='6'),
              tf('11 objects can be split into 2 equal groups with none left over.', key=False),
          ]),
          B('Split a rectangle into rows and columns of same-size squares and count them', '2.G.A.2', [
              sa('A rectangle is split into 3 rows of 4 same-size squares.\nHow many squares are there?', 'Squares:', key='12'),
              tf('A rectangle split into 2 rows of 5 same-size squares has 10 squares.', key=True),
              mc('How many same-size squares are in the rectangle?', ['8', '6', '10', '4'], fig=area_grid(2, 4)),
              sa('How many same-size squares are in each row of the rectangle?', 'Squares in each row:', key='5', fig=area_grid(3, 5)),
              tf('A rectangle split into 4 rows of 4 same-size squares has 8 squares.', key=False),
          ]),
      ],
      f1=B('Solve multiplicative comparison word problems by dividing', '4.OA.A.2', [
          sa('A tree is 24 feet tall. That is 4 times as tall as a bush.\nHow tall is the bush?', 'Height:', key='6 feet'),
          tf('Mia has 45 beads. That is 5 times as many beads as Jo has. Jo has 9 beads.', key=True),
          mc('A truck weighs 6 tons. That is 3 times as much as a van weighs.\nHow much does the van weigh?', ['2 tons', '18 tons', '3 tons', '9 tons']),
          sa('A book costs $36. That is 9 times as much as a pen costs.\nHow much does the pen cost?', 'Cost:', key='$4'),
          tf('A barn is 40 feet tall. That is 8 times as tall as a fence. The fence is 32 feet tall.', key=False),
      ]),
      f2=B('Interpret a fraction as division to find equal shares', '5.NF.B.3', [
          sa('4 friends share 3 pizzas equally.\nHow much pizza does each friend get?', 'Pizza:', key='3/4 of a pizza'),
          tf('When 2 sandwiches are shared equally by 5 people, each person gets {2/5} of a sandwich.', key=True),
          mc('6 people share 5 pounds of rice equally.\nHow much rice does each person get?', ['{5/6} pound', '{6/5} pounds', '1 pound', '{1/6} pound']),
          sa('Write 7 ÷ 3 as a fraction or a mixed number.', 'Answer:', key='7/3', note='2 1/3 is also correct.'),
          tf('3 ÷ 8 = {8/3}', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.2 (number of shares)
    S('3.OA.A.2', 'Interpret a quotient as the number of equal shares',
      main=[
          mc('30 pencils are put in boxes, with 5 pencils in each box.\nWhat does 30 ÷ 5 tell you?',
             ['The number of boxes', 'The number of pencils in each box', 'The number of pencils left over', 'The total number of pencils']),
          sa('24 eggs are packed 6 to a carton.\nWrite a division equation for the number of cartons. Then solve it.', ['Equation:', 'Cartons:'],
             key='24 ÷ 6 = 4; 4 cartons', note='Both parts are required.'),
          tf('In 40 ÷ 8 = 5, the 5 can mean the number of groups when 40 objects are put into groups of 8.', key=True),
          sa('Describe a situation in which 21 ÷ 3 tells how many groups there are.', ['Situation:', ''],
             key='21 students make teams of 3, so there are 7 teams.',
             note='Any situation in which 21 objects are put into groups of 3, with the answer as the number of groups, is correct.'),
          tf('A coach puts 36 balls into bags of 4. There are 32 bags.', key=False),
      ],
      back=[
          B('Skip-count by 5s and 10s', '2.NBT.A.2', [
              sa('Skip-count by 10s from 0 to 60.\nHow many 10s did you count?', 'Tens:', key='6'),
              tf('Counting by 5s from 0 to 25 takes 5 counts.', key=True),
              mc('Starting at 0, how many 5s do you count to reach 40?', ['8', '5', '40', '35']),
              sa('Skip-count by 10s.\n40, 50, 60, ___, ___', 'Next two:', key='70, 80'),
              tf('Counting by 10s from 0 to 90 takes 10 counts.', key=False),
          ]),
          B('Rows and columns of arrays up to 5 by 5', '2.OA.C.4', [
              sa('How many rows does the array have? How many dots are in each row?', ['Rows:', 'Dots in each row:'], key='4 rows; 5 dots',
                 fig=arr(4, 5)),
              tf('The array has 3 rows.', key=True, fig=arr(3, 5)),
              mc('How many dots are in each row of the array?', ['4', '3', '12', '7'], fig=arr(3, 4)),
              sa('Write an addition equation with equal addends for the array.', 'Equation:', key='4 + 4 = 8', fig=arr(2, 4),
                 note='2 + 2 + 2 + 2 = 8 is also correct.'),
              tf('The array has 5 rows.', key=False, fig=arr(4, 2)),
          ]),
      ],
      f1=B('Interpret remainders when dividing into groups', '4.OA.A.3', [
          sa('A teacher puts 26 students in groups of 4.\nHow many full groups are there, and how many students are left over?',
             ['Full groups:', 'Left over:'], key='6 groups; 2 students'),
          sa('29 people ride in boats that hold 6 people each.\nHow many boats are needed so everyone can ride?', 'Boats:', key='5 boats',
             note='29 ÷ 6 = 4 R 5. The 5 extra people need another boat, so 5 boats.'),
          mc('A baker puts 50 rolls in bags of 8.\nHow many bags can she fill completely?', ['6', '7', '8', '2']),
          tf('43 cards put in piles of 5 make 8 full piles with 3 cards left over.', key=True),
          tf('38 markers put in boxes of 6 fill 7 boxes.', key=False),
      ]),
      f2=B('Divide a whole number by a unit fraction to find the number of equal shares', '5.NF.B.7.c', [
          sa('How many {1/3}-cup servings are in 4 cups?', 'Servings:', key='12'),
          tf('6 ÷ {1/2} = 12', key=True),
          mc('A 5-foot board is cut into pieces that are each {1/4} foot long.\nHow many pieces are there?', ['20', '{5/4}', '9', '{1/20}']),
          sa('Divide.\n3 ÷ {1/5}', 'Quotient:', key='15'),
          tf('2 ÷ {1/4} = {1/8}', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.3 (multiply)
    S('3.OA.A.3', 'Solve multiplication word problems within 100',
      main=[
          sa('A bakery puts 6 muffins in each box. It fills 7 boxes.\nHow many muffins are in the boxes?', 'Muffins:', key='42 muffins'),
          sa('A wall has 8 rows of tiles with 9 tiles in each row.\nHow many tiles are on the wall?', 'Tiles:', key='72 tiles'),
          mc('Each ribbon is 4 feet long. Mia has 6 ribbons.\nWhat is the total length of the ribbons?', ['24 feet', '10 feet', '28 feet', '2 feet']),
          tf('A parking lot has 5 rows with 9 cars in each row. There are 54 cars.', key=False),
          sa('Tickets cost $7 each. A family buys 8 tickets.\nWrite an equation with a symbol for the total cost. Then solve it.',
             ['Equation:', 'Total cost:'], key='8 × 7 = c; $56',
             note='Any equation with a symbol for the unknown (such as 8 × 7 = ?) is correct. Both parts are required.'),
      ],
      back=[
          B('One-step addition word problems within 100', '2.OA.A.1', [
              sa('A box has 24 crayons. Another box has 24 crayons.\nHow many crayons are there in all?', 'Crayons:', key='48'),
              tf('Jo has 35 cards and gets 15 more. She has 50 cards.', key=True),
              mc('A bus has 27 children and 18 adults.\nHow many people are on the bus?', ['45', '9', '35', '55']),
              sa('A farmer picks 46 apples in the morning and 38 apples in the afternoon.\nHow many apples does he pick?', 'Apples:', key='84'),
              tf('A class has 16 girls and 17 boys. There are 23 students.', key=False),
          ]),
          B('Add lengths in word problems within 100', '2.MD.B.5', [
              sa('A red ribbon is 25 cm long. A blue ribbon is 30 cm long.\nWhat is their total length?', 'Length:', key='55 cm'),
              tf('Two 20-foot ropes laid end to end are 40 feet long.', key=True),
              mc('One path is 48 m long and another is 36 m long.\nWhat is their total length?', ['84 m', '12 m', '74 m', '94 m']),
              sa('A board is 47 inches long. Ben glues a 25-inch board to its end.\nHow long is it now?', 'Length:', key='72 inches'),
              tf('A 60-cm stick and a 35-cm stick laid end to end are 85 cm long.', key=False),
          ]),
      ],
      f1=B('Multiply a two-digit number by a one-digit number to solve word problems', '4.NBT.B.5', [
          sa('A school buys 6 boxes of 24 pencils.\nHow many pencils does it buy?', 'Pencils:', key='144 pencils'),
          tf('A theater has 9 rows of 32 seats. It has 288 seats.', key=True),
          mc('A bike trip covers 45 miles each day for 4 days.\nHow long is the trip?', ['180 miles', '49 miles', '160 miles', '90 miles']),
          sa('Tickets cost $18 each. A club buys 7 tickets.\nWhat is the total cost?', 'Cost:', key='$126'),
          tf('A farmer plants 5 rows of 76 trees. He plants 350 trees.', key=False),
      ]),
      f2=B('Multiply multi-digit whole numbers to solve word problems', '5.NBT.B.5', [
          sa('A stadium has 48 sections with 125 seats in each section.\nHow many seats are there?', 'Seats:', key='6,000 seats'),
          tf('A truck carries 36 crates with 144 apples in each crate. It carries 5,184 apples.', key=True),
          mc('A printer prints 215 pages each hour for 24 hours.\nHow many pages does it print?', ['5,160', '4,300', '1,290', '5,060']),
          sa('A school orders 32 boxes with 250 sheets of paper in each box.\nHow many sheets is that?', 'Sheets:', key='8,000 sheets'),
          tf('A farm packs 64 cartons of 18 eggs. That is 1,052 eggs.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.3 (divide)
    S('3.OA.A.3', 'Solve division word problems within 100',
      main=[
          sa('56 students are split equally into 7 teams.\nHow many students are on each team?', 'Students:', key='8 students'),
          sa('A gardener plants 63 seeds in rows of 9.\nHow many rows does she plant?', 'Rows:', key='7 rows'),
          mc('A 48-inch ribbon is cut into 6 equal pieces.\nHow long is each piece?', ['8 inches', '42 inches', '54 inches', '6 inches']),
          tf('81 chairs are set up in 9 equal rows. There are 9 chairs in each row.', key=True),
          sa('A coach has 54 balls. She puts the same number of balls in each of 6 bags.\n'
             'Write an equation with a symbol for the number of balls in each bag. Then solve it.', ['Equation:', 'Balls in each bag:'],
             key='54 ÷ 6 = b; 9 balls',
             note='Any equation with a symbol for the unknown (such as 6 × b = 54) is correct. Both parts are required.'),
      ],
      back=[
          B('One-step subtraction word problems within 100', '2.OA.A.1', [
              sa('A shelf has 64 books. 28 books are checked out.\nHow many books are left?', 'Books:', key='36'),
              tf('Mo had 50 stickers and gave away 18. He has 32 stickers left.', key=True),
              mc('A tank has 90 fish. 45 fish are moved to another tank.\nHow many fish are left?', ['45', '55', '135', '35']),
              sa('A rope is 75 feet long. 30 feet are cut off.\nHow much rope is left?', 'Rope left:', key='45 feet'),
              tf('A box had 40 pears. 15 were eaten, so 35 are left.', key=False),
          ]),
          B('Split circles and rectangles into 2, 3, or 4 equal shares', '2.G.A.3', [
              sa('A rectangle is split into 4 equal shares.\nWhat is each share called?', 'Name:', key='A fourth', note='"A quarter" is also correct.'),
              tf('A circle cut into 3 equal shares is cut into thirds.', key=True),
              mc('A sandwich is cut into 2 equal shares.\nWhat is each share called?', ['A half', 'A third', 'A fourth', 'A whole']),
              sa('How many thirds make a whole?', 'Thirds:', key='3'),
              tf('A rectangle cut into 4 shares of different sizes is cut into fourths.', key=False),
          ]),
      ],
      f1=B('Divide up to three-digit numbers by one-digit numbers to solve word problems', '4.NBT.B.6', [
          sa('A farmer packs 96 eggs into cartons of 6.\nHow many cartons does he fill?', 'Cartons:', key='16 cartons'),
          tf('A 135-page book is read in 5 equal parts. Each part is 27 pages.', key=True),
          mc('A school splits 252 students into 4 equal groups.\nHow many students are in each group?', ['63', '248', '61', '1,008']),
          sa('A rope 128 feet long is cut into 8 equal pieces.\nHow long is each piece?', 'Length:', key='16 feet'),
          tf('7 friends share 196 marbles equally. Each friend gets 29 marbles.', key=False),
      ]),
      f2=B('Divide by two-digit divisors to solve word problems', '5.NBT.B.6', [
          sa('A school has 672 students in 24 classes of the same size.\nHow many students are in each class?', 'Students:', key='28'),
          tf('A 1,350-mile trip is driven in 15 days, the same distance each day. Each day is 90 miles.', key=True),
          mc('A factory packs 2,016 cans in boxes of 48.\nHow many boxes does it fill?', ['42', '41', '2,064', '43']),
          sa('An orchard has 1,155 trees in 35 equal rows.\nHow many trees are in each row?', 'Trees:', key='33'),
          tf('3,600 seats are split into 25 equal sections. Each section has 154 seats.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.3 (represent)
    S('3.OA.A.3', 'Represent a multiplication or division word problem with a drawing and an equation',
      main=[
          draw_write('There are 4 plates with 5 grapes on each plate.\nDraw a picture of the problem. Then write an equation and find the total.',
                     DRAW, ['Equation:', 'Total:'],
                     draw='4 equal groups with 5 objects in each (or a 4-by-5 array, or another diagram of 4 equal groups of 5)',
                     key='4 × 5 = 20; 20 grapes',
                     note='Grade both: a drawing that shows 4 equal groups of 5, and the equation with the total. 5 × 4 = 20 is also correct.'),
          draw_write('18 crackers are shared equally among 3 children.\nDraw a picture of the problem. Then write a division equation and find how many crackers each child gets.',
                     DRAW, ['Equation:', 'Each child:'],
                     draw='18 objects split into 3 equal groups with 6 in each, or an equivalent diagram',
                     key='18 ÷ 3 = 6; 6 crackers', note='Grade both: the drawing of 3 equal groups, and the equation with the answer.'),
          mc('A drawing shows 3 rows with 6 stars in each row.\nWhich equation matches the drawing?', ['3 × 6 = ?', '3 + 6 = ?', '6 ÷ 3 = ?', '6 - 3 = ?']),
          draw_write('A 20-foot board is cut into pieces that are each 4 feet long.\nDraw a diagram. Then write an equation with a symbol for the unknown and solve it.',
                     DRAW, ['Equation:', 'Pieces:'],
                     draw='A bar or number line 20 units long marked into 4-unit parts, showing 5 parts',
                     key='20 ÷ 4 = p; 5 pieces',
                     note='Any equation with a symbol for the unknown (such as p × 4 = 20) is correct. Grade both the diagram and the equation with its solution.'),
          tf('A drawing of 5 groups with 3 dots in each group matches the equation 5 + 3 = 8.', key=False),
      ],
      back=[
          B('Use an equation with a symbol for the unknown in a one-step word problem', '2.OA.A.1', [
              sa('Lena has 23 shells. She finds some more and now has 41.\nWrite an equation with a symbol for the unknown. Then solve it.',
                 ['Equation:', 'Shells found:'], key='23 + ? = 41; 18',
                 note='Any equation with a symbol for the unknown (such as 41 - 23 = s) is correct. Both parts are required.'),
              tf('The equation 52 - b = 30 matches "52 birds were on a wire. Some flew away, and 30 were left."', key=True),
              mc('A box had some pens. 14 more were put in, and now there are 50.\nWhich equation matches?',
                 ['p + 14 = 50', 'p - 14 = 50', '50 + 14 = p', '14 - p = 50']),
              sa('A rope is 60 inches long. Kim cuts off 25 inches.\nWrite an equation with a symbol for the length left. Then solve it.',
                 ['Equation:', 'Length left:'], key='60 - 25 = r; 35 inches',
                 note='Any equation with a symbol for the unknown is correct. Both parts are required.'),
              tf('The equation 18 + 9 = n matches "There were 18 cats. 9 cats left. How many are still here?"', key=False),
          ]),
          B('Draw arrays with up to 5 rows and 5 columns', '2.OA.C.4', [
              plot('Draw an array with 3 rows of 4 dots.', DRAW, key='An array of 3 rows with 4 dots in each row (12 dots)'),
              tf('An array with 4 rows of 2 dots shows 2 + 2 + 2 + 2.', key=True),
              mc('How many dots do you draw for an array with 5 rows of 3 dots?', ['15', '8', '12', '53']),
              draw_write('Draw an array with 2 rows of 5 dots.\nThen write an addition equation for it.', DRAW, 'Equation:',
                         draw='2 rows with 5 dots in each row', key='5 + 5 = 10',
                         note='Grade both: the array, and the equation. 2 + 2 + 2 + 2 + 2 = 10 is also correct.'),
              tf('An array with 3 rows of 3 dots has 6 dots.', key=False),
          ]),
      ],
      f1=B('Use a drawing and an equation to solve a multiplicative comparison problem', '4.OA.A.2', [
          draw_write('A blue scarf is 3 feet long. A red scarf is 4 times as long.\nDraw a tape diagram. Then write an equation and find the red scarf\'s length.',
                     DRAW, ['Equation:', 'Length:'],
                     draw='A tape for the blue scarf with 1 part of 3 feet, and a tape for the red scarf with 4 equal parts of 3 feet',
                     key='r = 4 × 3; 12 feet', note='Grade both: the tape diagram, and the equation with the answer.'),
          tf('The equation 36 = 4 × n matches "36 is 4 times as many as n."', key=True),
          mc('A school has 8 teachers and 5 times as many parent helpers.\nWhich equation finds the number of parent helpers, p?',
             ['p = 5 × 8', 'p = 5 + 8', 'p = 8 - 5', 'p = 8 ÷ 5']),
          sa('Ty swam 30 laps. That is 6 times as many laps as Al swam.\nWrite an equation with a symbol for Al\'s laps. Then solve it.',
             ['Equation:', 'Laps:'], key='6 × a = 30; 5 laps',
             note='Any equivalent equation (such as a = 30 ÷ 6) is correct. Both parts are required.'),
          tf('"21 is 3 times as many as 7" can be written as 21 = 3 + 7.', key=False),
      ]),
      f2=B('Use a tape diagram to find a fraction of a whole number in context', '5.NF.B.6', [
          draw_write('A path is 6 miles long. Kai walked {2/3} of it.\nDraw a tape diagram. Then find how far Kai walked.', DRAW, 'Distance:',
                     draw='A tape for 6 miles split into 3 equal parts of 2 miles, with 2 parts marked', key='4 miles',
                     note='Grade both: the tape in 3 equal parts with 2 parts marked, and 4 miles.'),
          tf('{3/4} of a 12-pound bag of rice is 9 pounds.', key=True),
          mc('A recipe uses 2 cups of milk. Leo makes {1/2} of the recipe.\nHow much milk does he use?', ['1 cup', '4 cups', '{1/4} cup', '2{1/2} cups']),
          sa('A rope is 10 feet long. {3/5} of it is red.\nHow many feet of the rope are red?', 'Feet:', key='6 feet'),
          tf('{2/5} of 20 students is 5 students.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.4 (multiplication)
    S('3.OA.A.4', 'Find the unknown whole number in a multiplication equation',
      main=[
          sa('Find the unknown number.\n7 × ? = 56', 'Unknown:', key='8'),
          sa('Find the unknown number.\n? × 4 = 36', 'Unknown:', key='9'),
          mc('Which number makes the equation true?\n6 × n = 42', ['7', '6', '36', '48']),
          tf('In 4 × ▢ = 32, the unknown number is 9.', key=False),
          sa('Find the unknown number.\n63 = 9 × ?', 'Unknown:', key='7'),
      ],
      back=[
          B('Find the unknown number in an addition or subtraction equation within 20', '1.OA.D.8', [
              sa('Find the unknown number.\n9 + ? = 15', 'Unknown:', key='6'),
              tf('In 13 - ? = 6, the unknown number is 7.', key=True),
              mc('? + 7 = 16', ['9', '23', '8', '10']),
              sa('Find the unknown number.\n14 = ? + 5', 'Unknown:', key='9'),
              tf('In ? - 4 = 9, the unknown number is 5.', key=False),
          ]),
          B('Skip-count to find a number in a counting sequence', '2.NBT.A.2', [
              sa('Skip-count by 5s from 5.\nHow many numbers do you say to reach 35?', 'Numbers:', key='7'),
              tf('Skip-counting by 10s from 10, the 4th number is 40.', key=True),
              mc('Skip-count by 5s from 5.\nWhat is the 6th number?', ['30', '25', '35', '11']),
              sa('Skip-count by 100s from 100.\nWhat is the 5th number?', 'Number:', key='500'),
              tf('Skip-counting by 10s from 10, the 7th number is 80.', key=False),
          ]),
      ],
      f1=B('Find factor pairs and decide whether a number is a factor', '4.OA.B.4', [
          sa('List all the factor pairs of 20.', 'Factor pairs:', key='1 × 20, 2 × 10, 4 × 5', note='All three pairs are required, in any order.'),
          tf('7 is a factor of 63.', key=True),
          mc('Which is a factor pair of 36?', ['4 × 9', '5 × 7', '3 × 11', '6 × 5']),
          sa('Is 6 a factor of 44? Explain.', ['Answer:', 'Explanation:'], key='No',
             note='No whole number times 6 equals 44 (44 ÷ 6 = 7 R 2).'),
          tf('8 is a factor of 30.', key=False),
      ]),
      f2=B('Find an unknown factor with a two-digit factor', '5.NBT.B.6', [
          sa('Find the unknown number.\n24 × ? = 912', 'Unknown:', key='38'),
          tf('If 15 × n = 645, then n = 43.', key=True),
          mc('? × 32 = 1,248', ['39', '38', '41', '1,280']),
          sa('Find the unknown number.\n2,100 = 75 × ?', 'Unknown:', key='28'),
          tf('If 18 × n = 864, then n = 46.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.A.4 (division)
    S('3.OA.A.4', 'Find the unknown whole number in a division equation',
      main=[
          sa('Find the unknown number.\n45 ÷ ? = 9', 'Unknown:', key='5'),
          sa('Find the unknown number.\n? ÷ 6 = 7', 'Unknown:', key='42'),
          mc('Which number makes the equation true?\n72 ÷ n = 8', ['9', '64', '80', '8']),
          tf('In ? ÷ 4 = 8, the unknown number is 32.', key=True),
          tf('In 49 ÷ ▢ = 7, the unknown number is 42.', key=False),
      ],
      back=[
          B('Find the unknown number in a subtraction or addition equation within 20', '1.OA.D.8', [
              sa('Find the unknown number.\n17 - ? = 9', 'Unknown:', key='8'),
              tf('In ? + 6 = 14, the unknown number is 8.', key=True),
              mc('12 = ? - 3', ['15', '9', '4', '14']),
              sa('Find the unknown number.\n? - 7 = 7', 'Unknown:', key='14'),
              tf('In 16 - ? = 10, the unknown number is 4.', key=False),
          ]),
          B('Add and subtract within 20 mentally', '2.OA.B.2', [
              sa('Subtract.\n15 - 8', 'Difference:', key='7'),
              tf('9 + 8 = 17', key=True),
              mc('13 - 6 = ?', ['7', '8', '6', '19']),
              sa('Add.\n7 + 6', 'Sum:', key='13'),
              tf('16 - 9 = 8', key=False),
          ]),
      ],
      f1=B('Find the unknown number in a division equation with a larger dividend', '4.NBT.B.6', [
          sa('Find the unknown number.\n? ÷ 4 = 125', 'Unknown:', key='500'),
          tf('In 312 ÷ n = 6, n = 52.', key=True),
          mc('848 ÷ ? = 8', ['106', '840', '856', '16']),
          sa('Find the unknown number.\n? ÷ 7 = 36', 'Unknown:', key='252'),
          tf('In 450 ÷ n = 5, n = 9.', key=False),
      ]),
      f2=B('Find the unknown number in a division equation with a two-digit divisor', '5.NBT.B.6', [
          sa('Find the unknown number.\n? ÷ 25 = 36', 'Unknown:', key='900'),
          tf('In 1,092 ÷ n = 42, n = 26.', key=True),
          mc('1,512 ÷ ? = 36', ['42', '48', '1,476', '54']),
          sa('Find the unknown number.\n? ÷ 16 = 45', 'Unknown:', key='720'),
          tf('In 2,000 ÷ n = 80, n = 20.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.B.5 (commutative)
    S('3.OA.B.5', 'Use the commutative property of multiplication',
      main=[
          sa('7 × 8 = 56.\nWithout multiplying, what is 8 × 7? Explain.', ['Product:', 'Explanation:'], key='56',
             note='Changing the order of the factors does not change the product (the commutative property). Both parts are required.'),
          mc('Which is equal to 9 × 3?', ['3 × 9', '9 + 3', '9 × 9', '93']),
          tf('5 × 9 = 9 × 5', key=True),
          sa('An array has 4 rows of 7 dots. It is turned on its side, so it now has 7 rows.\nHow many dots are in each row now? How many dots are there in all?',
             ['Dots in each row:', 'Total:'], key='4; 28', note='Both parts are required.'),
          tf('8 × 4 = 4 + 8', key=False),
      ],
      back=[
          B('Add in either order', '1.OA.B.3', [
              sa('9 + 5 = 14.\nWhat is 5 + 9?', 'Sum:', key='14'),
              tf('7 + 6 = 6 + 7', key=True),
              mc('Which is equal to 4 + 9?', ['9 + 4', '9 - 4', '4 + 4', '49']),
              sa('Fill in the blank.\n6 + 8 = 8 + ___', 'Blank:', key='6'),
              tf('5 + 2 = 5 - 2', key=False),
          ]),
          B('Find the total of an array by rows or by columns', '2.OA.C.4', [
              sa('Add the rows. Then add the columns.\nWhat total do you get each way?', ['By rows:', 'By columns:'], key='12; 12', fig=arr(3, 4),
                 note='4 + 4 + 4 = 12 and 3 + 3 + 3 + 3 = 12. Both parts are required.'),
              tf('An array with 2 rows of 5 dots has the same number of dots as an array with 5 rows of 2 dots.', key=True),
              mc('An array has 3 rows of 5 dots.\nWhich addition adds its columns?', ['3 + 3 + 3 + 3 + 3', '5 + 5 + 5', '3 + 5', '5 + 3 + 5']),
              sa('How many dots are in an array with 4 rows of 5 dots?', 'Dots:', key='20'),
              tf('An array with 4 rows of 3 dots has more dots than an array with 3 rows of 4 dots.', key=False),
          ]),
      ],
      f1=B('Use the commutative property with multi-digit products', '4.NBT.B.5', [
          tf('24 × 15 = 15 × 24', key=True),
          sa('36 × 7 = 252.\nWhat is 7 × 36?', 'Product:', key='252'),
          mc('Which is equal to 48 × 25?', ['25 × 48', '48 + 25', '48 × 52', '84 × 25']),
          sa('Is 19 × 6 equal to 6 × 19? Find the product.', ['Equal?', 'Product:'], key='Yes; 114', note='Both parts are required.'),
          tf('125 × 8 = 8 × 152', key=False),
      ]),
      f2=B('Multiply a fraction and a whole number in either order', '5.NF.B.4.a', [
          tf('{2/3} × 6 = 6 × {2/3}', key=True),
          sa('Multiply.\n8 × {3/4}', 'Product:', key='6'),
          mc('Which is equal to {5/6} × 12?', ['12 × {5/6}', '{6/5} × 12', '{5/6} + 12', '12 × {6/5}']),
          sa('{3/5} × 10 = 6.\nWhat is 10 × {3/5}?', 'Product:', key='6'),
          tf('{1/2} × 14 = 14 × 2', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.B.5 (associative)
    S('3.OA.B.5', 'Use the associative property of multiplication',
      main=[
          sa('Find the product by first multiplying 2 × 5.\n2 × 5 × 7', 'Product:', key='70', note='2 × 5 = 10 and 10 × 7 = 70.'),
          mc('Which is equal to (4 × 2) × 3?', ['4 × (2 × 3)', '4 + (2 × 3)', '(4 + 2) × 3', '4 × 2 + 3']),
          tf('(3 × 2) × 4 = 3 × (2 × 4)', key=True),
          sa('Show two different ways to group 5 × 2 × 6. Then find the product.', ['Way 1:', 'Way 2:', 'Product:'],
             key='(5 × 2) × 6 = 60; 5 × (2 × 6) = 60; 60', note='Any two different groupings with the product 60 are correct.'),
          tf('(2 × 4) × 5 = 2 + (4 × 5)', key=False),
      ],
      back=[
          B('Add three numbers in any grouping', '1.OA.B.3', [
              sa('Add.\n7 + 3 + 5', 'Sum:', key='15'),
              tf('(4 + 6) + 3 = 4 + (6 + 3)', key=True),
              mc('Which sum is equal to 8 + 5 + 2?', ['10 + 5', '13 + 5', '8 + 7 + 2', '10 + 7']),
              sa('Add by making a ten first.\n6 + 9 + 4', 'Sum:', key='19'),
              tf('(5 + 5) + 4 = 10 + 9', key=False),
          ]),
          B('Add within 20 mentally', '2.OA.B.2', [
              sa('Add.\n8 + 9', 'Sum:', key='17'),
              tf('6 + 7 = 13', key=True),
              mc('9 + 9 = ?', ['18', '17', '19', '81']),
              sa('Add.\n10 + 7', 'Sum:', key='17'),
              tf('5 + 8 = 12', key=False),
          ]),
      ],
      f1=B('Use grouping and multiples of 10 to multiply', '4.NBT.B.5', [
          sa('Find 4 × 5 × 13 by first multiplying 4 × 5.', 'Product:', key='260'),
          tf('6 × 25 × 4 = 6 × 100', key=True),
          mc('2 × 37 × 5 = 37 × ?', ['10', '7', '2', '74']),
          sa('Multiply.\n3 × 20 × 5', 'Product:', key='300'),
          tf('25 × 3 × 4 = 75 × 12', key=False),
      ]),
      f2=B('Multiply by powers of 10 written with exponents', '5.NBT.A.2', [
          sa('Multiply.\n4 × 10²', 'Product:', key='400'),
          tf('7 × 10 × 10 × 10 = 7 × 10³', key=True),
          mc('Which is equal to 36 × 100?', ['36 × 10²', '36 × 10³', '36 × 10', '36 + 100']),
          sa('Find 25 × 4 × 10².', 'Product:', key='10,000'),
          tf('3 × 10² = 3,000', key=False),
      ])),
]
