from qb import S, B, sa, mc, tf, work
from common import arr, amodel

MUL_ALG = ('The standard multiplication algorithm with the partial products or regrouping shown. '
           'A correct product without the algorithm earns partial credit.')

SETS = [
    # ------------------------------------------------------------------ 3.OA.B.5 (distributive)
    S('3.OA.B.5', 'Use the distributive property to multiply',
      main=[
          sa('The dashed line splits the array of 6 rows of 7 into 6 rows of 5 and 6 rows of 2.\nUse 6 × 7 = 6 × 5 + 6 × 2 to find 6 × 7.',
             'Product:', key='42', note='6 × 5 = 30, 6 × 2 = 12, and 30 + 12 = 42.', fig=arr(6, 7, split=5)),
          mc('Which is equal to 4 × 9?', ['4 × 5 + 4 × 4', '4 × 5 + 4', '4 + 9', '4 × 5 × 4']),
          tf('9 × 6 = 9 × 3 + 9 × 3', key=True),
          work('Use the distributive property to find 8 × 6. Show the parts you add.', 'Product:', key='48',
               method='Any correct break-apart, for example 8 × 6 = 8 × 5 + 8 × 1 = 40 + 8, or 8 × 6 = 4 × 6 + 4 × 6 = 24 + 24. '
                      'The product without a break-apart earns partial credit.'),
          tf('7 × 8 = 7 × 4 + 4', key=False),
      ],
      back=[
          B('Add two-digit numbers within 100', '2.NBT.B.5', [
              sa('Add.\n40 + 16', 'Sum:', key='56'),
              tf('35 + 21 = 56', key=True),
              mc('30 + 18 = ?', ['48', '38', '58', '12']),
              sa('Add.\n26 + 26', 'Sum:', key='52'),
              tf('45 + 27 = 62', key=False),
          ]),
          B('Split an array into two parts and add the parts', '2.OA.C.4', [
              sa('The dashed line splits the array.\nHow many dots are on each side? How many dots are there in all?', ['Left:', 'Right:', 'Total:'],
                 key='9; 6; 15', fig=arr(3, 5, split=3), note='All three parts are required.'),
              tf('An array of 4 rows of 5 dots can be split into 4 rows of 3 dots and 4 rows of 2 dots.', key=True),
              mc('An array of 2 rows of 5 dots is split into 2 rows of 4 dots and 2 rows of 1 dot.\nHow many dots are there in all?', ['10', '8', '2', '12']),
              sa('An array of 5 rows of 4 dots is split into two arrays of 5 rows of 2 dots.\nHow many dots are in each part?', 'Dots in each part:', key='10'),
              tf('Splitting an array into two parts changes the total number of dots.', key=False),
          ]),
      ],
      f1=B('Multiply a two-digit number by a one-digit number with the distributive property', '4.NBT.B.5', [
          sa('Use the area model to find 7 × 23.', 'Product:', key='161', fig=amodel('7', [(20, '20', '140'), (3, '3', '21')])),
          tf('6 × 34 = 6 × 30 + 6 × 4', key=True),
          mc('Which is equal to 8 × 45?', ['8 × 40 + 8 × 5', '8 × 40 + 5', '8 × 4 + 8 × 5', '8 + 40 + 5']),
          work('Use the distributive property to find 5 × 68. Show your work.', 'Product:', key='340',
               method='Any correct break-apart, for example 5 × 60 + 5 × 8 = 300 + 40, or 5 × 70 - 5 × 2 = 350 - 10. '
                      'The product without a break-apart earns partial credit.'),
          tf('9 × 52 = 450 + 2', key=False),
      ]),
      f2=B('Evaluate expressions with parentheses that use the distributive property', '5.OA.A.1', [
          sa('Evaluate.\n6 × (10 + 3)', 'Value:', key='78'),
          tf('4 × (25 + 5) = 4 × 25 + 4 × 5', key=True),
          mc('Evaluate.\n(7 × 20) + (7 × 4)', ['168', '161', '140', '31']),
          sa('Evaluate.\n3 × (40 - 2)', 'Value:', key='114'),
          tf('5 × (8 + 2) = 42', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.B.6
    S('3.OA.B.6', 'Understand division as an unknown-factor problem',
      main=[
          sa('Find 36 ÷ 9 by finding the unknown factor.\n9 × ? = 36', 'Quotient:', key='4'),
          mc('Which multiplication fact helps you find 42 ÷ 6?', ['6 × 7 = 42', '6 × 6 = 36', '42 - 6 = 36', '6 + 7 = 13']),
          sa('Write the unknown-factor equation for 54 ÷ 9. Then find the quotient.', ['Equation:', 'Quotient:'], key='9 × ? = 54; 6',
             note='? × 9 = 54 is also correct. Both parts are required.'),
          tf('56 ÷ 7 = 8 because 7 × 8 = 56.', key=True),
          tf('27 ÷ 3 = 8 because 3 × 8 = 27.', key=False),
      ],
      back=[
          B('Understand subtraction as an unknown-addend problem', '1.OA.B.4', [
              sa('Find 15 - 9 by thinking 9 + ? = 15.', 'Difference:', key='6'),
              tf('13 - 5 = 8 because 5 + 8 = 13.', key=True),
              mc('Which addition fact helps you find 17 - 8?', ['8 + 9 = 17', '8 + 8 = 16', '17 + 8 = 25', '9 - 8 = 1']),
              sa('Write the unknown-addend equation for 12 - 7. Then find the difference.', ['Equation:', 'Difference:'], key='7 + ? = 12; 5',
                 note='? + 7 = 12 is also correct. Both parts are required.'),
              tf('14 - 6 = 9 because 6 + 9 = 14.', key=False),
          ]),
          B('Write even numbers as the sum of two equal addends', '2.OA.C.3', [
              sa('Write 18 as the sum of two equal addends.', 'Sum:', key='9 + 9'),
              tf('10 = 5 + 5, so 10 is even.', key=True),
              mc('Which number can be written as the sum of two equal whole-number addends?', ['14', '13', '9', '17']),
              sa('What number plus itself makes 12?', 'Number:', key='6'),
              tf('15 can be written as the sum of two equal whole-number addends.', key=False),
          ]),
      ],
      f1=B('Use multiplication to find and check quotients', '4.NBT.B.6', [
          sa('Find 84 ÷ 4 by thinking 4 × ? = 84.', 'Quotient:', key='21'),
          tf('96 ÷ 3 = 32 because 3 × 32 = 96.', key=True),
          mc('Which equation checks 135 ÷ 5 = 27?', ['5 × 27 = 135', '5 + 27 = 32', '135 × 5 = 675', '27 - 5 = 22']),
          sa('Write the unknown-factor equation for 224 ÷ 7. Then find the quotient.', ['Equation:', 'Quotient:'], key='7 × ? = 224; 32',
             note='? × 7 = 224 is also correct. Both parts are required.'),
          tf('152 ÷ 8 = 18 because 8 × 18 = 152.', key=False),
      ]),
      f2=B('Divide a whole number by a unit fraction and check with multiplication', '5.NF.B.7.b', [
          sa('Find 3 ÷ {1/4} by thinking ? × {1/4} = 3.', 'Quotient:', key='12'),
          tf('5 ÷ {1/2} = 10 because 10 × {1/2} = 5.', key=True),
          mc('Which equation checks 4 ÷ {1/3} = 12?', ['12 × {1/3} = 4', '4 × {1/3} = 12', '12 ÷ 4 = 3', '{1/3} + 12 = 4']),
          sa('Divide. Then write the multiplication equation that checks your answer.\n2 ÷ {1/6}', ['Quotient:', 'Check:'], key='12; 12 × 1/6 = 2',
             note='Both parts are required.'),
          tf('6 ÷ {1/3} = 2 because 2 × {1/3} = 6.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.C.7 (multiply)
    S('3.OA.C.7', 'Multiply fluently within 100',
      main=[
          sa('Multiply.\n7 × 6', 'Product:', key='42'),
          sa('Multiply.\n9 × 8', 'Product:', key='72'),
          mc('6 × 8 = ?', ['48', '42', '54', '14']),
          tf('7 × 7 = 49', key=True),
          tf('8 × 4 = 36', key=False),
      ],
      back=[
          B('Add equal addends to find a total', '2.OA.C.4', [
              sa('Add the equal addends.\n4 + 4 + 4 + 4 + 4', 'Sum:', key='20'),
              tf('3 + 3 + 3 + 3 = 12', key=True),
              mc('5 + 5 + 5 = ?', ['15', '10', '20', '555']),
              sa('An array has 4 rows of 3 dots.\nHow many dots are there?', 'Dots:', key='12'),
              tf('2 + 2 + 2 + 2 + 2 = 12', key=False),
          ]),
          B('Add doubles within 20', '2.OA.B.2', [
              sa('Add.\n7 + 7', 'Sum:', key='14'),
              tf('9 + 9 = 18', key=True),
              mc('8 + 8 = ?', ['16', '15', '18', '88']),
              sa('Add.\n6 + 6', 'Sum:', key='12'),
              tf('5 + 5 = 11', key=False),
          ]),
      ],
      f1=B('Multiply a two-digit number by a one-digit number', '4.NBT.B.5', [
          sa('Multiply.\n7 × 46', 'Product:', key='322'),
          tf('8 × 29 = 232', key=True),
          mc('6 × 57 = ?', ['342', '302', '352', '63']),
          sa('Multiply.\n9 × 84', 'Product:', key='756'),
          tf('4 × 73 = 282', key=False),
      ]),
      f2=B('Multiply multi-digit whole numbers with the standard algorithm', '5.NBT.B.5', [
          work('Use the standard algorithm to multiply. Show your work.\n346 × 27', 'Product:', method=MUL_ALG, key='9,342'),
          sa('Multiply.\n58 × 64', 'Product:', key='3,712'),
          mc('214 × 35 = ?', ['7,490', '7,390', '1,712', '7,590']),
          tf('125 × 48 = 6,000', key=True),
          tf('63 × 47 = 2,861', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.C.7 (divide)
    S('3.OA.C.7', 'Divide fluently within 100',
      main=[
          sa('Divide.\n63 ÷ 7', 'Quotient:', key='9'),
          sa('Divide.\n48 ÷ 8', 'Quotient:', key='6'),
          mc('54 ÷ 6 = ?', ['9', '8', '48', '60']),
          tf('72 ÷ 9 = 8', key=True),
          tf('42 ÷ 6 = 8', key=False),
      ],
      back=[
          B('Subtract within 100', '2.NBT.B.5', [
              sa('Subtract.\n63 - 27', 'Difference:', key='36'),
              tf('80 - 35 = 45', key=True),
              mc('72 - 18 = ?', ['54', '64', '56', '90']),
              sa('Subtract.\n91 - 46', 'Difference:', key='45'),
              tf('50 - 22 = 38', key=False),
          ]),
          B('Split up to 20 objects into two equal groups', '2.OA.C.3', [
              sa('16 counters are split into 2 equal groups.\nHow many counters are in each group?', 'Counters:', key='8'),
              tf('20 objects make 2 equal groups of 10.', key=True),
              mc('14 objects are split into 2 equal groups.\nHow many objects are in each group?', ['7', '6', '12', '28']),
              sa('12 objects are split into 2 equal groups.\nHow many objects are in each group?', 'Objects:', key='6'),
              tf('18 objects make 2 equal groups of 8.', key=False),
          ]),
      ],
      f1=B('Divide by a one-digit number, with remainders', '4.NBT.B.6', [
          sa('Divide. Write the quotient and the remainder.\n58 ÷ 7', ['Quotient:', 'Remainder:'], key='8 R 2'),
          tf('76 ÷ 9 = 8 R 4', key=True),
          mc('Divide.\n93 ÷ 4', ['23 R 1', '23', '22 R 5', '24 R 1']),
          sa('Divide.\n87 ÷ 3', 'Quotient:', key='29'),
          tf('65 ÷ 8 = 7 R 9', key=False),
      ]),
      f2=B('Divide by a two-digit divisor', '5.NBT.B.6', [
          sa('Divide.\n864 ÷ 24', 'Quotient:', key='36'),
          tf('1,104 ÷ 46 = 24', key=True),
          mc('Divide.\n975 ÷ 39', ['25', '24', '26', '936']),
          sa('Divide. Write the quotient and the remainder.\n700 ÷ 32', ['Quotient:', 'Remainder:'], key='21 R 28'),
          tf('1,512 ÷ 27 = 54', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.C.7 (relationship)
    S('3.OA.C.7', 'Use the relationship between multiplication and division',
      main=[
          sa('Write the four facts in the fact family for 6, 9, and 54.', ['Facts:', ''], key='6 × 9 = 54, 9 × 6 = 54, 54 ÷ 6 = 9, 54 ÷ 9 = 6',
             note='All four facts are required, in any order.'),
          mc('7 × 8 = 56.\nWhich division fact is in the same fact family?', ['56 ÷ 7 = 8', '7 ÷ 56 = 8', '56 × 7 = 8', '8 ÷ 56 = 7']),
          tf('Because 4 × 9 = 36, you know that 36 ÷ 4 = 9.', key=True),
          sa('Use multiplication to check: is 63 ÷ 9 = 7 correct? Write the multiplication fact you used.', ['Correct?', 'Fact:'],
             key='Yes; 9 × 7 = 63', note='7 × 9 = 63 is also correct. Both parts are required.'),
          tf('Because 5 × 8 = 40, you know that 40 ÷ 8 = 4.', key=False),
      ],
      back=[
          B('Use the relationship between addition and subtraction within 20', '1.OA.C.6', [
              sa('Write the four facts in the fact family for 7, 8, and 15.', ['Facts:', ''], key='7 + 8 = 15, 8 + 7 = 15, 15 - 7 = 8, 15 - 8 = 7',
                 note='All four facts are required, in any order.'),
              tf('Because 9 + 4 = 13, you know that 13 - 4 = 9.', key=True),
              mc('6 + 5 = 11.\nWhich subtraction fact is in the same fact family?', ['11 - 5 = 6', '11 - 4 = 7', '5 - 6 = 11', '6 - 5 = 1']),
              sa('Is 16 - 7 = 9 correct? Write the addition fact you used to check.', ['Correct?', 'Fact:'], key='Yes; 7 + 9 = 16',
                 note='9 + 7 = 16 is also correct. Both parts are required.'),
              tf('Because 8 + 6 = 14, you know that 14 - 6 = 7.', key=False),
          ]),
          B('Subtract within 20 mentally', '2.OA.B.2', [
              sa('Subtract.\n17 - 9', 'Difference:', key='8'),
              tf('14 - 7 = 7', key=True),
              mc('12 - 5 = ?', ['7', '8', '6', '17']),
              sa('Subtract.\n13 - 8', 'Difference:', key='5'),
              tf('16 - 8 = 9', key=False),
          ]),
      ],
      f1=B('Use multiplication to check division, including remainders', '4.NBT.B.6', [
          sa('Check: is 47 ÷ 5 = 9 R 2 correct? Write the multiplication and addition you used.', ['Correct?', 'Check:'], key='Yes; 5 × 9 + 2 = 47',
             note='Both parts are required.'),
          tf('34 ÷ 6 = 5 R 4 because 6 × 5 + 4 = 34.', key=True),
          mc('Which equation shows that 75 ÷ 8 = 9 R 3?', ['8 × 9 + 3 = 75', '8 × 9 = 75', '9 × 3 + 8 = 75', '8 + 9 + 3 = 75']),
          sa('Use multiplication to check: is 96 ÷ 4 = 24 correct? Write the multiplication you used.', ['Correct?', 'Check:'],
             key='Yes; 4 × 24 = 96', note='24 × 4 = 96 is also correct. Both parts are required.'),
          tf('59 ÷ 7 = 8 R 2 because 7 × 8 + 2 = 59.', key=False),
      ]),
      f2=B('Divide a unit fraction by a whole number and check with multiplication', '5.NF.B.7.a', [
          sa('Find {1/3} ÷ 4. Then write the multiplication that checks it.', ['Quotient:', 'Check:'], key='1/12; 1/12 × 4 = 1/3',
             note='Both parts are required.'),
          tf('{1/2} ÷ 3 = {1/6} because {1/6} × 3 = {1/2}.', key=True),
          mc('Which equation checks {1/4} ÷ 2 = {1/8}?', ['{1/8} × 2 = {1/4}', '{1/4} × 2 = {1/8}', '{1/8} × {1/4} = 2', '2 × 4 = 8']),
          sa('Divide.\n{1/5} ÷ 2', 'Quotient:', key='1/10'),
          tf('{1/6} ÷ 2 = {1/3}', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.D.8 (solve)
    S('3.OA.D.8', 'Solve two-step word problems using the four operations',
      main=[
          sa('Mia has 4 bags with 6 marbles in each bag. She gives away 9 marbles.\nHow many marbles does she have left?', 'Marbles:', key='15 marbles',
             note='4 × 6 = 24 and 24 - 9 = 15.'),
          sa('A class has 27 students, and 3 more students join. The class is split into 5 equal teams.\nHow many students are on each team?',
             'Students:', key='6 students', note='27 + 3 = 30 and 30 ÷ 5 = 6.'),
          mc('Pens cost $3 each. Leo buys 7 pens and pays with a $50 bill.\nHow much change does he get?', ['$29', '$21', '$47', '$53']),
          tf('A farmer has 32 eggs. He packs them 8 to a carton and sells 2 cartons. He has 2 cartons left.', key=True),
          sa('Ana read 8 pages on Monday and 4 times as many pages on Tuesday.\nHow many pages did she read on the two days?', 'Pages:', key='40 pages',
             note='4 × 8 = 32 and 8 + 32 = 40.'),
      ],
      back=[
          B('One-step take-from word problems within 100', '2.OA.A.1', [
              sa('There were 72 people on a train. 26 got off.\nHow many people are still on the train?', 'People:', key='46'),
              tf('Kim had 90 cents and spent 45 cents. She has 45 cents left.', key=True),
              mc('A store had 60 hats and sold 34.\nHow many hats are left?', ['26', '94', '36', '34']),
              sa('A tree had 83 apples. 47 fell off.\nHow many apples are still on the tree?', 'Apples:', key='36'),
              tf('A box had 55 nails. 18 were used, so 47 are left.', key=False),
          ]),
          B('Find the total of equal rows by repeated addition', '2.OA.C.4', [
              sa('There are 4 rows of 5 chairs.\nUse repeated addition to find the number of chairs.', 'Chairs:', key='20',
                 note='5 + 5 + 5 + 5 = 20.'),
              tf('3 rows of 4 tiles is 4 + 4 + 4 = 12 tiles.', key=True),
              mc('There are 5 rows of 2 trees.\nWhich addition gives the total?', ['2 + 2 + 2 + 2 + 2', '5 + 2', '5 + 5', '2 + 5 + 2']),
              sa('There are 3 rows of 3 cups.\nHow many cups are there?', 'Cups:', key='9'),
              tf('2 rows of 4 desks is 4 + 2 = 6 desks.', key=False),
          ]),
      ],
      f1=B('Solve multistep word problems with whole numbers', '4.OA.A.3', [
          sa('A store gets 6 boxes of 48 cans. It sells 175 cans.\nHow many cans are left?', 'Cans:', key='113 cans'),
          tf('Tickets cost $12 for adults and $7 for children. 3 adults and 4 children pay $64 in all.', key=True),
          mc('A school has 4 classes of 26 students and 3 classes of 24 students.\nHow many students are in these classes?', ['176', '104', '72', '160']),
          sa('A library has 1,250 books. It buys 8 boxes of 35 books.\nHow many books does it have now?', 'Books:', key='1,530 books'),
          tf('Leo saves $15 a week for 6 weeks and then spends $38. He has $62 left.', key=False),
      ]),
      f2=B('Write expressions that record multistep calculations', '5.OA.A.2', [
          sa('Write an expression for: buy 4 packs of 12 pencils, then give away 9 pencils.', 'Expression:', key='4 × 12 - 9',
             note='(4 × 12) - 9 is also correct.'),
          mc('27 students are joined by 3 more, and then they are split into 5 equal teams.\nWhich expression matches?',
             ['(27 + 3) ÷ 5', '27 + 3 ÷ 5', '27 + (3 ÷ 5)', '5 ÷ (27 + 3)']),
          tf('The expression 50 - 3 × 7 gives the change from $50 after buying 7 pens that cost $3 each.', key=True),
          sa('Evaluate.\n(18 + 6) ÷ 4 × 3', 'Value:', key='18'),
          tf('The expression 8 + 4 × 8 has a value of 96.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.D.8 (represent)
    S('3.OA.D.8', 'Represent two-step word problems with an equation with a letter for the unknown',
      main=[
          sa('A baker makes 5 trays of 8 rolls. She sells 23 rolls.\nWrite an equation with a letter for the number of rolls left. Then solve it.',
             ['Equation:', 'Rolls left:'], key='r = 5 × 8 - 23; r = 17',
             note='Any equivalent equation with a letter for the unknown is correct. Both parts are required.'),
          mc('Sam has $40. He buys 3 books that cost $9 each.\nWhich equation gives the money he has left, m?',
             ['m = 40 - 3 × 9', 'm = 40 - 3 + 9', 'm = 3 × 9 - 40', 'm = 40 + 3 × 9']),
          sa('There are 36 cupcakes. 4 are eaten, and the rest are shared equally by 8 friends.\n'
             'Write an equation with a letter for each friend\'s share. Then solve it.', ['Equation:', 'Each friend:'],
             key='c = (36 - 4) ÷ 8; c = 4',
             note='Any equivalent equation with a letter for the unknown is correct. Both parts are required.'),
          tf('"Jo had 15 stickers and then got 6 packs of 5 stickers" can be written as s = 15 + 6 × 5, and s = 45.', key=True),
          tf('"7 boxes of 6 crayons, then 10 crayons are lost" can be written as c = 7 + 6 - 10.', key=False),
      ],
      back=[
          B('Write an equation with a symbol for the unknown in a one-step word problem', '2.OA.A.1', [
              sa('Ty had some marbles. He got 25 more and now has 61.\nWrite an equation with a symbol for the unknown.', 'Equation:', key='? + 25 = 61',
                 note='Any equation with a symbol for the unknown (such as m + 25 = 61 or 61 - 25 = m) is correct.'),
              tf('"44 ducks were on a pond, and 19 flew away" can be written as 44 - 19 = d.', key=True),
              mc('There are 28 red cars and some blue cars. There are 50 cars in all.\nWhich equation matches?',
                 ['28 + b = 50', '28 - b = 50', '50 + 28 = b', 'b - 50 = 28']),
              sa('A pole is 70 cm long. Lu cuts off some, and 42 cm is left.\nWrite an equation with a symbol for the unknown.', 'Equation:',
                 key='70 - ? = 42', note='70 - c = 42 and 42 + c = 70 are also correct.'),
              tf('"There were 36 books, and 12 more came" can be written as 36 - 12 = b.', key=False),
          ]),
          B('Subtract two-digit numbers within 100', '2.NBT.B.5', [
              sa('Subtract.\n70 - 34', 'Difference:', key='36'),
              tf('58 - 29 = 29', key=True),
              mc('84 - 47 = ?', ['37', '43', '47', '131']),
              sa('Subtract.\n65 - 38', 'Difference:', key='27'),
              tf('93 - 55 = 48', key=False),
          ]),
      ],
      f1=B('Write and solve equations with a letter for multistep problems', '4.OA.A.3', [
          sa('A club buys 6 packs of 15 cups and uses 58 cups.\nWrite an equation with a letter for the cups left. Then solve it.',
             ['Equation:', 'Cups left:'], key='c = 6 × 15 - 58; c = 32',
             note='Any equivalent equation with a letter is correct. Both parts are required.'),
          mc('A farmer has 120 eggs. She sells 7 cartons of 12 eggs.\nWhich equation gives the eggs left, e?',
             ['e = 120 - 7 × 12', 'e = 120 - 7 + 12', 'e = 7 × 12 - 120', 'e = 120 ÷ 7 × 12']),
          tf('After a $16 gift, the rest of the cost of a $96 bike is paid in 8 equal parts. This can be written as p = (96 - 16) ÷ 8, and p = 10.',
             key=True),
          sa('4 vans carry 12 students each, and 3 cars carry 5 students each.\nWrite an equation with a letter for the number of students. Then solve it.',
             ['Equation:', 'Students:'], key='s = 4 × 12 + 3 × 5; s = 63',
             note='Any equivalent equation with a letter is correct. Both parts are required.'),
          tf('"A hall has 250 seats, and 9 rows of 24 seats are filled" can be written as s = 250 - 9 + 24 for the empty seats.', key=False),
      ]),
      f2=B('Write and interpret numerical expressions without evaluating them', '5.OA.A.2', [
          sa('Write an expression for "3 times the difference of 40 and 12."', 'Expression:', key='3 × (40 - 12)'),
          tf('(24 + 16) ÷ 8 is one-eighth of 24 + 16.', key=True),
          mc('Without calculating, how does 5 × (92 - 17) compare with 92 - 17?', ['It is 5 times as large.', 'It is 5 more.', 'It is 5 less.', 'It is the same.']),
          sa('Write an expression for "add 15 and 9, then divide by 6."', 'Expression:', key='(15 + 9) ÷ 6'),
          tf('7 × (18 + 3) is 7 more than 18 + 3.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.D.8 (reasonableness)
    S('3.OA.D.8', 'Check whether answers are reasonable using mental computation and rounding',
      main=[
          sa('Round each number to the nearest ten to estimate 48 + 31.\nThen tell whether a sum of 79 is reasonable.', ['Estimate:', 'Reasonable?'],
             key='80; yes', note='50 + 30 = 80, which is close to 79. Both parts are required.'),
          sa('Leo says 412 - 189 = 323.\nRound each number to the nearest hundred to estimate. Is his answer reasonable?', ['Estimate:', 'Reasonable?'],
             key='200; no', note='400 - 200 = 200, which is far from 323 (the exact difference is 223). Both parts are required.'),
          mc('A store sold 296 shirts on Monday and 404 shirts on Tuesday.\nRounding each number to the nearest hundred, which is the estimate of the total?',
             ['700', '600', '800', '900']),
          tf('Rounding each number to the nearest ten, 62 + 27 is about 90.', key=True),
          tf('Rounding each number to the nearest hundred, 589 - 312 is about 200.', key=False),
      ],
      back=[
          B('Add or subtract 10 or 100 mentally', '2.NBT.B.8', [
              sa('What is 100 more than 453?', 'Answer:', key='553'),
              tf('10 less than 280 is 270.', key=True),
              mc('What is 100 less than 615?', ['515', '605', '715', '614']),
              sa('What is 10 more than 395?', 'Answer:', key='405'),
              tf('100 more than 860 is 870.', key=False),
          ]),
          B('Compare three-digit numbers', '2.NBT.A.4', [
              sa('Write >, =, or <.\n482 ___ 428', 'Symbol:', key='>'),
              tf('609 < 690', key=True),
              mc('Which number is greatest?', ['731', '713', '371', '317']),
              sa('Write >, =, or <.\n350 ___ 305', 'Symbol:', key='>'),
              tf('298 > 302', key=False),
          ]),
      ],
      f1=B('Use rounding to check answers to multistep problems', '4.OA.A.3', [
          sa('Ty says 6 × 48 - 95 = 193.\nRound 48 and 95 to the nearest ten. Estimate, then tell whether his answer is reasonable.',
             ['Estimate:', 'Reasonable?'], key='200; yes',
             note='6 × 50 - 100 = 200, which is close to 193 (the exact value is 193). Both parts are required.'),
          tf('Rounding each number to the nearest hundred, 1,212 + 389 is about 1,600.', key=True),
          mc('Rounding each number to the nearest ten, which is the estimate of 4 × 39 + 52?', ['210', '200', '160', '190']),
          sa('Round each number to the nearest thousand to estimate 6,814 - 2,390.', 'Estimate:', key='5,000',
             note='7,000 - 2,000 = 5,000. The exact difference, 4,424, is not the estimate asked for.'),
          tf('Rounding 21 to the nearest ten, 8 × 21 is about 240.', key=False),
      ]),
      f2=B('Round decimals to estimate sums, differences, and products', '5.NBT.A.4', [
          sa('Round each number to the nearest whole number. Then estimate.\n3.8 + 6.4', 'Estimate:', key='10'),
          tf('Rounding each number to the nearest whole number, 9.7 - 2.2 is about 8.', key=True),
          mc('Round each number to the nearest whole number.\nWhich is the estimate of 5.6 × 3.1?', ['18', '15', '20', '16']),
          sa('Round each number to the nearest whole number. Then estimate.\n7.4 × 2.8', 'Estimate:', key='21'),
          tf('Rounding each number to the nearest whole number, 12.4 + 3.7 is about 15.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.D.9 (identify)
    S('3.OA.D.9', 'Identify arithmetic patterns in the addition and multiplication tables',
      main=[
          tf('Every product in the 4s row of the multiplication table is even.', key=True),
          sa('The 5s row of the multiplication table is 5, 10, 15, 20, 25, ...\nWhat pattern do you see in the ones digits?', 'Pattern:',
             key='The ones digits alternate between 5 and 0.'),
          mc('In the 9s row of the multiplication table (9, 18, 27, 36, ...), what happens to the digits from one product to the next?',
             ['The tens digit goes up by 1 and the ones digit goes down by 1.', 'Both digits go up by 1.', 'Both digits go down by 1.',
              'The digits stay the same.']),
          sa('In the addition table, look at the sums 1 + 9, 2 + 8, 3 + 7, and 4 + 6.\nWhat do you notice?', 'Pattern:', key='Every sum is 10.',
             note='Any description saying all these sums are 10 (one addend goes up by 1 while the other goes down by 1) is correct.'),
          tf('Every product in the 3s row of the multiplication table is odd.', key=False),
      ],
      back=[
          B('Odd and even numbers up to 20', '2.OA.C.3', [
              sa('Is 17 odd or even?', 'Answer:', key='Odd'),
              tf('14 is even.', key=True),
              mc('Which number is odd?', ['19', '12', '16', '20']),
              sa('Write 14 as the sum of two equal addends.', 'Sum:', key='7 + 7'),
              tf('An odd number of objects can be put into two equal groups with none left over.', key=False),
          ]),
          B('Skip-count by 5s, 10s, and 100s and see patterns', '2.NBT.A.2', [
              sa('Skip-count by 10s from 230.\n230, 240, 250, ___, ___', 'Next two:', key='260, 270'),
              tf('When you skip-count by 5s from 5, every number ends in 5 or 0.', key=True),
              mc('What comes next?\n400, 500, 600, ___', ['700', '610', '601', '800']),
              sa('Skip-count by 5s from 65.\n65, 70, 75, ___, ___', 'Next two:', key='80, 85'),
              tf('When you skip-count by 10s from 7, every number ends in 0.', key=False),
          ]),
      ],
      f1=B('Generate a pattern from a rule and identify its features', '4.OA.C.5', [
          sa('The rule is "add 6," starting at 3.\nWrite the first five terms.', 'Terms:', key='3, 9, 15, 21, 27'),
          tf('The rule "add 4," starting at 1, makes only odd numbers.', key=True),
          mc('The rule is "multiply by 2," starting at 5.\nWhat is the 4th term?', ['40', '20', '13', '80']),
          sa('The rule is "add 5," starting at 2: 2, 7, 12, 17, ...\nWhat do you notice about the ones digits?', 'Pattern:',
             key='They alternate between 2 and 7.'),
          tf('The rule "add 3," starting at 4, makes only even numbers.', key=False),
      ]),
      f2=B('Generate two numerical patterns and compare their terms', '5.OA.B.3', [
          sa('Pattern A starts at 0 and adds 3. Pattern B starts at 0 and adds 6.\nWrite the first four terms of each pattern.',
             ['Pattern A:', 'Pattern B:'], key='0, 3, 6, 9; 0, 6, 12, 18'),
          tf('Pattern A starts at 0 and adds 5. Pattern B starts at 0 and adds 10. Each term of B is 2 times the matching term of A.', key=True),
          mc('Pattern A: 0, 4, 8, 12. Pattern B: 0, 12, 24, 36.\nHow does each B term compare with the matching A term?',
             ['It is 3 times as large.', 'It is 8 more.', 'It is 4 times as large.', 'It is the same.']),
          sa('Pattern A starts at 0 and adds 2. Pattern B starts at 0 and adds 8.\nWhat is the B term when the A term is 10?', 'B term:', key='40'),
          tf('Pattern A: 0, 2, 4, 6. Pattern B: 0, 6, 12, 18. Each B term is 4 more than the matching A term.', key=False),
      ])),

    # ------------------------------------------------------------------ 3.OA.D.9 (explain)
    S('3.OA.D.9', 'Explain arithmetic patterns using properties of operations',
      main=[
          sa('Explain why 4 times any whole number is always even.', ['Explanation:', ''],
             key='4 times a number is 2 times (2 times the number), so it can always be split into two equal groups.',
             note='Any correct reason using equal groups, doubling, or 4 × n = 2 × (2 × n) is correct.'),
          mc('Why is every product in the 6s row of the multiplication table even?',
             ['6 = 2 × 3, so each product is 2 times a number.', '6 is greater than 5.', 'The 6s row has 10 products.', 'Every number is even.']),
          tf('The sum of two even numbers is always even.', key=True),
          sa('Is the product of two odd numbers odd or even? Give an example.', ['Answer:', 'Example:'], key='Odd; 3 × 5 = 15',
             note='Any correct example of two odd factors with an odd product is correct. Both parts are required.'),
          tf('An odd number times 2 is always odd.', key=False),
      ],
      back=[
          B('Explain why a number is even or odd', '2.OA.C.3', [
              sa('Explain why 12 is even.', ['Explanation:', ''], key='12 = 6 + 6, so it is the sum of two equal addends (it splits into 2 equal groups).'),
              tf('An even number can be written as the sum of two equal addends.', key=True),
              mc('Which equation shows that 10 is even?', ['10 = 5 + 5', '10 = 7 + 3', '10 = 9 + 1', '10 = 10 + 0']),
              sa('Is 15 even or odd? Explain.', ['Answer:', 'Explanation:'], key='Odd',
                 note='15 cannot be split into two equal groups: in pairs, one is left over. Both parts are required.'),
              tf('7 can be written as the sum of two equal whole-number addends.', key=False),
          ]),
          B('Explain that addends can be added in any order', '1.OA.B.3', [
              sa('Explain why 6 + 9 = 9 + 6.', ['Explanation:', ''], key='Changing the order of the addends does not change the sum.'),
              tf('5 + 8 = 8 + 5', key=True),
              mc('Which equation shows adding in a different order?', ['4 + 7 = 7 + 4', '4 + 7 = 4 - 7', '4 + 7 = 47', '4 + 7 = 7 - 4']),
              sa('9 + 3 = 12.\nWhat is 3 + 9?', 'Sum:', key='12'),
              tf('8 + 2 = 2 + 6', key=False),
          ]),
      ],
      f1=B('Explain features of a number pattern', '4.OA.C.5', [
          sa('The rule is "add 4," starting at 2: 2, 6, 10, 14, ...\nWhy is every term even?', ['Explanation:', ''],
             key='It starts at an even number, and adding an even number (4) to an even number always gives an even number.'),
          tf('The rule "add 5," starting at 1, makes terms that go odd, even, odd, even.', key=True),
          mc('The rule is "add 10," starting at 3.\nWhy does every term end in 3?',
             ['Adding 10 does not change the ones digit.', '10 is even.', '3 is odd.', 'The terms get larger.']),
          sa('The rule is "multiply by 3," starting at 1: 1, 3, 9, 27, ...\nAre the terms odd or even? Explain.', ['Answer:', 'Explanation:'], key='Odd',
             note='The pattern starts at an odd number, and an odd number times 3 (an odd number) is odd. Both parts are required.'),
          tf('The rule "add 2," starting at 5, makes only even numbers.', key=False),
      ]),
      f2=B('Explain the relationship between two numerical patterns', '5.OA.B.3', [
          sa('Pattern A starts at 0 and adds 2. Pattern B starts at 0 and adds 6.\nExplain why each B term is 3 times the matching A term.',
             ['Explanation:', ''], key='Both start at 0 and take the same number of steps, and B adds 3 times as much (6 = 3 × 2) at each step.',
             note='Must connect the rule amounts (6 = 3 × 2) with the same start of 0 and the same number of steps.'),
          tf('Pattern A starts at 0 and adds 5. Pattern B starts at 0 and adds 15. Each B term is 3 times the matching A term.', key=True),
          mc('Pattern A starts at 1 and adds 1. Pattern B starts at 1 and adds 2.\nWhy is B NOT always 2 times A?',
             ['They both start at 1, not at 0.', 'B adds less than A.', 'A has more terms.', 'Both rules add.']),
          sa('Pattern A starts at 0 and adds 4. Pattern B starts at 0 and adds 12.\nWhat is the A term when the B term is 36?', 'A term:', key='12'),
          tf('Pattern A starts at 0 and adds 3. Pattern B starts at 0 and adds 9. Each B term is 6 more than the matching A term.', key=False),
      ])),
]
