"""Distinct Grade 5 requirements and the set whose MAIN section focuses on each (for COVERAGE.md)."""
REQUIREMENTS = [
    ('5.OA.A.1', 'Use parentheses in numerical expressions and evaluate them', [1]),
    ('5.OA.A.1', 'Use brackets and braces and evaluate the expressions', [2]),
    ('5.OA.A.1', 'Place grouping symbols to make an equation true', [3]),
    ('5.OA.A.2', 'Write simple expressions that record calculations with numbers', [4]),
    ('5.OA.A.2', 'Interpret numerical expressions without evaluating them', [5]),
    ('5.OA.B.3', 'Generate two numerical patterns from two given rules', [6]),
    ('5.OA.B.3', 'Identify apparent relationships between corresponding terms and explain informally why', [58]),
    ('5.OA.B.3', 'Form ordered pairs from corresponding terms and graph them', [7]),
    ('5.NBT.A.1', 'A digit is worth 10 times as much as the same digit one place to its right', [8]),
    ('5.NBT.A.1', 'A digit is worth 1/10 of what it represents one place to its left', [9]),
    ('5.NBT.A.2', 'Multiply and divide whole numbers by powers of 10; use whole-number exponents for powers of 10', [10]),
    ('5.NBT.A.2', 'Place the decimal point when a decimal is multiplied or divided by a power of 10', [11]),
    ('5.NBT.A.2', 'Explain the patterns in the number of zeros and in the placement of the decimal point', [59]),
    ('5.NBT.A.3.a', 'Read and write decimals to thousandths with numerals and number names', [12]),
    ('5.NBT.A.3.a', 'Read and write decimals to thousandths in expanded form', [13]),
    ('5.NBT.A.3.b', 'Compare two decimals to thousandths with >, =, <', [14]),
    ('5.NBT.A.4', 'Use place value to round decimals to any place', [15]),
    ('5.NBT.B.5', 'Multiply multi-digit whole numbers using the standard algorithm (method graded)', [16]),
    ('5.NBT.B.6', 'Find whole-number quotients with up to four-digit dividends and two-digit divisors', [17]),
    ('5.NBT.B.6', 'Illustrate and explain division with equations and area models (representation graded)', [18, 60]),
    ('5.NBT.B.7', 'Add decimals to hundredths', [19]),
    ('5.NBT.B.7', 'Subtract decimals to hundredths', [61]),
    ('5.NBT.B.7', 'Use concrete models or drawings and place value for adding and subtracting decimals; explain the reasoning', [62]),
    ('5.NBT.B.7', 'Multiply decimals to hundredths', [20]),
    ('5.NBT.B.7', 'Use models and place value for multiplying decimals; explain the reasoning', [63]),
    ('5.NBT.B.7', 'Divide decimals to hundredths', [21]),
    ('5.NBT.B.7', 'Use models and place value for dividing decimals; explain the reasoning', [64]),
    ('5.NBT.B.7', 'Solve problems with decimal operations', [22]),
    ('5.NF.A.1', 'Add fractions with unlike denominators', [23]),
    ('5.NF.A.1', 'Subtract fractions with unlike denominators', [24]),
    ('5.NF.A.1', 'Add mixed numbers with unlike denominators', [25]),
    ('5.NF.A.1', 'Subtract mixed numbers with unlike denominators', [65]),
    ('5.NF.A.2', 'Solve word problems that add and subtract fractions', [26]),
    ('5.NF.A.2', 'Use benchmark fractions and number sense to estimate and assess reasonableness', [27]),
    ('5.NF.B.3', 'Interpret a fraction as division of the numerator by the denominator', [28]),
    ('5.NF.B.3', 'Solve sharing word problems whose answers are fractions or mixed numbers', [29]),
    ('5.NF.B.4.a', 'Multiply a fraction by a whole number', [30]),
    ('5.NF.B.4.a', 'Multiply a fraction by a fraction', [31]),
    ('5.NF.B.4.a', 'Interpret (a/b) × q with a visual fraction model (tape diagrams, area models)', [66]),
    ('5.NF.B.4.b', 'Find the area of a rectangle with fractional side lengths', [32]),
    ('5.NF.B.4.b', 'Tile the rectangle with unit-fraction squares and show the tiling gives the same area as multiplying', [67]),
    ('5.NF.B.5.a', 'Compare the size of a product to one factor without multiplying', [33]),
    ('5.NF.B.5.b', 'Explain why multiplying by a fraction greater than 1, less than 1, or equal to 1 changes the size as it does', [34]),
    ('5.NF.B.5.b', 'Relate equivalent fractions to multiplying by a fraction equal to 1', [68]),
    ('5.NF.B.6', 'Solve real-world problems by multiplying fractions and mixed numbers', [35, 36]),
    ('5.NF.B.7.a', 'Divide a unit fraction by a whole number', [37]),
    ('5.NF.B.7.a', 'Use a visual model and the relationship to multiplication to explain the quotient', [69]),
    ('5.NF.B.7.b', 'Divide a whole number by a unit fraction', [38]),
    ('5.NF.B.7.b', 'Use a visual model and the relationship to multiplication to explain the quotient', [70]),
    ('5.NF.B.7.c', 'Solve real-world problems dividing unit fractions and whole numbers', [39]),
    ('5.MD.A.1', 'Convert from a larger to a smaller unit within one system', [40]),
    ('5.MD.A.1', 'Convert from a smaller to a larger unit within one system', [41]),
    ('5.MD.A.1', 'Use conversions in multistep real-world problems', [42]),
    ('5.MD.B.2', 'Make a line plot of measurements in fractions of a unit', [43]),
    ('5.MD.B.2', 'Use operations on fractions to solve problems with line plot data', [44]),
    ('5.MD.C.3.a', 'A unit cube has one cubic unit of volume', [45]),
    ('5.MD.C.3.b', 'A solid packed with n unit cubes without gaps or overlaps has a volume of n cubic units', [46]),
    ('5.MD.C.4', 'Measure volume by counting unit cubes', [47]),
    ('5.MD.C.5.a', 'Relate packing with unit cubes to V = l × w × h and V = b × h', [48]),
    ('5.MD.C.5.b', 'Apply V = l × w × h and V = b × h to real-world problems', [49]),
    ('5.MD.C.5.b', 'Find a missing dimension when the volume is known', [50]),
    ('5.MD.C.5.c', 'Find the volume of a figure made of two non-overlapping rectangular prisms', [51]),
    ('5.G.A.1', 'Understand the coordinate system: axes, origin, and ordered pairs', [52]),
    ('5.G.A.2', 'Graph points in the first quadrant', [53]),
    ('5.G.A.2', 'Solve real-world problems by graphing points and interpreting coordinates', [54]),
    ('5.G.B.3', 'Attributes of a category belong to all its subcategories', [55]),
    ('5.G.B.4', 'Classify quadrilaterals in a hierarchy based on properties', [56]),
    ('5.G.B.4', 'Classify triangles by sides and angles', [57]),
    ('5.G.B.4', 'Place triangle categories and subcategories in a hierarchy', [71]),
]
