from qb import S, B, sa, mc, tf, table, plot
from common import grid, tplot

SETS = [
    # ------------------------------------------------------------------ 5.OA.A.1 (parentheses)
    S('5.OA.A.1', 'Evaluate expressions that use parentheses',
      main=[
          sa('Evaluate.\n6 × (8 + 5)', 'Value:', key='78'),
          sa('Evaluate.\n(35 - 11) ÷ 4', 'Value:', key='6'),
          sa('Evaluate.\n50 - (6 × 7)', 'Value:', key='8'),
          mc('Evaluate.\n3 + (24 ÷ 6) × 5', ['23', '35', '27', '135']),
          sa('Evaluate.\n(9 + 3) × (10 - 4)', 'Value:', key='72'),
      ],
      back=[
          B('Do the work in parentheses first', '3.OA.D.8', [
              tf('In 4 × (2 + 5), you add 2 + 5 first.', key=True),
              sa('Evaluate.\n(6 + 4) × 2', 'Value:', key='20'),
              mc('Which step comes first in 18 - (3 × 4)?', ['Multiply 3 × 4', 'Subtract 18 - 3', 'Subtract 18 - 4', 'Add 3 + 4']),
              sa('Evaluate.\n20 - (5 + 5)', 'Value:', key='10'),
              tf('(10 - 4) + 3 = 10 - 7', key=False),
          ]),
          B('Multiplication and division facts', '3.OA.C.7', [
              sa('Multiply.\n7 × 8', 'Product:', key='56'),
              sa('Divide.\n24 ÷ 6', 'Quotient:', key='4'),
              tf('9 × 7 = 56', key=False),
              mc('48 ÷ 8 = ?', ['6', '7', '8', '5']),
              sa('Multiply.\n3 × 9', 'Product:', key='27'),
          ]),
          B('Adding and subtracting multi-digit numbers', '4.NBT.B.4', [
              sa('Add.\n348 + 275', 'Sum:', key='623'),
              sa('Subtract.\n502 - 168', 'Difference:', key='334'),
              tf('1,250 - 375 = 985', key=False),
              mc('609 + 194 = ?', ['803', '793', '813', '703']),
              sa('Subtract.\n1,000 - 432', 'Difference:', key='568'),
          ]),
      ],
      f1=B('Evaluate expressions with variables', '6.EE.A.2.c', [
          sa('Evaluate 4(x + 3) when x = 5.', 'Value:', key='32'),
          sa('Evaluate 20 - 2y when y = 6.', 'Value:', key='8'),
          mc('Evaluate (a + b) ÷ 3 when a = 10 and b = 8.', ['6', '4', '9', '54']),
          sa('Evaluate 3m + 2 when m = 7.', 'Value:', key='23'),
          tf('When n = 4, the value of 5(n - 1) is 19.', key=False),
      ]),
      f2=B('Evaluate expressions with negative numbers', '7.NS.A.3', [
          sa('Find the value.\n-3 × (4 - 9)', 'Value:', key='15'),
          sa('Find the value.\n(-12 + 4) ÷ 2', 'Value:', key='-4'),
          mc('Find the value.\n6 - (2 - 10)', ['14', '-2', '2', '18']),
          sa('Find the value.\n(-5) × (-2) + (-7)', 'Value:', key='3'),
          tf('(-20) ÷ (3 + 2) = 4', key=False),
      ])),

    # ------------------------------------------------------------------ 5.OA.A.1 (brackets, braces)
    S('5.OA.A.1', 'Evaluate expressions with brackets and braces',
      main=[
          sa('Evaluate.\n2 × [5 + (3 × 4)]', 'Value:', key='34'),
          sa('Evaluate.\n[20 - (2 + 6)] ÷ 3', 'Value:', key='4'),
          mc('Evaluate.\n4 × {3 + [10 - (2 × 4)]}', ['20', '44', '36', '26']),
          sa('Evaluate.\n60 ÷ [3 × (7 - 5)]', 'Value:', key='10'),
          sa('Evaluate.\n{18 - [2 × (4 + 1)]} + 9', 'Value:', key='17'),
      ],
      back=[
          B('Do the work in parentheses first', '3.OA.D.8', [
              sa('Evaluate.\n(12 - 5) × 3', 'Value:', key='21'),
              tf('In (8 + 2) ÷ 5, you divide 2 ÷ 5 first.', key=False),
              mc('Evaluate.\n4 × (9 - 6)', ['12', '30', '33', '10']),
              sa('Evaluate.\n30 ÷ (2 + 4)', 'Value:', key='5'),
              tf('(3 + 5) × 2 = 16', key=True),
          ]),
          B('Multiplication and division facts', '3.OA.C.7', [
              sa('Multiply.\n8 × 6', 'Product:', key='48'),
              sa('Divide.\n56 ÷ 7', 'Quotient:', key='8'),
              tf('36 ÷ 4 = 8', key=False),
              mc('7 × 9 = ?', ['63', '56', '72', '49']),
              sa('Divide.\n81 ÷ 9', 'Quotient:', key='9'),
          ]),
          B('Adding and subtracting within 100', '2.NBT.B.5', [
              sa('Add.\n46 + 37', 'Sum:', key='83'),
              sa('Subtract.\n72 - 28', 'Difference:', key='44'),
              tf('55 + 29 = 74', key=False),
              mc('90 - 47 = ?', ['43', '53', '47', '33']),
              sa('Add.\n38 + 54', 'Sum:', key='92'),
          ]),
      ],
      f1=B('Evaluate expressions with whole-number exponents', '6.EE.A.1', [
          sa('Evaluate.\n2 × (3 + 1)²', 'Value:', key='32'),
          sa('Evaluate.\n[10 - 2³] × 5', 'Value:', key='10'),
          mc('Evaluate.\n4² - (6 + 2)', ['8', '0', '24', '2']),
          sa('Evaluate.\n(5² - 1) ÷ 6', 'Value:', key='4'),
          tf('3 × 2² = 36', key=False),
      ]),
      f2=B('Grouping symbols with negative numbers', '7.NS.A.3', [
          sa('Find the value.\n2 × [-3 + (8 ÷ (-4))]', 'Value:', key='-10'),
          sa('Find the value.\n[(-6) + 15] ÷ (-3)', 'Value:', key='-3'),
          mc('Find the value.\n-4 × [5 - (-1)]', ['-24', '-16', '16', '24']),
          sa('Find the value.\n{10 - [2 × (-3)]} ÷ 4', 'Value:', key='4'),
          tf('[-8 - (-2)] × 3 = -30', key=False),
      ])),

    # ------------------------------------------------------------------ 5.OA.A.1 (place grouping symbols)
    S('5.OA.A.1', 'Place grouping symbols to make an equation true',
      main=[
          sa('Insert parentheses to make the equation true.\n4 + 6 × 3 = 30', 'Equation:', key='(4 + 6) × 3 = 30'),
          sa('Insert parentheses to make the equation true.\n20 - 8 - 2 = 14', 'Equation:', key='20 - (8 - 2) = 14'),
          mc('Which placement of parentheses makes the equation true?\n2 × 5 + 3 × 4 = 52',
             ['(2 × 5 + 3) × 4 = 52', '2 × (5 + 3) × 4 = 52', '2 × 5 + (3 × 4) = 52', '2 × (5 + 3 × 4) = 52']),
          sa('Insert parentheses to make the equation true.\n36 ÷ 6 - 2 = 9', 'Equation:', key='36 ÷ (6 - 2) = 9'),
          sa('Insert brackets and parentheses to make the equation true.\n2 × 9 - 3 + 1 = 10', 'Equation:',
             key='2 × [9 - (3 + 1)] = 10'),
      ],
      back=[
          B('Do the work in parentheses first', '3.OA.D.8', [
              sa('Evaluate.\n(4 + 6) × 3', 'Value:', key='30'),
              sa('Evaluate.\n4 + (6 × 3)', 'Value:', key='22'),
              tf('(20 - 8) - 2 = 20 - (8 - 2)', key=False),
              mc('Evaluate.\n36 ÷ (6 - 2)', ['9', '4', '34', '7']),
              sa('Evaluate.\n(36 ÷ 6) - 2', 'Value:', key='4'),
          ]),
          B('When regrouping keeps the same value', '3.OA.B.5', [
              tf('(2 × 3) × 4 = 2 × (3 × 4)', key=True),
              tf('(12 ÷ 6) ÷ 2 = 12 ÷ (6 ÷ 2)', key=False),
              mc('Which equation is true?', ['(5 + 2) + 3 = 5 + (2 + 3)', '(9 - 4) - 1 = 9 - (4 - 1)',
                                             '(16 ÷ 4) ÷ 2 = 16 ÷ (4 ÷ 2)', '(7 - 3) - 2 = 7 - (3 - 2)']),
              tf('4 × (5 × 2) = (4 × 5) × 2', key=True),
              sa('Fill in the blank.\n(6 × 2) × 5 = 6 × (2 × ___)', 'Blank:', key='5'),
          ]),
          B('Multiplication and division facts', '3.OA.C.7', [
              sa('Multiply.\n9 × 4', 'Product:', key='36'),
              sa('Divide.\n42 ÷ 6', 'Quotient:', key='7'),
              tf('8 × 7 = 54', key=False),
              mc('64 ÷ 8 = ?', ['8', '9', '7', '6']),
              sa('Multiply.\n6 × 7', 'Product:', key='42'),
          ]),
      ],
      f1=B('Use parentheses to write equivalent expressions', '6.EE.A.3', [
          sa('Expand.\n3(x + 5)', 'Expression:', key='3x + 15'),
          sa('Expand.\n4(2y - 1)', 'Expression:', key='8y - 4'),
          mc('Which expression is equivalent to 6(a + 2)?', ['6a + 12', '6a + 2', 'a + 12', '8a']),
          sa('Factor.\n5m + 20', 'Expression:', key='5(m + 4)'),
          tf('2(x + 7) = 2x + 7', key=False),
      ]),
      f2=B('Expand and factor expressions with rational coefficients', '7.EE.A.1', [
          sa('Expand.\n-2(3x - 4)', 'Expression:', key='-6x + 8'),
          sa('Expand.\n{1/2}(6y + 10)', 'Expression:', key='3y + 5'),
          mc('Which expression is equivalent to -5(n + 2)?', ['-5n - 10', '-5n + 2', '-5n + 10', '5n - 10']),
          sa('Factor out 3.\n3x - 12', 'Expression:', key='3(x - 4)'),
          tf('0.5(4a - 8) = 2a - 8', key=False),
      ])),

    # ------------------------------------------------------------------ 5.OA.A.2 (write)
    S('5.OA.A.2', 'Write numerical expressions from words',
      main=[
          sa('Write an expression for "add 9 and 6, then multiply by 4."', 'Expression:', key='(9 + 6) × 4',
             note='4 × (9 + 6) is also correct. Parentheses are required.'),
          sa('Write an expression for "subtract 5 from 30, then divide by 5."', 'Expression:', key='(30 - 5) ÷ 5',
             note='Parentheses are required.'),
          mc('Which expression shows "triple the sum of 12 and 8"?', ['3 × (12 + 8)', '3 × 12 + 8', '12 + 8 × 3', '(3 + 12) × 8']),
          sa('Write an expression for "divide 40 by 8, then add 7."', 'Expression:', key='(40 ÷ 8) + 7',
             note='40 ÷ 8 + 7 is also correct.'),
          sa('Write an expression for "the product of 6 and the difference of 15 and 9."', 'Expression:',
             key='6 × (15 - 9)', note='(15 - 9) × 6 is also correct.'),
      ],
      back=[
          B('Products as equal groups', '3.OA.A.1', [
              tf('5 × 7 can mean 5 groups of 7.', key=True),
              mc('Which expression shows 4 groups of 6?', ['4 × 6', '4 + 6', '6 - 4', '46']),
              sa('Write a multiplication expression for 8 groups of 3.', 'Expression:', key='8 × 3'),
              tf('3 + 3 + 3 + 3 = 3 × 3', key=False),
              sa('What is the product of 7 and 5?', 'Product:', key='35'),
          ]),
          B('Quotients as equal shares', '3.OA.A.2', [
              tf('15 ÷ 3 can mean 15 shared equally into 3 groups.', key=True),
              mc('Which expression shows 20 apples shared equally among 4 bags?', ['20 ÷ 4', '20 × 4', '20 - 4', '4 ÷ 20']),
              sa('What is the quotient of 18 and 6?', 'Quotient:', key='3'),
              sa('Write a division expression for 32 split into groups of 8.', 'Expression:', key='32 ÷ 8'),
              tf('The quotient of 12 and 2 is 24.', key=False),
          ]),
          B('Sums and differences', '2.OA.A.1', [
              sa('What is the sum of 14 and 9?', 'Sum:', key='23'),
              sa('What is the difference of 20 and 7?', 'Difference:', key='13'),
              tf('The difference of 15 and 6 is 21.', key=False),
              mc('Which word names the answer to an addition problem?', ['Sum', 'Product', 'Quotient', 'Difference']),
              sa('Write an expression for "7 more than 25."', 'Expression:', key='25 + 7', note='7 + 25 is also correct.'),
          ]),
      ],
      f1=B('Write expressions with variables', '6.EE.A.2.a', [
          sa('Write an expression for "the sum of n and 8, times 3."', 'Expression:', key='3(n + 8)'),
          sa('Write an expression for "y divided by 5, then minus 2."', 'Expression:', key='y ÷ 5 - 2',
             note='y/5 - 2 is also correct.'),
          mc('Which expression means "4 less than the product of 2 and x"?', ['2x - 4', '4 - 2x', '2(x - 4)', '2 + x - 4']),
          sa('Write an expression for "twice the difference of m and 6."', 'Expression:', key='2(m - 6)'),
          tf('"9 more than k" can be written as k + 9.', key=True),
      ]),
      f2=B('Write and solve equations from words', '7.EE.B.4.a', [
          sa('Three times the sum of a number and 4 is 27.\nWrite and solve an equation to find the number.', 'Equation and solution:',
             key='3(n + 4) = 27; n = 5'),
          sa('Half of a number, minus 6, is 10.\nWrite and solve an equation to find the number.', 'Equation and solution:',
             key='(1/2)n - 6 = 10; n = 32'),
          mc('Which equation represents "2 less than 5 times a number is 33"?', ['5n - 2 = 33', '2 - 5n = 33', '5(n - 2) = 33', '5n + 2 = 33']),
          sa('A number divided by 4, plus 3, is 9.\nWrite and solve an equation to find the number.', 'Equation and solution:',
             key='n ÷ 4 + 3 = 9; n = 24'),
          tf('The solution of 2(x + 3) = 18 is x = 7.', key=False),
      ])),

    # ------------------------------------------------------------------ 5.OA.A.2 (interpret)
    S('5.OA.A.2', 'Interpret numerical expressions without evaluating them',
      main=[
          mc('How does 4 × (563 + 218) compare to 563 + 218?',
             ['It is 4 times as large.', 'It is 4 more.', 'It is 4 less.', 'It is one-fourth as large.']),
          tf('(7,215 - 1,005) ÷ 5 is one-fifth as large as 7,215 - 1,005.', key=True),
          sa('Without calculating, how many times as large is 9 × (48 + 27) as 48 + 27?', 'Times as large:', key='9'),
          mc('Which expression is twice as large as 356 × 12?', ['2 × (356 × 12)', '356 × 12 + 2', '356 × 14', '(356 + 2) × 12']),
          tf('6 × 25 + 4 is 6 times as large as 25 + 4.', key=False),
      ],
      back=[
          B('Multiplicative comparison', '4.OA.A.1', [
              tf('35 is 5 times as many as 7.', key=True),
              sa('Fill in the blank.\n48 is ___ times as many as 6.', 'Blank:', key='8'),
              mc('Which equation shows "36 is 4 times as many as 9"?', ['36 = 4 × 9', '36 = 4 + 9', '9 = 4 × 36', '36 - 9 = 4']),
              tf('30 is 3 times as many as 27.', key=False),
              sa('Tom has 6 cards. Ana has 3 times as many cards.\nHow many cards does Ana have?', 'Cards:', key='18'),
          ]),
          B('Groups of a sum', '3.OA.A.1', [
              tf('3 × (4 + 1) means 3 groups of (4 + 1).', key=True),
              mc('Which expression means 6 groups of (10 + 2)?', ['6 × (10 + 2)', '6 + (10 + 2)', '6 × 10 + 2', '(6 + 10) × 2']),
              sa('How many groups of (5 + 4) are in 7 × (5 + 4)?', 'Groups:', key='7'),
              tf('2 × (8 + 1) = (8 + 1) + 2', key=False),
              sa('Write 4 groups of 9 as a multiplication expression.', 'Expression:', key='4 × 9'),
          ]),
          B('Equal shares', '3.OA.A.2', [
              tf('12 shared equally among 3 people is 4 each.', key=True),
              sa('A 20-inch ribbon is cut into 5 equal pieces.\nHow long is each piece?', 'Length:', key='4 inches'),
              mc('Which expression finds one of 4 equal shares of 28?', ['28 ÷ 4', '28 × 4', '28 - 4', '4 ÷ 28']),
              tf('Dividing a number by 2 splits it into 2 equal shares.', key=True),
              sa('30 crayons are shared equally among 6 children.\nHow many crayons does each child get?', 'Crayons:', key='5'),
          ]),
      ],
      f1=B('Identify parts of an expression', '6.EE.A.2.b', [
          mc('In 5(x + 2), what is 5?', ['A factor', 'A sum', 'A quotient', 'A term of x + 2']),
          sa('How many terms are in 4a + 7b - 1?', 'Terms:', key='3'),
          sa('What is the coefficient of m in 9m + 4?', 'Coefficient:', key='9'),
          tf('In 3(y + 6), the quantity (y + 6) is a sum of two terms.', key=True),
          mc('What is the expression 12 ÷ (n + 1) called?', ['A quotient', 'A sum', 'A product', 'A coefficient']),
      ]),
      f2=B('Rewrite expressions to show how quantities are related', '7.EE.A.2', [
          mc('A price p is increased by 5%.\nWhich expression shows the new price?', ['1.05p', '0.05p', 'p + 5', '5p']),
          tf('x + 0.3x = 0.4x', key=False),
          sa('Write n - 0.4n as one term.', 'Expression:', key='0.6n'),
          mc('Which expression is equivalent to 2(3t)?', ['6t', '5t', '2t + 3t', '3t + 2']),
          sa('A sale price is 0.75p, where p is the original price.\nWhat percent of the original price is taken off?', 'Percent:', key='25%'),
      ])),

    # ------------------------------------------------------------------ 5.OA.B.3 (patterns)
    S('5.OA.B.3', 'Generate two numerical patterns and compare their terms',
      main=[
          sa('Pattern A starts at 0 and adds 3.\nPattern B starts at 0 and adds 6.\nWrite the first 5 terms of each pattern.',
             ['Pattern A:', 'Pattern B:'], key='Pattern A: 0, 3, 6, 9, 12; Pattern B: 0, 6, 12, 18, 24'),
          mc('Pattern A: 0, 4, 8, 12, 16\nPattern B: 0, 12, 24, 36, 48\nHow does each term in Pattern B compare to the matching term in Pattern A?',
             ['3 times as large', '8 more', '4 times as large', '12 more']),
          sa('Pattern A starts at 0 and adds 5. Pattern B starts at 0 and adds 10.\nWhat is the 6th term of each pattern?',
             ['Pattern A:', 'Pattern B:'], key='Pattern A: 25; Pattern B: 50'),
          tf('Pattern A starts at 0 and adds 2. Pattern B starts at 0 and adds 8. Each term in Pattern B is 4 times the matching term in Pattern A.', key=True),
          sa('Pattern A starts at 0 and adds 7. Pattern B starts at 0 and adds 21.\nWhen Pattern A is 28, what is the matching term in Pattern B?',
             'Term:', key='84'),
      ],
      back=[
          B('Patterns that follow a rule', '4.OA.C.5', [
              sa('The rule is "add 6." The pattern starts at 0.\nWrite the first five terms.', 'Terms:', key='0, 6, 12, 18, 24'),
              tf('The rule "add 4," starting at 0, gives 0, 4, 8, 16.', key=False),
              mc('What is the rule for the pattern?\n0, 9, 18, 27, 36', ['Add 9', 'Add 8', 'Multiply by 9', 'Add 18']),
              sa('The rule is "add 11." The pattern starts at 0.\nWhat is the 4th term?', 'Term:', key='33'),
              sa('What comes next?\n0, 15, 30, 45, ___', 'Next term:', key='60'),
          ]),
          B('Multiplication facts', '3.OA.C.7', [
              sa('Multiply.\n4 × 7', 'Product:', key='28'),
              tf('6 × 8 = 42', key=False),
              mc('What number times 3 equals 24?', ['8', '7', '6', '21']),
              sa('Multiply.\n5 × 9', 'Product:', key='45'),
              sa('What number times 6 equals 42?', 'Number:', key='7'),
          ]),
      ],
      f1=B('Equations relating dependent and independent variables', '6.EE.C.9', [
          sa('Each box holds 6 cans.\nWrite an equation for the number of cans c in b boxes.', 'Equation:', key='c = 6b'),
          mc('In c = 6b, which variable is the dependent variable?', ['c', 'b', '6', 'Neither']),
          sa('Write an equation for y in terms of x.', 'Equation:', key='y = 5x',
             fig=table([['x', '1', '2', '3', '4'], ['y', '5', '10', '15', '20']])),
          tf('In y = x + 4, y is the independent variable.', key=False),
          sa('A plant grows 2 cm each week.\nWrite an equation for its growth g after w weeks.', 'Equation:', key='g = 2w'),
      ]),
      f2=B('Equations for proportional relationships', '7.RP.A.2.c', [
          sa('Pencils cost $0.35 each.\nWrite an equation for the cost c of n pencils.', 'Equation:', key='c = 0.35n'),
          sa('The table shows a proportional relationship.\nWrite an equation for y in terms of x.', 'Equation:', key='y = 2.5x',
             fig=table([['x', '4', '6', '10'], ['y', '10', '15', '25']])),
          mc('Which equation represents a proportional relationship?', ['y = 1.5x', 'y = 1.5x + 2', 'y = x + 1.5', 'y = 1.5']),
          sa('A train travels 150 miles in 2 hours at a constant speed.\nWrite an equation for the distance d after t hours.', 'Equation:', key='d = 75t'),
          tf('y = {3/4}x represents a proportional relationship.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.OA.B.3 (graph)
    S('5.OA.B.3', 'Form ordered pairs from two patterns and graph them',
      main=[
          plot('Pattern A (x): start at 0 and add 1.\nPattern B (y): start at 0 and add 2.\nGraph the ordered pairs for the first 5 terms.',
               grid(6, 10, ystep=1), key='Points plotted at (0, 0), (1, 2), (2, 4), (3, 6), (4, 8)'),
          plot('Graph the ordered pairs from the two patterns.',
               tplot([['Pattern A', '0', '2', '4', '6'], ['Pattern B', '0', '3', '6', '9']], 7, 10),
               key='Points plotted at (0, 0), (2, 3), (4, 6), (6, 9)'),
          sa('Pattern A starts at 0 and adds 3. Pattern B starts at 0 and adds 9.\nWrite the first four ordered pairs (A, B).',
             'Ordered pairs:', key='(0, 0), (3, 9), (6, 18), (9, 27)'),
          mc('The points come from two patterns.\nWhich statement is true?',
             ['Each y-value is 4 times its x-value.', 'Each y-value is 4 more than its x-value.',
              'Each x-value is 4 times its y-value.', 'The y-values increase by 1 each time.'],
             fig=grid(6, 16, ystep=2, pts=[(0, 0), (1, 4), (2, 8), (3, 12)])),
          plot('Pattern A (x): start at 0 and add 2.\nPattern B (y): start at 0 and add 1.\nGraph the ordered pairs for the first 4 terms.',
               grid(8, 5), key='Points plotted at (0, 0), (2, 1), (4, 2), (6, 3)'),
      ],
      back=[
          B('Patterns that follow a rule', '4.OA.C.5', [
              sa('The rule is "add 3." The pattern starts at 0.\nWhat is the 5th term?', 'Term:', key='12'),
              tf('The pattern 0, 5, 10, 15 follows the rule "add 5."', key=True),
              mc('Which pattern follows the rule "add 2," starting at 0?', ['0, 2, 4, 6', '2, 4, 6, 8', '0, 2, 4, 8', '0, 1, 2, 3']),
              sa('What is the rule for the pattern?\n0, 8, 16, 24', 'Rule:', key='Add 8'),
              sa('The rule is "add 10." The pattern starts at 0.\nWhat is the 6th term?', 'Term:', key='50'),
          ]),
          B('Ordered pairs and the coordinate plane', '5.G.A.1', [
              tf('In (3, 6), the 3 tells how far to move along the x-axis.', key=True),
              mc('In the ordered pair (4, 9), which number is the y-coordinate?', ['9', '4', '13', '5']),
              sa('Which ordered pair names the origin?', 'Ordered pair:', key='(0, 0)'),
              tf('(2, 5) and (5, 2) name the same point.', key=False),
              sa('What are the coordinates of point P?', 'P =', key='(6, 3)', fig=grid(8, 8, pts=[(6, 3, 'P')])),
          ]),
          B('Reading the scale on an axis', '3.MD.B.3', [
              mc('An axis is numbered 0, 2, 4, 6, 8.\nHow much does each grid line stand for?', ['2', '1', '4', '8']),
              tf('On an axis numbered 0, 4, 8, 12, the value 10 is halfway between 4 and 8.', key=False),
              sa('An axis is numbered 0, 5, 10, 15.\nWhere does 20 go?', 'Answer:', key='One grid line above 15'),
              mc('On an axis numbered by 3s, which value is two grid lines above 0?', ['6', '2', '3', '9']),
              tf('On an axis numbered by 10s, the value 25 is on a grid line.', key=False),
          ]),
      ],
      f1=B('Plot pairs of values from a ratio table', '6.RP.A.3.a', [
          plot('Plot the pairs of values from the ratio table on the coordinate plane.',
               tplot([['Cups of rice', '1', '2', '3'], ['Cups of water', '2', '4', '6']], 4, 8),
               key='Points plotted at (1, 2), (2, 4), (3, 6)'),
          sa('The table shows equivalent ratios.\nFind the missing value.', 'Missing value:', key='15',
             fig=table([['Laps', '2', '4', '6', '8'], ['Minutes', '5', '10', '?', '20']])),
          mc('Which point comes from the ratio table?', ['(2, 12)', '(12, 2)', '(2, 6)', '(3, 12)'],
             fig=table([['Boxes', '1', '2', '3'], ['Pens', '6', '12', '18']])),
          plot('Plot the pairs of values from the ratio table on the coordinate plane.',
               tplot([['Hours', '1', '2', '3', '4'], ['Dollars', '8', '16', '24', '32']], 5, 35, ystep=5),
               key='Points plotted at (1, 8), (2, 16), (3, 24), (4, 32)'),
          tf('The points (1, 3), (2, 6), and (3, 9) come from a ratio table with the ratio 1 : 3.', key=True),
      ]),
      f2=B('Use a graph to decide whether a relationship is proportional', '7.RP.A.2.a', [
          tf('The points lie on a straight line through the origin, so the relationship is proportional.', key=True,
             fig=grid(6, 12, ystep=2, pts=[(1, 2), (2, 4), (3, 6), (4, 8)], lines=[((0, 0), (6, 12))])),
          mc('Which statement about the graph is true?',
             ['It is not proportional because the line does not pass through (0, 0).', 'It is proportional because the points are on a line.',
              'It is proportional because y increases by 2.', 'It is not proportional because the points are not on a line.'],
             fig=grid(5, 10, ystep=2, pts=[(0, 1), (1, 3), (2, 5), (3, 7)], lines=[((0, 1), (4.5, 10))])),
          sa('Graph the pairs (1, 4), (2, 8), and (3, 12).\nIs the relationship proportional?', 'Answer:', key='Yes',
             note='The points lie on a straight line through (0, 0).', fig=grid(4, 14, ystep=2)),
          tf('The points (1, 2), (2, 5), and (3, 8) show a proportional relationship.', key=False),
          mc('Which set of points shows a proportional relationship?',
             ['(2, 5), (4, 10), (6, 15)', '(1, 2), (2, 3), (3, 4)', '(0, 3), (1, 6), (2, 9)', '(1, 1), (2, 4), (3, 9)']),
      ])),
]
