from qb import S, B, sa, mc, tf, nl, tape, draw_write, work, LONG_DIVISION
from common import bar, fracs

SETS = [
    # ------------------------------------------------------------------ 5.NF.A.1 (add)
    S('5.NF.A.1', 'Add fractions with unlike denominators',
      main=[
          sa('Add.\n{2/3} + {1/4}', 'Sum:', key='11/12'),
          sa('Add.\n{3/5} + {1/10}', 'Sum:', key='7/10'),
          mc('Add.\n{5/6} + {3/8}', ['1{5/24}', '{8/14}', '{8/24}', '1{1/24}']),
          sa('Add.\n{1/2} + {2/7}', 'Sum:', key='11/14'),
          sa('Add.\n{3/4} + {5/12} + {1/6}', 'Sum:', key='1 1/3', note='16/12 or 4/3 is also correct.'),
      ],
      back=[
          B('Equivalent fractions', '4.NF.A.1', [
              sa('Find the missing number.\n{2/3} = {?/12}', 'Missing number:', key='8'),
              tf('{1/4} = {4/12}', key=False),
              mc('Which fraction is equivalent to {3/5}?', ['{6/10}', '{3/10}', '{5/3}', '{6/5}']),
              sa('Find the missing number.\n{5/6} = {20/?}', 'Missing number:', key='24'),
              tf('{2/7} = {4/21}', key=False),
          ]),
          B('Adding fractions with like denominators', '4.NF.B.3.a', [
              sa('Add.\n{3/8} + {2/8}', 'Sum:', key='5/8'),
              tf('{4/12} + {5/12} = {9/24}', key=False),
              mc('{7/10} + {6/10} = ?', ['1{3/10}', '{13/20}', '{1/10}', '1{6/10}']),
              sa('Add.\n{1/6} + {4/6}', 'Sum:', key='5/6'),
              tf('{2/5} + {3/5} = 1', key=True),
          ]),
          B('Common multiples', '4.OA.B.4', [
              sa('List the first five positive multiples of 4.', 'Multiples:', key='4, 8, 12, 16, 20'),
              tf('10 is a multiple of both 3 and 4.', key=False),
              mc('Which number is a multiple of both 6 and 8?', ['24', '14', '16', '30']),
              sa('Name a positive number that is a multiple of both 5 and 10.', 'Number:', key='10',
                 note='Any positive multiple of 10 (10, 20, 30, ...) is correct.'),
              tf('18 is a multiple of both 4 and 6.', key=False),
          ]),
      ],
      f1=B('Find the least common multiple', '6.NS.B.4', [
          sa('Find the least common multiple of 6 and 10.', 'LCM:', key='30'),
          sa('Find the least common multiple of 8 and 12.', 'LCM:', key='24'),
          mc('What is the least common multiple of 4 and 9?', ['36', '13', '72', '18']),
          sa('Find the least common multiple of 5 and 15.', 'LCM:', key='15'),
          tf('The least common multiple of 6 and 9 is 54.', key=False),
      ]),
      f2=B('Add rational numbers', '7.NS.A.1.d', [
          sa('Find the value.\n-{2/3} + {1/4}', 'Value:', key='-5/12'),
          sa('Find the value.\n{3/5} + (-{7/10})', 'Value:', key='-1/10'),
          mc('Find the value.\n-{1/2} + (-{3/8})', ['-{7/8}', '-{1/8}', '{1/8}', '-{4/10}']),
          sa('Find the value.\n-1{1/3} + {5/6}', 'Value:', key='-1/2'),
          tf('-{3/4} + {3/4} = 0', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.A.1 (subtract)
    S('5.NF.A.1', 'Subtract fractions with unlike denominators',
      main=[
          sa('Subtract.\n{5/6} - {1/4}', 'Difference:', key='7/12'),
          sa('Subtract.\n{7/8} - {1/2}', 'Difference:', key='3/8'),
          mc('Subtract.\n{4/5} - {2/3}', ['{2/15}', '{2/2}', '{6/15}', '{1/5}']),
          sa('Subtract.\n{9/10} - {2/5}', 'Difference:', key='1/2', note='5/10 is also correct.'),
          sa('Subtract.\n1 - {3/7}', 'Difference:', key='4/7'),
      ],
      back=[
          B('Equivalent fractions', '4.NF.A.1', [
              sa('Find the missing number.\n{1/4} = {?/12}', 'Missing number:', key='3'),
              tf('{1/2} = {4/8}', key=True),
              mc('Which fraction is equivalent to {2/3}?', ['{10/15}', '{3/4}', '{2/6}', '{4/9}']),
              sa('Find the missing number.\n{4/5} = {?/15}', 'Missing number:', key='12'),
              tf('{3/4} = {9/16}', key=False),
          ]),
          B('Subtracting fractions with like denominators', '4.NF.B.3.a', [
              sa('Subtract.\n{7/9} - {2/9}', 'Difference:', key='5/9'),
              tf('{5/8} - {3/8} = {2/8}', key=True),
              mc('{11/12} - {4/12} = ?', ['{7/12}', '{15/12}', '{7/24}', '{4/12}']),
              sa('Subtract.\n1 - {3/5}', 'Difference:', key='2/5'),
              tf('{9/10} - {4/10} = {5/20}', key=False),
          ]),
          B('Common multiples', '4.OA.B.4', [
              sa('List the first four positive multiples of 6.', 'Multiples:', key='6, 12, 18, 24'),
              tf('15 is a multiple of both 3 and 5.', key=True),
              mc('Which number is a multiple of both 4 and 5?', ['20', '9', '15', '25']),
              sa('Name a positive number that is a multiple of both 3 and 8.', 'Number:', key='24',
                 note='Any positive multiple of 24 (24, 48, 72, ...) is correct.'),
              tf('16 is a multiple of both 4 and 6.', key=False),
          ]),
      ],
      f1=B('Solve equations of the form x + p = q with fractions', '6.EE.B.7', [
          sa('Solve for x.\nx + {1/3} = {5/6}', 'x =', key='1/2'),
          sa('Solve for y.\ny - {2/5} = {3/10}', 'y =', key='7/10'),
          mc('Solve for n.\n{3/4} + n = 1{1/2}', ['{3/4}', '2{1/4}', '{1/4}', '1{1/4}']),
          sa('Solve for m.\nm + {5/8} = 2', 'm =', key='1 3/8'),
          tf('The solution of x - {1/6} = {2/3} is x = {5/6}.', key=True),
      ]),
      f2=B('Subtract rational numbers', '7.NS.A.1.c', [
          sa('Find the value.\n{1/4} - {5/6}', 'Value:', key='-7/12'),
          sa('Find the value.\n-{2/3} - {1/6}', 'Value:', key='-5/6'),
          mc('Find the value.\n{1/2} - (-{3/4})', ['1{1/4}', '-{1/4}', '{1/4}', '-1{1/4}']),
          sa('Find the value.\n-{3/5} - (-{1/2})', 'Value:', key='-1/10'),
          tf('{2/9} - {5/9} = {1/3}', key=False),
      ])),

    # ------------------------------------------------------------------ 5.NF.A.1 (mixed numbers)
    S('5.NF.A.1', 'Add mixed numbers with unlike denominators',
      main=[
          sa('Add.\n2{1/3} + 1{1/2}', 'Sum:', key='3 5/6'),
          sa('Add.\n4{3/4} + 2{1/6}', 'Sum:', key='6 11/12'),
          mc('Add.\n1{2/5} + 3{1/2}', ['4{9/10}', '4{3/7}', '5{1/10}', '4{3/10}']),
          sa('Add.\n3{5/8} + 2{3/4}', 'Sum:', key='6 3/8'),
          sa('Add.\n5{2/3} + 1{5/9}', 'Sum:', key='7 2/9'),
      ],
      back=[
          B('Adding mixed numbers with like denominators', '4.NF.B.3.c', [
              sa('Add.\n1{2/5} + 2{1/5}', 'Sum:', key='3 3/5'),
              sa('Add.\n4{1/6} + 1{4/6}', 'Sum:', key='5 5/6'),
              tf('2{3/4} + 1{3/4} = 3{6/8}', key=False),
              mc('2{2/3} + 1{2/3} = ?', ['4{1/3}', '3{1/3}', '4{2/3}', '3{2/3}']),
              sa('Add.\n3{7/8} + {3/8}', 'Sum:', key='4 2/8', note='4 1/4 is also correct.'),
          ]),
          B('Mixed numbers and fractions greater than 1', '4.NF.B.3.b', [
              sa('Write 2{3/4} as a fraction.', 'Fraction:', key='11/4'),
              sa('Write {17/5} as a mixed number.', 'Mixed number:', key='3 2/5'),
              tf('1{1/3} = {4/3}', key=True),
              mc('Which fraction is equal to 3{1/2}?', ['{7/2}', '{5/2}', '{6/2}', '{31/2}']),
              tf('5{2/3} = 4{5/3}', key=True),
          ]),
          B('Equivalent fractions', '4.NF.A.1', [
              sa('Find the missing number.\n{3/4} = {?/8}', 'Missing number:', key='6'),
              tf('{1/6} = {2/12}', key=True),
              mc('Which fraction is equivalent to {1/2}?', ['{5/10}', '{2/3}', '{1/4}', '{2/2}']),
              sa('Find the missing number.\n{2/5} = {?/10}', 'Missing number:', key='4'),
              tf('{5/6} = {10/18}', key=False),
          ]),
      ],
      f1=B('Solve equations of the form x + p = q with mixed numbers', '6.EE.B.7', [
          sa('Solve for x.\nx + 2{1/2} = 6{1/4}', 'x =', key='3 3/4'),
          sa('Solve for y.\ny - 1{2/3} = 3{1/6}', 'y =', key='4 5/6'),
          mc('Solve for n.\nn + 4{3/8} = 7', ['2{5/8}', '3{5/8}', '11{3/8}', '2{3/8}']),
          sa('A board was 8{1/2} feet long. After a piece was cut off, it was 5{3/4} feet long.\nWrite and solve an equation to find the length p of the piece.',
             'Equation and solution:', key='8 1/2 - p = 5 3/4; p = 2 3/4 feet', note='Any equivalent equation is correct.'),
          tf('The solution of x - 1{1/4} = 2{1/2} is x = 1{1/4}.', key=False),
      ]),
      f2=B('Solve equations of the form px + q = r with fractions', '7.EE.B.4.a', [
          sa('Solve for x.\n2x + {1/2} = 3{1/2}', 'x =', key='1 1/2'),
          sa('Solve for x.\n{1/3}x - 1{1/4} = 2{3/4}', 'x =', key='12'),
          mc('Solve for x.\n4x - 2{1/3} = 1', ['{5/6}', '{1/3}', '1{1/12}', '{1/6}']),
          sa('Jo bought 3 bags of flour that weigh the same and one 1{1/2}-pound bag of sugar. The total weight was 9{3/4} pounds.\nHow much does each bag of flour weigh?',
             'Weight:', key='2 3/4 pounds', note='3f + 1 1/2 = 9 3/4'),
          tf('The solution of {1/2}(x + 3) = 4 is x = 5.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.A.1 (subtract mixed numbers)
    S('5.NF.A.1', 'Subtract mixed numbers with unlike denominators',
      main=[
          sa('Subtract.\n5{3/4} - 2{1/6}', 'Difference:', key='3 7/12'),
          mc('Subtract.\n4{1/5} - 1{1/2}', ['2{7/10}', '3{3/10}', '3{7/10}', '2{3/10}']),
          sa('Subtract.\n6 - 2{2/3}', 'Difference:', key='3 1/3'),
          sa('Subtract.\n7{1/4} - 3{5/6}', 'Difference:', key='3 5/12'),
          tf('3{1/2} - 1{2/3} = 1{5/6}', key=True),
      ],
      back=[
          B('Subtracting mixed numbers with like denominators', '4.NF.B.3.c', [
              sa('Subtract.\n4{5/6} - 1{4/6}', 'Difference:', key='3 1/6'),
              mc('5{1/3} - 2{2/3} = ?', ['2{2/3}', '3{1/3}', '3{2/3}', '2{1/3}']),
              sa('Subtract.\n6{1/4} - 3{3/4}', 'Difference:', key='2 2/4', note='2 1/2 is also correct.'),
              tf('7{2/5} - 4{4/5} = 3{2/5}', key=False),
              sa('Subtract.\n5 - 1{3/8}', 'Difference:', key='3 5/8'),
          ]),
          B('Rename a mixed number by decomposing a whole', '4.NF.B.3.b', [
              sa('Fill in the blank.\n3{1/4} = 2{?/4}', 'Blank:', key='5'),
              tf('5{2/3} = 4{5/3}', key=True),
              mc('Which is equal to 4{1/8}?', ['3{9/8}', '4{9/8}', '3{1/8}', '5{1/8}']),
              sa('Fill in the blank.\n6 = 5{?/5}', 'Blank:', key='5'),
              tf('2{3/10} = 1{3/10}', key=False),
          ]),
      ],
      f1=B('Solve equations of the form x + p = q with mixed numbers', '6.EE.B.7', [
          sa('Solve for x.\nx + 3{2/3} = 7{1/4}', 'x =', key='3 7/12'),
          sa('Solve for y.\n9{1/2} - y = 4{5/6}', 'y =', key='4 2/3'),
          mc('Solve for n.\nn + 1{5/8} = 4{1/4}', ['2{5/8}', '3{5/8}', '5{7/8}', '2{3/8}']),
          sa('A tank had 10{1/4} gallons of water. After some water was used, 6{2/3} gallons were left.\nWrite and solve an equation to find the amount w used.',
             'Equation and solution:', key='10 1/4 - w = 6 2/3; w = 3 7/12 gallons', note='Any equivalent equation is correct.'),
          tf('The solution of x + 2{3/4} = 5 is x = 2{1/4}.', key=True),
      ]),
      f2=B('Subtract rational numbers', '7.NS.A.1.c', [
          sa('Find the value.\n2{1/4} - 5{1/2}', 'Value:', key='-3 1/4'),
          sa('Find the value.\n-1{2/3} - 2{1/6}', 'Value:', key='-3 5/6'),
          mc('Find the value.\n3{1/2} - (-1{3/4})', ['5{1/4}', '1{3/4}', '-1{3/4}', '-5{1/4}']),
          sa('Find the value.\n-4{1/3} - (-1{5/6})', 'Value:', key='-2 1/2'),
          tf('1{1/4} - 3 = -1{3/4}', key=True),
      ]), num=65),

    # ------------------------------------------------------------------ 5.NF.A.2 (word problems)
    S('5.NF.A.2', 'Solve word problems by adding and subtracting fractions',
      main=[
          sa('Mia walked {3/4} mile to school and then {2/3} mile to the park.\nHow far did she walk in all?', 'Distance:',
             key='1 5/12 miles'),
          sa('A jug had {7/8} gallon of milk. Ben drank {1/3} gallon.\nHow much milk is left?', 'Milk left:', key='13/24 gallon'),
          mc('Ana used 2{1/2} cups of flour and 1{3/4} cups of sugar.\nHow many cups did she use in all?',
             ['4{1/4} cups', '3{1/4} cups', '3{3/4} cups', '4{3/4} cups']),
          sa('A ribbon is 5{1/6} feet long. Lea cuts off 2{1/2} feet.\nHow long is the ribbon now?', 'Length:', key='2 2/3 feet'),
          sa('Tom read {1/4} of a book on Monday and {3/8} of the book on Tuesday.\nWhat fraction of the book does he still have to read?',
             'Fraction:', key='3/8'),
      ],
      back=[
          B('Word problems with like denominators', '4.NF.B.3.d', [
              sa('Kim ate {3/8} of a pizza and Joe ate {2/8} of the pizza.\nWhat fraction of the pizza did they eat in all?', 'Fraction:', key='5/8'),
              sa('A rope is {9/10} meter long. {4/10} meter is cut off.\nHow much rope is left?', 'Rope left:', key='5/10 meter',
                 note='1/2 meter is also correct.'),
              tf('{2/6} of a garden is corn and {3/6} is beans. Corn and beans cover {5/6} of the garden.', key=True),
              mc('Lu had {7/12} of a cake. She gave away {5/12} of the cake.\nHow much of the cake is left?',
                 ['{2/12}', '{12/12}', '{2/24}', '{35/12}']),
              sa('A tank is {3/5} full. Water is added to fill another {1/5} of the tank.\nHow full is the tank now?', 'Fraction:', key='4/5'),
          ]),
          B('Choosing addition or subtraction', '2.OA.A.1', [
              mc('A class has 14 boys and 13 girls.\nWhich operation finds the number of students in all?',
                 ['Addition', 'Subtraction', 'Multiplication', 'Division']),
              tf('To find how much is left after some is used, you subtract.', key=True),
              sa('Sam had 42 marbles. He lost 15 marbles.\nHow many marbles are left?', 'Marbles:', key='27'),
              mc('A shelf holds 35 books. 18 books are on it now.\nWhich equation finds how many more books fit?',
                 ['35 - 18 = □', '35 + 18 = □', '18 - 35 = □', '35 × 18 = □']),
              sa('Liz has 26 stickers. She gets 17 more.\nHow many stickers does she have now?', 'Stickers:', key='43'),
          ]),
          B('Equivalent fractions', '4.NF.A.1', [
              sa('Find the missing number.\n{3/4} = {?/12}', 'Missing number:', key='9'),
              tf('{2/3} = {8/12}', key=True),
              mc('Which fraction is equivalent to {5/6}?', ['{10/12}', '{5/12}', '{6/5}', '{15/16}']),
              sa('Rewrite {1/2} and {1/3} as fractions with the denominator 6.', ['{1/2} =', '{1/3} ='], key='3/6 and 2/6'),
              tf('{3/8} = {6/24}', key=False),
          ], num=4),
      ],
      f1=B('Write and solve equations of the form x + p = q', '6.EE.B.7', [
          sa('After using {2/3} cup of oil, Ray has {3/4} cup left.\nWrite and solve an equation to find how much oil c he started with.',
             'Equation and solution:', key='c - 2/3 = 3/4; c = 1 5/12 cups', note='Any equivalent equation is correct.'),
          sa('A plant grew {5/8} inch and is now 4{1/4} inches tall.\nWrite and solve an equation to find its starting height h.',
             'Equation and solution:', key='h + 5/8 = 4 1/4; h = 3 5/8 inches', note='Any equivalent equation is correct.'),
          mc('{3/10} inch of rain fell on day 1. In all, {9/10} inch fell on days 1 and 2.\nWhich equation finds the rain r on day 2?',
             ['{3/10} + r = {9/10}', 'r - {3/10} = {9/10}', '{3/10}r = {9/10}', 'r + {9/10} = {3/10}']),
          sa('Solve for x.\nx + {2/9} = {2/3}', 'x =', key='4/9'),
          tf('If n - {1/4} = {5/8}, then n = {7/8}.', key=True),
      ]),
      f2=B('Write and solve equations of the form px + q = r', '7.EE.B.4.a', [
          sa('A recipe uses {3/4} cup of sugar per batch, plus {1/2} cup for frosting. Ali used 2{3/4} cups of sugar in all.\nHow many batches did he make?',
             'Batches:', key='3', note='(3/4)b + 1/2 = 2 3/4'),
          sa('Solve for x.\n{2/3}x + {1/6} = {5/6}', 'x =', key='1'),
          mc('A 6-foot board is cut into 4 equal pieces, with {1/2} foot left over.\nHow long is each piece?',
             ['1{3/8} feet', '1{1/2} feet', '1{5/8} feet', '5{1/2} feet']),
          sa('Solve for x.\n5x - {3/4} = 4{1/4}', 'x =', key='1'),
          tf('The solution of 2x + {1/3} = 1 is x = {2/3}.', key=False),
      ])),

    # ------------------------------------------------------------------ 5.NF.A.2 (benchmarks)
    S('5.NF.A.2', 'Use benchmark fractions to estimate and to check answers',
      main=[
          tf('Ella says {3/4} + {1/6} = {4/10}. Her answer must be wrong, because {4/10} is less than {3/4}, one of the fractions she added.', key=True),
          mc('Which is the best estimate of {7/8} + {5/12}?', ['About 1{1/2}', 'About {1/2}', 'About 2{1/2}', 'About 3']),
          sa('Is {3/5} + {4/9} more or less than 1?\nUse benchmark fractions to explain.', ['Answer:', 'Explanation:'], key='More than 1',
             note='3/5 is more than 1/2 by 1/10, and 4/9 is less than 1/2 by only 1/18, so the sum is a little more than 1/2 + 1/2 = 1.'),
          sa('Jen ran {9/10} mile and walked {1/8} mile.\nEstimate the total distance to the nearest whole mile.', 'Estimate:', key='1 mile'),
          mc('Leo says {5/6} - {1/3} = {4/3}.\nWhich statement explains why his answer is not reasonable?',
             ['The answer is greater than {5/6}, but subtracting should give less than {5/6}.', 'The denominators are different.',
              '{4/3} is less than 1.', 'The answer should be 0.']),
      ],
      back=[
          B('Comparing fractions to 1/2 and 1', '4.NF.A.2', [
              tf('{5/8} is less than {1/2}.', key=False),
              mc('Which fraction is greater than {1/2}?', ['{4/7}', '{2/5}', '{3/8}', '{1/3}']),
              sa('Is {5/9} closest to 0, {1/2}, or 1?', 'Answer:', key='1/2'),
              tf('{6/10} is less than {1/2}.', key=False),
              sa('Is {11/12} closer to {1/2} or to 1?', 'Answer:', key='1'),
          ]),
          B('Fractions on a number line', '3.NF.A.2', [
              sa('What fraction is at point A?', 'A =', key='3/4',
                 fig=nl(0, 1, 0.25, pts=[(0.75, 'A')], labels={0: '0', 1: '1'})),
              tf('On a number line, {1/2} is halfway between 0 and 1.', key=True),
              mc('Which point is at {1/3}?', ['Point A', 'Point B', 'Point C', 'Point D'],
                 fig=nl(0, 1, 1 / 6, pts=[(1 / 3, 'A'), (2 / 3, 'B'), (1 / 6, 'C'), (5 / 6, 'D')], labels={0: '0', 1: '1'})),
              sa('What fraction is at point B?', 'B =', key='5/8',
                 fig=nl(0, 1, 0.125, pts=[(0.625, 'B')], labels={0: '0', 1: '1'})),
              tf('{7/8} is closer to 1 than to {1/2}.', key=True),
          ]),
      ],
      f1=B('Reason about the size of a quotient of fractions', '6.NS.A.1', [
          tf('{3/4} ÷ {1/8} is greater than 1.', key=True),
          mc('Without dividing, which quotient is less than 1?', ['{1/3} ÷ {1/2}', '{3/4} ÷ {1/2}', '2 ÷ {1/2}', '{5/6} ÷ {1/3}']),
          sa('Divide.\n{5/6} ÷ {5/12}', 'Quotient:', key='2'),
          sa('Estimate 2{7/8} ÷ {1/2} by first rounding 2{7/8} to the nearest whole number.', 'Estimate:', key='6',
             note='3 ÷ 1/2 = 6'),
          tf('{1/2} ÷ 4 is greater than {1/2}.', key=False),
      ]),
      f2=B('Use estimation to judge whether an answer is reasonable', '7.EE.B.3', [
          sa('A board 9{7/8} feet long is cut into 3 equal pieces.\nRound the length of the board to the nearest whole foot. Then use it to estimate the length of each piece.',
             ['Rounded length:', 'Estimate:'], key='10 feet; about 3 1/3 feet',
             note='10 ÷ 3 = 3 1/3 feet. Both parts are required. The exact length, 3 7/24 feet, is not the estimate asked for.'),
          mc('Ann earns $11.85 per hour and works 7{3/4} hours.\nWhich is the best estimate of her pay?', ['$96', '$84', '$77', '$120']),
          tf('{3/4} of $79.95 is about $60.', key=True),
          sa('Kai says 4{5/6} + 3{1/8} is about 9.\nRound each mixed number to the nearest whole number and estimate the sum. Is the exact sum more or less than 9?',
             ['Your estimate:', 'More or less than 9?'], key='8; less',
             note='5 + 3 = 8. The exact sum, 7 23/24, is less than 9. Both parts are required.'),
          sa('A recipe needs 2{1/3} cups of flour per batch.\nRound 2{1/3} to the nearest whole number. Then estimate the flour needed for 4 batches.',
             ['Rounded amount:', 'Estimate:'], key='2 cups; 8 cups',
             note='2 × 4 = 8 cups. Both parts are required. The exact amount, 9 1/3 cups, is not the estimate asked for.'),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.3 (fraction as division)
    S('5.NF.B.3', 'Interpret a fraction as division of the numerator by the denominator',
      main=[
          sa('Write 3 ÷ 5 as a fraction.', 'Fraction:', key='3/5'),
          sa('4 friends share 3 pizzas equally.\nHow much pizza does each friend get?', 'Each friend gets:', key='3/4 pizza'),
          mc('Which division expression is equal to {7/4}?', ['7 ÷ 4', '4 ÷ 7', '7 × 4', '7 - 4']),
          sa('Write {13/6} as a division expression. Then write the quotient as a mixed number.', ['Division:', 'Mixed number:'],
             key='13 ÷ 6; 2 1/6'),
          tf('When 2 pounds of rice are shared equally among 3 bags, each bag gets {2/3} pound.', key=True),
      ],
      back=[
          B('Unit fractions', '3.NF.A.1', [
              tf('{1/4} is one of 4 equal parts of a whole.', key=True),
              sa('A sandwich is cut into 3 equal parts.\nWhat fraction of the sandwich is one part?', 'Fraction:', key='1/3'),
              mc('What fraction of the bar is shaded?', ['{3/8}', '{5/8}', '{8/3}', '{3/5}'], fig=bar(8, 3)),
              sa('How many {1/6}s make {5/6}?', 'Answer:', key='5'),
              tf('{3/8} is 3 parts of size {1/8}.', key=True),
          ]),
          B('Division with remainders', '4.NBT.B.6', [
              sa('Divide. Write the quotient and the remainder.\n17 ÷ 5', 'Quotient and remainder:', key='3 R 2'),
              tf('23 ÷ 4 = 6 R 1', key=False),
              mc('29 ÷ 6 = ?', ['4 R 5', '5 R 1', '4 R 3', '5 R 5']),
              sa('Divide. Write the quotient and the remainder.\n50 ÷ 8', 'Quotient and remainder:', key='6 R 2'),
              tf('15 ÷ 2 = 7 R 2', key=False),
          ]),
          B('Mixed numbers and fractions greater than 1', '4.NF.B.3.b', [
              sa('Write {9/4} as a mixed number.', 'Mixed number:', key='2 1/4'),
              sa('Write 1{2/3} as a fraction.', 'Fraction:', key='5/3'),
              tf('{11/5} = 1{1/5}', key=False),
              mc('Which mixed number is equal to {7/3}?', ['2{1/3}', '3{1/3}', '2{2/3}', '1{1/3}']),
              sa('Write {15/4} as a mixed number.', 'Mixed number:', key='3 3/4'),
          ]),
      ],
      f1=B('Unit rates written as fractions', '6.RP.A.2', [
          sa('A recipe uses 3 cups of flour for every 4 cups of water.\nHow many cups of flour are used per cup of water?', 'Cups of flour:', key='3/4 cup'),
          sa('8 apples cost $6.\nWhat is the cost per apple?', 'Cost per apple:', key='$0.75', note='3/4 dollar is also correct.'),
          mc('A car goes 150 miles on 4 gallons of gas.\nWhat is the rate in miles per gallon?', ['37.5', '{4/150}', '600', '154']),
          sa('There are 5 cups of juice for every 2 pitchers.\nHow many cups of juice are there per pitcher?', 'Cups per pitcher:', key='2 1/2 cups'),
          tf('The ratio 3 : 8 has the unit rate {3/8}.', key=True),
      ]),
      f2=B('Write fractions as decimals using division', '7.NS.A.2.d', [
          sa('Write 5 ÷ 8 as a decimal.', 'Decimal:', key='0.625'),
          work('Use long division to write {7/12} as a decimal. Show your work.', 'Decimal:', method=LONG_DIVISION, key='0.58333... (the 3 repeats)'),
          mc('Which fraction has a decimal form that repeats?', ['{5/6}', '{3/8}', '{7/20}', '{9/25}']),
          sa('Write 11 ÷ 4 as a decimal.', 'Decimal:', key='2.75'),
          tf('{1/3} = 0.3', key=False),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.3 (sharing problems)
    S('5.NF.B.3', 'Solve sharing problems whose answers are fractions or mixed numbers',
      main=[
          sa('6 friends share 10 granola bars equally.\nHow many bars does each friend get? Write a mixed number.', 'Bars:', key='1 2/3 bars',
             note='1 4/6 is also correct.'),
          sa('A 50-pound bag of rice is shared equally among 8 families.\nHow many pounds does each family get?', 'Pounds:', key='6 1/4 pounds'),
          mc('9 yards of ribbon are cut into 4 equal pieces.\nHow long is each piece?', ['2{1/4} yards', '{4/9} yard', '2{1/9} yards', '4{1/2} yards']),
          sa('7 liters of juice are poured equally into 3 jugs.\nHow many liters are in each jug? Between which two whole numbers is your answer?',
             ['Liters:', 'Between:'], key='2 1/3 liters; between 2 and 3'),
          tf('When 5 cookies are shared equally by 2 children, each child gets 2{1/2} cookies.', key=True),
      ],
      back=[
          B('Division word problems', '3.OA.A.3', [
              sa('24 stickers are shared equally by 6 friends.\nHow many stickers does each friend get?', 'Stickers:', key='4'),
              mc('35 chairs are set out in 5 equal rows.\nHow many chairs are in each row?', ['7', '30', '40', '6']),
              tf('If 4 boxes hold 28 toys, with the same number in each box, each box holds 7 toys.', key=True),
              sa('A baker puts 45 muffins into bags of 9.\nHow many bags does she fill?', 'Bags:', key='5'),
              sa('18 pencils are shared equally by 3 students.\nHow many pencils does each student get?', 'Pencils:', key='6'),
          ]),
          B('Whole numbers as fractions', '3.NF.A.3.c', [
              tf('{6/3} = 3', key=False),
              sa('Write 4 as a fraction with a denominator of 1.', 'Fraction:', key='4/1'),
              mc('Which fraction is equal to 3?', ['{6/2}', '{2/6}', '{3/2}', '{3/3}']),
              sa('How many halves are in 5 wholes?', 'Halves:', key='10'),
              tf('{8/8} = 8', key=False),
          ]),
      ],
      f1=B('Solve unit rate problems', '6.RP.A.3.b', [
          sa('3 pounds of grapes cost $7.\nWhat is the cost per pound?', 'Cost per pound:', key='$2 1/3',
             note='About $2.33 is also correct.'),
          sa('A car travels 100 miles in 3 hours at a constant speed.\nAt this rate, how far does it travel in 6 hours?', 'Distance:', key='200 miles'),
          mc('8 cans of soup cost $6.\nAt this rate, how much do 12 cans cost?', ['$9', '$8', '$4', '$16']),
          sa('A runner runs 5 miles in 40 minutes at a constant pace.\nAt this pace, how long does she take to run 8 miles?', 'Time:', key='64 minutes'),
          tf('If 4 pens cost $3, then 10 pens cost $7.00.', key=False),
      ]),
      f2=B('Unit rates with fractional quantities', '7.RP.A.1', [
          sa('A snail crawls {2/3} foot in {1/4} hour.\nWhat is its speed in feet per hour?', 'Speed:', key='2 2/3 feet per hour'),
          sa('A recipe uses {3/4} cup of sugar for every {1/2} cup of milk.\nHow many cups of sugar are used per cup of milk?', 'Cups of sugar:',
             key='1 1/2 cups'),
          mc('Jo walks {1/2} mile in {1/6} hour.\nWhat is her speed?', ['3 miles per hour', '{1/12} mile per hour', '{1/3} mile per hour', '2 miles per hour']),
          sa('A pump fills {5/8} of a tank in {1/2} hour.\nHow much of the tank does it fill per hour?', 'Tanks per hour:', key='1 1/4 tanks'),
          tf('{1/2} cup of juice for every {1/4} cup of water is a rate of 2 cups of juice per cup of water.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.4.a (fraction × whole)
    S('5.NF.B.4.a', 'Multiply a fraction by a whole number',
      main=[
          sa('Multiply.\n{3/4} × 12', 'Product:', key='9'),
          sa('Multiply.\n5 × {2/3}', 'Product:', key='3 1/3', note='10/3 is also correct.'),
          mc('What is {2/5} of 20?', ['8', '10', '4', '50']),
          sa('Multiply.\n{5/8} × 6', 'Product:', key='3 3/4', note='30/8 or 15/4 is also correct.'),
          tf('{1/3} × 15 means 15 split into 3 equal parts, with 1 of the parts taken.', key=True),
      ],
      back=[
          B('A fraction times a whole number as repeated unit fractions', '4.NF.B.4.b', [
              sa('Write {4/5} as a whole number times {1/5}.', 'Expression:', key='4 × 1/5'),
              tf('3 × {2/7} = {6/21}', key=False),
              mc('3 × {3/8} = ?', ['{9/8}', '{9/24}', '{6/8}', '3{3/8}']),
              sa('Multiply.\n4 × {2/9}', 'Product:', key='8/9'),
              tf('2 × {3/5} = {6/10}', key=False),
          ]),
          B('Parts of a whole', '3.NF.A.1', [
              tf('{1/4} of a bar means 1 of 4 equal parts.', key=True),
              sa('What fraction of the bar is shaded?', 'Fraction:', key='3/8', fig=bar(8, 3)),
              mc('What fraction is 2 parts of size {1/3}?', ['{2/3}', '{1/6}', '{3/2}', '{1/3}']),
              sa('How many {1/8}s are in {5/8}?', 'Answer:', key='5'),
              tf('{3/4} means 3 parts of size {1/4}.', key=True),
          ]),
          B('Splitting a number into equal parts', '3.OA.A.2', [
              sa('12 is split into 4 equal parts.\nHow much is in each part?', 'Answer:', key='3'),
              tf('20 split into 5 equal parts gives 4 in each part.', key=True),
              mc('Which expression shows 18 split into 3 equal parts?', ['18 ÷ 3', '18 × 3', '18 - 3', '3 ÷ 18']),
              sa('Divide.\n24 ÷ 8', 'Quotient:', key='3'),
              sa('30 is split into 6 equal parts.\nHow much is in each part?', 'Answer:', key='5'),
          ]),
      ],
      f1=B('Find a percent of a quantity', '6.RP.A.3.c', [
          sa('What is 25% of 48?', 'Answer:', key='12'),
          sa('What is 60% of 35?', 'Answer:', key='21'),
          mc('A $40 game is 15% off.\nHow many dollars are taken off the price?', ['$6', '$15', '$34', '$4']),
          sa('A class has 30 students. 70% of them ride the bus.\nHow many students ride the bus?', 'Students:', key='21'),
          tf('50% of 18 is 36.', key=False),
      ]),
      f2=B('Multistep percent problems', '7.RP.A.3', [
          sa('A $60 coat is 30% off.\nWhat is the sale price?', 'Sale price:', key='$42'),
          sa('A meal costs $25. A 20% tip is added.\nWhat is the total cost?', 'Total:', key='$30'),
          mc('A $80 bike has a 6% sales tax added.\nWhat is the total cost?', ['$84.80', '$86.00', '$4.80', '$85.60']),
          sa('A town of 500 people grew by 12%.\nWhat is the new population?', 'Population:', key='560'),
          tf('A 25% markup on a $40 item makes the price $50.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.4.a (fraction × fraction)
    S('5.NF.B.4.a', 'Multiply a fraction by a fraction',
      main=[
          sa('Multiply.\n{3/4} × {2/7}', 'Product:', key='3/14', note='6/28 is also correct.'),
          sa('Multiply.\n{3/4} × {1/6}', 'Product:', key='1/8', note='3/24 is also correct.'),
          mc('Multiply.\n{5/6} × {3/10}', ['{1/4}', '{8/16}', '{15/6}', '{1/2}']),
          sa('What is {1/2} of {3/8}?', 'Answer:', key='3/16'),
          tf('{2/5} × {2/3} = {4/15}', key=True),
      ],
      back=[
          B('A whole number times a fraction', '4.NF.B.4.b', [
              sa('Multiply.\n2 × {3/10}', 'Product:', key='6/10', note='3/5 is also correct.'),
              tf('5 × {1/4} = {5/20}', key=False),
              mc('4 × {2/3} = ?', ['{8/3}', '{8/12}', '{6/3}', '{2/12}']),
              sa('Multiply.\n3 × {5/12}', 'Product:', key='15/12', note='1 1/4 or 5/4 is also correct.'),
              tf('6 × {1/6} = 1', key=True),
          ]),
          B('Equivalent fractions and simplest form', '4.NF.A.1', [
              sa('Write {6/8} as an equivalent fraction with a denominator of 4.', 'Fraction:', key='3/4'),
              tf('{10/15} = {3/4}', key=False),
              mc('Which fraction is equivalent to {4/12}?', ['{1/3}', '{1/4}', '{4/3}', '{2/4}']),
              sa('Find the missing number.\n{9/12} = {?/4}', 'Missing number:', key='3'),
              tf('{5/20} = {1/5}', key=False),
          ]),
      ],
      f1=B('Divide fractions by fractions', '6.NS.A.1', [
          sa('Divide.\n{2/3} ÷ {4/5}', 'Quotient:', key='5/6'),
          sa('Divide.\n{3/4} ÷ {1/6}', 'Quotient:', key='4 1/2', note='9/2 is also correct.'),
          mc('Divide.\n{5/8} ÷ {1/4}', ['2{1/2}', '{5/32}', '{1/2}', '1{1/4}']),
          sa('How many {3/8}-cup servings are in {3/4} cup?', 'Servings:', key='2'),
          tf('{1/2} ÷ {1/4} = {1/8}', key=False),
      ]),
      f2=B('Multiply rational numbers', '7.NS.A.2.c', [
          sa('Find the product.\n-{2/3} × {3/4}', 'Product:', key='-1/2'),
          sa('Find the product.\n(-{4/5}) × (-{5/6})', 'Product:', key='2/3'),
          mc('Find the product.\n{3/7} × (-{7/9})', ['-{1/3}', '{1/3}', '-{3/7}', '{10/16}']),
          sa('Find the product.\n(-{1/2}) × (-{1/2}) × (-{1/2})', 'Product:', key='-1/8'),
          tf('(-{2/5}) × {5/2} = 1', key=False),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.4.a (visual models)
    S('5.NF.B.4.a', 'Interpret fraction products with tape diagrams and area models',
      main=[
          mc('The tape diagram shows 12 split into 4 equal parts, with 3 parts shaded.\nWhich product does the shaded part show?',
             ['{3/4} × 12', '{4/3} × 12', '3 × 12', '{1/4} × 3'], fig=tape(dict(n=4, shade=3, seg='3', brace='12'))),
          draw_write('Shade the tape diagram to show {2/5} × 15.\nThen write the product.', tape(dict(n=5, brace='15')), 'Product:',
                     draw='2 of the 5 equal parts shaded (each part is 3)', key='6',
                     note='Grade both: exactly 2 of the 5 parts shaded, and the product 6.'),
          mc('In the model, the darker part shows a product of two fractions.\nWhich equation does the model show?',
             ['{2/3} × {3/4} = {6/12}', '{2/3} × {3/4} = {5/7}', '{2/3} + {3/4} = {5/7}', '{1/3} × {1/4} = {1/12}'],
             fig=dict(k='grid', rows=3, cols=4, rshade=2, cshade=3, h=200, maxcell=44)),
          draw_write('Shade 3 of the 5 columns. Then shade 1 of the 2 rows.\nWhat product of fractions does the part shaded twice show, and what is it?',
                     dict(k='grid', rows=2, cols=5, rshade=0, cshade=0, h=180, maxcell=50,
                          desc='Blank rectangle divided into 2 rows and 5 columns of equal parts.'),
                     ['Product:', 'Value:'],
                     draw='3 of the 5 columns shaded and 1 of the 2 rows shaded; 3 parts are shaded twice', key='1/2 × 3/5; 3/10',
                     note='Grade both: the shading (3 columns, 1 row, 3 parts overlap) and the written product 1/2 × 3/5 = 3/10 '
                          '(3/5 × 1/2 is also correct).'),
          tf('In a model of {3/4} × 8, 8 is split into 4 equal parts and 3 of the parts are taken, so the product is 6.', key=True),
      ],
      back=[
          B('Fractions of a whole in a model', '3.NF.A.1', [
              sa('What fraction of the bar is shaded?', 'Fraction:', key='3/4', fig=bar(4, 3)),
              tf('{2/3} of a bar means 2 of 3 equal parts.', key=True),
              mc('A bar is split into 6 equal parts and 4 parts are shaded.\nWhat fraction is shaded?', ['{4/6}', '{6/4}', '{4/10}', '{2/6}']),
              sa('How many {1/3}s make {2/3}?', 'Answer:', key='2'),
              tf('A bar split into 8 equal parts with 3 parts shaded shows {3/5}.', key=False),
          ]),
          B('Split a whole number into equal parts', '3.OA.A.2', [
              sa('15 is split into 5 equal parts.\nHow much is in each part?', 'Answer:', key='3'),
              tf('21 split into 3 equal parts gives 7 in each part.', key=True),
              mc('Which expression shows 32 split into 4 equal parts?', ['32 ÷ 4', '32 × 4', '32 - 4', '4 ÷ 32']),
              sa('The tape diagram shows 16 split into 8 equal parts.\nWhat number goes in each part?', 'Answer:', key='2',
                 fig=tape(dict(n=8, brace='16'))),
              tf('36 split into 6 equal parts gives 5 in each part.', key=False),
          ]),
      ],
      f1=B('Use visual models to divide fractions by fractions', '6.NS.A.1', [
          sa('How many {1/6}s are in {2/3}?', 'Answer:', key='4'),
          tf('{3/4} ÷ {1/8} = 6 because there are 6 eighths in {3/4}.', key=True),
          mc('A model shows 2 wholes, each cut into thirds.\nHow many {1/3}s are in 2?', ['6', '{2/3}', '5', '{1/6}']),
          sa('Divide.\n{5/6} ÷ {1/12}', 'Quotient:', key='10'),
          tf('{2/5} ÷ {1/10} = {2/50}', key=False),
      ]),
      f2=B('Multiply rational numbers', '7.NS.A.2.c', [
          sa('Find the product.\n{3/4} × (-8)', 'Product:', key='-6'),
          tf('-{2/3} × {3/4} = -{1/2}', key=True),
          mc('Find the product.\n(-{1/2}) × (-{3/5})', ['{3/10}', '-{3/10}', '{4/7}', '-{4/7}']),
          sa('Find the product.\n-{2/5} × 15', 'Product:', key='-6'),
          tf('(-1) × (-{5/6}) = -{5/6}', key=False),
      ]), num=66),

]
