from qb import S, B, sa, mc, tf, nl, coord, table, tri, plot, hist, draw_write
from common import grid, tplot

FRUIT = hist(['Apples', 'Pears', 'Plums', 'Kiwis'], [20, 35, 10, 25], gap=0.35, ymax=40, ystep=5,
             xlabel='Fruit', ylabel='Number sold')
WALKS = hist(['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], [4, 8, 6, 10, 2], gap=0.35, ymax=10, ystep=2,
             xlabel='Day', ylabel='Miles walked')
DRAW = dict(k='grid', rows=9, cols=12, shade=0, h=230, maxcell=24,
            desc='Blank grid for drawing. Each small square is 1 unit by 1 unit.')


def angles(rays, labels, ra=(), desc=None, h=230):
    d = dict(k='rays', rays=list(rays), labels=list(labels), ra=list(ra), h=h, fs=1.05, lr=0.62)
    if desc:
        d['desc'] = desc
    return d


PEARS = grid(5, 10, ystep=2, xlabel='Pounds', ylabel='Cost ($)', pts=[(1, 2), (2, 4), (3, 6)], lines=[((0, 0), (5, 10))])

SETS = [
    # ------------------------------------------------------------------ 5.G.A.1
    S('5.G.A.1', 'Understand the coordinate plane: axes, origin, and coordinates',
      main=[
          mc('What is the point where the x-axis and the y-axis meet called?', ['The origin', 'The x-coordinate', 'The y-axis', 'A quadrant']),
          sa('In the ordered pair (7, 2), what does the 7 tell you?', 'Answer:',
             key='Start at the origin and move 7 units along the x-axis (to the right).'),
          sa('What are the coordinates of point A?', 'A =', key='(3, 5)', fig=grid(8, 8, pts=[(3, 5, 'A')])),
          tf('To reach (0, 6), you start at the origin and move 6 units to the right along the x-axis.', key=False),
          mc('Which point is at (5, 1)?', ['Point A', 'Point B', 'Point C', 'Point D'],
             fig=grid(8, 8, pts=[(5, 1, 'A'), (1, 5, 'B'), (5, 5, 'C'), (1, 1, 'D')])),
      ],
      back=[
          B('Whole numbers on a number line', '2.MD.B.6', [
              sa('What number is at point P?', 'P =', key='6', fig=nl(0, 10, 1, pts=[(6, 'P')])),
              tf('On a number line, numbers increase from left to right.', key=True),
              mc('Which number is 4 units to the right of 0?', ['4', '0', '8', '40']),
              sa('How many units is it from 0 to 9 on a number line?', 'Units:', key='9'),
              tf('On a number line, 3 is farther from 0 than 7 is.', key=False),
          ]),
          B('Perpendicular lines', '4.G.A.1', [
              tf('Perpendicular lines meet to form right angles.', key=True),
              mc('The x-axis and the y-axis are ___.', ['perpendicular', 'parallel', 'curved', 'the same line']),
              sa('How many degrees are in a right angle?', 'Degrees:', key='90'),
              tf('Parallel lines never meet.', key=True),
              mc('Which letter is made of two perpendicular line segments?', ['L', 'O', 'S', 'C']),
          ]),
      ],
      f1=B('Name the coordinates of points in all four quadrants', '6.NS.C.6.c', [
          sa('What are the coordinates of point A?', 'A =', key='(-3, 4)', fig=coord(pts=[(-3, 4, 'A')])),
          sa('What are the coordinates of point B?', 'B =', key='(2, -5)', fig=coord(pts=[(2, -5, 'B')])),
          mc('Which ordered pair names point C?', ['(-4, -2)', '(-2, -4)', '(4, 2)', '(-4, 2)'], fig=coord(pts=[(-4, -2, 'C')])),
          sa('What are the coordinates of point D?', 'D =', key='(0, -3)', fig=coord(pts=[(0, -3, 'D')])),
          tf('Point E is located at (5, -1).', key=False, fig=coord(pts=[(-1, 5, 'E')])),
      ]),
      f2=B('Interpret a point on the graph of a proportional relationship', '7.RP.A.2.d', [
          sa('The graph shows the cost of pears.\nWhat does the point (3, 6) represent?', 'Meaning:', key='3 pounds of pears cost $6.', fig=PEARS),
          mc('The graph shows the cost of pears.\nWhat does the point (1, 2) represent?',
             ['1 pound costs $2.', '2 pounds cost $1.', 'The cost starts at $2.', '$1 buys 2 pounds.'], fig=PEARS),
          tf('On the graph of a proportional relationship between pounds and cost, the point (0, 0) means 0 pounds cost $0.', key=True),
          sa('The graph of a proportional relationship passes through (1, r) and (4, 20).\nWhat is r?', 'r =', key='5'),
          mc('A graph shows a proportional relationship between the time x, in hours, that a bus drives and the distance y, in miles. It passes through (2, 90).\nWhat does this point mean?',
             ['In 2 hours, the distance is 90 miles.', 'In 90 hours, the distance is 2 miles.', 'The speed is 2 miles per hour.', 'The speed is 90 miles per hour.']),
      ])),

    # ------------------------------------------------------------------ 5.G.A.2 (graph points)
    S('5.G.A.2', 'Graph points in the first quadrant',
      main=[
          plot('Plot and label the points A(2, 7), B(6, 3), and C(0, 5).', grid(8, 8),
               key='A plotted at (2, 7), B at (6, 3), and C at (0, 5) on the y-axis, each labeled'),
          plot('Plot and label the points D(4, 4), E(7, 0), and F(1, 6).', grid(8, 8),
               key='D plotted at (4, 4), E at (7, 0) on the x-axis, and F at (1, 6), each labeled'),
          plot('Plot the points from the table.', tplot([['Hours', '1', '2', '3', '4'], ['Miles', '3', '6', '9', '12']], 5, 14, ystep=2),
               key='Points plotted at (1, 3), (2, 6), (3, 9), (4, 12)'),
          plot('Plot and label the points G(3, 2{1/2}) and H(5{1/2}, 4).', grid(8, 8),
               key='G plotted at (3, 2 1/2), halfway between 2 and 3 on the y-axis scale; H plotted at (5 1/2, 4); each labeled'),
          draw_write('Plot P(2, 3) and Q(2, 7).\nHow far apart are the two points?', grid(8, 8), 'Distance:',
                     draw='P plotted at (2, 3) and Q plotted at (2, 7)', key='4 units',
                     note='Grade both: both points at the correct places, and the distance 4 units.'),
      ],
      back=[
          B('Read a scaled bar graph', '3.MD.B.3', [
              mc('What does each grid line on the scale stand for?', ['5', '1', '10', '20'], fig=FRUIT),
              sa('How many pears were sold?', 'Pears:', key='35', fig=FRUIT),
              tf('More kiwis than apples were sold.', key=True, fig=FRUIT),
              sa('How many fewer plums than pears were sold?', 'Plums:', key='25', fig=FRUIT),
              sa('How many apples and kiwis were sold in all?', 'Fruit:', key='45', fig=FRUIT),
          ], num=2),
          B('Fractions and whole numbers on a number line', '3.NF.A.2', [
              sa('What number is at point A?', 'A =', key='2 1/2', note='5/2 is also correct.',
                 fig=nl(0, 4, 0.5, labels={0: '0', 1: '1', 2: '2', 3: '3', 4: '4'}, pts=[(2.5, 'A')])),
              tf('2{1/2} is halfway between 2 and 3 on a number line.', key=True),
              mc('Which point is at 1{1/2}?', ['Point A', 'Point B', 'Point C', 'Point D'],
                 fig=nl(0, 4, 0.5, labels={0: '0', 1: '1', 2: '2', 3: '3', 4: '4'}, pts=[(1.5, 'A'), (2.5, 'B'), (0.5, 'C'), (3.5, 'D')])),
              sa('What number is at point B?', 'B =', key='4', fig=nl(0, 6, 1, labels={0: '0', 3: '3', 6: '6'}, pts=[(4, 'B')])),
              tf('On a number line, 5{1/2} is between 6 and 7.', key=False),
          ], num=3),
      ],
      f1=B('Reflect points across the axes', '6.NS.C.6.b', [
          plot('Plot and label A(2, 4). Then plot its reflection across the x-axis and label it B.', coord(),
               key='A plotted at (2, 4) and B at (2, -4), each labeled'),
          sa('The point (5, 2) is reflected across the x-axis.\nWhat are the coordinates of its image?', 'Image:', key='(5, -2)'),
          mc('The point (-3, 5) is reflected across the x-axis.\nWhat are the coordinates of its image?', ['(-3, -5)', '(3, 5)', '(3, -5)', '(5, -3)']),
          sa('The point (-4, 1) is reflected across the y-axis.\nWhat are the coordinates of its image?', 'Image:', key='(4, 1)'),
          tf('The points (3, 5) and (-3, 5) are reflections of each other across the x-axis.', key=False),
      ]),
      f2=B('Graph pairs to decide whether a relationship is proportional', '7.RP.A.2.a', [
          draw_write('Graph the pairs (1, 3), (2, 6), and (4, 12).\nIs the relationship proportional? Explain using your graph.', grid(5, 14, ystep=2),
                     ['Answer:', 'Reason:'], draw='Points plotted at (1, 3), (2, 6) and (4, 12)',
                     key='Yes; the points lie on a straight line through (0, 0)',
                     note='Grade both: all three points at the correct places, and "yes" with the reason (a straight line through the origin, or y = 3x for every point).'),
          draw_write('Graph the pairs (0, 2), (1, 4), and (2, 6).\nIs the relationship proportional? Explain using your graph.', grid(4, 8),
                     ['Answer:', 'Reason:'], draw='Points plotted at (0, 2), (1, 4) and (2, 6)',
                     key='No; the points are on a line, but the line does not pass through (0, 0)',
                     note='Grade both: all three points at the correct places, and "no" with the reason (the line does not go through the origin; when x is 0, y is 2).'),
          mc('Which graph shows a proportional relationship?', ['A straight line through (0, 0)', 'A straight line through (0, 3)',
                                                               'A curve through (0, 0)', 'Points that are not on a line']),
          tf('The points (2, 1), (4, 2), and (6, 3) show a proportional relationship.', key=True),
          draw_write('Graph the pairs from the table.\nIs the relationship proportional? Explain using your graph.',
                     tplot([['x', '1', '2', '3'], ['y', '4', '8', '12']], 4, 14, ystep=2), ['Answer:', 'Reason:'],
                     draw='Points plotted at (1, 4), (2, 8) and (3, 12)', key='Yes; the points lie on a straight line through (0, 0)',
                     note='Grade both: all three points at the correct places, and "yes" with the reason (a straight line through the origin, or y = 4x).'),
      ])),

    # ------------------------------------------------------------------ 5.G.A.2 (real-world)
    S('5.G.A.2', 'Solve real-world problems by graphing points and interpreting coordinates',
      main=[
          sa('The grid is a map. Each unit is 1 block.\nHow many blocks is it from the school S to the library L?', 'Blocks:', key='5',
             fig=grid(10, 10, pts=[(2, 3, 'S'), (2, 8, 'L')])),
          sa('The graph shows the height of a plant.\nHow tall was the plant after 4 weeks?', 'Height:', key='8 cm',
             fig=grid(6, 12, ystep=2, xlabel='Weeks', ylabel='Height (cm)', pts=[(1, 2), (2, 4), (3, 6), (4, 8), (5, 10)])),
          mc('The point (3, 12) is on a graph of hours worked (x) and dollars earned (y).\nWhat does the point mean?',
             ['Working 3 hours earns $12.', 'Working 12 hours earns $3.', 'Each hour earns $3.', 'The pay starts at $12.']),
          plot('The table shows the cost of a taxi ride.\nGraph the points.', tplot([['Miles', '1', '2', '3', '4'], ['Cost ($)', '5', '7', '9', '11']], 5, 12),
               key='Points plotted at (1, 5), (2, 7), (3, 9), (4, 11)'),
          sa('On a map grid, the park is at (1, 6) and the pool is at (7, 6). Each unit is 100 meters.\nHow far apart are the park and the pool?',
             'Distance:', key='600 meters'),
      ],
      back=[
          B('Distance between whole numbers on a number line', '2.MD.B.6', [
              sa('What is the distance from 2 to 7 on a number line?', 'Distance:', key='5 units'),
              tf('The distance from 3 to 10 is 13 units.', key=False),
              mc('How many units apart are 1 and 8 on a number line?', ['7', '9', '8', '1']),
              sa('What is the distance from 6 to 6 on a number line?', 'Distance:', key='0'),
              sa('How many units apart are points A and B?', 'Units:', key='7', fig=nl(0, 10, 1, pts=[(2, 'A'), (9, 'B')])),
          ], num=2),
          B('Solve problems with a scaled bar graph', '3.MD.B.3', [
              sa('How many miles were walked on Thursday?', 'Miles:', key='10', fig=WALKS),
              tf('The same number of miles were walked on Monday and Wednesday.', key=False, fig=WALKS),
              mc('On which day were 8 miles walked?', ['Tuesday', 'Monday', 'Thursday', 'Friday'], fig=WALKS),
              sa('How many more miles were walked on Thursday than on Friday?', 'Miles:', key='8', fig=WALKS),
              tf('Each grid line on the scale stands for 2 miles.', key=True, fig=WALKS),
          ], num=3),
      ],
      f1=B('Find distances in all four quadrants', '6.NS.C.8', [
          sa('Find the distance between (-4, 2) and (5, 2).', 'Distance:', key='9 units'),
          sa('Find the distance between (3, -6) and (3, 1).', 'Distance:', key='7 units'),
          mc('On a map, the store is at (-2, -3) and the bank is at (-2, 4). Each unit is 1 block.\nHow far apart are they?',
             ['7 blocks', '1 block', '6 blocks', '4 blocks']),
          sa('A rectangle has vertices at (-3, 1), (2, 1), (2, -2), and (-3, -2).\nWhat is its perimeter?', 'Perimeter:', key='16 units'),
          tf('The distance between (-5, 0) and (5, 0) is 0.', key=False),
      ]),
      f2=B('Use a scale on a map grid', '7.G.A.1', [
          sa('On a map grid, each unit is 2 miles. Two towns are at (1, 3) and (6, 3).\nWhat is the actual distance between them?', 'Distance:', key='10 miles'),
          sa('On a floor plan, each unit is 1{1/2} feet. A wall goes from (0, 0) to (0, 8).\nHow long is the real wall?', 'Length:', key='12 feet'),
          mc('A scale drawing uses 1 grid unit = 5 m. A path on the grid is 7 units long.\nHow long is the real path?', ['35 m', '12 m', '7 m', '2 m']),
          sa('A garden plan has corners at (0, 0), (6, 0), (6, 4), and (0, 4). Each unit is 3 feet.\nWhat are the real length and width?',
             'Length and width:', key='18 feet by 12 feet'),
          tf('If each grid unit is 10 km, the points (2, 5) and (2, 9) are 4 km apart.', key=False),
      ])),

    # ------------------------------------------------------------------ 5.G.B.3
    S('5.G.B.3', 'Attributes of a category belong to all of its subcategories',
      main=[
          tf('Every parallelogram has opposite sides of equal length. A rhombus is a parallelogram, so every rhombus has opposite sides of equal length.', key=True),
          mc('All parallelograms have two pairs of parallel sides.\nWhich shape must also have two pairs of parallel sides?',
             ['Rhombus', 'Kite', 'Triangle', 'Pentagon']),
          sa('A rhombus is a quadrilateral with 4 sides of equal length.\nIs every square a rhombus? Explain.', ['Answer:', 'Explanation:'],
             key='Yes', note='A square is a quadrilateral with 4 sides of equal length, so it has every attribute of a rhombus.'),
          tf('All quadrilaterals have 4 right angles.', key=False),
          mc('Which statement is true?', ['Every square is a rectangle.', 'Every rectangle is a square.',
                                          'Every parallelogram is a square.', 'Every quadrilateral is a rectangle.']),
      ],
      back=[
          B('Quadrilaterals and their attributes', '3.G.A.1', [
              sa('How many sides does every quadrilateral have?', 'Sides:', key='4'),
              tf('Triangles, rectangles, and squares are all quadrilaterals.', key=False),
              mc('Which shape is NOT a quadrilateral?', ['Triangle', 'Square', 'Rectangle', 'Rhombus']),
              tf('A square has 4 sides of equal length.', key=True),
              sa('Name a quadrilateral that always has 4 right angles.', 'Shape:', key='Rectangle', note='Square is also correct.'),
          ]),
          B('Parallel lines, perpendicular lines, and angles', '4.G.A.1', [
              tf('Parallel lines are always the same distance apart.', key=True),
              mc('Which angle measure is a right angle?', ['90°', '45°', '120°', '180°']),
              sa('What do we call two lines that meet to form right angles?', 'Answer:', key='Perpendicular lines'),
              tf('An obtuse angle is smaller than a right angle.', key=False),
              mc('How many pairs of parallel sides does a rectangle have?', ['2', '1', '0', '4']),
          ]),
          B('Classifying shapes by sides and angles', '4.G.A.2', [
              tf('A shape with no parallel sides can still be a quadrilateral.', key=True),
              mc('Which kind of triangle has a right angle?', ['A right triangle', 'An acute triangle', 'An obtuse triangle', 'An equilateral triangle']),
              sa('How many right angles does a square have?', 'Right angles:', key='4'),
              tf('A rhombus always has 4 right angles.', key=False),
              mc('Which shape always has two pairs of parallel sides?', ['Rectangle', 'Triangle', 'Pentagon', 'Kite']),
          ]),
      ],
      f1=B('Draw polygons in the coordinate plane', '6.G.A.3', [
          draw_write('Plot A(-2, 1), B(3, 1), C(3, -3), and D(-2, -3). Connect them in order.\nWhat is the most specific name for the polygon?', coord(),
                     'Most specific name:', draw='A, B, C and D plotted and joined in order A-B-C-D-A',
                     key='Rectangle',
                     note='Grade both: the four points and the four connecting segments, and the name. The sides are 5 and 4 units with four right angles, '
                          'so "rectangle" is the most specific name. "Parallelogram" or "quadrilateral" are true but not the most specific; "square" is wrong.'),
          draw_write('Plot E(0, 3), F(3, 0), G(0, -3), and H(-3, 0). Connect them in order.\nWhat is the most specific name for the polygon?', coord(),
                     'Most specific name:', draw='E, F, G and H plotted and joined in order E-F-G-H-E',
                     key='Square',
                     note='Grade both: the four points and the four connecting segments, and the name. All four sides are equal and all four angles are right angles, '
                          'so "square" is the most specific name. "Rhombus", "rectangle", "parallelogram" and "quadrilateral" are true but not the most specific.'),
          mc('The points (-1, 2), (4, 2), and (4, -1) are three vertices of a rectangle.\nWhat is the fourth vertex?',
             ['(-1, -1)', '(4, 2)', '(-1, 4)', '(1, -1)']),
          sa('What is the length of the side from (-2, 5) to (4, 5)?', 'Length:', key='6 units'),
          tf('The points (0, 0), (4, 0), (4, 2), and (0, 2) are the vertices of a square.', key=False),
      ]),
      f2=B('Draw shapes with given conditions', '7.G.A.2', [
          draw_write('Draw a triangle with sides of 3 units, 4 units, and 5 units. Put the 3-unit and 4-unit sides along grid lines.\nClassify the triangle by its angles.',
                     DRAW, 'Kind of triangle:', draw='A triangle with a 3-unit side and a 4-unit side along grid lines meeting at a right angle, and the third side (5 units) joining their ends',
                     key='Right triangle', note='Grade both: the drawn side lengths 3 and 4 along grid lines with the third side joining them, and "right triangle".'),
          sa('Can a triangle have sides of 2 cm, 2 cm, and 5 cm? Explain.', ['Answer:', 'Explanation:'], key='No',
             note='2 + 2 = 4 is less than 5, so the two short sides cannot meet to close the triangle.'),
          draw_write('Draw a triangle with angles of 90°, 45°, and 45°. Make its two shorter sides 4 units long, along grid lines.\nCould a triangle with these same angles be drawn in a different size?',
                     DRAW, 'Answer:', draw='A right triangle with two 4-unit legs along grid lines meeting at a right angle, and the third side joining their ends',
                     key='Yes', note='Grade both: the drawing (two 4-unit legs at a right angle) and "yes": three angles do not fix the size, '
                                     'so larger or smaller triangles with the same angles can be drawn.'),
          sa('Can a triangle have angles of 100°, 50°, and 40°? Explain.', ['Answer:', 'Explanation:'], key='No',
             note='The angles of a triangle add to 180°, but 100 + 50 + 40 = 190.'),
          draw_write('Draw a quadrilateral that has exactly one pair of parallel sides.\nWhat is the name of this kind of quadrilateral?', DRAW, 'Name:',
                     draw='A quadrilateral with one pair of parallel sides (for example a horizontal top and bottom of different lengths) and one pair of sides that are not parallel',
                     key='Trapezoid', note='Grade both: exactly one pair of parallel sides in the drawing, and the name "trapezoid".'),
      ])),

    # ------------------------------------------------------------------ 5.G.B.4 (quadrilaterals)
    S('5.G.B.4', 'Classify quadrilaterals in a hierarchy based on their properties',
      main=[
          mc('Which list goes from the most general category to the most specific?',
             ['Quadrilateral, parallelogram, rectangle, square', 'Square, rectangle, parallelogram, quadrilateral',
              'Rectangle, square, quadrilateral, parallelogram', 'Parallelogram, quadrilateral, square, rectangle']),
          tf('A square is a rectangle, a rhombus, and a parallelogram.', key=True),
          sa('Which of these categories does every rhombus belong to?\nquadrilateral, parallelogram, rectangle, square', 'Categories:',
             key='Quadrilateral and parallelogram'),
          mc('A shape has 4 sides of equal length and 4 right angles.\nWhat is the most specific name for it?', ['Square', 'Rhombus', 'Rectangle', 'Quadrilateral']),
          tf('Every parallelogram is a rhombus.', key=False),
      ],
      back=[
          B('Quadrilaterals', '3.G.A.1', [
              tf('A rectangle is a quadrilateral.', key=True),
              mc('Which shape always has 4 sides of equal length?', ['Rhombus', 'Rectangle', 'Kite', 'Triangle']),
              sa('How many angles does a quadrilateral have?', 'Angles:', key='4'),
              tf('Every quadrilateral is a square.', key=False),
              sa('Name a shape that is a quadrilateral but is not a parallelogram.', 'Shape:', key='A trapezoid with exactly one pair of parallel sides',
                 note='Any quadrilateral with fewer than two pairs of parallel sides is correct, for example a trapezoid with exactly one pair of parallel sides '
                      'or a kite with no parallel sides. A rhombus, rectangle or square is wrong because each is a parallelogram.'),
          ]),
          B('Classifying by parallel sides and right angles', '4.G.A.2', [
              tf('A quadrilateral with 2 pairs of parallel sides is a parallelogram.', key=True),
              mc('Which shape always has 4 right angles?', ['Rectangle', 'Rhombus', 'Parallelogram', 'Kite']),
              sa('How many pairs of parallel sides does a parallelogram have?', 'Pairs:', key='2'),
              tf('The sides of a square that meet at a corner are perpendicular.', key=True),
              mc('Which description fits every rhombus?', ['4 sides of equal length', '4 right angles', 'No parallel sides', '3 sides']),
          ]),
      ],
      f1=B('Area of parallelograms, rhombuses, and trapezoids', '6.G.A.1', [
          sa('A parallelogram has a base of 10 cm and a height of 6 cm.\nWhat is its area?', 'Area:', key='60 square cm'),
          sa('A rhombus has a base of 7 in. and a height of 5 in.\nWhat is its area?', 'Area:', key='35 square inches'),
          mc('A trapezoid has bases of 4 m and 10 m and a height of 6 m. It is cut into a 4-m by 6-m rectangle and two triangles, each with a base of 3 m and a height of 6 m.\nWhat is the area of the trapezoid?',
             ['42 square meters', '84 square meters', '24 square meters', '60 square meters']),
          sa('A trapezoid has bases of 6 ft and 10 ft and a height of 4 ft.\nWhat is its area?', 'Area:', key='32 square feet'),
          tf('A parallelogram has a greater area than a rectangle with the same base and the same height.', key=False),
      ]),
      f2=B('Draw quadrilaterals and triangles with given conditions', '7.G.A.2', [
          draw_write('Draw a rectangle that is not a square.\nWrite its side lengths.', DRAW, 'Side lengths:',
                     draw='A rectangle drawn along grid lines with two different side lengths',
                     key='Two different lengths that match the drawing, for example 6 units by 3 units',
                     note='Grade both: four right angles with unequal adjacent sides in the drawing, and side lengths that match it.'),
          draw_write('Draw a rhombus that is not a square, with every side 5 units long.\n(Hint: a side can go 3 units across and 4 units up.)\nHow do you know it is not a square?',
                     DRAW, 'Reason:', draw='A quadrilateral with four 5-unit sides whose angles are not right angles, for example with vertices (0, 0), (5, 0), (8, 4) and (3, 4)',
                     key='Its angles are not right angles.',
                     note='Grade both: four equal sides that are not perpendicular, and a reason that names the angles (not right angles).'),
          sa('Can a quadrilateral have exactly 3 right angles? Explain.', ['Answer:', 'Explanation:'], key='No',
             note='The angles of a quadrilateral add to 360°. If three are 90°, the fourth is 360 - 270 = 90°, so it has 4 right angles.'),
          draw_write('Draw a parallelogram that is not a rectangle, with a base of 6 units and a height of 3 units.\nWhat is its area?', DRAW, 'Area:',
                     draw='A parallelogram with a 6-unit base along a grid line and the opposite side 3 units above it, shifted sideways so the angles are not right angles',
                     key='18 square units', note='Grade both: the drawing meets all three conditions, and the area 18 square units.'),
          sa('A triangle has sides of 6 cm, 6 cm, and 6 cm. Can triangles of different shapes be drawn with these sides? Explain.',
             ['Answer:', 'Explanation:'], key='No',
             note='Three side lengths determine one unique triangle (here an equilateral triangle); every copy is the same shape and size.'),
      ])),

    # ------------------------------------------------------------------ 5.G.B.4 (triangles)
    S('5.G.B.4', 'Classify triangles by their sides and angles',
      main=[
          mc('A triangle has sides of 6 cm, 6 cm, and 6 cm.\nWhich name fits it?', ['Equilateral', 'Scalene', 'Right', 'Obtuse']),
          sa('A triangle has angles of 90°, 50°, and 40°.\nClassify it by its angles.', 'Classification:', key='Right triangle'),
          tf('An isosceles triangle has at least two sides of equal length. Every equilateral triangle is also an isosceles triangle.', key=True),
          mc('A triangle has sides of 3, 5, and 7 units and an angle of 120°.\nWhich name fits it?',
             ['Obtuse scalene', 'Right isosceles', 'Acute equilateral', 'Right scalene']),
          sa('A triangle has angles of 70°, 70°, and 40°.\nClassify it by its angles and by its sides.', ['By angles:', 'By sides:'],
             key='Acute; isosceles', note='Two equal angles mean two equal sides.'),
      ],
      back=[
          B('Right, acute, and obtuse triangles', '4.G.A.2', [
              tf('A right triangle has exactly one right angle.', key=True),
              mc('Which angle measure is obtuse?', ['130°', '90°', '45°', '10°']),
              sa('A triangle has one angle greater than 90°.\nWhat kind of triangle is it?', 'Kind:', key='Obtuse triangle'),
              tf('In an acute triangle, all three angles are less than 90°.', key=True),
              mc('Which angle measure is acute?', ['60°', '90°', '100°', '180°']),
          ]),
          B('Kinds of angles', '4.G.A.1', [
              tf('A right angle measures 90°.', key=True),
              mc('What kind of angle measures 35°?', ['Acute', 'Right', 'Obtuse', 'Straight']),
              sa('What kind of angle measures 150°?', 'Kind:', key='Obtuse'),
              tf('Two right angles together make 360°.', key=False),
              sa('What kind of angle measures exactly 90°?', 'Kind:', key='Right angle'),
          ]),
          B('Triangles', '2.G.A.1', [
              sa('How many sides does a triangle have?', 'Sides:', key='3'),
              tf('A triangle has 3 angles.', key=True),
              mc('Which shape has 3 sides?', ['Triangle', 'Square', 'Pentagon', 'Hexagon']),
              tf('All triangles have sides of equal length.', key=False),
              sa('How many vertices (corners) does a triangle have?', 'Vertices:', key='3'),
          ]),
      ],
      f1=B('Area of triangles', '6.G.A.1', [
          sa('A right triangle has legs that are 6 cm and 8 cm long.\nWhat is its area?', 'Area:', key='24 square cm'),
          sa('A triangle has a base of 10 in. and a height of 7 in.\nWhat is its area?', 'Area:', key='35 square inches'),
          mc('An obtuse triangle has a base of 5 m. Its height, measured outside the triangle, is 4 m.\nWhat is its area?',
             ['10 square meters', '20 square meters', '9 square meters', '40 square meters']),
          sa('Find the area of the triangle.', 'Area:', key='20 square feet', fig=tri(8, 5, 3, '8 ft', '5 ft')),
          tf('Two triangles with the same base and the same height have the same area.', key=True),
      ]),
      f2=B('Write and solve equations for unknown angles', '7.G.B.5', [
          sa('The two angles form a straight line.\nWrite an equation and solve for x.', ['Equation:', 'x ='], key='(3x + 20) + 64 = 180; x = 32',
             note='Any equivalent equation is correct (for example 3x + 84 = 180). Both the equation and x = 32 are required.',
             fig=angles([0, 116, 180], [(58, '(3x + 20)°'), (148, '64°')],
                        desc='A straight line with a ray from a point on it. The angle on the right is labeled (3x + 20)° and the angle on the left is labeled 64°.')),
          sa('The two angles together form a right angle.\nWrite an equation and solve for x.', ['Equation:', 'x ='], key='(2x + 15) + 35 = 90; x = 20',
             note='Any equivalent equation is correct (for example 2x + 50 = 90). Both the equation and x = 20 are required.',
             fig=angles([0, 55, 90], [(22, '(2x + 15)°', 0.98), (73, '35°', 0.6)], ra=[0],
                        desc='A right angle split by a ray into two angles: (2x + 15)° (lower) and 35° (upper). A right-angle mark is shown.')),
          sa('Two lines cross. The marked angles are vertical angles.\nWrite an equation and solve for x.', ['Equation:', 'x ='], key='4x - 10 = 50; x = 15',
             note='Vertical angles are equal. Any equivalent equation is correct. Both the equation and x = 15 are required.',
             fig=angles([0, 50, 180, 230], [(20, '(4x − 10)°', 0.95), (205, '50°', 0.7)],
                        desc='Two lines cross at a point. One angle is labeled (4x − 10)°; the angle vertical to it is labeled 50°.')),
          mc('Three angles together form a straight line.\nWhich equation can be used to find x?',
             ['40 + x + 70 = 180', '40 + x + 70 = 90', 'x = 40 × 70', '40 + x = 70'], cols=1,
             fig=angles([0, 40, 110, 180], [(20, '40°'), (75, 'x°'), (145, '70°')],
                        desc='A straight line with two rays from one point on it, making three angles: 40°, x°, and 70°.')),
          sa('Angle ABC and angle CBD together form a straight line. Angle ABC is (5x)° and angle CBD is (x + 30)°.\nWrite an equation, solve for x, and find both angles.',
             ['Equation:', 'x =', 'Angles:'], key='5x + (x + 30) = 180; x = 25; angle ABC = 125°, angle CBD = 55°',
             note='Any equivalent equation is correct (6x + 30 = 180). All three parts are required.',
             fig=angles([0, 55, 180], [(27, '(x + 30)°'), (117, '(5x)°')],
                        desc='A straight line with a ray from a point on it. The angle on the right is labeled (x + 30)° and the angle on the left is labeled (5x)°.', h=190)),
      ])),

    # ------------------------------------------------------------------ 5.G.B.4 (triangle hierarchy)
    S('5.G.B.4', 'Place triangles in a hierarchy of categories and subcategories',
      main=[
          mc('Which list goes from the most general category to the most specific?',
             ['Triangle, isosceles triangle, equilateral triangle', 'Equilateral triangle, isosceles triangle, triangle',
              'Isosceles triangle, triangle, equilateral triangle', 'Triangle, equilateral triangle, isosceles triangle']),
          tf('Every right isosceles triangle belongs to both the category of right triangles and the category of isosceles triangles.', key=True),
          sa('Isosceles means at least two sides of equal length.\nA triangle has sides of 7, 7, and 7 units. Which of these categories does it belong to?\ntriangle, isosceles, equilateral, scalene',
             'Categories:', key='Triangle, isosceles, and equilateral',
             note='All three are required. Scalene is wrong because a scalene triangle has no sides of equal length.'),
          mc('Isosceles means at least two sides of equal length.\nWhich statement is true?',
             ['Some isosceles triangles are equilateral.', 'Every isosceles triangle is equilateral.',
              'Some scalene triangles are isosceles.', 'No right triangle is isosceles.']),
          sa('Explain why a triangle cannot be both a right triangle and an obtuse triangle.', ['Explanation:', ''],
             key='A right triangle has a 90° angle and an obtuse triangle has an angle greater than 90°. The three angles of a triangle add to 180°, so these two angles together would already be more than 180°.',
             note='Accept the 180° angle-sum reason, or that a triangle can have only one angle of 90° or more because the two sides would '
                  'never meet. The categories "right" and "obtuse" do not overlap.'),
      ],
      back=[
          B('Classify triangles by their angles', '4.G.A.2', [
              tf('A triangle with angles of 30°, 60°, and 90° is a right triangle.', key=True),
              mc('A triangle has angles of 110°, 40°, and 30°.\nWhat kind of triangle is it?', ['Obtuse', 'Right', 'Acute', 'Equilateral']),
              sa('A triangle has angles of 50°, 60°, and 70°.\nIs it acute, right, or obtuse?', 'Answer:', key='Acute'),
              tf('A triangle can have two obtuse angles.', key=False),
              mc('Which three angles could be the angles of an acute triangle?', ['80°, 60°, 40°', '90°, 45°, 45°', '100°, 50°, 30°', '120°, 30°, 30°']),
          ]),
          B('Shapes in different categories share attributes', '3.G.A.1', [
              tf('Rhombuses, rectangles, and squares are all quadrilaterals.', key=True),
              mc('What do all quadrilaterals have in common?', ['4 sides', '4 right angles', '4 sides of equal length', '2 pairs of parallel sides']),
              sa('Name a quadrilateral that is not a rectangle.', 'Shape:', key='A rhombus that is not a square',
                 note='Any quadrilateral that is not a rectangle is correct, for example a trapezoid or a rhombus that is not a square.'),
              tf('Every quadrilateral is a rhombus.', key=False),
              mc('A square is also a ___.', ['rectangle', 'triangle', 'pentagon', 'hexagon']),
          ]),
      ],
      f1=B('Area of special triangles', '6.G.A.1', [
          sa('A right isosceles triangle has legs that are 6 cm long.\nWhat is its area?', 'Area:', key='18 square cm'),
          tf('A triangle with a base of 4 in. and a height of 3{1/2} in. has an area of 7 square inches.', key=True),
          mc('A square with sides of 8 m is cut along a diagonal into two triangles.\nWhat is the area of each triangle?',
             ['32 square meters', '64 square meters', '16 square meters', '8 square meters']),
          sa('An isosceles triangle has a base of 10 ft and a height of 12 ft.\nWhat is its area?', 'Area:', key='60 square feet'),
          tf('A right triangle with legs of 5 units and 9 units has an area of 45 square units.', key=False),
      ]),
      f2=B('Decide whether conditions give one triangle, more than one, or none', '7.G.A.2', [
          mc('How many differently shaped triangles can be drawn with sides of 5 cm, 5 cm, and 8 cm?', ['Exactly one', 'More than one', 'None', 'Exactly two']),
          tf('Triangles of many different sizes can be drawn with angles of 60°, 60°, and 60°.', key=True),
          sa('Can a triangle have sides of 3 m, 4 m, and 8 m? Explain.', ['Answer:', 'Explanation:'], key='No',
             note='3 + 4 = 7 is less than 8, so the two shorter sides cannot meet.'),
          tf('A triangle can have angles of 90°, 60°, and 40°.', key=False),
          sa('Can a right triangle also be isosceles? If it can, give its angle measures.', ['Answer:', 'Angles:'], key='Yes; 90°, 45°, 45°'),
      ]), num=71),
]
