from qb import S, B, sa, mc, tf, table, rect, tri, prism
from common import bar

SETS = [
    # ------------------------------------------------------------------ 5.NF.B.4.b
    S('5.NF.B.4.b', 'Find the area of a rectangle with fractional side lengths',
      main=[
          sa('Find the area of the rectangle.', 'Area:', key='1/2 square foot', note='15/30 is also correct.',
             fig=rect(5, 3, '{5/6} ft', '{3/5} ft')),
          sa('A rectangle is 2{1/2} inches long and {4/5} inch wide.\nWhat is its area?', 'Area:', key='2 square inches'),
          mc('A rectangle that is {2/3} unit by {3/4} unit is tiled with small rectangles that are each {1/3} unit by {1/4} unit.\nWhat is the area of the large rectangle?',
             ['{6/12} square unit', '{5/7} square unit', '{6/7} square unit', '1{5/12} square units']),
          sa('Find the area of the rectangle.', 'Area:', key='1 5/16 square yards', note='21/16 is also correct.',
             fig=rect(6, 3.5, '1{1/2} yd', '{7/8} yd')),
          tf('A rectangle that is {1/2} foot by {1/2} foot has an area of 1 square foot.', key=False),
      ],
      back=[
          B('Area by tiling with unit squares', '3.MD.C.7.a', [
              sa('A rectangle is covered by 4 rows of 6 unit squares, with no gaps.\nWhat is its area?', 'Area:', key='24 square units'),
              tf('Tiling a 3-by-5 rectangle takes 8 unit squares.', key=False),
              mc('How many unit squares cover a 7-by-2 rectangle?', ['14', '9', '18', '72']),
              sa('A rectangle has 5 rows of unit squares with 8 squares in each row.\nWhat is its area?', 'Area:', key='40 square units'),
              tf('The number of unit squares that cover a rectangle equals its length times its width.', key=True),
          ]),
          B('The area formula for rectangles', '4.MD.A.3', [
              sa('A rectangle is 12 m long and 5 m wide.\nWhat is its area?', 'Area:', key='60 square meters'),
              sa('A rectangle has an area of 54 square feet and a length of 9 feet.\nWhat is its width?', 'Width:', key='6 feet'),
              tf('The formula A = l × w gives the area of a rectangle.', key=True),
              mc('A rectangle is 15 cm long and 4 cm wide.\nWhat is its area?', ['60 square cm', '38 square cm', '19 square cm', '45 square cm']),
              sa('Find the area of the rectangle.', 'Area:', key='40 square inches', fig=rect(8, 5, '8 in.', '5 in.')),
          ]),
          B('Multiplying fractions', '5.NF.B.4.a', [
              sa('Multiply.\n{5/6} × {3/5}', 'Product:', key='1/2'),
              sa('Multiply.\n{5/2} × {4/5}', 'Product:', key='2'),
              tf('{2/3} × {3/4} = {6/12}', key=True),
              mc('{3/2} × {7/8} = ?', ['{21/16}', '{10/10}', '{21/8}', '{3/7}']),
              sa('Multiply.\n{1/2} × {1/2}', 'Product:', key='1/4'),
          ]),
      ],
      f1=B('Area of triangles and other polygons with fractional measures', '6.G.A.1', [
          sa('A triangle has a base of 4{1/2} inches and a height of 2 inches.\nWhat is its area?', 'Area:', key='4 1/2 square inches'),
          sa('A parallelogram has a base of 3{1/4} feet and a height of 4 feet.\nWhat is its area?', 'Area:', key='13 square feet'),
          mc('A triangle has a base of {3/4} m and a height of {2/3} m.\nWhat is its area?',
             ['{1/4} square meter', '{1/2} square meter', '{5/7} square meter', '{6/7} square meter']),
          sa('Find the area of the triangle.', 'Area:', key='7 1/2 square cm', fig=tri(6, 2.5, 2, '6 cm', '2{1/2} cm')),
          tf('A trapezoid with bases of 2{1/2} m and 3{1/2} m and a height of 2 m has an area of 6 square meters.', key=True),
      ]),
      f2=B('Area of composite figures', '7.G.B.6', [
          sa('A figure is made of a rectangle that is 6{1/2} ft by 4 ft and a triangle with a base of 4 ft and a height of 3 ft.\nWhat is the total area?',
             'Area:', key='32 square feet'),
          sa('A rectangular garden is 10 m by 7{1/2} m. A square patio with 2{1/2}-m sides is inside the garden.\nWhat is the area of the garden that is not patio?',
             'Area:', key='68 3/4 square meters', note='68.75 is also correct.'),
          mc('A {1/2}-by-2 rectangle is cut out of a 5-by-4 rectangle.\nWhat is the area of the part that is left?',
             ['19 square units', '20 square units', '18 square units', '21 square units']),
          sa('A kite is made of two triangles. Each triangle has a base of 8 in. and a height of 3{1/2} in.\nWhat is the area of the kite?',
             'Area:', key='28 square inches'),
          tf('A figure made of two {1/2}-by-3 rectangles that do not overlap has an area of 6 square units.', key=False),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.5.a
    S('5.NF.B.5.a', 'Compare the size of a product to the size of one factor without multiplying',
      main=[
          mc('Without multiplying, how does {3/4} × 20 compare to 20?',
             ['It is less than 20.', 'It is greater than 20.', 'It is equal to 20.', 'It is 4 times 20.']),
          tf('5 × 3{1/2} is greater than 5.', key=True),
          sa('Without multiplying, is {2/3} × 15 greater than, less than, or equal to 15?', 'Answer:', key='Less than 15'),
          mc('Which product is greater than 8?', ['{9/8} × 8', '{7/8} × 8', '{1/2} × 8', '{8/8} × 8']),
          sa('A photo is 6 inches wide. It is resized to {5/4} of its width.\nIs the new width greater than or less than 6 inches?', 'Answer:',
             key='Greater than 6 inches', note='5/4 is greater than 1. The new width is 7 1/2 inches.'),
      ],
      back=[
          B('Multiplicative comparison', '4.OA.A.2', [
              tf('3 × 12 is 3 more than 12.', key=False),
              sa('A dog weighs 4 times as much as a 6-pound cat.\nHow much does the dog weigh?', 'Weight:', key='24 pounds'),
              mc('Which number is 5 times as much as 7?', ['35', '12', '2', '57']),
              tf('2 × 9 is less than 9.', key=False),
              sa('Fill in the blank.\n42 is ___ times as much as 7.', 'Blank:', key='6'),
          ]),
          B('Comparing fractions to 1', '4.NF.A.2', [
              tf('{4/5} is greater than 1.', key=False),
              mc('Which fraction is less than 1?', ['{6/7}', '{7/6}', '{9/9}', '{3/2}']),
              sa('Write >, <, or = to compare.\n{8/8} ___ 1', 'Symbol:', key='='),
              tf('{3/5} > 1', key=False),
              sa('Is {11/10} greater than, less than, or equal to 1?', 'Answer:', key='Greater than 1'),
          ]),
      ],
      f1=B('Scale quantities in ratio tables', '6.RP.A.3.a', [
          sa('A recipe uses 2 cups of rice for every 3 cups of water.\nHow many cups of water are needed for 8 cups of rice?', 'Cups of water:', key='12'),
          mc('A ratio table starts with 4 : 10.\nWhich ratio could also be in the table?', ['2 : 5', '4 : 5', '8 : 15', '10 : 4']),
          sa('The table shows equivalent ratios.\nFind the missing value.', 'Missing value:', key='15',
             fig=table([['Red', '3', '6', '?'], ['Blue', '5', '10', '25']])),
          tf('Multiplying both numbers in 6 : 9 by {1/3} gives 2 : 3, an equivalent ratio.', key=True),
          sa('A map shows 5 km for every 2 cm.\nHow many kilometers do 7 cm show?', 'Kilometers:', key='17.5 km', note='17 1/2 is also correct.'),
      ]),
      f2=B('Use a scale to find lengths in scale drawings', '7.G.A.1', [
          sa('A scale drawing uses 1 inch = 4 feet. A wall is 3{1/2} inches long in the drawing.\nHow long is the real wall?', 'Length:', key='14 feet'),
          sa('A room is 15 feet long.\nHow long is it on a drawing with a scale of 1 inch = 3 feet?', 'Length:', key='5 inches'),
          mc('A drawing is reduced to {1/2} of its size.\nA 10-cm side becomes how long?', ['5 cm', '20 cm', '10 cm', '2 cm']),
          sa('A drawing that is 4 cm by 6 cm is enlarged by a scale factor of {3/2}.\nWhat are the new dimensions?', 'Dimensions:', key='6 cm by 9 cm'),
          tf('Using a scale factor less than 1 makes a drawing smaller.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.5.b
    S('5.NF.B.5.b', 'Explain the effect of multiplying by a fraction greater than, less than, or equal to 1',
      main=[
          tf('Multiplying 12 by {7/6} gives a product greater than 12.', key=True),
          mc('Which statement explains why {4/5} × 30 is less than 30?',
             ['{4/5} is less than 1.', '{4/5} is greater than 1.', '30 is greater than 1.', 'The product is a fraction.']),
          sa('Use the fact that {4/4} = 1 to explain why {2/3} = {8/12}.', 'Explanation:',
             key='2/3 × 4/4 = 8/12, and 4/4 = 1, so multiplying by 4/4 does not change the value.',
             note='The response must connect the equivalent fraction to multiplying by a fraction equal to 1.'),
          mc('Which expression has a value equal to 9?', ['{5/5} × 9', '{5/6} × 9', '{6/5} × 9', '{1/5} × 9']),
          sa('Without multiplying, order the products from least to greatest.\n{3/4} × 10, {4/3} × 10, {4/4} × 10', 'Order:',
             key='3/4 × 10, 4/4 × 10, 4/3 × 10'),
      ],
      back=[
          B('Equivalent fractions', '4.NF.A.1', [
              tf('To write a fraction equal to {3/5}, you can multiply its numerator and denominator by the same number.', key=True),
              sa('Find the missing number.\n{3/5} = {?/20}', 'Missing number:', key='12'),
              mc('Which fraction is equivalent to {7/8}?', ['{21/24}', '{14/24}', '{7/16}', '{8/7}']),
              sa('Find the missing number.\n{1/3} = {4/?}', 'Missing number:', key='12'),
              tf('{2/9} = {4/27}', key=False),
          ]),
          B('Fractions equal to 1', '3.NF.A.3.c', [
              tf('{4/4} = 4', key=False),
              sa('Write 1 as a fraction with a denominator of 6.', 'Fraction:', key='6/6'),
              mc('Which fraction is equal to 1?', ['{9/9}', '{9/1}', '{1/9}', '{0/9}']),
              tf('{5/5} is greater than 1.', key=False),
              sa('How many eighths make 1 whole?', 'Eighths:', key='8'),
          ]),
      ],
      f1=B('Percents greater than and less than 100%', '6.RP.A.3.c', [
          tf('150% of 40 is less than 40.', key=False),
          sa('What is 120% of 50?', 'Answer:', key='60'),
          mc('Which value is less than 80?', ['75% of 80', '100% of 80', '125% of 80', '200% of 80']),
          sa('What is 100% of 37?', 'Answer:', key='37'),
          sa('What is 250% of 12?', 'Answer:', key='30'),
      ]),
      f2=B('Use a multiplier for percent increase and decrease', '7.RP.A.3', [
          mc('A $60 price increases by 15%.\nWhich expression gives the new price?', ['1.15 × 60', '0.15 × 60', '0.85 × 60', '60 + 15']),
          sa('A $90 jacket is 20% off.\nMultiply by a decimal to find the sale price.', 'Sale price:', key='$72', note='0.8 × 90 = 72'),
          tf('Multiplying a price by 0.7 decreases it by 30%.', key=True),
          sa('A population of 2,000 grows by 5%.\nWhat is the new population?', 'Population:', key='2,100'),
          mc('Which multiplier shows a 40% decrease?', ['0.6', '0.4', '1.4', '1.04']),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.6 (real-world)
    S('5.NF.B.6', 'Solve real-world problems by multiplying fractions and mixed numbers',
      main=[
          sa('A recipe uses {3/4} cup of oats per batch.\nHow many cups of oats are in 2{1/2} batches?', 'Cups:', key='1 7/8 cups'),
          sa('A garden is 6 m long. {2/3} of its length is planted with beans.\nHow many meters are planted with beans?', 'Meters:', key='4 m'),
          mc('Sam walks {5/8} mile each day.\nHow far does he walk in 4 days?', ['2{1/2} miles', '{5/32} mile', '4{5/8} miles', '{9/8} miles']),
          sa('A board is 3{1/3} feet long. Jo uses {3/5} of the board.\nHow many feet does she use?', 'Feet:', key='2 feet'),
          sa('A pitcher holds 1{1/2} liters. It is {2/3} full.\nHow many liters are in the pitcher?', 'Liters:', key='1 liter'),
      ],
      back=[
          B('Word problems: a whole number times a fraction', '4.NF.B.4.c', [
              sa('Each serving is {2/3} cup.\nHow many cups are in 5 servings?', 'Cups:', key='3 1/3 cups', note='10/3 is also correct.'),
              tf('4 children each drink {3/8} liter of milk. They drink 1{1/2} liters in all.', key=True),
              mc('Each piece of ribbon is {5/6} yard long.\nHow long are 3 pieces in all?', ['2{1/2} yards', '{15/18} yard', '3{5/6} yards', '{5/18} yard']),
              sa('A bug crawls {3/10} meter each minute.\nHow far does it crawl in 7 minutes?', 'Distance:', key='2 1/10 meters',
                 note='21/10 is also correct.'),
              sa('Each bag holds {1/4} pound of nuts.\nHow many pounds are in 6 bags?', 'Pounds:', key='1 1/2 pounds'),
          ]),
          B('Mixed numbers as fractions', '4.NF.B.3.b', [
              sa('Write 2{1/2} as a fraction.', 'Fraction:', key='5/2'),
              sa('Write 3{1/3} as a fraction.', 'Fraction:', key='10/3'),
              tf('1{1/2} = {11/2}', key=False),
              mc('Which fraction is equal to 4{2/5}?', ['{22/5}', '{42/5}', '{11/5}', '{24/5}']),
              sa('Write {15/8} as a mixed number.', 'Mixed number:', key='1 7/8'),
          ]),
          B('Multiplying fractions', '5.NF.B.4.a', [
              sa('Multiply.\n{3/4} × {5/2}', 'Product:', key='15/8', note='1 7/8 is also correct.'),
              sa('Multiply.\n{2/3} × {3/2}', 'Product:', key='1'),
              tf('{10/3} × {3/5} = 2', key=True),
              mc('{3/2} × {2/3} = ?', ['1', '{6/5}', '{5/6}', '{9/4}']),
              sa('Multiply.\n{5/8} × 4', 'Product:', key='2 1/2', note='20/8 or 5/2 is also correct.'),
          ]),
      ],
      f1=B('Word problems with division of fractions', '6.NS.A.1', [
          sa('How many {3/4}-cup servings are in 6 cups of soup?', 'Servings:', key='8'),
          sa('A {7/8}-mile trail is split into {1/8}-mile sections.\nHow many sections are there?', 'Sections:', key='7'),
          mc('A rectangle has an area of {3/4} square foot and a width of {1/2} foot.\nWhat is its length?',
             ['1{1/2} feet', '{3/8} foot', '1{1/4} feet', '{2/3} foot']),
          sa('Ann has 2{1/2} pounds of clay. Each pot uses {5/8} pound.\nHow many pots can she make?', 'Pots:', key='4'),
          tf('{2/3} ÷ {1/6} = {1/9}', key=False),
      ]),
      f2=B('Real-world problems with rational numbers', '7.NS.A.3', [
          sa('A diver descends {3/4} foot per second for 6{1/2} seconds.\nWhat is the diver\'s change in depth?', 'Change:', key='-4 7/8 feet',
             note='"4 7/8 feet down" is also correct.'),
          sa('The temperature was 2°F. It dropped {1/2}°F each hour for 9 hours.\nWhat was the final temperature?', 'Temperature:', key='-2 1/2°F'),
          mc('A stock loses {3/8} dollar each day for 4 days.\nWhat is the total change in value?',
             ['-1{1/2} dollars', '1{1/2} dollars', '-{3/32} dollar', '-4{3/8} dollars']),
          sa('A tank holds 12{1/2} gallons. {2/5} of the water drains out.\nHow many gallons drain out?', 'Gallons:', key='5 gallons'),
          tf('-{2/3} × 4{1/2} = -3', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.6 (mixed numbers)
    S('5.NF.B.6', 'Multiply mixed numbers',
      main=[
          sa('Multiply.\n2{1/2} × 3', 'Product:', key='7 1/2'),
          sa('Multiply.\n1{1/3} × 1{1/2}', 'Product:', key='2'),
          mc('Multiply.\n2{1/4} × 1{2/3}', ['3{3/4}', '2{2/12}', '3{1/6}', '4{1/2}']),
          sa('Multiply.\n3{1/5} × 2{1/2}', 'Product:', key='8'),
          tf('1{1/2} × 1{1/2} = 1{1/4}', key=False),
      ],
      back=[
          B('Mixed numbers and fractions greater than 1', '4.NF.B.3.b', [
              sa('Write 1{3/4} as a fraction.', 'Fraction:', key='7/4'),
              sa('Write {13/3} as a mixed number.', 'Mixed number:', key='4 1/3'),
              tf('2{2/3} = {22/3}', key=False),
              mc('Which mixed number is equal to {9/2}?', ['4{1/2}', '9{1/2}', '2{1/9}', '4{1/9}']),
              sa('Write 5{1/2} as a fraction.', 'Fraction:', key='11/2'),
          ]),
          B('Multiplying fractions', '5.NF.B.4.a', [
              sa('Multiply.\n{7/4} × {2/3}', 'Product:', key='7/6', note='14/12 or 1 1/6 is also correct.'),
              tf('{5/2} × {3/2} = {15/2}', key=False),
              mc('{4/3} × {9/4} = ?', ['3', '{13/7}', '{36/7}', '2']),
              sa('Multiply.\n{5/3} × 6', 'Product:', key='10'),
              sa('Multiply.\n{3/2} × {3/2}', 'Product:', key='9/4', note='2 1/4 is also correct.'),
          ]),
          B('Breaking apart a factor to multiply', '3.OA.B.5', [
              tf('4 × (5 + 2) = 4 × 5 + 4 × 2', key=True),
              sa('Fill in the blank.\n6 × 12 = 6 × 10 + 6 × ___', 'Blank:', key='2'),
              mc('Which expression is equal to 3 × 15?', ['3 × 10 + 3 × 5', '3 × 10 + 5', '3 + 10 × 5', '3 × 10 × 5']),
              tf('7 × 13 = 7 × 10 + 3', key=False),
              sa('Fill in the blank.\n8 × (4 + 1) = 8 × 4 + 8 × ___', 'Blank:', key='1'),
          ]),
      ],
      f1=B('Volume of prisms with fractional edge lengths', '6.G.A.2', [
          sa('A box is 2{1/2} ft by 2 ft by 1{1/2} ft.\nWhat is its volume?', 'Volume:', key='7 1/2 cubic feet'),
          sa('A cube has edges that are 2{1/2} inches long.\nWhat is its volume?', 'Volume:', key='15 5/8 cubic inches',
             note='125/8 is also correct.'),
          mc('A prism has a base area of 3{1/3} square cm and a height of 1{1/2} cm.\nWhat is its volume?',
             ['5 cubic cm', '4{5/6} cubic cm', '3{1/2} cubic cm', '10 cubic cm']),
          sa('Find the volume of the prism.', 'Volume:', key='3 cubic feet', fig=prism(4, 1, 3, labels=('4 ft', '{1/2} ft', '1{1/2} ft'))),
          tf('A box that is {1/2} m by {1/2} m by {1/2} m has a volume of {1/8} cubic meter.', key=True),
      ]),
      f2=B('Surface area and volume of prisms', '7.G.B.6', [
          sa('A rectangular prism is 4 cm by 3 cm by 2{1/2} cm.\nWhat is its surface area?', 'Surface area:', key='59 square cm'),
          sa('A triangular prism has triangle bases with a base of 3 in. and a height of 2{1/2} in. The prism is 6 in. long.\nWhat is its volume?',
             'Volume:', key='22 1/2 cubic inches', note='22.5 is also correct.'),
          mc('A box is 5 in. by 4 in. by 1{1/2} in.\nWhat is its volume?', ['30 cubic inches', '20 cubic inches', '10{1/2} cubic inches', '300 cubic inches']),
          sa('A cube has edges that are 1{1/2} m long.\nWhat is its surface area?', 'Surface area:', key='13 1/2 square meters'),
          tf('A prism with a base area of 7{1/2} square feet and a height of 4 feet has a volume of 11{1/2} cubic feet.', key=False),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.7.a
    S('5.NF.B.7.a', 'Divide a unit fraction by a whole number',
      main=[
          sa('Divide.\n{1/3} ÷ 4', 'Quotient:', key='1/12'),
          sa('Divide.\n{1/2} ÷ 5', 'Quotient:', key='1/10'),
          mc('{1/4} ÷ 2 = ?', ['{1/8}', '{1/2}', '8', '{2/4}']),
          sa('{1/5} of a pan of brownies is shared equally by 3 friends.\nWhat fraction of the whole pan does each friend get?', 'Fraction:', key='1/15'),
          tf('{1/6} ÷ 3 = {1/2}', key=False),
      ],
      back=[
          B('Unit fractions get smaller as the number of parts grows', '3.NF.A.1', [
              tf('When a whole is cut into more equal parts, each part is smaller.', key=True),
              mc('Which unit fraction is the smallest?', ['{1/12}', '{1/2}', '{1/5}', '{1/8}']),
              sa('A bar is cut into 6 equal parts.\nWhat fraction of the bar is one part?', 'Fraction:', key='1/6'),
              tf('{1/3} < {1/4}', key=False),
              sa('What fraction of the bar is shaded?', 'Fraction:', key='1/4', fig=bar(4, 1)),
          ]),
          B('Sharing equally', '3.OA.A.2', [
              sa('15 is shared equally among 5 groups.\nHow much is in each group?', 'Answer:', key='3'),
              tf('Sharing 8 equally between 2 groups gives 4 in each group.', key=True),
              mc('Which expression shows 21 shared equally among 7 people?', ['21 ÷ 7', '21 × 7', '21 - 7', '7 ÷ 21']),
              sa('Divide.\n16 ÷ 4', 'Quotient:', key='4'),
              sa('36 is shared equally among 6 people.\nHow much does each person get?', 'Answer:', key='6'),
          ]),
          B('Multiplying unit fractions', '5.NF.B.4.a', [
              sa('Multiply.\n{1/3} × {1/4}', 'Product:', key='1/12'),
              tf('{1/2} × {1/5} = {1/10}', key=True),
              mc('{1/6} × {1/2} = ?', ['{1/12}', '{1/8}', '{2/6}', '{1/3}']),
              sa('Multiply.\n{1/4} × {1/4}', 'Product:', key='1/16'),
              tf('{1/2} × {1/3} = {2/5}', key=False),
          ]),
      ],
      f1=B('Divide fractions', '6.NS.A.1', [
          sa('Divide.\n{3/4} ÷ 3', 'Quotient:', key='1/4'),
          sa('Divide.\n{2/5} ÷ 4', 'Quotient:', key='1/10'),
          mc('Divide.\n{5/6} ÷ {1/3}', ['2{1/2}', '{5/18}', '{1/2}', '{6/9}']),
          sa('{3/4} pound of trail mix is shared equally among 6 bags.\nHow much trail mix is in each bag?', 'Pounds:', key='1/8 pound'),
          tf('{2/3} ÷ 2 = 1{1/3}', key=False),
      ]),
      f2=B('Divide rational numbers', '7.NS.A.2.b', [
          sa('Find the quotient.\n-{1/3} ÷ 4', 'Quotient:', key='-1/12'),
          sa('Find the quotient.\n{3/5} ÷ (-{3/10})', 'Quotient:', key='-2'),
          mc('Find the quotient.\n(-{1/2}) ÷ (-{1/4})', ['2', '-2', '{1/8}', '-{1/8}']),
          sa('Find the quotient.\n-{4/9} ÷ {2/3}', 'Quotient:', key='-2/3'),
          tf('-({1/2} ÷ 5) = (-{1/2}) ÷ 5', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.7.b
    S('5.NF.B.7.b', 'Divide a whole number by a unit fraction',
      main=[
          sa('Divide.\n4 ÷ {1/5}', 'Quotient:', key='20'),
          sa('Divide.\n3 ÷ {1/6}', 'Quotient:', key='18'),
          mc('How many {1/3}s are in 7?', ['21', '{7/3}', '{1/21}', '10']),
          sa('Divide.\n9 ÷ {1/4}', 'Quotient:', key='36'),
          tf('5 ÷ {1/2} = 2{1/2}', key=False),
      ],
      back=[
          B('Division as "how many groups?"', '3.OA.A.2', [
              sa('How many groups of 3 are in 18?', 'Groups:', key='6'),
              tf('20 ÷ 5 can mean "How many 5s are in 20?"', key=True),
              mc('Pam puts 24 eggs into cartons of 6.\nWhich equation finds the number of cartons?', ['24 ÷ 6 = □', '24 × 6 = □', '24 - 6 = □', '6 ÷ 24 = □']),
              sa('How many 4s are in 32?', 'Answer:', key='8'),
              sa('A 30-inch ribbon is cut into 5-inch pieces.\nHow many pieces are there?', 'Pieces:', key='6'),
          ]),
          B('Unit fractions that make a whole', '3.NF.A.1', [
              sa('How many {1/4}s make 1 whole?', 'Answer:', key='4'),
              tf('There are 3 thirds in 2 wholes.', key=False),
              mc('How many {1/5}s make 2 wholes?', ['10', '5', '2', '7']),
              sa('How many {1/8}s make 1 whole?', 'Answer:', key='8'),
              tf('There are 2 halves in 2 wholes.', key=False),
          ]),
      ],
      f1=B('Divide whole numbers by fractions', '6.NS.A.1', [
          sa('Divide.\n6 ÷ {3/4}', 'Quotient:', key='8'),
          sa('Divide.\n4 ÷ {2/5}', 'Quotient:', key='10'),
          mc('How many {2/3}-cup servings are in 8 cups?', ['12', '{16/3}', '{1/12}', '6']),
          sa('Divide.\n5 ÷ {5/6}', 'Quotient:', key='6'),
          tf('3 ÷ {3/8} = {9/8}', key=False),
      ]),
      f2=B('Unit rates from quantities measured in fractions', '7.RP.A.1', [
          sa('A car uses {1/4} gallon of gas to go 6 miles.\nHow many miles does it go per gallon?', 'Miles per gallon:', key='24'),
          sa('A machine makes 5 parts every {1/3} minute.\nHow many parts does it make per minute?', 'Parts per minute:', key='15'),
          mc('Lee runs 2 miles in {1/6} hour.\nWhat is his speed?', ['12 miles per hour', '{1/12} mile per hour', '3 miles per hour', '8 miles per hour']),
          sa('A hose fills 10 liters in {1/2} minute.\nHow many liters does it fill per minute?', 'Liters per minute:', key='20'),
          tf('Walking 3 miles in {3/4} hour is a speed of 4 miles per hour.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.NF.B.7.c
    S('5.NF.B.7.c', 'Solve word problems that divide unit fractions and whole numbers',
      main=[
          sa('How many {1/3}-cup servings of raisins are in 2 cups?', 'Servings:', key='6'),
          sa('3 friends share {1/2} pound of chocolate equally.\nHow much chocolate does each friend get?', 'Pounds:', key='1/6 pound'),
          mc('A 5-meter rope is cut into pieces that are {1/4} meter long.\nHow many pieces are there?', ['20', '{5/4}', '{1/20}', '9']),
          sa('{1/8} of a pizza is shared equally by 2 people.\nWhat fraction of the whole pizza does each person get?', 'Fraction:', key='1/16'),
          tf('A 6-mile trail is split into {1/2}-mile sections. There are 12 sections.', key=True),
      ],
      back=[
          B('Division word problems', '3.OA.A.3', [
              sa('Kim has 28 beads. Each bracelet uses 7 beads.\nHow many bracelets can she make?', 'Bracelets:', key='4'),
              tf('If 32 students sit 4 at each table, there are 6 tables.', key=False),
              mc('Raj shares 40 cards equally among 5 friends.\nHow many cards does each friend get?', ['8', '35', '45', '200']),
              sa('A 27-foot fence is split into 9 equal sections.\nHow long is each section?', 'Length:', key='3 feet'),
              sa('48 eggs are packed 6 to a carton.\nHow many cartons are filled?', 'Cartons:', key='8'),
          ]),
          B('A fraction as division', '5.NF.B.3', [
              sa('Write 1 ÷ 4 as a fraction.', 'Fraction:', key='1/4'),
              tf('2 ÷ 3 = {2/3}', key=True),
              mc('4 people share 1 pie equally.\nHow much pie does each person get?', ['{1/4} pie', '4 pies', '{4/1} pies', '{3/4} pie']),
              sa('Write {1/6} as a division expression.', 'Expression:', key='1 ÷ 6'),
              tf('5 people share 2 sandwiches equally, so each person gets {5/2} sandwiches.', key=False),
          ]),
      ],
      f1=B('Word problems that divide fractions by fractions', '6.NS.A.1', [
          sa('How many {3/8}-pound bags can be filled from 3 pounds of rice?', 'Bags:', key='8'),
          sa('{2/3} of a cake is shared equally by 4 people.\nWhat fraction of the whole cake does each person get?', 'Fraction:', key='1/6'),
          mc('A path is {9/10} mile long. It is split into sections that are {3/10} mile long.\nHow many sections are there?', ['3', '{27/100}', '{1/3}', '6']),
          sa('A rectangle has an area of 2 square yards and a length of 2{1/2} yards.\nWhat is its width?', 'Width:', key='4/5 yard'),
          tf('{3/4} cup of oil fills exactly 3 bottles that hold {1/4} cup each.', key=True),
      ]),
      f2=B('Real-world problems that divide rational numbers', '7.NS.A.3', [
          sa('A diver descends 18 feet in {1/2} minute at a constant rate.\nWhat is the change in depth per minute?', 'Change per minute:',
             key='-36 feet per minute', note='"36 feet down per minute" is also correct.'),
          sa('The temperature fell 5°F in {1/4} hour.\nAt this rate, what is the change in temperature per hour?', 'Change per hour:', key='-20°F per hour'),
          mc('A bank account changes by -$45 in {1/3} month at a steady rate.\nWhat is the change per month?', ['-$135', '$135', '-$15', '-$45']),
          sa('Find the value.\n-6 ÷ {1/3}', 'Value:', key='-18'),
          tf('-2 ÷ {1/4} = -{1/2}', key=False),
      ])),
]
