from qb import S, B, sa, mc, tf, nl, coord, table, tri, plot
from common import grid, tplot

PEARS = grid(5, 10, ystep=2, xlabel='Pounds', ylabel='Cost ($)', pts=[(1, 2), (2, 4), (3, 6)], lines=[((0, 0), (5, 10))])

SETS = [
    # ------------------------------------------------------------------ 5.G.A.1
    S('5.G.A.1', 'Understand the coordinate plane: axes, origin, and coordinates',
      main=[
          mc('What is the point where the x-axis and the y-axis meet called?', ['The origin', 'The x-coordinate', 'The y-axis', 'A quadrant']),
          sa('In the ordered pair (7, 2), what does the 7 tell you?', 'Answer:',
             key='Start at the origin and move 7 units along the x-axis (to the right).'),
          sa('What are the coordinates of point A?', 'A =', key='(3, 5)', fig=grid(8, 8, pts=[(3, 5, 'A')])),
          tf('To reach (0, 6), you start at the origin and move 6 units to the right along the x-axis.', key=False),
          mc('Which point is at (5, 1)?', ['Point A', 'Point B', 'Point C', 'Point D'],
             fig=grid(8, 8, pts=[(5, 1, 'A'), (1, 5, 'B'), (5, 5, 'C'), (1, 1, 'D')])),
      ],
      back=[
          B('Whole numbers on a number line', '2.MD.B.6', [
              sa('What number is at point P?', 'P =', key='6', fig=nl(0, 10, 1, pts=[(6, 'P')])),
              tf('On a number line, numbers increase from left to right.', key=True),
              mc('Which number is 4 units to the right of 0?', ['4', '0', '8', '40']),
              sa('How many units is it from 0 to 9 on a number line?', 'Units:', key='9'),
              tf('On a number line, 3 is farther from 0 than 7 is.', key=False),
          ]),
          B('Perpendicular lines', '4.G.A.1', [
              tf('Perpendicular lines meet to form right angles.', key=True),
              mc('The x-axis and the y-axis are ___.', ['perpendicular', 'parallel', 'curved', 'the same line']),
              sa('How many degrees are in a right angle?', 'Degrees:', key='90'),
              tf('Parallel lines never meet.', key=True),
              mc('Which letter is made of two perpendicular line segments?', ['L', 'O', 'S', 'C']),
          ]),
      ],
      f1=B('Name the coordinates of points in all four quadrants', '6.NS.C.6.c', [
          sa('What are the coordinates of point A?', 'A =', key='(-3, 4)', fig=coord(pts=[(-3, 4, 'A')])),
          sa('What are the coordinates of point B?', 'B =', key='(2, -5)', fig=coord(pts=[(2, -5, 'B')])),
          mc('Which ordered pair names point C?', ['(-4, -2)', '(-2, -4)', '(4, 2)', '(-4, 2)'], fig=coord(pts=[(-4, -2, 'C')])),
          sa('What are the coordinates of point D?', 'D =', key='(0, -3)', fig=coord(pts=[(0, -3, 'D')])),
          tf('Point E is located at (5, -1).', key=False, fig=coord(pts=[(-1, 5, 'E')])),
      ]),
      f2=B('Interpret a point on the graph of a proportional relationship', '7.RP.A.2.d', [
          sa('The graph shows the cost of pears.\nWhat does the point (3, 6) represent?', 'Meaning:', key='3 pounds of pears cost $6.', fig=PEARS),
          mc('The graph shows the cost of pears.\nWhat does the point (1, 2) represent?',
             ['1 pound costs $2.', '2 pounds cost $1.', 'The cost starts at $2.', '$1 buys 2 pounds.'], fig=PEARS),
          tf('On the graph of a proportional relationship between pounds and cost, the point (0, 0) means 0 pounds cost $0.', key=True),
          sa('The graph of a proportional relationship passes through (1, r) and (4, 20).\nWhat is r?', 'r =', key='5'),
          mc('A graph shows the distance y in miles after x hours. It passes through (2, 90).\nWhat does this point mean?',
             ['In 2 hours, the distance is 90 miles.', 'In 90 hours, the distance is 2 miles.', 'The speed is 2 miles per hour.', 'The speed is 90 miles per hour.']),
      ])),

    # ------------------------------------------------------------------ 5.G.A.2 (graph points)
    S('5.G.A.2', 'Graph points in the first quadrant',
      main=[
          plot('Plot and label the points A(2, 7), B(6, 3), and C(0, 5).', grid(8, 8),
               key='A plotted at (2, 7), B at (6, 3), and C at (0, 5) on the y-axis, each labeled'),
          plot('Plot and label the points D(4, 4), E(7, 0), and F(1, 6).', grid(8, 8),
               key='D plotted at (4, 4), E at (7, 0) on the x-axis, and F at (1, 6), each labeled'),
          plot('Plot the points from the table.', tplot([['Hours', '1', '2', '3', '4'], ['Miles', '3', '6', '9', '12']], 5, 14, ystep=2),
               key='Points plotted at (1, 3), (2, 6), (3, 9), (4, 12)'),
          plot('Plot and label the points G(3, 2{1/2}) and H(5{1/2}, 4).', grid(8, 8),
               key='G plotted at (3, 2 1/2), halfway between 2 and 3 on the y-axis scale; H plotted at (5 1/2, 4); each labeled'),
          sa('Plot P(2, 3) and Q(2, 7).\nHow far apart are the two points?', 'Distance:', key='4 units',
             note='Points plotted at (2, 3) and (2, 7).', fig=grid(8, 8)),
      ],
      back=[
          B('Reading coordinates', '5.G.A.1', [
              sa('What are the coordinates of point K?', 'K =', key='(4, 6)', fig=grid(8, 8, pts=[(4, 6, 'K')])),
              tf('To plot (3, 8), you move up 3 units.', key=False),
              mc('Which point is at (6, 2)?', ['Point A', 'Point B', 'Point C', 'Point D'],
                 fig=grid(8, 8, pts=[(6, 2, 'A'), (2, 6, 'B'), (6, 6, 'C'), (2, 2, 'D')])),
              sa('What are the coordinates of point M?', 'M =', key='(0, 4)', fig=grid(8, 8, pts=[(0, 4, 'M')])),
              tf('The point (5, 0) is on the y-axis.', key=False),
          ]),
          B('Reading the scale on an axis', '3.MD.B.3', [
              mc('An axis is numbered by 5s: 0, 5, 10, 15, ...\nWhat value is 4 grid lines above 0?', ['20', '4', '15', '25']),
              tf('On an axis numbered by 2s, the value 7 is halfway between 6 and 8.', key=True),
              sa('An axis is numbered by 10s.\nWhat value is at the 3rd grid line above 0?', 'Value:', key='30'),
              mc('An axis is numbered by 3s.\nWhere is the value 12?', ['At the 4th grid line', 'At the 12th grid line', 'At the 3rd grid line',
                                                                     'Between the 3rd and 4th grid lines']),
              tf('On an axis numbered by 5s, the value 12 is on a grid line.', key=False),
          ]),
      ],
      f1=B('Plot and reflect points in all four quadrants', '6.NS.C.6.b', [
          plot('Plot and label the points P(-3, 4) and Q(3, -4).', coord(), key='P plotted at (-3, 4) and Q at (3, -4), each labeled'),
          sa('The point (5, 2) is reflected across the x-axis.\nWhat are the coordinates of its image?', 'Image:', key='(5, -2)'),
          mc('In which quadrant is the point (-2, -6)?', ['Quadrant III', 'Quadrant I', 'Quadrant II', 'Quadrant IV']),
          sa('The point (-4, 1) is reflected across the y-axis.\nWhat are the coordinates of its image?', 'Image:', key='(4, 1)'),
          tf('The points (3, 5) and (-3, 5) are reflections of each other across the x-axis.', key=False),
      ]),
      f2=B('Graph pairs to decide whether a relationship is proportional', '7.RP.A.2.a', [
          sa('Graph the pairs (1, 3), (2, 6), and (4, 12).\nIs the relationship proportional?', 'Answer:', key='Yes',
             note='The points lie on a straight line through (0, 0).', fig=grid(5, 14, ystep=2)),
          sa('Graph the pairs (0, 2), (1, 4), and (2, 6).\nIs the relationship proportional?', 'Answer:', key='No',
             note='The points are on a line, but the line does not pass through (0, 0).', fig=grid(4, 8)),
          mc('Which graph shows a proportional relationship?', ['A straight line through (0, 0)', 'A straight line through (0, 3)',
                                                               'A curve through (0, 0)', 'Points that are not on a line']),
          tf('The points (2, 1), (4, 2), and (6, 3) show a proportional relationship.', key=True),
          sa('Graph the pairs from the table.\nIs the relationship proportional?', 'Answer:', key='Yes',
             note='Points (1, 4), (2, 8), (3, 12) lie on a line through (0, 0).',
             fig=tplot([['x', '1', '2', '3'], ['y', '4', '8', '12']], 4, 14, ystep=2)),
      ])),

    # ------------------------------------------------------------------ 5.G.A.2 (real-world)
    S('5.G.A.2', 'Solve real-world problems by graphing points and interpreting coordinates',
      main=[
          sa('The grid is a map. Each unit is 1 block.\nHow many blocks is it from the school S to the library L?', 'Blocks:', key='5',
             fig=grid(10, 10, pts=[(2, 3, 'S'), (2, 8, 'L')])),
          sa('The graph shows the height of a plant.\nHow tall was the plant after 4 weeks?', 'Height:', key='8 cm',
             fig=grid(6, 12, ystep=2, xlabel='Weeks', ylabel='Height (cm)', pts=[(1, 2), (2, 4), (3, 6), (4, 8), (5, 10)])),
          mc('The point (3, 12) is on a graph of hours worked (x) and dollars earned (y).\nWhat does the point mean?',
             ['Working 3 hours earns $12.', 'Working 12 hours earns $3.', 'Each hour earns $3.', 'The pay starts at $12.']),
          plot('The table shows the cost of a taxi ride.\nGraph the points.', tplot([['Miles', '1', '2', '3', '4'], ['Cost ($)', '5', '7', '9', '11']], 5, 12),
               key='Points plotted at (1, 5), (2, 7), (3, 9), (4, 11)'),
          sa('On a map grid, the park is at (1, 6) and the pool is at (7, 6). Each unit is 100 meters.\nHow far apart are the park and the pool?',
             'Distance:', key='600 meters'),
      ],
      back=[
          B('The coordinate system', '5.G.A.1', [
              sa('What are the coordinates of the origin?', 'Origin:', key='(0, 0)'),
              tf('The first number in an ordered pair tells how far to move along the x-axis.', key=True),
              mc('Point R is 4 units to the right of the origin and 1 unit up.\nWhat are its coordinates?', ['(4, 1)', '(1, 4)', '(4, 4)', '(5, 0)']),
              sa('What are the coordinates of point T?', 'T =', key='(7, 3)', fig=grid(8, 8, pts=[(7, 3, 'T')])),
              tf('(0, 2) and (2, 0) name the same point.', key=False),
          ]),
          B('Distance between whole numbers on a number line', '2.MD.B.6', [
              sa('What is the distance from 2 to 7 on a number line?', 'Distance:', key='5 units'),
              tf('The distance from 3 to 10 is 13 units.', key=False),
              mc('How many units apart are 1 and 8 on a number line?', ['7', '9', '8', '1']),
              sa('What is the distance from 6 to 6 on a number line?', 'Distance:', key='0'),
              sa('How many units apart are points A and B?', 'Units:', key='7', fig=nl(0, 10, 1, pts=[(2, 'A'), (9, 'B')])),
          ]),
      ],
      f1=B('Find distances in all four quadrants', '6.NS.C.8', [
          sa('Find the distance between (-4, 2) and (5, 2).', 'Distance:', key='9 units'),
          sa('Find the distance between (3, -6) and (3, 1).', 'Distance:', key='7 units'),
          mc('On a map, the store is at (-2, -3) and the bank is at (-2, 4). Each unit is 1 block.\nHow far apart are they?',
             ['7 blocks', '1 block', '6 blocks', '4 blocks']),
          sa('A rectangle has vertices at (-3, 1), (2, 1), (2, -2), and (-3, -2).\nWhat is its perimeter?', 'Perimeter:', key='16 units'),
          tf('The distance between (-5, 0) and (5, 0) is 0.', key=False),
      ]),
      f2=B('Use a scale on a map grid', '7.G.A.1', [
          sa('On a map grid, each unit is 2 miles. Two towns are at (1, 3) and (6, 3).\nWhat is the actual distance between them?', 'Distance:', key='10 miles'),
          sa('On a floor plan, each unit is 1{1/2} feet. A wall goes from (0, 0) to (0, 8).\nHow long is the real wall?', 'Length:', key='12 feet'),
          mc('A scale drawing uses 1 grid unit = 5 m. A path on the grid is 7 units long.\nHow long is the real path?', ['35 m', '12 m', '7 m', '2 m']),
          sa('A garden plan has corners at (0, 0), (6, 0), (6, 4), and (0, 4). Each unit is 3 feet.\nWhat are the real length and width?',
             'Length and width:', key='18 feet by 12 feet'),
          tf('If each grid unit is 10 km, the points (2, 5) and (2, 9) are 4 km apart.', key=False),
      ])),

    # ------------------------------------------------------------------ 5.G.B.3
    S('5.G.B.3', 'Attributes of a category belong to all of its subcategories',
      main=[
          tf('All rectangles have four right angles. Squares are rectangles, so all squares have four right angles.', key=True),
          mc('All parallelograms have two pairs of parallel sides.\nWhich shape must also have two pairs of parallel sides?',
             ['Rhombus', 'Kite', 'Triangle', 'Pentagon']),
          sa('A rhombus is a quadrilateral with 4 sides of equal length.\nIs every square a rhombus? Explain.', ['Answer:', 'Explanation:'],
             key='Yes', note='A square is a quadrilateral with 4 sides of equal length, so it has every attribute of a rhombus.'),
          tf('All quadrilaterals have 4 right angles.', key=False),
          mc('Which statement is true?', ['Every square is a rectangle.', 'Every rectangle is a square.',
                                          'Every parallelogram is a square.', 'Every quadrilateral is a rectangle.']),
      ],
      back=[
          B('Quadrilaterals and their attributes', '3.G.A.1', [
              sa('How many sides does every quadrilateral have?', 'Sides:', key='4'),
              tf('Triangles, rectangles, and squares are all quadrilaterals.', key=False),
              mc('Which shape is NOT a quadrilateral?', ['Triangle', 'Square', 'Rectangle', 'Rhombus']),
              tf('A square has 4 sides of equal length.', key=True),
              sa('Name a quadrilateral that always has 4 right angles.', 'Shape:', key='Rectangle', note='Square is also correct.'),
          ]),
          B('Parallel lines, perpendicular lines, and angles', '4.G.A.1', [
              tf('Parallel lines are always the same distance apart.', key=True),
              mc('Which angle measure is a right angle?', ['90°', '45°', '120°', '180°']),
              sa('What do we call two lines that meet to form right angles?', 'Answer:', key='Perpendicular lines'),
              tf('An obtuse angle is smaller than a right angle.', key=False),
              mc('How many pairs of parallel sides does a rectangle have?', ['2', '1', '0', '4']),
          ]),
          B('Classifying shapes by sides and angles', '4.G.A.2', [
              tf('A shape with no parallel sides can still be a quadrilateral.', key=True),
              mc('Which kind of triangle has a right angle?', ['A right triangle', 'An acute triangle', 'An obtuse triangle', 'An equilateral triangle']),
              sa('How many right angles does a square have?', 'Right angles:', key='4'),
              tf('A rhombus always has 4 right angles.', key=False),
              mc('Which shape always has two pairs of parallel sides?', ['Rectangle', 'Triangle', 'Pentagon', 'Kite']),
          ]),
      ],
      f1=B('Draw polygons in the coordinate plane', '6.G.A.3', [
          sa('Plot A(-2, 1), B(3, 1), C(3, -3), and D(-2, -3). Connect them in order.\nWhat polygon did you draw?', 'Polygon:', key='A rectangle',
             note='The sides are 5 units and 4 units long.', fig=coord()),
          sa('Plot E(0, 3), F(3, 0), G(0, -3), and H(-3, 0). Connect them in order.\nWhat polygon did you draw?', 'Polygon:', key='A square',
             note='"Rhombus" is also correct, since a square is a rhombus.', fig=coord()),
          mc('The points (-1, 2), (4, 2), and (4, -1) are three vertices of a rectangle.\nWhat is the fourth vertex?',
             ['(-1, -1)', '(4, 2)', '(-1, 4)', '(1, -1)']),
          sa('What is the length of the side from (-2, 5) to (4, 5)?', 'Length:', key='6 units'),
          tf('The points (0, 0), (4, 0), (4, 2), and (0, 2) are the vertices of a square.', key=False),
      ]),
      f2=B('Decide whether shapes with given conditions are possible', '7.G.A.2', [
          tf('A triangle can have side lengths of 3 cm, 4 cm, and 5 cm.', key=True),
          mc('Which three lengths can form a triangle?', ['4, 5, 7', '2, 3, 6', '1, 1, 3', '5, 5, 10']),
          sa('Can a triangle have side lengths of 2 cm, 2 cm, and 5 cm? Write yes or no.', 'Answer:', key='No'),
          tf('A triangle can have two right angles.', key=False),
          sa('Can a quadrilateral have exactly 3 right angles? Write yes or no.', 'Answer:', key='No',
             note='If 3 angles are right angles, the 4th must be a right angle too.'),
      ])),

    # ------------------------------------------------------------------ 5.G.B.4 (quadrilaterals)
    S('5.G.B.4', 'Classify quadrilaterals in a hierarchy based on their properties',
      main=[
          mc('Which list goes from the most general category to the most specific?',
             ['Quadrilateral, parallelogram, rectangle, square', 'Square, rectangle, parallelogram, quadrilateral',
              'Rectangle, square, quadrilateral, parallelogram', 'Parallelogram, quadrilateral, square, rectangle']),
          tf('A square is a rectangle, a rhombus, and a parallelogram.', key=True),
          sa('Which of these categories does every rhombus belong to?\nquadrilateral, parallelogram, rectangle, square', 'Categories:',
             key='Quadrilateral and parallelogram'),
          mc('A shape has 4 sides of equal length and 4 right angles.\nWhat is the most specific name for it?', ['Square', 'Rhombus', 'Rectangle', 'Quadrilateral']),
          tf('Every parallelogram is a rhombus.', key=False),
      ],
      back=[
          B('Quadrilaterals', '3.G.A.1', [
              tf('A rectangle is a quadrilateral.', key=True),
              mc('Which shape always has 4 sides of equal length?', ['Rhombus', 'Rectangle', 'Kite', 'Triangle']),
              sa('How many angles does a quadrilateral have?', 'Angles:', key='4'),
              tf('Every quadrilateral is a square.', key=False),
              sa('Name a shape that is a quadrilateral but is not a parallelogram.', 'Shape:', key='A kite',
                 note='Any quadrilateral without two pairs of parallel sides is correct, such as a kite or a trapezoid with one pair of parallel sides.'),
          ]),
          B('Classifying by parallel sides and right angles', '4.G.A.2', [
              tf('A quadrilateral with 2 pairs of parallel sides is a parallelogram.', key=True),
              mc('Which shape always has 4 right angles?', ['Rectangle', 'Rhombus', 'Parallelogram', 'Kite']),
              sa('How many pairs of parallel sides does a parallelogram have?', 'Pairs:', key='2'),
              tf('The sides of a square that meet at a corner are perpendicular.', key=True),
              mc('Which description fits every rhombus?', ['4 sides of equal length', '4 right angles', 'No parallel sides', '3 sides']),
          ]),
      ],
      f1=B('Area of parallelograms, rhombuses, and trapezoids', '6.G.A.1', [
          sa('A parallelogram has a base of 10 cm and a height of 6 cm.\nWhat is its area?', 'Area:', key='60 square cm'),
          sa('A rhombus has a base of 7 in. and a height of 5 in.\nWhat is its area?', 'Area:', key='35 square inches'),
          mc('A square has sides that are 9 m long.\nWhat is its area?', ['81 square meters', '36 square meters', '18 square meters', '90 square meters']),
          sa('A trapezoid has bases of 6 ft and 10 ft and a height of 4 ft.\nWhat is its area?', 'Area:', key='32 square feet'),
          tf('A parallelogram has a greater area than a rectangle with the same base and the same height.', key=False),
      ]),
      f2=B('Shapes with given conditions', '7.G.A.2', [
          sa('Can you draw a rectangle that is not a square? Write yes or no.', 'Answer:', key='Yes'),
          mc('A quadrilateral has 4 sides of equal length but no right angles.\nWhat is it?',
             ['A rhombus that is not a square', 'A square', 'A rectangle', 'A trapezoid']),
          tf('Only one triangle can be drawn with angles of 40°, 60°, and 80°.', key=False),
          sa('Is there more than one triangle shape with sides of 6 cm, 6 cm, and 6 cm? Write yes or no.', 'Answer:', key='No',
             note='Three side lengths determine one unique triangle.'),
          tf('A triangle with three sides of 5 cm also has three equal angles.', key=True),
      ])),

    # ------------------------------------------------------------------ 5.G.B.4 (triangles)
    S('5.G.B.4', 'Classify triangles by their sides and angles',
      main=[
          mc('A triangle has sides of 6 cm, 6 cm, and 6 cm.\nWhich name fits it?', ['Equilateral', 'Scalene', 'Right', 'Obtuse']),
          sa('A triangle has angles of 90°, 50°, and 40°.\nClassify it by its angles.', 'Classification:', key='Right triangle'),
          tf('Every equilateral triangle is also an isosceles triangle.', key=True),
          mc('A triangle has sides of 3, 5, and 7 units and an angle of 120°.\nWhich name fits it?',
             ['Obtuse scalene', 'Right isosceles', 'Acute equilateral', 'Right scalene']),
          sa('A triangle has angles of 70°, 70°, and 40°.\nClassify it by its angles and by its sides.', ['By angles:', 'By sides:'],
             key='Acute; isosceles', note='Two equal angles mean two equal sides.'),
      ],
      back=[
          B('Right, acute, and obtuse triangles', '4.G.A.2', [
              tf('A right triangle has exactly one right angle.', key=True),
              mc('Which angle measure is obtuse?', ['130°', '90°', '45°', '10°']),
              sa('A triangle has one angle greater than 90°.\nWhat kind of triangle is it?', 'Kind:', key='Obtuse triangle'),
              tf('In an acute triangle, all three angles are less than 90°.', key=True),
              mc('Which angle measure is acute?', ['60°', '90°', '100°', '180°']),
          ]),
          B('Kinds of angles', '4.G.A.1', [
              tf('A right angle measures 90°.', key=True),
              mc('What kind of angle measures 35°?', ['Acute', 'Right', 'Obtuse', 'Straight']),
              sa('What kind of angle measures 150°?', 'Kind:', key='Obtuse'),
              tf('Two right angles together make 360°.', key=False),
              sa('What kind of angle measures exactly 90°?', 'Kind:', key='Right angle'),
          ]),
          B('Triangles', '2.G.A.1', [
              sa('How many sides does a triangle have?', 'Sides:', key='3'),
              tf('A triangle has 3 angles.', key=True),
              mc('Which shape has 3 sides?', ['Triangle', 'Square', 'Pentagon', 'Hexagon']),
              tf('All triangles have sides of equal length.', key=False),
              sa('How many vertices (corners) does a triangle have?', 'Vertices:', key='3'),
          ]),
      ],
      f1=B('Area of triangles', '6.G.A.1', [
          sa('A right triangle has legs that are 6 cm and 8 cm long.\nWhat is its area?', 'Area:', key='24 square cm'),
          sa('A triangle has a base of 10 in. and a height of 7 in.\nWhat is its area?', 'Area:', key='35 square inches'),
          mc('An obtuse triangle has a base of 5 m. Its height, measured outside the triangle, is 4 m.\nWhat is its area?',
             ['10 square meters', '20 square meters', '9 square meters', '40 square meters']),
          sa('Find the area of the triangle.', 'Area:', key='20 square feet', fig=tri(8, 5, 3, '8 ft', '5 ft')),
          tf('Two triangles with the same base and the same height have the same area.', key=True),
      ]),
      f2=B('Complementary, supplementary, and vertical angles', '7.G.B.5', [
          sa('Two angles are complementary. One measures 35°.\nWhat is the measure of the other angle?', 'Angle:', key='55°'),
          sa('Two angles are supplementary. One measures 110°.\nWhat is the measure of the other angle?', 'Angle:', key='70°'),
          mc('Vertical angles are always ___.', ['equal', 'supplementary', 'complementary', 'right angles']),
          sa('An angle and a 72° angle together form a straight line.\nWhat is the measure of the angle?', 'Angle:', key='108°'),
          tf('Two adjacent angles that together form a right angle are complementary.', key=True),
      ])),
]
